// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost3_wrt_DeltaRot_Nl4
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost3WrtDeltarotNl4(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 2044

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (622)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp1 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp2 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp3 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp4 = _tmp0 + _tmp1 - _tmp2 + _tmp3;
  const Scalar _tmp5 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp6 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp7 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp8 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp9 = -_tmp5 + _tmp6 + _tmp7 + _tmp8;
  const Scalar _tmp10 = 2 * _tmp4 * _tmp9;
  const Scalar _tmp11 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp12 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp13 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp14 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp15 = _tmp11 - _tmp12 + _tmp13 + _tmp14;
  const Scalar _tmp16 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp17 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp18 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp19 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp20 = -_tmp16 - _tmp17 - _tmp18 + _tmp19;
  const Scalar _tmp21 = 2 * _tmp20;
  const Scalar _tmp22 = _tmp15 * _tmp21;
  const Scalar _tmp23 = Scalar(0.20999999999999999) * _tmp10 - Scalar(0.20999999999999999) * _tmp22;
  const Scalar _tmp24 = -_tmp23;
  const Scalar _tmp25 = 2 * _tmp15;
  const Scalar _tmp26 = _tmp25 * _tmp9;
  const Scalar _tmp27 = _tmp21 * _tmp4;
  const Scalar _tmp28 =
      -Scalar(0.010999999999999999) * _tmp26 - Scalar(0.010999999999999999) * _tmp27;
  const Scalar _tmp29 = -2 * std::pow(_tmp4, Scalar(2));
  const Scalar _tmp30 = -2 * std::pow(_tmp15, Scalar(2));
  const Scalar _tmp31 = Scalar(0.20999999999999999) * _tmp29 +
                        Scalar(0.20999999999999999) * _tmp30 + Scalar(0.20999999999999999);
  const Scalar _tmp32 = _tmp28 - _tmp31;
  const Scalar _tmp33 = _tmp24 + _tmp32;
  const Scalar _tmp34 = _tmp33 + position_vector(0, 0) + Scalar(1.9874742031097401);
  const Scalar _tmp35 = Scalar(0.20999999999999999) * _tmp10 + Scalar(0.20999999999999999) * _tmp22;
  const Scalar _tmp36 = -_tmp35;
  const Scalar _tmp37 = _tmp25 * _tmp4;
  const Scalar _tmp38 = _tmp21 * _tmp9;
  const Scalar _tmp39 =
      -Scalar(0.010999999999999999) * _tmp37 + Scalar(0.010999999999999999) * _tmp38;
  const Scalar _tmp40 = 1 - 2 * std::pow(_tmp9, Scalar(2));
  const Scalar _tmp41 = Scalar(0.20999999999999999) * _tmp30 + Scalar(0.20999999999999999) * _tmp40;
  const Scalar _tmp42 = _tmp39 - _tmp41;
  const Scalar _tmp43 = _tmp36 + _tmp42;
  const Scalar _tmp44 = _tmp43 + position_vector(1, 0) + Scalar(8.3196563720703107);
  const Scalar _tmp45 = std::pow(_tmp34, Scalar(2)) + std::pow(_tmp44, Scalar(2));
  const Scalar _tmp46 = std::pow(_tmp45, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp47 = _tmp46 * fh1;
  const Scalar _tmp48 = _tmp34 * _tmp47;
  const Scalar _tmp49 =
      -Scalar(0.010999999999999999) * _tmp29 - Scalar(0.010999999999999999) * _tmp40;
  const Scalar _tmp50 = Scalar(0.20999999999999999) * _tmp26 - Scalar(0.20999999999999999) * _tmp27;
  const Scalar _tmp51 = Scalar(0.20999999999999999) * _tmp37 + Scalar(0.20999999999999999) * _tmp38;
  const Scalar _tmp52 = _tmp49 - _tmp50 + _tmp51;
  const Scalar _tmp53 = _tmp39 + _tmp41;
  const Scalar _tmp54 = _tmp35 + _tmp53;
  const Scalar _tmp55 = _tmp54 + position_vector(1, 0) + Scalar(-4.7744369927459998);
  const Scalar _tmp56 = _tmp28 + _tmp31;
  const Scalar _tmp57 = _tmp23 + _tmp56;
  const Scalar _tmp58 = _tmp57 + position_vector(0, 0) + Scalar(-2.7171519410699099);
  const Scalar _tmp59 = std::pow(_tmp55, Scalar(2)) + std::pow(_tmp58, Scalar(2));
  const Scalar _tmp60 = std::pow(_tmp59, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp61 = _tmp58 * _tmp60;
  const Scalar _tmp62 = _tmp52 * _tmp61;
  const Scalar _tmp63 = _tmp49 + _tmp50;
  const Scalar _tmp64 = _tmp51 + _tmp63;
  const Scalar _tmp65 = _tmp23 + _tmp32;
  const Scalar _tmp66 = Scalar(1.0) * _tmp65;
  const Scalar _tmp67 = _tmp24 + _tmp56;
  const Scalar _tmp68 = _tmp66 - _tmp67;
  const Scalar _tmp69 = _tmp36 + _tmp53;
  const Scalar _tmp70 = Scalar(1.0) * _tmp69;
  const Scalar _tmp71 = _tmp35 + _tmp42;
  const Scalar _tmp72 = -_tmp70 + _tmp71;
  const Scalar _tmp73 = Scalar(1.0) / (_tmp72);
  const Scalar _tmp74 = -_tmp51 + _tmp63;
  const Scalar _tmp75 = _tmp71 + position_vector(1, 0) + Scalar(8.3885017487099702);
  const Scalar _tmp76 = _tmp67 + position_vector(0, 0) + Scalar(-2.5193355532036801);
  const Scalar _tmp77 = std::pow(_tmp75, Scalar(2)) + std::pow(_tmp76, Scalar(2));
  const Scalar _tmp78 = std::pow(_tmp77, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp79 = _tmp75 * _tmp78;
  const Scalar _tmp80 = _tmp69 + position_vector(1, 0) + Scalar(-4.83288938413423);
  const Scalar _tmp81 = _tmp65 + position_vector(0, 0) + Scalar(1.7965602546229);
  const Scalar _tmp82 = Scalar(1.0) / (_tmp81);
  const Scalar _tmp83 = _tmp80 * _tmp82;
  const Scalar _tmp84 = _tmp76 * _tmp78;
  const Scalar _tmp85 = _tmp52 * _tmp84;
  const Scalar _tmp86 = _tmp74 * _tmp79 - _tmp83 * _tmp85;
  const Scalar _tmp87 = -_tmp79 + _tmp83 * _tmp84;
  const Scalar _tmp88 = Scalar(1.0) / (_tmp87);
  const Scalar _tmp89 = _tmp55 * _tmp60;
  const Scalar _tmp90 = _tmp61 * _tmp83 - _tmp89;
  const Scalar _tmp91 = _tmp88 * _tmp90;
  const Scalar _tmp92 = _tmp52 * _tmp83;
  const Scalar _tmp93 = -_tmp61 * _tmp92 + _tmp64 * _tmp89 - _tmp86 * _tmp91;
  const Scalar _tmp94 = _tmp73 * _tmp93;
  const Scalar _tmp95 = -_tmp74 * _tmp84 + _tmp85;
  const Scalar _tmp96 = -_tmp61 * _tmp64 + _tmp62 - _tmp68 * _tmp94 - _tmp91 * _tmp95;
  const Scalar _tmp97 = Scalar(1.0) / (_tmp96);
  const Scalar _tmp98 = _tmp54 * _tmp60;
  const Scalar _tmp99 = std::pow(_tmp81, Scalar(2));
  const Scalar _tmp100 = std::pow(_tmp80, Scalar(2)) + _tmp99;
  const Scalar _tmp101 = std::sqrt(_tmp100);
  const Scalar _tmp102 = Scalar(1.0) / (_tmp101);
  const Scalar _tmp103 = _tmp102 * _tmp81;
  const Scalar _tmp104 = _tmp102 * _tmp65;
  const Scalar _tmp105 = -_tmp103 * _tmp69 + _tmp104 * _tmp80;
  const Scalar _tmp106 = _tmp101 * _tmp82;
  const Scalar _tmp107 = _tmp105 * _tmp106;
  const Scalar _tmp108 = _tmp107 * _tmp84 - _tmp67 * _tmp79 + _tmp71 * _tmp84;
  const Scalar _tmp109 = _tmp107 * _tmp61 - _tmp108 * _tmp91 - _tmp57 * _tmp89 + _tmp58 * _tmp98;
  const Scalar _tmp110 = Scalar(1.0) / (_tmp109);
  const Scalar _tmp111 = _tmp108 * _tmp88;
  const Scalar _tmp112 = _tmp86 * _tmp88;
  const Scalar _tmp113 = _tmp112 * _tmp83 + _tmp92;
  const Scalar _tmp114 = _tmp113 * _tmp73;
  const Scalar _tmp115 = _tmp88 * _tmp95;
  const Scalar _tmp116 = -_tmp114 * _tmp68 + _tmp115 * _tmp83 - _tmp52;
  const Scalar _tmp117 = _tmp109 * _tmp97;
  const Scalar _tmp118 = -_tmp107 + _tmp111 * _tmp83 - _tmp116 * _tmp117;
  const Scalar _tmp119 = _tmp110 * _tmp118;
  const Scalar _tmp120 = _tmp116 + _tmp119 * _tmp96;
  const Scalar _tmp121 = _tmp120 * _tmp97;
  const Scalar _tmp122 = _tmp90 * _tmp97;
  const Scalar _tmp123 = -_tmp120 * _tmp122 - _tmp83;
  const Scalar _tmp124 = _tmp84 * _tmp88;
  const Scalar _tmp125 = _tmp121 * _tmp61 + _tmp123 * _tmp124 + Scalar(1.0);
  const Scalar _tmp126 = _tmp106 * _tmp125;
  const Scalar _tmp127 = _tmp68 * _tmp73;
  const Scalar _tmp128 = _tmp127 * _tmp70 + _tmp66;
  const Scalar _tmp129 = 0;
  const Scalar _tmp130 = _tmp129 * _tmp97;
  const Scalar _tmp131 = _tmp130 * _tmp91;
  const Scalar _tmp132 = _tmp130 * _tmp61 - _tmp131 * _tmp84;
  const Scalar _tmp133 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp134 = _tmp106 * _tmp133;
  const Scalar _tmp135 = Scalar(1.0) * _tmp110;
  const Scalar _tmp136 = _tmp135 * _tmp91;
  const Scalar _tmp137 = _tmp135 * _tmp61 - _tmp136 * _tmp84;
  const Scalar _tmp138 = _tmp44 * _tmp46;
  const Scalar _tmp139 = _tmp43 * _tmp46;
  const Scalar _tmp140 = _tmp138 * _tmp33 - _tmp139 * _tmp34;
  const Scalar _tmp141 = _tmp140 * fh1;
  const Scalar _tmp142 = _tmp106 * _tmp141;
  const Scalar _tmp143 = Scalar(1.0) * _tmp112;
  const Scalar _tmp144 = -Scalar(1.0) * _tmp115 + _tmp127 * _tmp143;
  const Scalar _tmp145 = -Scalar(1.0) * _tmp111 - _tmp117 * _tmp144;
  const Scalar _tmp146 = _tmp110 * _tmp145;
  const Scalar _tmp147 = _tmp144 + _tmp146 * _tmp96;
  const Scalar _tmp148 = _tmp147 * _tmp97;
  const Scalar _tmp149 = -_tmp148 * _tmp90 + Scalar(1.0);
  const Scalar _tmp150 = _tmp149 * _tmp88;
  const Scalar _tmp151 = _tmp148 * _tmp61 + _tmp150 * _tmp84;
  const Scalar _tmp152 = _tmp138 * fh1;
  const Scalar _tmp153 = _tmp106 * _tmp152;
  const Scalar _tmp154 =
      std::exp(_tmp126 * _tmp48 + _tmp132 * _tmp134 + _tmp137 * _tmp142 + _tmp151 * _tmp153);
  const Scalar _tmp155 = -Scalar(1) / Scalar(2) * _tmp16 - Scalar(1) / Scalar(2) * _tmp17 -
                         Scalar(1) / Scalar(2) * _tmp18 + (Scalar(1) / Scalar(2)) * _tmp19;
  const Scalar _tmp156 = Scalar(0.41999999999999998) * _tmp155;
  const Scalar _tmp157 = _tmp156 * _tmp4;
  const Scalar _tmp158 = (Scalar(1) / Scalar(2)) * _tmp11;
  const Scalar _tmp159 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp160 = (Scalar(1) / Scalar(2)) * _tmp13;
  const Scalar _tmp161 = (Scalar(1) / Scalar(2)) * _tmp14;
  const Scalar _tmp162 = _tmp158 - _tmp159 + _tmp160 + _tmp161;
  const Scalar _tmp163 = Scalar(0.41999999999999998) * _tmp9;
  const Scalar _tmp164 = _tmp162 * _tmp163;
  const Scalar _tmp165 = _tmp157 + _tmp164;
  const Scalar _tmp166 = Scalar(0.83999999999999997) * _tmp162;
  const Scalar _tmp167 = _tmp166 * _tmp4;
  const Scalar _tmp168 = Scalar(0.021999999999999999) * _tmp15;
  const Scalar _tmp169 = -_tmp155 * _tmp168;
  const Scalar _tmp170 = (Scalar(1) / Scalar(2)) * _tmp5;
  const Scalar _tmp171 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp172 = (Scalar(1) / Scalar(2)) * _tmp7;
  const Scalar _tmp173 = (Scalar(1) / Scalar(2)) * _tmp8;
  const Scalar _tmp174 = _tmp170 - _tmp171 - _tmp172 - _tmp173;
  const Scalar _tmp175 = Scalar(0.021999999999999999) * _tmp4;
  const Scalar _tmp176 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp177 = (Scalar(1) / Scalar(2)) * _tmp1;
  const Scalar _tmp178 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp179 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp180 = -_tmp176 - _tmp177 + _tmp178 - _tmp179;
  const Scalar _tmp181 = Scalar(0.021999999999999999) * _tmp9;
  const Scalar _tmp182 = _tmp180 * _tmp181;
  const Scalar _tmp183 = Scalar(0.021999999999999999) * _tmp20;
  const Scalar _tmp184 = -_tmp162 * _tmp183 + _tmp169 - _tmp174 * _tmp175 - _tmp182;
  const Scalar _tmp185 = _tmp167 + _tmp184;
  const Scalar _tmp186 = Scalar(0.83999999999999997) * _tmp15;
  const Scalar _tmp187 = _tmp180 * _tmp186;
  const Scalar _tmp188 = Scalar(0.41999999999999998) * _tmp15;
  const Scalar _tmp189 = _tmp174 * _tmp188;
  const Scalar _tmp190 = -_tmp189;
  const Scalar _tmp191 = Scalar(0.41999999999999998) * _tmp180;
  const Scalar _tmp192 = _tmp191 * _tmp20;
  const Scalar _tmp193 = _tmp190 - _tmp192;
  const Scalar _tmp194 = _tmp187 + _tmp193;
  const Scalar _tmp195 = _tmp165 + _tmp185 + _tmp194;
  const Scalar _tmp196 = Scalar(1.0) / (_tmp99);
  const Scalar _tmp197 = _tmp101 * _tmp196;
  const Scalar _tmp198 = _tmp132 * _tmp133;
  const Scalar _tmp199 = _tmp197 * _tmp198;
  const Scalar _tmp200 = -_tmp157;
  const Scalar _tmp201 = -_tmp164 + _tmp200;
  const Scalar _tmp202 = _tmp189 + _tmp192;
  const Scalar _tmp203 = _tmp187 + _tmp202;
  const Scalar _tmp204 = _tmp185 + _tmp201 + _tmp203;
  const Scalar _tmp205 = _tmp126 * _tmp47;
  const Scalar _tmp206 = _tmp195 * _tmp197;
  const Scalar _tmp207 = _tmp125 * _tmp48;
  const Scalar _tmp208 = _tmp137 * _tmp141;
  const Scalar _tmp209 = std::pow(_tmp87, Scalar(-2));
  const Scalar _tmp210 = Scalar(0.83999999999999997) * _tmp9;
  const Scalar _tmp211 = _tmp155 * _tmp210;
  const Scalar _tmp212 = -_tmp175 * _tmp180;
  const Scalar _tmp213 = _tmp155 * _tmp183;
  const Scalar _tmp214 = -_tmp162 * _tmp168 + _tmp174 * _tmp181 + _tmp212 + _tmp213;
  const Scalar _tmp215 = _tmp165 + _tmp214;
  const Scalar _tmp216 = _tmp203 + _tmp211 + _tmp215;
  const Scalar _tmp217 = 2 * _tmp75;
  const Scalar _tmp218 = -_tmp187;
  const Scalar _tmp219 = _tmp202 + _tmp218;
  const Scalar _tmp220 = -_tmp167 + _tmp184;
  const Scalar _tmp221 = _tmp201 + _tmp219 + _tmp220;
  const Scalar _tmp222 = 2 * _tmp76;
  const Scalar _tmp223 = _tmp216 * _tmp217 + _tmp221 * _tmp222;
  const Scalar _tmp224 = std::pow(_tmp77, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp225 = (Scalar(1) / Scalar(2)) * _tmp224;
  const Scalar _tmp226 = _tmp225 * _tmp75;
  const Scalar _tmp227 = _tmp223 * _tmp226;
  const Scalar _tmp228 = -_tmp211;
  const Scalar _tmp229 = _tmp193 + _tmp218;
  const Scalar _tmp230 = _tmp201 + _tmp214;
  const Scalar _tmp231 = _tmp228 + _tmp229 + _tmp230;
  const Scalar _tmp232 = _tmp231 * _tmp82;
  const Scalar _tmp233 = _tmp196 * _tmp80;
  const Scalar _tmp234 = _tmp195 * _tmp233;
  const Scalar _tmp235 = _tmp216 * _tmp78;
  const Scalar _tmp236 = _tmp225 * _tmp76;
  const Scalar _tmp237 = _tmp223 * _tmp236;
  const Scalar _tmp238 = _tmp221 * _tmp78;
  const Scalar _tmp239 = _tmp209 * (_tmp227 + _tmp232 * _tmp84 - _tmp234 * _tmp84 - _tmp235 -
                                    _tmp237 * _tmp83 + _tmp238 * _tmp83);
  const Scalar _tmp240 = _tmp123 * _tmp84;
  const Scalar _tmp241 = _tmp215 + _tmp219 + _tmp228;
  const Scalar _tmp242 = 2 * _tmp55;
  const Scalar _tmp243 = _tmp165 + _tmp220 + _tmp229;
  const Scalar _tmp244 = 2 * _tmp58;
  const Scalar _tmp245 = _tmp241 * _tmp242 + _tmp243 * _tmp244;
  const Scalar _tmp246 = std::pow(_tmp59, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp247 = (Scalar(1) / Scalar(2)) * _tmp246;
  const Scalar _tmp248 = _tmp247 * _tmp58;
  const Scalar _tmp249 = _tmp245 * _tmp248;
  const Scalar _tmp250 = Scalar(0.41999999999999998) * _tmp4;
  const Scalar _tmp251 = _tmp174 * _tmp250;
  const Scalar _tmp252 = Scalar(0.41999999999999998) * _tmp20;
  const Scalar _tmp253 = _tmp162 * _tmp252;
  const Scalar _tmp254 = _tmp191 * _tmp4;
  const Scalar _tmp255 = _tmp156 * _tmp20;
  const Scalar _tmp256 = _tmp254 + _tmp255;
  const Scalar _tmp257 = Scalar(0.043999999999999997) * _tmp4;
  const Scalar _tmp258 = _tmp162 * _tmp257;
  const Scalar _tmp259 = Scalar(0.043999999999999997) * _tmp9;
  const Scalar _tmp260 = _tmp155 * _tmp259;
  const Scalar _tmp261 = _tmp258 + _tmp260;
  const Scalar _tmp262 = _tmp162 * _tmp188;
  const Scalar _tmp263 = _tmp163 * _tmp174;
  const Scalar _tmp264 = _tmp262 + _tmp263;
  const Scalar _tmp265 = _tmp15 * _tmp156;
  const Scalar _tmp266 = _tmp191 * _tmp9;
  const Scalar _tmp267 = -_tmp265 - _tmp266;
  const Scalar _tmp268 = _tmp251 + _tmp253 + _tmp256 + _tmp261 + _tmp264 + _tmp267;
  const Scalar _tmp269 = _tmp268 * _tmp83;
  const Scalar _tmp270 = _tmp86 * _tmp90;
  const Scalar _tmp271 = _tmp238 * _tmp52;
  const Scalar _tmp272 = -_tmp251;
  const Scalar _tmp273 = -_tmp253;
  const Scalar _tmp274 = _tmp261 + _tmp272 + _tmp273;
  const Scalar _tmp275 = -_tmp263;
  const Scalar _tmp276 = -_tmp254;
  const Scalar _tmp277 = -_tmp255;
  const Scalar _tmp278 = _tmp265 + _tmp266;
  const Scalar _tmp279 = _tmp276 + _tmp277 + _tmp278;
  const Scalar _tmp280 = -_tmp262 + _tmp275 + _tmp279;
  const Scalar _tmp281 = _tmp274 + _tmp280;
  const Scalar _tmp282 = -_tmp227 * _tmp74 - _tmp232 * _tmp85 + _tmp234 * _tmp85 +
                         _tmp235 * _tmp74 + _tmp237 * _tmp92 - _tmp269 * _tmp84 - _tmp271 * _tmp83 +
                         _tmp281 * _tmp79;
  const Scalar _tmp283 = _tmp232 * _tmp52;
  const Scalar _tmp284 = _tmp247 * _tmp55;
  const Scalar _tmp285 = _tmp245 * _tmp284;
  const Scalar _tmp286 = _tmp241 * _tmp60;
  const Scalar _tmp287 = _tmp256 + _tmp278;
  const Scalar _tmp288 = _tmp264 + _tmp274 + _tmp287;
  const Scalar _tmp289 = _tmp243 * _tmp60;
  const Scalar _tmp290 =
      _tmp232 * _tmp61 - _tmp234 * _tmp61 - _tmp249 * _tmp83 + _tmp285 - _tmp286 + _tmp289 * _tmp83;
  const Scalar _tmp291 = _tmp52 * _tmp60;
  const Scalar _tmp292 = _tmp243 * _tmp291;
  const Scalar _tmp293 = _tmp174 * _tmp186;
  const Scalar _tmp294 = Scalar(1.6799999999999999) * _tmp9;
  const Scalar _tmp295 = Scalar(0.83999999999999997) * _tmp20;
  const Scalar _tmp296 = _tmp180 * _tmp295;
  const Scalar _tmp297 = Scalar(0.83999999999999997) * _tmp4;
  const Scalar _tmp298 = _tmp155 * _tmp297;
  const Scalar _tmp299 = Scalar(1.6799999999999999) * _tmp15;
  const Scalar _tmp300 = _tmp166 * _tmp9 + _tmp180 * _tmp299 + _tmp298;
  const Scalar _tmp301 = _tmp155 * _tmp294 + _tmp293 + _tmp296 + _tmp300;
  const Scalar _tmp302 = _tmp68 / std::pow(_tmp72, Scalar(2));
  const Scalar _tmp303 = _tmp302 * _tmp93;
  const Scalar _tmp304 = _tmp90 * _tmp95;
  const Scalar _tmp305 = Scalar(1.6799999999999999) * _tmp4;
  const Scalar _tmp306 = _tmp162 * _tmp305 - _tmp293 - _tmp296 + _tmp300;
  const Scalar _tmp307 = _tmp60 * _tmp64;
  const Scalar _tmp308 = -_tmp237 * _tmp52 + _tmp237 * _tmp74 - _tmp238 * _tmp74 +
                         _tmp268 * _tmp84 + _tmp271 - _tmp281 * _tmp84;
  const Scalar _tmp309 =
      -_tmp115 * _tmp290 -
      _tmp127 * (-_tmp112 * _tmp290 + _tmp234 * _tmp62 + _tmp239 * _tmp270 + _tmp249 * _tmp92 -
                 _tmp269 * _tmp61 - _tmp282 * _tmp91 - _tmp283 * _tmp61 - _tmp285 * _tmp64 +
                 _tmp286 * _tmp64 + _tmp288 * _tmp89 - _tmp292 * _tmp83) +
      _tmp239 * _tmp304 - _tmp243 * _tmp307 - _tmp249 * _tmp52 + _tmp249 * _tmp64 +
      _tmp268 * _tmp61 - _tmp288 * _tmp61 + _tmp292 + _tmp301 * _tmp303 - _tmp306 * _tmp94 -
      _tmp308 * _tmp91;
  const Scalar _tmp310 = std::pow(_tmp96, Scalar(-2));
  const Scalar _tmp311 = _tmp309 * _tmp310;
  const Scalar _tmp312 = _tmp120 * _tmp61;
  const Scalar _tmp313 = _tmp105 * _tmp197;
  const Scalar _tmp314 = _tmp195 * _tmp313;
  const Scalar _tmp315 = _tmp83 * _tmp88;
  const Scalar _tmp316 = _tmp83 * _tmp86;
  const Scalar _tmp317 = _tmp113 * _tmp302;
  const Scalar _tmp318 = _tmp83 * _tmp95;
  const Scalar _tmp319 = -_tmp114 * _tmp306 + _tmp115 * _tmp232 - _tmp115 * _tmp234 -
                         _tmp127 * (_tmp112 * _tmp232 - _tmp112 * _tmp234 - _tmp234 * _tmp52 -
                                    _tmp239 * _tmp316 + _tmp269 + _tmp282 * _tmp315 + _tmp283) -
                         _tmp239 * _tmp318 - _tmp258 - _tmp260 + _tmp272 + _tmp273 + _tmp280 +
                         _tmp301 * _tmp317 + _tmp308 * _tmp315;
  const Scalar _tmp320 = _tmp65 * _tmp80;
  const Scalar _tmp321 = 2 * _tmp81;
  const Scalar _tmp322 = 2 * _tmp80;
  const Scalar _tmp323 = _tmp195 * _tmp321 + _tmp231 * _tmp322;
  const Scalar _tmp324 = (Scalar(1) / Scalar(2)) / (_tmp100 * std::sqrt(_tmp100));
  const Scalar _tmp325 = _tmp323 * _tmp324;
  const Scalar _tmp326 = _tmp69 * _tmp81;
  const Scalar _tmp327 = _tmp102 * _tmp80;
  const Scalar _tmp328 = _tmp102 * _tmp69;
  const Scalar _tmp329 = _tmp106 * (-_tmp103 * _tmp231 + _tmp104 * _tmp231 + _tmp195 * _tmp327 -
                                    _tmp195 * _tmp328 - _tmp320 * _tmp325 + _tmp325 * _tmp326);
  const Scalar _tmp330 = (Scalar(1) / Scalar(2)) * _tmp102 * _tmp82;
  const Scalar _tmp331 = _tmp105 * _tmp330;
  const Scalar _tmp332 = _tmp323 * _tmp331;
  const Scalar _tmp333 = _tmp108 * _tmp90;
  const Scalar _tmp334 = -_tmp107 * _tmp237 + _tmp107 * _tmp238 - _tmp221 * _tmp79 +
                         _tmp227 * _tmp67 - _tmp235 * _tmp67 + _tmp235 * _tmp76 - _tmp237 * _tmp71 +
                         _tmp238 * _tmp71 - _tmp314 * _tmp84 + _tmp329 * _tmp84 + _tmp332 * _tmp84;
  const Scalar _tmp335 = -_tmp107 * _tmp249 + _tmp107 * _tmp289 - _tmp111 * _tmp290 +
                         _tmp239 * _tmp333 - _tmp243 * _tmp89 + _tmp243 * _tmp98 -
                         _tmp249 * _tmp54 + _tmp285 * _tmp57 - _tmp286 * _tmp57 + _tmp286 * _tmp58 -
                         _tmp314 * _tmp61 + _tmp329 * _tmp61 + _tmp332 * _tmp61 - _tmp334 * _tmp91;
  const Scalar _tmp336 = _tmp116 * _tmp97;
  const Scalar _tmp337 = _tmp108 * _tmp83;
  const Scalar _tmp338 = _tmp109 * _tmp116;
  const Scalar _tmp339 = _tmp110 * _tmp96;
  const Scalar _tmp340 = std::pow(_tmp109, Scalar(-2));
  const Scalar _tmp341 = _tmp340 * _tmp96;
  const Scalar _tmp342 = _tmp118 * _tmp341;
  const Scalar _tmp343 = _tmp119 * _tmp309 + _tmp319 - _tmp335 * _tmp342 +
                         _tmp339 * (_tmp111 * _tmp232 - _tmp111 * _tmp234 - _tmp117 * _tmp319 -
                                    _tmp239 * _tmp337 + _tmp311 * _tmp338 + _tmp314 +
                                    _tmp315 * _tmp334 - _tmp329 - _tmp332 - _tmp335 * _tmp336);
  const Scalar _tmp344 = _tmp61 * _tmp97;
  const Scalar _tmp345 = _tmp120 * _tmp90;
  const Scalar _tmp346 =
      -_tmp121 * _tmp290 - _tmp122 * _tmp343 - _tmp232 + _tmp234 + _tmp311 * _tmp345;
  const Scalar _tmp347 = _tmp123 * _tmp88;
  const Scalar _tmp348 = _tmp106 * _tmp48;
  const Scalar _tmp349 = _tmp84 * _tmp91;
  const Scalar _tmp350 = _tmp129 * _tmp349;
  const Scalar _tmp351 = _tmp129 * _tmp61;
  const Scalar _tmp352 = _tmp239 * _tmp84;
  const Scalar _tmp353 = _tmp122 * _tmp129;
  const Scalar _tmp354 = _tmp124 * _tmp130;
  const Scalar _tmp355 = _tmp194 + _tmp211 + _tmp230;
  const Scalar _tmp356 = _tmp355 * _tmp46;
  const Scalar _tmp357 = _tmp106 * fh1;
  const Scalar _tmp358 = _tmp151 * _tmp357;
  const Scalar _tmp359 = Scalar(1.0) * _tmp340;
  const Scalar _tmp360 = _tmp335 * _tmp359;
  const Scalar _tmp361 = Scalar(0.5) * _tmp110;
  const Scalar _tmp362 = _tmp246 * _tmp361 * _tmp58;
  const Scalar _tmp363 = Scalar(1.0) * _tmp88;
  const Scalar _tmp364 = _tmp110 * _tmp363;
  const Scalar _tmp365 = _tmp364 * _tmp84;
  const Scalar _tmp366 = _tmp224 * _tmp361 * _tmp76 * _tmp91;
  const Scalar _tmp367 = _tmp135 * _tmp90;
  const Scalar _tmp368 = 2 * _tmp44;
  const Scalar _tmp369 = 2 * _tmp34;
  const Scalar _tmp370 = (Scalar(1) / Scalar(2)) / (_tmp45 * std::sqrt(_tmp45));
  const Scalar _tmp371 = _tmp370 * (_tmp204 * _tmp369 + _tmp355 * _tmp368);
  const Scalar _tmp372 = _tmp34 * _tmp43;
  const Scalar _tmp373 = _tmp33 * _tmp44;
  const Scalar _tmp374 = _tmp138 * _tmp204 - _tmp139 * _tmp204 + _tmp33 * _tmp356 -
                         _tmp34 * _tmp356 + _tmp371 * _tmp372 - _tmp371 * _tmp373;
  const Scalar _tmp375 = _tmp137 * _tmp357;
  const Scalar _tmp376 = _tmp208 * _tmp330;
  const Scalar _tmp377 = _tmp151 * _tmp152;
  const Scalar _tmp378 = _tmp358 * _tmp44;
  const Scalar _tmp379 = _tmp125 * _tmp34 * _tmp357;
  const Scalar _tmp380 = _tmp198 * _tmp330;
  const Scalar _tmp381 = _tmp147 * _tmp90;
  const Scalar _tmp382 = Scalar(1.0) * _tmp108;
  const Scalar _tmp383 = _tmp109 * _tmp144;
  const Scalar _tmp384 = _tmp144 * _tmp97;
  const Scalar _tmp385 = _tmp143 * _tmp302;
  const Scalar _tmp386 = _tmp127 * _tmp363;
  const Scalar _tmp387 = Scalar(1.0) * _tmp95;
  const Scalar _tmp388 = _tmp143 * _tmp73;
  const Scalar _tmp389 = _tmp127 * _tmp86;
  const Scalar _tmp390 = Scalar(1.0) * _tmp389;
  const Scalar _tmp391 = _tmp239 * _tmp387 - _tmp239 * _tmp390 + _tmp282 * _tmp386 -
                         _tmp301 * _tmp385 + _tmp306 * _tmp388 - _tmp308 * _tmp363;
  const Scalar _tmp392 = _tmp145 * _tmp341;
  const Scalar _tmp393 = _tmp146 * _tmp309 - _tmp335 * _tmp392 +
                         _tmp339 * (-_tmp117 * _tmp391 + _tmp239 * _tmp382 + _tmp311 * _tmp383 -
                                    _tmp334 * _tmp363 - _tmp335 * _tmp384) +
                         _tmp391;
  const Scalar _tmp394 = -_tmp122 * _tmp393 - _tmp148 * _tmp290 + _tmp311 * _tmp381;
  const Scalar _tmp395 = _tmp149 * _tmp84;
  const Scalar _tmp396 = _tmp147 * _tmp61;
  const Scalar _tmp397 = _tmp207 * _tmp330;
  const Scalar _tmp398 = _tmp330 * _tmp377;
  const Scalar _tmp399 = _tmp135 * fh1;
  const Scalar _tmp400 = _tmp140 * _tmp399;
  const Scalar _tmp401 = _tmp129 * _tmp133;
  const Scalar _tmp402 = _tmp401 * _tmp97;
  const Scalar _tmp403 = _tmp150 * fh1;
  const Scalar _tmp404 =
      std::exp(-_tmp138 * _tmp403 - _tmp347 * _tmp48 + _tmp400 * _tmp91 + _tmp402 * _tmp91);
  const Scalar _tmp405 = _tmp122 * _tmp401;
  const Scalar _tmp406 = _tmp374 * _tmp399;
  const Scalar _tmp407 = _tmp402 * _tmp88;
  const Scalar _tmp408 = _tmp347 * _tmp47;
  const Scalar _tmp409 = _tmp311 * _tmp401;
  const Scalar _tmp410 = _tmp403 * _tmp44;
  const Scalar _tmp411 = _tmp141 * _tmp364;
  const Scalar _tmp412 = _tmp48 * _tmp88;
  const Scalar _tmp413 = _tmp149 * _tmp152;
  const Scalar _tmp414 = _tmp123 * _tmp48;
  const Scalar _tmp415 = _tmp141 * _tmp360;
  const Scalar _tmp416 = _tmp34 * fh1;
  const Scalar _tmp417 = _tmp347 * _tmp416;
  const Scalar _tmp418 = _tmp152 * _tmp88;
  const Scalar _tmp419 = _tmp400 * _tmp90;
  const Scalar _tmp420 = _tmp148 * fh1;
  const Scalar _tmp421 = std::exp(-_tmp121 * _tmp48 - _tmp138 * _tmp420 - _tmp400 - _tmp402);
  const Scalar _tmp422 = _tmp120 * _tmp48;
  const Scalar _tmp423 = _tmp48 * _tmp97;
  const Scalar _tmp424 = _tmp147 * _tmp152;
  const Scalar _tmp425 = _tmp420 * _tmp44;
  const Scalar _tmp426 = _tmp121 * _tmp47;
  const Scalar _tmp427 = _tmp152 * _tmp97;
  const Scalar _tmp428 = _tmp121 * _tmp416;
  const Scalar _tmp429 = -_tmp158 + _tmp159 - _tmp160 - _tmp161;
  const Scalar _tmp430 = -_tmp170 + _tmp171 + _tmp172 + _tmp173;
  const Scalar _tmp431 = -_tmp168 * _tmp429 - _tmp181 * _tmp430 + _tmp212 - _tmp213;
  const Scalar _tmp432 = _tmp298 + _tmp431;
  const Scalar _tmp433 = _tmp250 * _tmp429;
  const Scalar _tmp434 = -_tmp433;
  const Scalar _tmp435 = _tmp156 * _tmp9;
  const Scalar _tmp436 = -_tmp435;
  const Scalar _tmp437 = _tmp434 + _tmp436;
  const Scalar _tmp438 = _tmp186 * _tmp430;
  const Scalar _tmp439 = _tmp15 * _tmp191;
  const Scalar _tmp440 = _tmp252 * _tmp430;
  const Scalar _tmp441 = _tmp439 + _tmp440;
  const Scalar _tmp442 = _tmp438 + _tmp441;
  const Scalar _tmp443 = _tmp432 + _tmp437 + _tmp442;
  const Scalar _tmp444 = -_tmp439 - _tmp440;
  const Scalar _tmp445 = _tmp438 + _tmp444;
  const Scalar _tmp446 = _tmp210 * _tmp429;
  const Scalar _tmp447 = _tmp169 - _tmp175 * _tmp430 + _tmp182 + _tmp183 * _tmp429;
  const Scalar _tmp448 = _tmp446 + _tmp447;
  const Scalar _tmp449 = _tmp437 + _tmp445 + _tmp448;
  const Scalar _tmp450 = _tmp370 * (_tmp368 * _tmp449 + _tmp369 * _tmp443);
  const Scalar _tmp451 = _tmp449 * _tmp46;
  const Scalar _tmp452 = _tmp138 * _tmp443 - _tmp139 * _tmp443 + _tmp33 * _tmp451 -
                         _tmp34 * _tmp451 + _tmp372 * _tmp450 - _tmp373 * _tmp450;
  const Scalar _tmp453 = _tmp433 + _tmp435;
  const Scalar _tmp454 = _tmp432 + _tmp445 + _tmp453;
  const Scalar _tmp455 = _tmp197 * _tmp454;
  const Scalar _tmp456 = -_tmp446 + _tmp447;
  const Scalar _tmp457 = -_tmp438;
  const Scalar _tmp458 = _tmp437 + _tmp457;
  const Scalar _tmp459 = _tmp444 + _tmp456 + _tmp458;
  const Scalar _tmp460 = _tmp321 * _tmp454 + _tmp322 * _tmp459;
  const Scalar _tmp461 = _tmp330 * _tmp460;
  const Scalar _tmp462 = _tmp295 * _tmp430;
  const Scalar _tmp463 = _tmp211 + _tmp297 * _tmp429 + _tmp299 * _tmp430;
  const Scalar _tmp464 = _tmp187 + _tmp294 * _tmp429 + _tmp462 + _tmp463;
  const Scalar _tmp465 = _tmp250 * _tmp430;
  const Scalar _tmp466 = _tmp252 * _tmp429;
  const Scalar _tmp467 = _tmp155 * _tmp257;
  const Scalar _tmp468 = _tmp259 * _tmp429;
  const Scalar _tmp469 = _tmp467 + _tmp468;
  const Scalar _tmp470 = _tmp465 + _tmp466 + _tmp469;
  const Scalar _tmp471 = _tmp188 * _tmp429;
  const Scalar _tmp472 = _tmp163 * _tmp430;
  const Scalar _tmp473 = _tmp471 + _tmp472;
  const Scalar _tmp474 = _tmp279 + _tmp470 + _tmp473;
  const Scalar _tmp475 = -_tmp471;
  const Scalar _tmp476 = _tmp287 + _tmp470 - _tmp472 + _tmp475;
  const Scalar _tmp477 = _tmp233 * _tmp454;
  const Scalar _tmp478 = _tmp453 + _tmp457;
  const Scalar _tmp479 = _tmp441 + _tmp456 + _tmp478;
  const Scalar _tmp480 = -_tmp298 + _tmp431;
  const Scalar _tmp481 = _tmp444 + _tmp478 + _tmp480;
  const Scalar _tmp482 = _tmp242 * _tmp479 + _tmp244 * _tmp481;
  const Scalar _tmp483 = _tmp284 * _tmp482;
  const Scalar _tmp484 = _tmp481 * _tmp60;
  const Scalar _tmp485 = _tmp459 * _tmp82;
  const Scalar _tmp486 = _tmp479 * _tmp60;
  const Scalar _tmp487 = _tmp248 * _tmp482;
  const Scalar _tmp488 = -_tmp477 * _tmp61 + _tmp483 + _tmp484 * _tmp83 + _tmp485 * _tmp61 -
                         _tmp486 - _tmp487 * _tmp83;
  const Scalar _tmp489 = _tmp442 + _tmp448 + _tmp453;
  const Scalar _tmp490 = _tmp489 * _tmp78;
  const Scalar _tmp491 = _tmp441 + _tmp458 + _tmp480;
  const Scalar _tmp492 = _tmp217 * _tmp489 + _tmp222 * _tmp491;
  const Scalar _tmp493 = _tmp226 * _tmp492;
  const Scalar _tmp494 = _tmp236 * _tmp492;
  const Scalar _tmp495 = _tmp491 * _tmp78;
  const Scalar _tmp496 = _tmp209 * (-_tmp477 * _tmp84 + _tmp485 * _tmp84 - _tmp490 + _tmp493 -
                                    _tmp494 * _tmp83 + _tmp495 * _tmp83);
  const Scalar _tmp497 = _tmp476 * _tmp83;
  const Scalar _tmp498 = _tmp267 + _tmp276 + _tmp277 - _tmp465 - _tmp466 + _tmp473;
  const Scalar _tmp499 = _tmp469 + _tmp498;
  const Scalar _tmp500 = _tmp476 * _tmp84;
  const Scalar _tmp501 = _tmp495 * _tmp52;
  const Scalar _tmp502 = _tmp477 * _tmp85 - _tmp485 * _tmp85 + _tmp490 * _tmp74 - _tmp493 * _tmp74 +
                         _tmp494 * _tmp92 + _tmp499 * _tmp79 - _tmp500 * _tmp83 - _tmp501 * _tmp83;
  const Scalar _tmp503 = _tmp291 * _tmp481;
  const Scalar _tmp504 = _tmp485 * _tmp52;
  const Scalar _tmp505 = _tmp155 * _tmp305 + _tmp218 - _tmp462 + _tmp463;
  const Scalar _tmp506 = -_tmp494 * _tmp52 + _tmp494 * _tmp74 - _tmp495 * _tmp74 -
                         _tmp499 * _tmp84 + _tmp500 + _tmp501;
  const Scalar _tmp507 =
      -_tmp115 * _tmp488 -
      _tmp127 * (-_tmp112 * _tmp488 + _tmp270 * _tmp496 + _tmp474 * _tmp89 + _tmp477 * _tmp62 -
                 _tmp483 * _tmp64 + _tmp486 * _tmp64 + _tmp487 * _tmp92 - _tmp497 * _tmp61 -
                 _tmp502 * _tmp91 - _tmp503 * _tmp83 - _tmp504 * _tmp61) +
      _tmp303 * _tmp464 + _tmp304 * _tmp496 - _tmp307 * _tmp481 - _tmp474 * _tmp61 +
      _tmp476 * _tmp61 - _tmp487 * _tmp52 + _tmp487 * _tmp64 + _tmp503 - _tmp505 * _tmp94 -
      _tmp506 * _tmp91;
  const Scalar _tmp508 = _tmp310 * _tmp507;
  const Scalar _tmp509 = _tmp508 * _tmp61;
  const Scalar _tmp510 = Scalar(1.0) * _tmp496;
  const Scalar _tmp511 = -_tmp363 * _tmp506 - _tmp385 * _tmp464 + _tmp386 * _tmp502 +
                         _tmp388 * _tmp505 - _tmp389 * _tmp510 + _tmp510 * _tmp95;
  const Scalar _tmp512 = _tmp313 * _tmp454;
  const Scalar _tmp513 = _tmp324 * _tmp460;
  const Scalar _tmp514 = _tmp106 * (-_tmp103 * _tmp459 + _tmp104 * _tmp459 - _tmp320 * _tmp513 +
                                    _tmp326 * _tmp513 + _tmp327 * _tmp454 - _tmp328 * _tmp454);
  const Scalar _tmp515 = _tmp331 * _tmp460;
  const Scalar _tmp516 = -_tmp107 * _tmp494 + _tmp107 * _tmp495 - _tmp490 * _tmp67 +
                         _tmp490 * _tmp76 - _tmp491 * _tmp79 + _tmp493 * _tmp67 - _tmp494 * _tmp71 +
                         _tmp495 * _tmp71 - _tmp512 * _tmp84 + _tmp514 * _tmp84 + _tmp515 * _tmp84;
  const Scalar _tmp517 = _tmp107 * _tmp484 - _tmp107 * _tmp487 - _tmp111 * _tmp488 +
                         _tmp333 * _tmp496 - _tmp481 * _tmp89 + _tmp481 * _tmp98 +
                         _tmp483 * _tmp57 - _tmp486 * _tmp57 + _tmp486 * _tmp58 - _tmp487 * _tmp54 -
                         _tmp512 * _tmp61 + _tmp514 * _tmp61 + _tmp515 * _tmp61 - _tmp516 * _tmp91;
  const Scalar _tmp518 = _tmp146 * _tmp507 +
                         _tmp339 * (_tmp108 * _tmp510 - _tmp117 * _tmp511 - _tmp363 * _tmp516 +
                                    _tmp383 * _tmp508 - _tmp384 * _tmp517) -
                         _tmp392 * _tmp517 + _tmp511;
  const Scalar _tmp519 = -_tmp122 * _tmp518 - _tmp148 * _tmp488 + _tmp381 * _tmp508;
  const Scalar _tmp520 = -_tmp114 * _tmp505 - _tmp115 * _tmp477 + _tmp115 * _tmp485 -
                         _tmp127 * (-_tmp112 * _tmp477 + _tmp112 * _tmp485 + _tmp315 * _tmp502 -
                                    _tmp316 * _tmp496 - _tmp477 * _tmp52 + _tmp497 + _tmp504) +
                         _tmp315 * _tmp506 + _tmp317 * _tmp464 - _tmp318 * _tmp496 - _tmp467 -
                         _tmp468 + _tmp498;
  const Scalar _tmp521 = _tmp119 * _tmp507 +
                         _tmp339 * (-_tmp111 * _tmp477 + _tmp111 * _tmp485 - _tmp117 * _tmp520 +
                                    _tmp315 * _tmp516 - _tmp336 * _tmp517 - _tmp337 * _tmp496 +
                                    _tmp338 * _tmp508 + _tmp512 - _tmp514 - _tmp515) -
                         _tmp342 * _tmp517 + _tmp520;
  const Scalar _tmp522 =
      -_tmp121 * _tmp488 - _tmp122 * _tmp521 + _tmp345 * _tmp508 + _tmp477 - _tmp485;
  const Scalar _tmp523 = _tmp496 * _tmp84;
  const Scalar _tmp524 = _tmp359 * _tmp61;
  const Scalar _tmp525 = _tmp349 * _tmp359;
  const Scalar _tmp526 = _tmp399 * _tmp452;
  const Scalar _tmp527 = _tmp401 * _tmp508;
  const Scalar _tmp528 = _tmp141 * _tmp359;
  const Scalar _tmp529 = _tmp517 * _tmp528;
  const Scalar _tmp530 = _tmp155 * _tmp186;
  const Scalar _tmp531 = _tmp277 + _tmp475;
  const Scalar _tmp532 = _tmp530 + _tmp531;
  const Scalar _tmp533 = _tmp176 + _tmp177 - _tmp178 + _tmp179;
  const Scalar _tmp534 = _tmp250 * _tmp533;
  const Scalar _tmp535 = _tmp263 + _tmp534;
  const Scalar _tmp536 = _tmp174 * _tmp297;
  const Scalar _tmp537 =
      -_tmp155 * _tmp181 - _tmp168 * _tmp533 - _tmp174 * _tmp183 - _tmp175 * _tmp429;
  const Scalar _tmp538 = _tmp536 + _tmp537;
  const Scalar _tmp539 = _tmp532 + _tmp535 + _tmp538;
  const Scalar _tmp540 = _tmp197 * _tmp539;
  const Scalar _tmp541 = _tmp210 * _tmp533;
  const Scalar _tmp542 =
      -_tmp155 * _tmp175 - _tmp168 * _tmp174 + _tmp181 * _tmp429 + _tmp183 * _tmp533;
  const Scalar _tmp543 = _tmp541 + _tmp542;
  const Scalar _tmp544 = _tmp255 + _tmp471;
  const Scalar _tmp545 = _tmp535 + _tmp544;
  const Scalar _tmp546 = _tmp530 + _tmp543 + _tmp545;
  const Scalar _tmp547 = -_tmp530;
  const Scalar _tmp548 = -_tmp536 + _tmp537;
  const Scalar _tmp549 = _tmp275 - _tmp534;
  const Scalar _tmp550 = _tmp544 + _tmp549;
  const Scalar _tmp551 = _tmp547 + _tmp548 + _tmp550;
  const Scalar _tmp552 = _tmp217 * _tmp546 + _tmp222 * _tmp551;
  const Scalar _tmp553 = _tmp531 + _tmp547;
  const Scalar _tmp554 = -_tmp541 + _tmp542;
  const Scalar _tmp555 = _tmp549 + _tmp553 + _tmp554;
  const Scalar _tmp556 = _tmp102 * _tmp539;
  const Scalar _tmp557 = _tmp321 * _tmp539 + _tmp322 * _tmp555;
  const Scalar _tmp558 = _tmp324 * _tmp557;
  const Scalar _tmp559 = _tmp106 * (-_tmp103 * _tmp555 + _tmp104 * _tmp555 - _tmp320 * _tmp558 +
                                    _tmp326 * _tmp558 - _tmp556 * _tmp69 + _tmp556 * _tmp80);
  const Scalar _tmp560 = _tmp236 * _tmp552;
  const Scalar _tmp561 = _tmp233 * _tmp539;
  const Scalar _tmp562 = _tmp546 * _tmp78;
  const Scalar _tmp563 = _tmp555 * _tmp82;
  const Scalar _tmp564 = _tmp226 * _tmp552;
  const Scalar _tmp565 = _tmp551 * _tmp78;
  const Scalar _tmp566 = _tmp209 * (-_tmp560 * _tmp83 - _tmp561 * _tmp84 - _tmp562 +
                                    _tmp563 * _tmp84 + _tmp564 + _tmp565 * _tmp83);
  const Scalar _tmp567 = _tmp313 * _tmp539;
  const Scalar _tmp568 = _tmp545 + _tmp547 + _tmp554;
  const Scalar _tmp569 = _tmp535 + _tmp548 + _tmp553;
  const Scalar _tmp570 = _tmp242 * _tmp568 + _tmp244 * _tmp569;
  const Scalar _tmp571 = _tmp248 * _tmp570;
  const Scalar _tmp572 = _tmp331 * _tmp557;
  const Scalar _tmp573 =
      _tmp88 * (-_tmp107 * _tmp560 + _tmp107 * _tmp565 - _tmp551 * _tmp79 + _tmp559 * _tmp84 -
                _tmp560 * _tmp71 - _tmp562 * _tmp67 + _tmp562 * _tmp76 + _tmp564 * _tmp67 +
                _tmp565 * _tmp71 - _tmp567 * _tmp84 + _tmp572 * _tmp84);
  const Scalar _tmp574 = _tmp284 * _tmp570;
  const Scalar _tmp575 = _tmp568 * _tmp60;
  const Scalar _tmp576 = _tmp569 * _tmp60;
  const Scalar _tmp577 = -_tmp561 * _tmp61 + _tmp563 * _tmp61 - _tmp571 * _tmp83 + _tmp574 -
                         _tmp575 + _tmp576 * _tmp83;
  const Scalar _tmp578 = -_tmp107 * _tmp571 + _tmp107 * _tmp576 - _tmp111 * _tmp577 +
                         _tmp333 * _tmp566 - _tmp54 * _tmp571 + _tmp559 * _tmp61 -
                         _tmp567 * _tmp61 - _tmp569 * _tmp89 + _tmp569 * _tmp98 + _tmp57 * _tmp574 -
                         _tmp57 * _tmp575 + _tmp572 * _tmp61 - _tmp573 * _tmp90 + _tmp575 * _tmp58;
  const Scalar _tmp579 = _tmp566 * _tmp84;
  const Scalar _tmp580 = _tmp530 + _tmp538 + _tmp550;
  const Scalar _tmp581 = _tmp186 * _tmp429;
  const Scalar _tmp582 = _tmp155 * _tmp295;
  const Scalar _tmp583 = _tmp155 * _tmp299 + _tmp174 * _tmp210 + _tmp297 * _tmp533;
  const Scalar _tmp584 = _tmp294 * _tmp533 + _tmp581 + _tmp582 + _tmp583;
  const Scalar _tmp585 = _tmp163 * _tmp429;
  const Scalar _tmp586 = _tmp252 * _tmp533;
  const Scalar _tmp587 = _tmp174 * _tmp257;
  const Scalar _tmp588 = _tmp259 * _tmp533;
  const Scalar _tmp589 = _tmp587 + _tmp588;
  const Scalar _tmp590 = _tmp157 + _tmp189 + _tmp585 + _tmp586 + _tmp589;
  const Scalar _tmp591 = _tmp188 * _tmp533;
  const Scalar _tmp592 = _tmp174 * _tmp252;
  const Scalar _tmp593 = _tmp434 + _tmp435 + _tmp591 - _tmp592;
  const Scalar _tmp594 = _tmp590 + _tmp593;
  const Scalar _tmp595 = _tmp433 + _tmp436 + _tmp590 - _tmp591 + _tmp592;
  const Scalar _tmp596 = _tmp595 * _tmp61;
  const Scalar _tmp597 = _tmp291 * _tmp569;
  const Scalar _tmp598 = _tmp190 + _tmp200 - _tmp585 - _tmp586 + _tmp593;
  const Scalar _tmp599 = _tmp589 + _tmp598;
  const Scalar _tmp600 = _tmp595 * _tmp84;
  const Scalar _tmp601 = _tmp52 * _tmp563;
  const Scalar _tmp602 = _tmp52 * _tmp565;
  const Scalar _tmp603 = _tmp560 * _tmp92 + _tmp561 * _tmp85 + _tmp562 * _tmp74 - _tmp564 * _tmp74 +
                         _tmp599 * _tmp79 - _tmp600 * _tmp83 - _tmp601 * _tmp84 - _tmp602 * _tmp83;
  const Scalar _tmp604 = _tmp174 * _tmp305 - _tmp581 - _tmp582 + _tmp583;
  const Scalar _tmp605 = -_tmp52 * _tmp560 + _tmp560 * _tmp74 - _tmp565 * _tmp74 -
                         _tmp599 * _tmp84 + _tmp600 + _tmp602;
  const Scalar _tmp606 =
      -_tmp115 * _tmp577 -
      _tmp127 * (-_tmp112 * _tmp577 + _tmp270 * _tmp566 + _tmp561 * _tmp62 + _tmp571 * _tmp92 -
                 _tmp574 * _tmp64 + _tmp575 * _tmp64 + _tmp594 * _tmp89 - _tmp596 * _tmp83 -
                 _tmp597 * _tmp83 - _tmp601 * _tmp61 - _tmp603 * _tmp91) +
      _tmp303 * _tmp584 + _tmp304 * _tmp566 - _tmp307 * _tmp569 - _tmp52 * _tmp571 +
      _tmp571 * _tmp64 - _tmp594 * _tmp61 + _tmp596 + _tmp597 - _tmp604 * _tmp94 - _tmp605 * _tmp91;
  const Scalar _tmp607 = _tmp310 * _tmp606;
  const Scalar _tmp608 = _tmp566 * _tmp83;
  const Scalar _tmp609 =
      -_tmp114 * _tmp604 - _tmp115 * _tmp561 + _tmp115 * _tmp563 -
      _tmp127 * (-_tmp112 * _tmp561 + _tmp112 * _tmp563 + _tmp315 * _tmp603 - _tmp52 * _tmp561 +
                 _tmp595 * _tmp83 + _tmp601 - _tmp608 * _tmp86) +
      _tmp315 * _tmp605 + _tmp317 * _tmp584 - _tmp587 - _tmp588 + _tmp598 - _tmp608 * _tmp95;
  const Scalar _tmp610 = _tmp119 * _tmp606 +
                         _tmp339 * (-_tmp111 * _tmp561 + _tmp111 * _tmp563 - _tmp117 * _tmp609 -
                                    _tmp336 * _tmp578 - _tmp337 * _tmp566 + _tmp338 * _tmp607 -
                                    _tmp559 + _tmp567 - _tmp572 + _tmp573 * _tmp83) -
                         _tmp342 * _tmp578 + _tmp609;
  const Scalar _tmp611 =
      -_tmp121 * _tmp577 - _tmp122 * _tmp610 + _tmp345 * _tmp607 + _tmp561 - _tmp563;
  const Scalar _tmp612 = _tmp532 + _tmp543 + _tmp549;
  const Scalar _tmp613 = _tmp370 * (_tmp368 * _tmp612 + _tmp369 * _tmp580);
  const Scalar _tmp614 = _tmp46 * _tmp612;
  const Scalar _tmp615 = _tmp138 * _tmp580 - _tmp139 * _tmp580 + _tmp33 * _tmp614 -
                         _tmp34 * _tmp614 + _tmp372 * _tmp613 - _tmp373 * _tmp613;
  const Scalar _tmp616 = -_tmp363 * _tmp605 - _tmp385 * _tmp584 + _tmp386 * _tmp603 +
                         _tmp387 * _tmp566 + _tmp388 * _tmp604 - _tmp390 * _tmp566;
  const Scalar _tmp617 = _tmp146 * _tmp606 +
                         _tmp339 * (-_tmp117 * _tmp616 + _tmp382 * _tmp566 + _tmp383 * _tmp607 -
                                    _tmp384 * _tmp578 - Scalar(1.0) * _tmp573) -
                         _tmp392 * _tmp578 + _tmp616;
  const Scalar _tmp618 = -_tmp122 * _tmp617 - _tmp148 * _tmp577 + _tmp381 * _tmp607;
  const Scalar _tmp619 = _tmp528 * _tmp578;
  const Scalar _tmp620 = _tmp399 * _tmp615;
  const Scalar _tmp621 = _tmp401 * _tmp607;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = 0;
  _res(1, 0) =
      -_tmp154 *
      (-_tmp134 * (-_tmp130 * _tmp249 + _tmp130 * _tmp289 + _tmp131 * _tmp237 - _tmp131 * _tmp238 -
                   _tmp290 * _tmp354 + _tmp311 * _tmp350 - _tmp311 * _tmp351 + _tmp352 * _tmp353) -
       _tmp142 * (_tmp135 * _tmp289 - _tmp136 * _tmp238 + _tmp223 * _tmp366 - _tmp245 * _tmp362 -
                  _tmp290 * _tmp365 + _tmp349 * _tmp360 + _tmp352 * _tmp367 - _tmp360 * _tmp61) -
       _tmp153 * (_tmp124 * _tmp394 - _tmp148 * _tmp249 + _tmp148 * _tmp289 - _tmp150 * _tmp237 +
                  _tmp150 * _tmp238 - _tmp239 * _tmp395 - _tmp311 * _tmp396 + _tmp344 * _tmp393) +
       _tmp195 * _tmp199 - _tmp204 * _tmp205 + _tmp206 * _tmp207 + _tmp206 * _tmp208 +
       _tmp206 * _tmp377 - _tmp323 * _tmp376 - _tmp323 * _tmp380 - _tmp323 * _tmp397 -
       _tmp323 * _tmp398 -
       _tmp348 * (-_tmp121 * _tmp249 + _tmp121 * _tmp289 + _tmp124 * _tmp346 - _tmp237 * _tmp347 +
                  _tmp238 * _tmp347 - _tmp239 * _tmp240 - _tmp311 * _tmp312 + _tmp343 * _tmp344) -
       _tmp356 * _tmp358 + _tmp371 * _tmp378 + _tmp371 * _tmp379 - _tmp374 * _tmp375);
  _res(2, 0) =
      -_tmp404 * (_tmp204 * _tmp408 + _tmp239 * _tmp405 - _tmp239 * _tmp413 - _tmp239 * _tmp414 +
                  _tmp239 * _tmp419 - _tmp290 * _tmp407 - _tmp290 * _tmp411 + _tmp346 * _tmp412 +
                  _tmp356 * _tmp403 - _tmp371 * _tmp410 - _tmp371 * _tmp417 + _tmp394 * _tmp418 -
                  _tmp406 * _tmp91 + _tmp409 * _tmp91 + _tmp415 * _tmp91);
  _res(3, 0) = -_tmp421 * (_tmp204 * _tmp426 - _tmp311 * _tmp422 - _tmp311 * _tmp424 +
                           _tmp343 * _tmp423 + _tmp356 * _tmp420 - _tmp371 * _tmp425 -
                           _tmp371 * _tmp428 + _tmp393 * _tmp427 + _tmp406 - _tmp409 - _tmp415);
  _res(0, 1) = 0;
  _res(1, 1) =
      -_tmp154 *
      (-_tmp134 * (-_tmp129 * _tmp509 + _tmp130 * _tmp484 - _tmp130 * _tmp487 + _tmp131 * _tmp494 -
                   _tmp131 * _tmp495 + _tmp350 * _tmp508 + _tmp353 * _tmp523 - _tmp354 * _tmp488) -
       _tmp142 * (_tmp135 * _tmp484 - _tmp136 * _tmp495 - _tmp362 * _tmp482 - _tmp365 * _tmp488 +
                  _tmp366 * _tmp492 + _tmp367 * _tmp523 - _tmp517 * _tmp524 + _tmp517 * _tmp525) -
       _tmp153 * (_tmp124 * _tmp519 - _tmp147 * _tmp509 + _tmp148 * _tmp484 - _tmp148 * _tmp487 -
                  _tmp150 * _tmp494 + _tmp150 * _tmp495 + _tmp344 * _tmp518 - _tmp395 * _tmp496) +
       _tmp198 * _tmp455 - _tmp205 * _tmp443 + _tmp207 * _tmp455 - _tmp207 * _tmp461 +
       _tmp208 * _tmp455 -
       _tmp348 * (-_tmp120 * _tmp509 + _tmp121 * _tmp484 - _tmp121 * _tmp487 + _tmp124 * _tmp522 -
                  _tmp240 * _tmp496 + _tmp344 * _tmp521 - _tmp347 * _tmp494 + _tmp347 * _tmp495) -
       _tmp358 * _tmp451 - _tmp375 * _tmp452 - _tmp376 * _tmp460 + _tmp377 * _tmp455 -
       _tmp377 * _tmp461 + _tmp378 * _tmp450 + _tmp379 * _tmp450 - _tmp380 * _tmp460);
  _res(2, 1) =
      -_tmp404 * (_tmp403 * _tmp451 + _tmp405 * _tmp496 - _tmp407 * _tmp488 + _tmp408 * _tmp443 -
                  _tmp410 * _tmp450 - _tmp411 * _tmp488 + _tmp412 * _tmp522 - _tmp413 * _tmp496 -
                  _tmp414 * _tmp496 - _tmp417 * _tmp450 + _tmp418 * _tmp519 + _tmp419 * _tmp496 -
                  _tmp526 * _tmp91 + _tmp527 * _tmp91 + _tmp529 * _tmp91);
  _res(3, 1) = -_tmp421 * (_tmp420 * _tmp451 - _tmp422 * _tmp508 + _tmp423 * _tmp521 -
                           _tmp424 * _tmp508 - _tmp425 * _tmp450 + _tmp426 * _tmp443 +
                           _tmp427 * _tmp518 - _tmp428 * _tmp450 + _tmp526 - _tmp527 - _tmp529);
  _res(0, 2) = 0;
  _res(1, 2) =
      -_tmp154 *
      (-_tmp134 * (-_tmp130 * _tmp571 + _tmp130 * _tmp576 + _tmp131 * _tmp560 - _tmp131 * _tmp565 +
                   _tmp350 * _tmp607 - _tmp351 * _tmp607 + _tmp353 * _tmp579 - _tmp354 * _tmp577) -
       _tmp142 * (_tmp135 * _tmp576 - _tmp136 * _tmp565 - _tmp362 * _tmp570 - _tmp365 * _tmp577 +
                  _tmp366 * _tmp552 + _tmp367 * _tmp579 - _tmp524 * _tmp578 + _tmp525 * _tmp578) -
       _tmp153 * (_tmp124 * _tmp618 - _tmp148 * _tmp571 + _tmp148 * _tmp576 - _tmp149 * _tmp579 -
                  _tmp150 * _tmp560 + _tmp150 * _tmp565 + _tmp344 * _tmp617 - _tmp396 * _tmp607) +
       _tmp199 * _tmp539 - _tmp205 * _tmp580 + _tmp207 * _tmp540 + _tmp208 * _tmp540 -
       _tmp348 * (-_tmp121 * _tmp571 + _tmp121 * _tmp576 - _tmp123 * _tmp579 + _tmp124 * _tmp611 -
                  _tmp312 * _tmp607 + _tmp344 * _tmp610 - _tmp347 * _tmp560 + _tmp347 * _tmp565) -
       _tmp358 * _tmp614 - _tmp375 * _tmp615 - _tmp376 * _tmp557 + _tmp377 * _tmp540 +
       _tmp378 * _tmp613 + _tmp379 * _tmp613 - _tmp380 * _tmp557 - _tmp397 * _tmp557 -
       _tmp398 * _tmp557);
  _res(2, 2) =
      -_tmp404 * (_tmp403 * _tmp614 + _tmp405 * _tmp566 - _tmp407 * _tmp577 + _tmp408 * _tmp580 -
                  _tmp410 * _tmp613 - _tmp411 * _tmp577 + _tmp412 * _tmp611 - _tmp413 * _tmp566 -
                  _tmp414 * _tmp566 - _tmp417 * _tmp613 + _tmp418 * _tmp618 + _tmp419 * _tmp566 +
                  _tmp619 * _tmp91 - _tmp620 * _tmp91 + _tmp621 * _tmp91);
  _res(3, 2) = -_tmp421 * (_tmp420 * _tmp614 - _tmp422 * _tmp607 + _tmp423 * _tmp610 -
                           _tmp424 * _tmp607 - _tmp425 * _tmp613 + _tmp426 * _tmp580 +
                           _tmp427 * _tmp617 - _tmp428 * _tmp613 - _tmp619 + _tmp620 - _tmp621);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
