// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost3_wrt_DeltaRot_Nl10
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost3WrtDeltarotNl10(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 2058

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (637)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp1 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp2 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp3 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp4 = -_tmp0 + _tmp1 + _tmp2 + _tmp3;
  const Scalar _tmp5 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp6 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp7 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp8 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp9 = _tmp5 + _tmp6 - _tmp7 + _tmp8;
  const Scalar _tmp10 = 2 * _tmp9;
  const Scalar _tmp11 = _tmp10 * _tmp4;
  const Scalar _tmp12 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp13 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp14 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp15 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp16 = _tmp12 - _tmp13 + _tmp14 + _tmp15;
  const Scalar _tmp17 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp18 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp19 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp20 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp21 = -_tmp17 - _tmp18 - _tmp19 + _tmp20;
  const Scalar _tmp22 = 2 * _tmp21;
  const Scalar _tmp23 = _tmp16 * _tmp22;
  const Scalar _tmp24 = Scalar(0.20999999999999999) * _tmp11 - Scalar(0.20999999999999999) * _tmp23;
  const Scalar _tmp25 = 2 * _tmp16 * _tmp4;
  const Scalar _tmp26 = _tmp22 * _tmp9;
  const Scalar _tmp27 =
      -Scalar(0.010999999999999999) * _tmp25 - Scalar(0.010999999999999999) * _tmp26;
  const Scalar _tmp28 = -2 * std::pow(_tmp9, Scalar(2));
  const Scalar _tmp29 = 1 - 2 * std::pow(_tmp16, Scalar(2));
  const Scalar _tmp30 = Scalar(0.20999999999999999) * _tmp28 + Scalar(0.20999999999999999) * _tmp29;
  const Scalar _tmp31 = _tmp27 - _tmp30;
  const Scalar _tmp32 = _tmp24 + _tmp31;
  const Scalar _tmp33 = Scalar(1.0) * _tmp32;
  const Scalar _tmp34 = Scalar(0.20999999999999999) * _tmp11 + Scalar(0.20999999999999999) * _tmp23;
  const Scalar _tmp35 = -_tmp34;
  const Scalar _tmp36 = -2 * std::pow(_tmp4, Scalar(2));
  const Scalar _tmp37 = Scalar(0.20999999999999999) * _tmp29 + Scalar(0.20999999999999999) * _tmp36;
  const Scalar _tmp38 = _tmp10 * _tmp16;
  const Scalar _tmp39 = _tmp22 * _tmp4;
  const Scalar _tmp40 =
      -Scalar(0.010999999999999999) * _tmp38 + Scalar(0.010999999999999999) * _tmp39;
  const Scalar _tmp41 = _tmp37 + _tmp40;
  const Scalar _tmp42 = _tmp35 + _tmp41;
  const Scalar _tmp43 = Scalar(1.0) * _tmp42;
  const Scalar _tmp44 = -_tmp37 + _tmp40;
  const Scalar _tmp45 = _tmp35 + _tmp44;
  const Scalar _tmp46 = -_tmp43 + _tmp45;
  const Scalar _tmp47 = Scalar(1.0) / (_tmp46);
  const Scalar _tmp48 = -_tmp24;
  const Scalar _tmp49 = _tmp31 + _tmp48;
  const Scalar _tmp50 = _tmp33 - _tmp49;
  const Scalar _tmp51 = _tmp47 * _tmp50;
  const Scalar _tmp52 = _tmp33 + _tmp43 * _tmp51;
  const Scalar _tmp53 = 0;
  const Scalar _tmp54 = _tmp27 + _tmp30;
  const Scalar _tmp55 = _tmp24 + _tmp54;
  const Scalar _tmp56 = position_vector(0, 0) + Scalar(-125.0);
  const Scalar _tmp57 = _tmp55 + _tmp56;
  const Scalar _tmp58 = _tmp34 + _tmp41;
  const Scalar _tmp59 = position_vector(1, 0) + Scalar(-110.0);
  const Scalar _tmp60 = _tmp58 + _tmp59;
  const Scalar _tmp61 = std::pow(_tmp57, Scalar(2)) + std::pow(_tmp60, Scalar(2));
  const Scalar _tmp62 = std::pow(_tmp61, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp63 = Scalar(0.20999999999999999) * _tmp25 - Scalar(0.20999999999999999) * _tmp26;
  const Scalar _tmp64 = -Scalar(0.010999999999999999) * _tmp28 -
                        Scalar(0.010999999999999999) * _tmp36 + Scalar(-0.010999999999999999);
  const Scalar _tmp65 = Scalar(0.20999999999999999) * _tmp38 + Scalar(0.20999999999999999) * _tmp39;
  const Scalar _tmp66 = _tmp64 + _tmp65;
  const Scalar _tmp67 = _tmp63 + _tmp66;
  const Scalar _tmp68 = _tmp62 * _tmp67;
  const Scalar _tmp69 = _tmp42 + _tmp59;
  const Scalar _tmp70 = position_vector(0, 0) + Scalar(125.0);
  const Scalar _tmp71 = _tmp32 + _tmp70;
  const Scalar _tmp72 = Scalar(1.0) / (_tmp71);
  const Scalar _tmp73 = _tmp69 * _tmp72;
  const Scalar _tmp74 = _tmp57 * _tmp62;
  const Scalar _tmp75 = _tmp60 * _tmp62;
  const Scalar _tmp76 = _tmp73 * _tmp74 - _tmp75;
  const Scalar _tmp77 = position_vector(1, 0) + Scalar(110.0);
  const Scalar _tmp78 = _tmp45 + _tmp77;
  const Scalar _tmp79 = _tmp49 + _tmp70;
  const Scalar _tmp80 = std::pow(_tmp78, Scalar(2)) + std::pow(_tmp79, Scalar(2));
  const Scalar _tmp81 = std::pow(_tmp80, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp82 = _tmp79 * _tmp81;
  const Scalar _tmp83 = _tmp78 * _tmp81;
  const Scalar _tmp84 = _tmp73 * _tmp82 - _tmp83;
  const Scalar _tmp85 = Scalar(1.0) / (_tmp84);
  const Scalar _tmp86 = -_tmp63;
  const Scalar _tmp87 = _tmp66 + _tmp86;
  const Scalar _tmp88 = _tmp81 * _tmp87;
  const Scalar _tmp89 = _tmp79 * _tmp88;
  const Scalar _tmp90 = _tmp64 - _tmp65 + _tmp86;
  const Scalar _tmp91 = -_tmp82 * _tmp90 + _tmp89;
  const Scalar _tmp92 = _tmp85 * _tmp91;
  const Scalar _tmp93 = _tmp62 * _tmp87;
  const Scalar _tmp94 = _tmp57 * _tmp93;
  const Scalar _tmp95 = -_tmp73 * _tmp89 + _tmp83 * _tmp90;
  const Scalar _tmp96 = _tmp85 * _tmp95;
  const Scalar _tmp97 = _tmp67 * _tmp75 - _tmp73 * _tmp94 - _tmp76 * _tmp96;
  const Scalar _tmp98 = -_tmp51 * _tmp97 - _tmp57 * _tmp68 - _tmp76 * _tmp92 + _tmp94;
  const Scalar _tmp99 = Scalar(1.0) / (_tmp98);
  const Scalar _tmp100 = _tmp74 * _tmp99;
  const Scalar _tmp101 = _tmp82 * _tmp85;
  const Scalar _tmp102 = _tmp76 * _tmp99;
  const Scalar _tmp103 = _tmp102 * _tmp53;
  const Scalar _tmp104 = _tmp100 * _tmp53 - _tmp101 * _tmp103;
  const Scalar _tmp105 = Scalar(19.620000000000001) - fv1;
  const Scalar _tmp106 = std::pow(_tmp71, Scalar(2));
  const Scalar _tmp107 = _tmp106 + std::pow(_tmp69, Scalar(2));
  const Scalar _tmp108 = std::sqrt(_tmp107);
  const Scalar _tmp109 = _tmp108 * _tmp72;
  const Scalar _tmp110 = _tmp105 * _tmp109;
  const Scalar _tmp111 = _tmp58 * _tmp62;
  const Scalar _tmp112 = Scalar(1.0) / (_tmp108);
  const Scalar _tmp113 = _tmp112 * _tmp69;
  const Scalar _tmp114 = _tmp112 * _tmp42;
  const Scalar _tmp115 = _tmp113 * _tmp32 - _tmp114 * _tmp71;
  const Scalar _tmp116 = _tmp109 * _tmp115;
  const Scalar _tmp117 = _tmp45 * _tmp81;
  const Scalar _tmp118 = _tmp116 * _tmp82 + _tmp117 * _tmp79 - _tmp49 * _tmp83;
  const Scalar _tmp119 = _tmp76 * _tmp85;
  const Scalar _tmp120 = _tmp111 * _tmp57 + _tmp116 * _tmp74 - _tmp118 * _tmp119 - _tmp55 * _tmp75;
  const Scalar _tmp121 = Scalar(1.0) / (_tmp120);
  const Scalar _tmp122 = Scalar(1.0) * _tmp121;
  const Scalar _tmp123 = Scalar(1.0) * _tmp85;
  const Scalar _tmp124 = _tmp121 * _tmp123;
  const Scalar _tmp125 = _tmp124 * _tmp82;
  const Scalar _tmp126 = _tmp122 * _tmp74 - _tmp125 * _tmp76;
  const Scalar _tmp127 = _tmp34 + _tmp44;
  const Scalar _tmp128 = _tmp127 + _tmp77;
  const Scalar _tmp129 = _tmp48 + _tmp54;
  const Scalar _tmp130 = _tmp129 + _tmp56;
  const Scalar _tmp131 = std::pow(_tmp128, Scalar(2)) + std::pow(_tmp130, Scalar(2));
  const Scalar _tmp132 = std::pow(_tmp131, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp133 = _tmp129 * _tmp132;
  const Scalar _tmp134 = _tmp130 * _tmp132;
  const Scalar _tmp135 = -_tmp127 * _tmp134 + _tmp128 * _tmp133;
  const Scalar _tmp136 = _tmp135 * fh1;
  const Scalar _tmp137 = _tmp109 * _tmp136;
  const Scalar _tmp138 = Scalar(1.0) * _tmp96;
  const Scalar _tmp139 = _tmp138 * _tmp51 - Scalar(1.0) * _tmp92;
  const Scalar _tmp140 = _tmp120 * _tmp99;
  const Scalar _tmp141 = -_tmp118 * _tmp123 - _tmp139 * _tmp140;
  const Scalar _tmp142 = _tmp121 * _tmp141;
  const Scalar _tmp143 = _tmp139 + _tmp142 * _tmp98;
  const Scalar _tmp144 = -_tmp102 * _tmp143 + Scalar(1.0);
  const Scalar _tmp145 = _tmp143 * _tmp99;
  const Scalar _tmp146 = _tmp101 * _tmp144 + _tmp145 * _tmp74;
  const Scalar _tmp147 = _tmp128 * _tmp132;
  const Scalar _tmp148 = _tmp147 * fh1;
  const Scalar _tmp149 = _tmp109 * _tmp148;
  const Scalar _tmp150 = _tmp118 * _tmp85;
  const Scalar _tmp151 = _tmp73 * _tmp87;
  const Scalar _tmp152 = _tmp151 + _tmp73 * _tmp96;
  const Scalar _tmp153 = -_tmp152 * _tmp51 + _tmp73 * _tmp92 - _tmp87;
  const Scalar _tmp154 = _tmp153 * _tmp99;
  const Scalar _tmp155 = -_tmp116 - _tmp120 * _tmp154 + _tmp150 * _tmp73;
  const Scalar _tmp156 = _tmp121 * _tmp98;
  const Scalar _tmp157 = _tmp153 + _tmp155 * _tmp156;
  const Scalar _tmp158 = -_tmp102 * _tmp157 - _tmp73;
  const Scalar _tmp159 = _tmp157 * _tmp99;
  const Scalar _tmp160 = _tmp101 * _tmp158 + _tmp159 * _tmp74 + Scalar(1.0);
  const Scalar _tmp161 = _tmp134 * fh1;
  const Scalar _tmp162 = _tmp109 * _tmp161;
  const Scalar _tmp163 =
      std::exp(_tmp104 * _tmp110 + _tmp126 * _tmp137 + _tmp146 * _tmp149 + _tmp160 * _tmp162);
  const Scalar _tmp164 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp165 = (Scalar(1) / Scalar(2)) * _tmp1;
  const Scalar _tmp166 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp167 = (Scalar(1) / Scalar(2)) * _tmp3;
  const Scalar _tmp168 = _tmp164 - _tmp165 - _tmp166 - _tmp167;
  const Scalar _tmp169 = Scalar(0.41999999999999998) * _tmp16;
  const Scalar _tmp170 = _tmp168 * _tmp169;
  const Scalar _tmp171 = (Scalar(1) / Scalar(2)) * _tmp5;
  const Scalar _tmp172 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp173 = (Scalar(1) / Scalar(2)) * _tmp7;
  const Scalar _tmp174 = (Scalar(1) / Scalar(2)) * _tmp8;
  const Scalar _tmp175 = -_tmp171 - _tmp172 + _tmp173 - _tmp174;
  const Scalar _tmp176 = Scalar(0.41999999999999998) * _tmp21;
  const Scalar _tmp177 = _tmp175 * _tmp176;
  const Scalar _tmp178 = _tmp170 + _tmp177;
  const Scalar _tmp179 = Scalar(0.83999999999999997) * _tmp16;
  const Scalar _tmp180 = _tmp175 * _tmp179;
  const Scalar _tmp181 = -Scalar(1) / Scalar(2) * _tmp17 - Scalar(1) / Scalar(2) * _tmp18 -
                         Scalar(1) / Scalar(2) * _tmp19 + (Scalar(1) / Scalar(2)) * _tmp20;
  const Scalar _tmp182 = Scalar(0.41999999999999998) * _tmp9;
  const Scalar _tmp183 = _tmp181 * _tmp182;
  const Scalar _tmp184 = -_tmp183;
  const Scalar _tmp185 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp186 = (Scalar(1) / Scalar(2)) * _tmp13;
  const Scalar _tmp187 = (Scalar(1) / Scalar(2)) * _tmp14;
  const Scalar _tmp188 = (Scalar(1) / Scalar(2)) * _tmp15;
  const Scalar _tmp189 = _tmp185 - _tmp186 + _tmp187 + _tmp188;
  const Scalar _tmp190 = Scalar(0.41999999999999998) * _tmp4;
  const Scalar _tmp191 = _tmp189 * _tmp190;
  const Scalar _tmp192 = _tmp184 - _tmp191;
  const Scalar _tmp193 = _tmp180 + _tmp192;
  const Scalar _tmp194 = Scalar(0.83999999999999997) * _tmp9;
  const Scalar _tmp195 = _tmp189 * _tmp194;
  const Scalar _tmp196 = Scalar(0.021999999999999999) * _tmp9;
  const Scalar _tmp197 = Scalar(0.021999999999999999) * _tmp16;
  const Scalar _tmp198 = -_tmp181 * _tmp197;
  const Scalar _tmp199 = Scalar(0.021999999999999999) * _tmp4;
  const Scalar _tmp200 = _tmp175 * _tmp199;
  const Scalar _tmp201 = Scalar(0.021999999999999999) * _tmp21;
  const Scalar _tmp202 = -_tmp168 * _tmp196 - _tmp189 * _tmp201 + _tmp198 - _tmp200;
  const Scalar _tmp203 = _tmp195 + _tmp202;
  const Scalar _tmp204 = _tmp178 + _tmp193 + _tmp203;
  const Scalar _tmp205 = _tmp81 * _tmp85;
  const Scalar _tmp206 = _tmp103 * _tmp205;
  const Scalar _tmp207 = 2 * _tmp79;
  const Scalar _tmp208 = -_tmp170;
  const Scalar _tmp209 = -_tmp177 + _tmp208;
  const Scalar _tmp210 = Scalar(0.83999999999999997) * _tmp4;
  const Scalar _tmp211 = _tmp181 * _tmp210;
  const Scalar _tmp212 = -_tmp175 * _tmp196;
  const Scalar _tmp213 = _tmp181 * _tmp201;
  const Scalar _tmp214 = _tmp168 * _tmp199 - _tmp189 * _tmp197 + _tmp212 + _tmp213;
  const Scalar _tmp215 = _tmp211 + _tmp214;
  const Scalar _tmp216 = _tmp193 + _tmp209 + _tmp215;
  const Scalar _tmp217 = 2 * _tmp78;
  const Scalar _tmp218 = _tmp204 * _tmp207 + _tmp216 * _tmp217;
  const Scalar _tmp219 = std::pow(_tmp80, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp220 = (Scalar(1) / Scalar(2)) * _tmp219;
  const Scalar _tmp221 = _tmp220 * _tmp79;
  const Scalar _tmp222 = _tmp218 * _tmp221;
  const Scalar _tmp223 = _tmp183 + _tmp191;
  const Scalar _tmp224 = _tmp180 + _tmp223;
  const Scalar _tmp225 = _tmp203 + _tmp209 + _tmp224;
  const Scalar _tmp226 = Scalar(1.0) / (_tmp106);
  const Scalar _tmp227 = _tmp226 * _tmp69;
  const Scalar _tmp228 = _tmp225 * _tmp227;
  const Scalar _tmp229 = -_tmp180;
  const Scalar _tmp230 = _tmp209 + _tmp229;
  const Scalar _tmp231 = -_tmp211 + _tmp214;
  const Scalar _tmp232 = _tmp192 + _tmp230 + _tmp231;
  const Scalar _tmp233 = _tmp232 * _tmp72;
  const Scalar _tmp234 = _tmp220 * _tmp78;
  const Scalar _tmp235 = _tmp218 * _tmp234;
  const Scalar _tmp236 = _tmp73 * _tmp81;
  const Scalar _tmp237 = _tmp216 * _tmp81;
  const Scalar _tmp238 = _tmp204 * _tmp236 - _tmp222 * _tmp73 - _tmp228 * _tmp82 +
                         _tmp233 * _tmp82 + _tmp235 - _tmp237;
  const Scalar _tmp239 = std::pow(_tmp84, Scalar(-2));
  const Scalar _tmp240 = _tmp239 * _tmp82;
  const Scalar _tmp241 = _tmp103 * _tmp240;
  const Scalar _tmp242 = -_tmp195 + _tmp202;
  const Scalar _tmp243 = _tmp223 + _tmp230 + _tmp242;
  const Scalar _tmp244 = _tmp243 * _tmp62;
  const Scalar _tmp245 = _tmp178 + _tmp229;
  const Scalar _tmp246 = _tmp223 + _tmp231 + _tmp245;
  const Scalar _tmp247 = 2 * _tmp60;
  const Scalar _tmp248 = 2 * _tmp57;
  const Scalar _tmp249 = _tmp243 * _tmp248 + _tmp246 * _tmp247;
  const Scalar _tmp250 = std::pow(_tmp61, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp251 = (Scalar(1) / Scalar(2)) * _tmp250;
  const Scalar _tmp252 = _tmp251 * _tmp60;
  const Scalar _tmp253 = _tmp249 * _tmp252;
  const Scalar _tmp254 = _tmp251 * _tmp57;
  const Scalar _tmp255 = _tmp249 * _tmp254;
  const Scalar _tmp256 = _tmp246 * _tmp62;
  const Scalar _tmp257 = -_tmp228 * _tmp74 + _tmp233 * _tmp74 + _tmp244 * _tmp73 + _tmp253 -
                         _tmp255 * _tmp73 - _tmp256;
  const Scalar _tmp258 = _tmp239 * _tmp76;
  const Scalar _tmp259 = _tmp258 * _tmp91;
  const Scalar _tmp260 = _tmp169 * _tmp181;
  const Scalar _tmp261 = _tmp175 * _tmp190;
  const Scalar _tmp262 = -_tmp260 - _tmp261;
  const Scalar _tmp263 = _tmp175 * _tmp182;
  const Scalar _tmp264 = _tmp176 * _tmp181;
  const Scalar _tmp265 = -_tmp264;
  const Scalar _tmp266 = -_tmp263 + _tmp265;
  const Scalar _tmp267 = _tmp262 + _tmp266;
  const Scalar _tmp268 = _tmp169 * _tmp189;
  const Scalar _tmp269 = _tmp168 * _tmp190;
  const Scalar _tmp270 = -_tmp269;
  const Scalar _tmp271 = -_tmp268 + _tmp270;
  const Scalar _tmp272 = _tmp168 * _tmp182;
  const Scalar _tmp273 = _tmp176 * _tmp189;
  const Scalar _tmp274 = Scalar(0.043999999999999997) * _tmp9;
  const Scalar _tmp275 = _tmp189 * _tmp274;
  const Scalar _tmp276 = Scalar(0.043999999999999997) * _tmp4;
  const Scalar _tmp277 = _tmp181 * _tmp276;
  const Scalar _tmp278 = _tmp275 + _tmp277;
  const Scalar _tmp279 = _tmp272 + _tmp273 + _tmp278;
  const Scalar _tmp280 = _tmp267 + _tmp271 + _tmp279;
  const Scalar _tmp281 = _tmp263 + _tmp264;
  const Scalar _tmp282 = _tmp262 + _tmp281;
  const Scalar _tmp283 = _tmp268 + _tmp269;
  const Scalar _tmp284 = _tmp279 + _tmp282 + _tmp283;
  const Scalar _tmp285 = _tmp81 * _tmp90;
  const Scalar _tmp286 = _tmp204 * _tmp88;
  const Scalar _tmp287 = -_tmp204 * _tmp285 - _tmp222 * _tmp87 + _tmp222 * _tmp90 -
                         _tmp280 * _tmp82 + _tmp284 * _tmp82 + _tmp286;
  const Scalar _tmp288 = _tmp260 + _tmp261;
  const Scalar _tmp289 = _tmp281 + _tmp288;
  const Scalar _tmp290 = -_tmp272 - _tmp273;
  const Scalar _tmp291 = _tmp278 + _tmp283 + _tmp289 + _tmp290;
  const Scalar _tmp292 = _tmp254 * _tmp87;
  const Scalar _tmp293 = _tmp284 * _tmp73;
  const Scalar _tmp294 = _tmp258 * _tmp95;
  const Scalar _tmp295 = _tmp233 * _tmp87;
  const Scalar _tmp296 = _tmp151 * _tmp222 + _tmp228 * _tmp89 - _tmp235 * _tmp90 +
                         _tmp237 * _tmp90 + _tmp280 * _tmp83 - _tmp286 * _tmp73 - _tmp293 * _tmp82 -
                         _tmp295 * _tmp82;
  const Scalar _tmp297 = _tmp243 * _tmp93;
  const Scalar _tmp298 = _tmp181 * _tmp194;
  const Scalar _tmp299 = Scalar(0.83999999999999997) * _tmp21;
  const Scalar _tmp300 = -_tmp168 * _tmp179 - _tmp175 * _tmp299 + _tmp189 * _tmp210 + _tmp298;
  const Scalar _tmp301 = _tmp47 * _tmp97;
  const Scalar _tmp302 = _tmp254 * _tmp67;
  const Scalar _tmp303 = Scalar(1.6799999999999999) * _tmp16;
  const Scalar _tmp304 = Scalar(1.6799999999999999) * _tmp4;
  const Scalar _tmp305 = _tmp175 * _tmp303 + _tmp181 * _tmp304;
  const Scalar _tmp306 = _tmp50 / std::pow(_tmp46, Scalar(2));
  const Scalar _tmp307 = _tmp306 * _tmp97;
  const Scalar _tmp308 =
      -_tmp119 * _tmp287 + _tmp238 * _tmp259 - _tmp243 * _tmp68 - _tmp249 * _tmp292 +
      _tmp249 * _tmp302 - _tmp257 * _tmp92 + _tmp284 * _tmp74 - _tmp291 * _tmp74 + _tmp297 -
      _tmp300 * _tmp301 + _tmp305 * _tmp307 -
      _tmp51 * (-_tmp119 * _tmp296 + _tmp151 * _tmp255 + _tmp228 * _tmp94 + _tmp238 * _tmp294 -
                _tmp253 * _tmp67 + _tmp256 * _tmp67 - _tmp257 * _tmp96 + _tmp291 * _tmp75 -
                _tmp293 * _tmp74 - _tmp295 * _tmp74 - _tmp297 * _tmp73);
  const Scalar _tmp309 = std::pow(_tmp98, Scalar(-2));
  const Scalar _tmp310 = _tmp308 * _tmp309;
  const Scalar _tmp311 = _tmp119 * _tmp53 * _tmp82;
  const Scalar _tmp312 = _tmp257 * _tmp99;
  const Scalar _tmp313 = _tmp101 * _tmp53;
  const Scalar _tmp314 = _tmp53 * _tmp99;
  const Scalar _tmp315 = _tmp53 * _tmp74;
  const Scalar _tmp316 = _tmp103 * _tmp85;
  const Scalar _tmp317 = _tmp254 * _tmp314;
  const Scalar _tmp318 = _tmp192 + _tmp242 + _tmp245;
  const Scalar _tmp319 = _tmp132 * fh1;
  const Scalar _tmp320 = _tmp318 * _tmp319;
  const Scalar _tmp321 = _tmp109 * _tmp160;
  const Scalar _tmp322 = _tmp160 * _tmp161;
  const Scalar _tmp323 = _tmp108 * _tmp226;
  const Scalar _tmp324 = _tmp225 * _tmp323;
  const Scalar _tmp325 = _tmp112 * _tmp72;
  const Scalar _tmp326 = 2 * _tmp71;
  const Scalar _tmp327 = 2 * _tmp69;
  const Scalar _tmp328 =
      (Scalar(1) / Scalar(2)) * _tmp225 * _tmp326 + (Scalar(1) / Scalar(2)) * _tmp232 * _tmp327;
  const Scalar _tmp329 = _tmp325 * _tmp328;
  const Scalar _tmp330 = _tmp146 * _tmp148;
  const Scalar _tmp331 = _tmp178 + _tmp215 + _tmp224;
  const Scalar _tmp332 = _tmp109 * _tmp319;
  const Scalar _tmp333 = _tmp146 * _tmp332;
  const Scalar _tmp334 = _tmp126 * _tmp136;
  const Scalar _tmp335 = _tmp323 * _tmp334;
  const Scalar _tmp336 = _tmp115 * _tmp325;
  const Scalar _tmp337 = _tmp328 * _tmp336;
  const Scalar _tmp338 = _tmp112 * _tmp71;
  const Scalar _tmp339 = _tmp112 * _tmp32;
  const Scalar _tmp340 = std::pow(_tmp107, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp341 = _tmp42 * _tmp71;
  const Scalar _tmp342 = _tmp340 * _tmp341;
  const Scalar _tmp343 = _tmp32 * _tmp69;
  const Scalar _tmp344 = _tmp340 * _tmp343;
  const Scalar _tmp345 = _tmp109 * (_tmp113 * _tmp225 - _tmp114 * _tmp225 - _tmp232 * _tmp338 +
                                    _tmp232 * _tmp339 + _tmp328 * _tmp342 - _tmp328 * _tmp344);
  const Scalar _tmp346 = _tmp116 * _tmp81;
  const Scalar _tmp347 = _tmp115 * _tmp323;
  const Scalar _tmp348 = _tmp225 * _tmp347;
  const Scalar _tmp349 = -_tmp116 * _tmp222 + _tmp117 * _tmp204 + _tmp204 * _tmp346 -
                         _tmp204 * _tmp83 - _tmp222 * _tmp45 + _tmp235 * _tmp49 - _tmp237 * _tmp49 +
                         _tmp237 * _tmp79 + _tmp337 * _tmp82 + _tmp345 * _tmp82 - _tmp348 * _tmp82;
  const Scalar _tmp350 = _tmp254 * _tmp58;
  const Scalar _tmp351 = _tmp118 * _tmp258;
  const Scalar _tmp352 = _tmp111 * _tmp243 + _tmp116 * _tmp244 - _tmp116 * _tmp255 -
                         _tmp119 * _tmp349 - _tmp150 * _tmp257 + _tmp238 * _tmp351 -
                         _tmp243 * _tmp75 - _tmp249 * _tmp350 + _tmp253 * _tmp55 -
                         _tmp256 * _tmp55 + _tmp256 * _tmp57 + _tmp337 * _tmp74 + _tmp345 * _tmp74 -
                         _tmp348 * _tmp74;
  const Scalar _tmp353 = std::pow(_tmp120, Scalar(-2));
  const Scalar _tmp354 = _tmp353 * _tmp98;
  const Scalar _tmp355 = _tmp155 * _tmp354;
  const Scalar _tmp356 = _tmp121 * _tmp155;
  const Scalar _tmp357 = _tmp239 * _tmp73;
  const Scalar _tmp358 = _tmp238 * _tmp357;
  const Scalar _tmp359 = _tmp73 * _tmp85;
  const Scalar _tmp360 = _tmp120 * _tmp153;
  const Scalar _tmp361 = _tmp152 * _tmp47;
  const Scalar _tmp362 = _tmp152 * _tmp306;
  const Scalar _tmp363 = _tmp266 + _tmp288;
  const Scalar _tmp364 = -_tmp228 * _tmp92 + _tmp233 * _tmp92 + _tmp271 - _tmp275 - _tmp277 +
                         _tmp287 * _tmp359 + _tmp290 - _tmp300 * _tmp361 + _tmp305 * _tmp362 -
                         _tmp358 * _tmp91 + _tmp363 -
                         _tmp51 * (-_tmp228 * _tmp87 - _tmp228 * _tmp96 + _tmp233 * _tmp96 +
                                   _tmp293 + _tmp295 + _tmp296 * _tmp359 - _tmp358 * _tmp95);
  const Scalar _tmp365 = _tmp156 * (-_tmp118 * _tmp358 - _tmp140 * _tmp364 - _tmp150 * _tmp228 +
                                    _tmp150 * _tmp233 - _tmp154 * _tmp352 + _tmp310 * _tmp360 -
                                    _tmp337 - _tmp345 + _tmp348 + _tmp349 * _tmp359) +
                         _tmp308 * _tmp356 - _tmp352 * _tmp355 + _tmp364;
  const Scalar _tmp366 = _tmp158 * _tmp240;
  const Scalar _tmp367 = _tmp158 * _tmp205;
  const Scalar _tmp368 = _tmp157 * _tmp74;
  const Scalar _tmp369 = _tmp157 * _tmp76;
  const Scalar _tmp370 =
      -_tmp102 * _tmp365 - _tmp157 * _tmp312 + _tmp228 - _tmp233 + _tmp310 * _tmp369;
  const Scalar _tmp371 = _tmp158 * _tmp85;
  const Scalar _tmp372 = _tmp325 * _tmp334;
  const Scalar _tmp373 = _tmp124 * _tmp76;
  const Scalar _tmp374 = _tmp373 * _tmp81;
  const Scalar _tmp375 = _tmp123 * _tmp353 * _tmp76;
  const Scalar _tmp376 = _tmp375 * _tmp82;
  const Scalar _tmp377 = Scalar(0.5) * _tmp121;
  const Scalar _tmp378 = _tmp250 * _tmp377 * _tmp57;
  const Scalar _tmp379 = _tmp119 * _tmp219 * _tmp377 * _tmp79;
  const Scalar _tmp380 = Scalar(1.0) * _tmp353;
  const Scalar _tmp381 = _tmp380 * _tmp74;
  const Scalar _tmp382 = _tmp122 * _tmp82;
  const Scalar _tmp383 = _tmp258 * _tmp382;
  const Scalar _tmp384 = _tmp144 * _tmp205;
  const Scalar _tmp385 = _tmp143 * _tmp74;
  const Scalar _tmp386 = _tmp141 * _tmp354;
  const Scalar _tmp387 = _tmp123 * _tmp51;
  const Scalar _tmp388 = _tmp138 * _tmp47;
  const Scalar _tmp389 = _tmp138 * _tmp306;
  const Scalar _tmp390 = Scalar(1.0) * _tmp239;
  const Scalar _tmp391 = _tmp51 * _tmp95;
  const Scalar _tmp392 = _tmp390 * _tmp391;
  const Scalar _tmp393 = _tmp390 * _tmp91;
  const Scalar _tmp394 = -_tmp123 * _tmp287 - _tmp238 * _tmp392 + _tmp238 * _tmp393 +
                         _tmp296 * _tmp387 + _tmp300 * _tmp388 - _tmp305 * _tmp389;
  const Scalar _tmp395 = _tmp139 * _tmp99;
  const Scalar _tmp396 = _tmp118 * _tmp390;
  const Scalar _tmp397 = _tmp120 * _tmp139;
  const Scalar _tmp398 = _tmp142 * _tmp308 +
                         _tmp156 * (-_tmp123 * _tmp349 - _tmp140 * _tmp394 + _tmp238 * _tmp396 +
                                    _tmp310 * _tmp397 - _tmp352 * _tmp395) -
                         _tmp352 * _tmp386 + _tmp394;
  const Scalar _tmp399 = _tmp144 * _tmp240;
  const Scalar _tmp400 = _tmp144 * _tmp85;
  const Scalar _tmp401 = _tmp143 * _tmp76;
  const Scalar _tmp402 = -_tmp102 * _tmp398 - _tmp143 * _tmp312 + _tmp310 * _tmp401;
  const Scalar _tmp403 = 2 * _tmp130;
  const Scalar _tmp404 = 2 * _tmp128;
  const Scalar _tmp405 = (Scalar(1) / Scalar(2)) / (_tmp131 * std::sqrt(_tmp131));
  const Scalar _tmp406 = _tmp405 * (_tmp318 * _tmp403 + _tmp331 * _tmp404);
  const Scalar _tmp407 = _tmp109 * _tmp146;
  const Scalar _tmp408 = _tmp128 * fh1;
  const Scalar _tmp409 = _tmp407 * _tmp408;
  const Scalar _tmp410 = _tmp109 * _tmp126;
  const Scalar _tmp411 = _tmp128 * _tmp129;
  const Scalar _tmp412 = _tmp127 * _tmp132;
  const Scalar _tmp413 = _tmp127 * _tmp130;
  const Scalar _tmp414 = _tmp133 * _tmp331 - _tmp134 * _tmp331 + _tmp147 * _tmp318 -
                         _tmp318 * _tmp412 - _tmp406 * _tmp411 + _tmp406 * _tmp413;
  const Scalar _tmp415 = _tmp414 * fh1;
  const Scalar _tmp416 = _tmp104 * _tmp105;
  const Scalar _tmp417 = _tmp325 * _tmp416;
  const Scalar _tmp418 = _tmp323 * _tmp416;
  const Scalar _tmp419 = _tmp130 * fh1;
  const Scalar _tmp420 = _tmp321 * _tmp419;
  const Scalar _tmp421 = _tmp105 * _tmp53;
  const Scalar _tmp422 = _tmp421 * _tmp85;
  const Scalar _tmp423 =
      std::exp(_tmp102 * _tmp422 + _tmp136 * _tmp373 - _tmp148 * _tmp400 - _tmp161 * _tmp371);
  const Scalar _tmp424 = _tmp102 * _tmp421;
  const Scalar _tmp425 = _tmp238 * _tmp239;
  const Scalar _tmp426 = _tmp148 * _tmp85;
  const Scalar _tmp427 = _tmp371 * _tmp419;
  const Scalar _tmp428 = _tmp319 * _tmp400;
  const Scalar _tmp429 = _tmp124 * _tmp136;
  const Scalar _tmp430 = _tmp400 * _tmp408;
  const Scalar _tmp431 = _tmp310 * _tmp421;
  const Scalar _tmp432 = _tmp144 * _tmp148;
  const Scalar _tmp433 = _tmp161 * _tmp85;
  const Scalar _tmp434 = _tmp136 * _tmp375;
  const Scalar _tmp435 = _tmp158 * _tmp161;
  const Scalar _tmp436 = _tmp122 * fh1;
  const Scalar _tmp437 = _tmp135 * _tmp436;
  const Scalar _tmp438 = _tmp258 * _tmp437;
  const Scalar _tmp439 = _tmp421 * _tmp99;
  const Scalar _tmp440 = std::exp(-_tmp145 * _tmp148 - _tmp159 * _tmp161 - _tmp437 - _tmp439);
  const Scalar _tmp441 = _tmp159 * _tmp419;
  const Scalar _tmp442 = _tmp157 * _tmp161;
  const Scalar _tmp443 = _tmp145 * _tmp408;
  const Scalar _tmp444 = _tmp136 * _tmp380;
  const Scalar _tmp445 = _tmp145 * _tmp319;
  const Scalar _tmp446 = _tmp161 * _tmp99;
  const Scalar _tmp447 = _tmp143 * _tmp148;
  const Scalar _tmp448 = _tmp148 * _tmp99;
  const Scalar _tmp449 = -_tmp164 + _tmp165 + _tmp166 + _tmp167;
  const Scalar _tmp450 = _tmp179 * _tmp449;
  const Scalar _tmp451 = _tmp169 * _tmp175;
  const Scalar _tmp452 = _tmp176 * _tmp449;
  const Scalar _tmp453 = _tmp451 + _tmp452;
  const Scalar _tmp454 = _tmp450 + _tmp453;
  const Scalar _tmp455 = -_tmp185 + _tmp186 - _tmp187 - _tmp188;
  const Scalar _tmp456 = _tmp182 * _tmp455;
  const Scalar _tmp457 = _tmp181 * _tmp190;
  const Scalar _tmp458 = _tmp456 + _tmp457;
  const Scalar _tmp459 = _tmp210 * _tmp455;
  const Scalar _tmp460 = -_tmp196 * _tmp449 + _tmp198 + _tmp200 + _tmp201 * _tmp455;
  const Scalar _tmp461 = _tmp459 + _tmp460;
  const Scalar _tmp462 = _tmp454 + _tmp458 + _tmp461;
  const Scalar _tmp463 = -_tmp197 * _tmp455 - _tmp199 * _tmp449 + _tmp212 - _tmp213;
  const Scalar _tmp464 = _tmp298 + _tmp463;
  const Scalar _tmp465 = -_tmp451 - _tmp452;
  const Scalar _tmp466 = _tmp458 + _tmp465;
  const Scalar _tmp467 = _tmp450 + _tmp464 + _tmp466;
  const Scalar _tmp468 = _tmp323 * _tmp467;
  const Scalar _tmp469 = -_tmp450;
  const Scalar _tmp470 = -_tmp457;
  const Scalar _tmp471 = -_tmp456;
  const Scalar _tmp472 = _tmp470 + _tmp471;
  const Scalar _tmp473 = _tmp469 + _tmp472;
  const Scalar _tmp474 = -_tmp298 + _tmp463;
  const Scalar _tmp475 = _tmp453 + _tmp473 + _tmp474;
  const Scalar _tmp476 = _tmp403 * _tmp475 + _tmp404 * _tmp462;
  const Scalar _tmp477 = _tmp405 * _tmp413;
  const Scalar _tmp478 = _tmp405 * _tmp411;
  const Scalar _tmp479 = _tmp133 * _tmp462 - _tmp134 * _tmp462 + _tmp147 * _tmp475 -
                         _tmp412 * _tmp475 + _tmp476 * _tmp477 - _tmp476 * _tmp478;
  const Scalar _tmp480 = _tmp479 * fh1;
  const Scalar _tmp481 = -_tmp459 + _tmp460;
  const Scalar _tmp482 = _tmp465 + _tmp473 + _tmp481;
  const Scalar _tmp483 =
      (Scalar(1) / Scalar(2)) * _tmp326 * _tmp467 + (Scalar(1) / Scalar(2)) * _tmp327 * _tmp482;
  const Scalar _tmp484 = _tmp325 * _tmp483;
  const Scalar _tmp485 = _tmp405 * _tmp476;
  const Scalar _tmp486 = _tmp160 * _tmp332;
  const Scalar _tmp487 = _tmp453 + _tmp458 + _tmp469 + _tmp481;
  const Scalar _tmp488 = _tmp466 + _tmp469 + _tmp474;
  const Scalar _tmp489 = _tmp247 * _tmp487 + _tmp248 * _tmp488;
  const Scalar _tmp490 = _tmp254 * _tmp489;
  const Scalar _tmp491 = _tmp227 * _tmp467;
  const Scalar _tmp492 = _tmp487 * _tmp62;
  const Scalar _tmp493 = _tmp482 * _tmp72;
  const Scalar _tmp494 = _tmp488 * _tmp62;
  const Scalar _tmp495 = _tmp252 * _tmp489;
  const Scalar _tmp496 = -_tmp490 * _tmp73 - _tmp491 * _tmp74 - _tmp492 + _tmp493 * _tmp74 +
                         _tmp494 * _tmp73 + _tmp495;
  const Scalar _tmp497 = _tmp496 * _tmp99;
  const Scalar _tmp498 = _tmp488 * _tmp93;
  const Scalar _tmp499 = _tmp303 * _tmp449 + _tmp304 * _tmp455;
  const Scalar _tmp500 = _tmp194 * _tmp455 + _tmp211 + _tmp229 - _tmp299 * _tmp449;
  const Scalar _tmp501 = _tmp454 + _tmp464 + _tmp472;
  const Scalar _tmp502 = _tmp450 + _tmp461 + _tmp465 + _tmp472;
  const Scalar _tmp503 = _tmp207 * _tmp501 + _tmp217 * _tmp502;
  const Scalar _tmp504 = _tmp221 * _tmp503;
  const Scalar _tmp505 = _tmp181 * _tmp274;
  const Scalar _tmp506 = _tmp169 * _tmp455;
  const Scalar _tmp507 = -_tmp506;
  const Scalar _tmp508 = _tmp190 * _tmp449;
  const Scalar _tmp509 = _tmp276 * _tmp455;
  const Scalar _tmp510 = _tmp505 + _tmp507 - _tmp508 + _tmp509;
  const Scalar _tmp511 = _tmp182 * _tmp449;
  const Scalar _tmp512 = _tmp176 * _tmp455;
  const Scalar _tmp513 = -_tmp511 - _tmp512;
  const Scalar _tmp514 = _tmp282 + _tmp510 + _tmp513;
  const Scalar _tmp515 = _tmp511 + _tmp512;
  const Scalar _tmp516 = _tmp289 + _tmp510 + _tmp515;
  const Scalar _tmp517 = _tmp516 * _tmp82;
  const Scalar _tmp518 = _tmp501 * _tmp81;
  const Scalar _tmp519 = _tmp518 * _tmp87;
  const Scalar _tmp520 = -_tmp504 * _tmp87 + _tmp504 * _tmp90 - _tmp514 * _tmp82 + _tmp517 -
                         _tmp518 * _tmp90 + _tmp519;
  const Scalar _tmp521 = _tmp516 * _tmp74;
  const Scalar _tmp522 = _tmp502 * _tmp81;
  const Scalar _tmp523 = _tmp234 * _tmp503;
  const Scalar _tmp524 = _tmp151 * _tmp504 + _tmp491 * _tmp89 - _tmp493 * _tmp89 +
                         _tmp514 * _tmp83 - _tmp517 * _tmp73 - _tmp519 * _tmp73 + _tmp522 * _tmp90 -
                         _tmp523 * _tmp90;
  const Scalar _tmp525 = _tmp506 + _tmp508;
  const Scalar _tmp526 = _tmp363 + _tmp505 + _tmp509 + _tmp515 + _tmp525;
  const Scalar _tmp527 = -_tmp491 * _tmp82 + _tmp493 * _tmp82 - _tmp504 * _tmp73 +
                         _tmp518 * _tmp73 - _tmp522 + _tmp523;
  const Scalar _tmp528 =
      -_tmp119 * _tmp520 + _tmp259 * _tmp527 - _tmp292 * _tmp489 - _tmp301 * _tmp500 +
      _tmp302 * _tmp489 + _tmp307 * _tmp499 - _tmp488 * _tmp68 - _tmp496 * _tmp92 + _tmp498 -
      _tmp51 * (-_tmp119 * _tmp524 + _tmp151 * _tmp490 + _tmp294 * _tmp527 + _tmp491 * _tmp94 +
                _tmp492 * _tmp67 - _tmp493 * _tmp94 - _tmp495 * _tmp67 - _tmp496 * _tmp96 -
                _tmp498 * _tmp73 - _tmp521 * _tmp73 + _tmp526 * _tmp75) +
      _tmp521 - _tmp526 * _tmp74;
  const Scalar _tmp529 = _tmp309 * _tmp528;
  const Scalar _tmp530 = _tmp518 * _tmp85;
  const Scalar _tmp531 = _tmp347 * _tmp467;
  const Scalar _tmp532 = _tmp357 * _tmp527;
  const Scalar _tmp533 =
      _tmp267 + _tmp359 * _tmp520 - _tmp361 * _tmp500 + _tmp362 * _tmp499 - _tmp491 * _tmp92 +
      _tmp493 * _tmp92 - _tmp505 - _tmp509 -
      _tmp51 * (_tmp359 * _tmp524 - _tmp491 * _tmp87 - _tmp491 * _tmp96 + _tmp493 * _tmp87 +
                _tmp493 * _tmp96 + _tmp516 * _tmp73 - _tmp532 * _tmp95) +
      _tmp513 + _tmp525 - _tmp532 * _tmp91;
  const Scalar _tmp534 = _tmp112 * _tmp467;
  const Scalar _tmp535 = _tmp109 * (-_tmp338 * _tmp482 + _tmp339 * _tmp482 + _tmp342 * _tmp483 -
                                    _tmp344 * _tmp483 - _tmp42 * _tmp534 + _tmp534 * _tmp69);
  const Scalar _tmp536 = _tmp336 * _tmp483;
  const Scalar _tmp537 = -_tmp116 * _tmp504 + _tmp116 * _tmp518 + _tmp117 * _tmp501 -
                         _tmp45 * _tmp504 - _tmp49 * _tmp522 + _tmp49 * _tmp523 - _tmp501 * _tmp83 +
                         _tmp522 * _tmp79 - _tmp531 * _tmp82 + _tmp535 * _tmp82 + _tmp536 * _tmp82;
  const Scalar _tmp538 = _tmp111 * _tmp488 - _tmp116 * _tmp490 + _tmp116 * _tmp494 -
                         _tmp119 * _tmp537 - _tmp150 * _tmp496 - _tmp350 * _tmp489 +
                         _tmp351 * _tmp527 - _tmp488 * _tmp75 - _tmp492 * _tmp55 +
                         _tmp492 * _tmp57 + _tmp495 * _tmp55 - _tmp531 * _tmp74 + _tmp535 * _tmp74 +
                         _tmp536 * _tmp74;
  const Scalar _tmp539 = _tmp156 * (-_tmp118 * _tmp532 - _tmp140 * _tmp533 - _tmp150 * _tmp491 +
                                    _tmp150 * _tmp493 - _tmp154 * _tmp538 + _tmp359 * _tmp537 +
                                    _tmp360 * _tmp529 + _tmp531 - _tmp535 - _tmp536) -
                         _tmp355 * _tmp538 + _tmp356 * _tmp528 + _tmp533;
  const Scalar _tmp540 =
      -_tmp102 * _tmp539 - _tmp157 * _tmp497 + _tmp369 * _tmp529 + _tmp491 - _tmp493;
  const Scalar _tmp541 = _tmp390 * _tmp527;
  const Scalar _tmp542 = -_tmp123 * _tmp520 + _tmp387 * _tmp524 + _tmp388 * _tmp500 -
                         _tmp389 * _tmp499 - _tmp391 * _tmp541 + _tmp541 * _tmp91;
  const Scalar _tmp543 = _tmp142 * _tmp528 +
                         _tmp156 * (_tmp118 * _tmp541 - _tmp123 * _tmp537 - _tmp140 * _tmp542 -
                                    _tmp395 * _tmp538 + _tmp397 * _tmp529) -
                         _tmp386 * _tmp538 + _tmp542;
  const Scalar _tmp544 = -_tmp102 * _tmp543 - _tmp143 * _tmp497 + _tmp401 * _tmp529;
  const Scalar _tmp545 = _tmp258 * _tmp527;
  const Scalar _tmp546 = _tmp421 * _tmp529;
  const Scalar _tmp547 = _tmp319 * _tmp371;
  const Scalar _tmp548 = _tmp239 * _tmp527;
  const Scalar _tmp549 = _tmp159 * _tmp319;
  const Scalar _tmp550 = _tmp168 * _tmp194;
  const Scalar _tmp551 = _tmp179 * _tmp181;
  const Scalar _tmp552 = _tmp171 + _tmp172 - _tmp173 + _tmp174;
  const Scalar _tmp553 = _tmp182 * _tmp552;
  const Scalar _tmp554 = _tmp269 + _tmp553;
  const Scalar _tmp555 = _tmp551 + _tmp554;
  const Scalar _tmp556 = _tmp265 + _tmp507;
  const Scalar _tmp557 =
      -_tmp168 * _tmp201 - _tmp181 * _tmp199 - _tmp196 * _tmp455 - _tmp197 * _tmp552;
  const Scalar _tmp558 = _tmp556 + _tmp557;
  const Scalar _tmp559 = _tmp550 + _tmp555 + _tmp558;
  const Scalar _tmp560 = _tmp210 * _tmp552;
  const Scalar _tmp561 =
      -_tmp168 * _tmp197 - _tmp181 * _tmp196 + _tmp199 * _tmp455 + _tmp201 * _tmp552;
  const Scalar _tmp562 = -_tmp560 + _tmp561;
  const Scalar _tmp563 = -_tmp551;
  const Scalar _tmp564 = _tmp270 - _tmp553;
  const Scalar _tmp565 = _tmp563 + _tmp564;
  const Scalar _tmp566 = _tmp556 + _tmp562 + _tmp565;
  const Scalar _tmp567 =
      (Scalar(1) / Scalar(2)) * _tmp326 * _tmp559 + (Scalar(1) / Scalar(2)) * _tmp327 * _tmp566;
  const Scalar _tmp568 = _tmp325 * _tmp567;
  const Scalar _tmp569 = -_tmp550;
  const Scalar _tmp570 = _tmp554 + _tmp563;
  const Scalar _tmp571 = _tmp558 + _tmp569 + _tmp570;
  const Scalar _tmp572 = _tmp571 * _tmp62;
  const Scalar _tmp573 = _tmp264 + _tmp506;
  const Scalar _tmp574 = _tmp557 + _tmp573;
  const Scalar _tmp575 = _tmp551 + _tmp564;
  const Scalar _tmp576 = _tmp550 + _tmp574 + _tmp575;
  const Scalar _tmp577 = _tmp566 * _tmp72;
  const Scalar _tmp578 = _tmp560 + _tmp561;
  const Scalar _tmp579 = _tmp556 + _tmp575 + _tmp578;
  const Scalar _tmp580 = _tmp579 * _tmp81;
  const Scalar _tmp581 = _tmp207 * _tmp576 + _tmp217 * _tmp579;
  const Scalar _tmp582 = _tmp234 * _tmp581;
  const Scalar _tmp583 = _tmp221 * _tmp581;
  const Scalar _tmp584 = _tmp227 * _tmp559;
  const Scalar _tmp585 = _tmp236 * _tmp576 + _tmp577 * _tmp82 - _tmp580 + _tmp582 -
                         _tmp583 * _tmp73 - _tmp584 * _tmp82;
  const Scalar _tmp586 = _tmp571 * _tmp93;
  const Scalar _tmp587 = _tmp562 + _tmp570 + _tmp573;
  const Scalar _tmp588 = _tmp247 * _tmp587 + _tmp248 * _tmp571;
  const Scalar _tmp589 = _tmp252 * _tmp588;
  const Scalar _tmp590 = _tmp254 * _tmp588;
  const Scalar _tmp591 = _tmp587 * _tmp62;
  const Scalar _tmp592 =
      _tmp572 * _tmp73 + _tmp577 * _tmp74 - _tmp584 * _tmp74 + _tmp589 - _tmp590 * _tmp73 - _tmp591;
  const Scalar _tmp593 = _tmp181 * _tmp303 + _tmp304 * _tmp552;
  const Scalar _tmp594 = _tmp168 * _tmp274;
  const Scalar _tmp595 = _tmp276 * _tmp552;
  const Scalar _tmp596 = _tmp190 * _tmp455;
  const Scalar _tmp597 = _tmp176 * _tmp552;
  const Scalar _tmp598 = _tmp170 + _tmp183 + _tmp596 + _tmp597;
  const Scalar _tmp599 = _tmp169 * _tmp552;
  const Scalar _tmp600 = _tmp168 * _tmp176;
  const Scalar _tmp601 = _tmp457 + _tmp471 + _tmp599 - _tmp600;
  const Scalar _tmp602 = _tmp594 + _tmp595 + _tmp598 + _tmp601;
  const Scalar _tmp603 = _tmp456 + _tmp470 + _tmp594 + _tmp595 - _tmp599 + _tmp600;
  const Scalar _tmp604 = _tmp184 + _tmp208 - _tmp596 - _tmp597;
  const Scalar _tmp605 = _tmp603 + _tmp604;
  const Scalar _tmp606 = _tmp576 * _tmp88;
  const Scalar _tmp607 = _tmp598 + _tmp603;
  const Scalar _tmp608 = _tmp607 * _tmp73;
  const Scalar _tmp609 = _tmp151 * _tmp583 - _tmp577 * _tmp89 + _tmp580 * _tmp90 -
                         _tmp582 * _tmp90 + _tmp584 * _tmp89 + _tmp605 * _tmp83 - _tmp606 * _tmp73 -
                         _tmp608 * _tmp82;
  const Scalar _tmp610 =
      _tmp47 * (_tmp168 * _tmp210 - _tmp179 * _tmp455 - _tmp181 * _tmp299 + _tmp194 * _tmp552);
  const Scalar _tmp611 = -_tmp285 * _tmp576 - _tmp583 * _tmp87 + _tmp583 * _tmp90 -
                         _tmp605 * _tmp82 + _tmp606 + _tmp607 * _tmp82;
  const Scalar _tmp612 =
      -_tmp119 * _tmp611 + _tmp259 * _tmp585 - _tmp292 * _tmp588 + _tmp302 * _tmp588 +
      _tmp307 * _tmp593 -
      _tmp51 * (-_tmp119 * _tmp609 + _tmp151 * _tmp590 + _tmp294 * _tmp585 - _tmp577 * _tmp94 +
                _tmp584 * _tmp94 - _tmp586 * _tmp73 - _tmp589 * _tmp67 + _tmp591 * _tmp67 -
                _tmp592 * _tmp96 + _tmp602 * _tmp75 - _tmp608 * _tmp74) -
      _tmp572 * _tmp67 + _tmp586 - _tmp592 * _tmp92 - _tmp602 * _tmp74 + _tmp607 * _tmp74 -
      _tmp610 * _tmp97;
  const Scalar _tmp613 = _tmp309 * _tmp612;
  const Scalar _tmp614 = _tmp592 * _tmp99;
  const Scalar _tmp615 = _tmp565 + _tmp569 + _tmp574;
  const Scalar _tmp616 = _tmp555 + _tmp573 + _tmp578;
  const Scalar _tmp617 = _tmp403 * _tmp615 + _tmp404 * _tmp616;
  const Scalar _tmp618 = fh1 * (_tmp133 * _tmp616 - _tmp134 * _tmp616 + _tmp147 * _tmp615 -
                                _tmp412 * _tmp615 + _tmp477 * _tmp617 - _tmp478 * _tmp617);
  const Scalar _tmp619 = _tmp336 * _tmp567;
  const Scalar _tmp620 = _tmp340 * _tmp567;
  const Scalar _tmp621 = _tmp109 * (_tmp113 * _tmp559 - _tmp114 * _tmp559 - _tmp338 * _tmp566 +
                                    _tmp339 * _tmp566 + _tmp341 * _tmp620 - _tmp343 * _tmp620);
  const Scalar _tmp622 = _tmp347 * _tmp559;
  const Scalar _tmp623 = -_tmp116 * _tmp583 + _tmp117 * _tmp576 + _tmp346 * _tmp576 -
                         _tmp45 * _tmp583 - _tmp49 * _tmp580 + _tmp49 * _tmp582 - _tmp576 * _tmp83 +
                         _tmp580 * _tmp79 + _tmp619 * _tmp82 + _tmp621 * _tmp82 - _tmp622 * _tmp82;
  const Scalar _tmp624 = _tmp116 * _tmp572 - _tmp116 * _tmp590 - _tmp119 * _tmp623 -
                         _tmp150 * _tmp592 - _tmp350 * _tmp588 + _tmp351 * _tmp585 +
                         _tmp55 * _tmp589 - _tmp55 * _tmp591 + _tmp57 * _tmp591 - _tmp571 * _tmp75 +
                         _tmp572 * _tmp58 + _tmp619 * _tmp74 + _tmp621 * _tmp74 - _tmp622 * _tmp74;
  const Scalar _tmp625 = _tmp357 * _tmp585;
  const Scalar _tmp626 =
      -_tmp152 * _tmp610 + _tmp359 * _tmp611 + _tmp362 * _tmp593 -
      _tmp51 * (_tmp359 * _tmp609 + _tmp577 * _tmp87 + _tmp577 * _tmp96 - _tmp584 * _tmp87 -
                _tmp584 * _tmp96 + _tmp608 - _tmp625 * _tmp95) +
      _tmp577 * _tmp92 - _tmp584 * _tmp92 - _tmp594 - _tmp595 + _tmp601 + _tmp604 -
      _tmp625 * _tmp91;
  const Scalar _tmp627 = _tmp156 * (-_tmp118 * _tmp625 - _tmp140 * _tmp626 + _tmp150 * _tmp577 -
                                    _tmp150 * _tmp584 - _tmp154 * _tmp624 + _tmp359 * _tmp623 +
                                    _tmp360 * _tmp613 - _tmp619 - _tmp621 + _tmp622) -
                         _tmp355 * _tmp624 + _tmp356 * _tmp612 + _tmp626;
  const Scalar _tmp628 =
      -_tmp102 * _tmp627 - _tmp157 * _tmp614 + _tmp369 * _tmp613 - _tmp577 + _tmp584;
  const Scalar _tmp629 = -_tmp123 * _tmp611 + _tmp138 * _tmp610 + _tmp387 * _tmp609 -
                         _tmp389 * _tmp593 - _tmp392 * _tmp585 + _tmp393 * _tmp585;
  const Scalar _tmp630 = _tmp142 * _tmp612 +
                         _tmp156 * (-_tmp123 * _tmp623 - _tmp140 * _tmp629 - _tmp395 * _tmp624 +
                                    _tmp396 * _tmp585 + _tmp397 * _tmp613) -
                         _tmp386 * _tmp624 + _tmp629;
  const Scalar _tmp631 = -_tmp102 * _tmp630 - _tmp143 * _tmp614 + _tmp401 * _tmp613;
  const Scalar _tmp632 = _tmp405 * _tmp617;
  const Scalar _tmp633 = _tmp323 * _tmp559;
  const Scalar _tmp634 = _tmp319 * _tmp616;
  const Scalar _tmp635 = _tmp239 * _tmp585;
  const Scalar _tmp636 = _tmp421 * _tmp613;

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = 0;
  _res(1, 0) =
      -_tmp163 *
      (-_tmp110 * (-_tmp204 * _tmp206 + _tmp222 * _tmp316 + _tmp238 * _tmp241 + _tmp244 * _tmp314 -
                   _tmp249 * _tmp317 + _tmp310 * _tmp311 - _tmp310 * _tmp315 - _tmp312 * _tmp313) -
       _tmp137 * (_tmp122 * _tmp244 - _tmp125 * _tmp257 - _tmp204 * _tmp374 + _tmp218 * _tmp379 +
                  _tmp238 * _tmp383 - _tmp249 * _tmp378 + _tmp352 * _tmp376 - _tmp352 * _tmp381) -
       _tmp149 * (_tmp100 * _tmp398 + _tmp101 * _tmp402 + _tmp145 * _tmp244 - _tmp145 * _tmp255 +
                  _tmp204 * _tmp384 - _tmp222 * _tmp400 - _tmp238 * _tmp399 - _tmp310 * _tmp385) -
       _tmp162 * (_tmp100 * _tmp365 + _tmp101 * _tmp370 + _tmp159 * _tmp244 - _tmp159 * _tmp255 +
                  _tmp204 * _tmp367 - _tmp222 * _tmp371 - _tmp238 * _tmp366 - _tmp310 * _tmp368) +
       _tmp225 * _tmp335 + _tmp225 * _tmp418 - _tmp320 * _tmp321 + _tmp322 * _tmp324 -
       _tmp322 * _tmp329 + _tmp324 * _tmp330 - _tmp328 * _tmp372 - _tmp328 * _tmp417 -
       _tmp329 * _tmp330 - _tmp331 * _tmp333 + _tmp406 * _tmp409 + _tmp406 * _tmp420 -
       _tmp410 * _tmp415);
  _res(2, 0) =
      -_tmp423 * (_tmp119 * _tmp431 + _tmp238 * _tmp438 - _tmp257 * _tmp429 - _tmp312 * _tmp422 +
                  _tmp320 * _tmp371 + _tmp331 * _tmp428 + _tmp352 * _tmp434 + _tmp370 * _tmp433 -
                  _tmp373 * _tmp415 + _tmp402 * _tmp426 - _tmp406 * _tmp427 - _tmp406 * _tmp430 +
                  _tmp424 * _tmp425 - _tmp425 * _tmp432 - _tmp425 * _tmp435);
  _res(3, 0) =
      -_tmp440 * (_tmp159 * _tmp320 - _tmp310 * _tmp442 - _tmp310 * _tmp447 + _tmp331 * _tmp445 -
                  _tmp352 * _tmp444 + _tmp365 * _tmp446 + _tmp398 * _tmp448 - _tmp406 * _tmp441 -
                  _tmp406 * _tmp443 + _tmp414 * _tmp436 - _tmp431);
  _res(0, 1) = 0;
  _res(1, 1) =
      -_tmp163 *
      (-_tmp110 * (-_tmp103 * _tmp530 + _tmp241 * _tmp527 + _tmp311 * _tmp529 - _tmp313 * _tmp497 +
                   _tmp314 * _tmp494 - _tmp315 * _tmp529 + _tmp316 * _tmp504 - _tmp317 * _tmp489) -
       _tmp137 * (_tmp122 * _tmp494 - _tmp125 * _tmp496 - _tmp373 * _tmp518 + _tmp376 * _tmp538 -
                  _tmp378 * _tmp489 + _tmp379 * _tmp503 - _tmp381 * _tmp538 + _tmp382 * _tmp545) -
       _tmp149 * (_tmp100 * _tmp543 + _tmp101 * _tmp544 + _tmp144 * _tmp530 - _tmp145 * _tmp490 +
                  _tmp145 * _tmp494 - _tmp385 * _tmp529 - _tmp399 * _tmp527 - _tmp400 * _tmp504) -
       _tmp162 * (_tmp100 * _tmp539 + _tmp101 * _tmp540 + _tmp158 * _tmp530 - _tmp159 * _tmp490 +
                  _tmp159 * _tmp494 - _tmp366 * _tmp527 - _tmp368 * _tmp529 - _tmp371 * _tmp504) +
       _tmp322 * _tmp468 - _tmp322 * _tmp484 + _tmp330 * _tmp468 - _tmp330 * _tmp484 -
       _tmp333 * _tmp462 + _tmp334 * _tmp468 - _tmp372 * _tmp483 + _tmp409 * _tmp485 -
       _tmp410 * _tmp480 + _tmp416 * _tmp468 - _tmp417 * _tmp483 + _tmp420 * _tmp485 -
       _tmp475 * _tmp486);
  _res(2, 1) =
      -_tmp423 * (_tmp119 * _tmp546 - _tmp373 * _tmp480 + _tmp424 * _tmp548 + _tmp426 * _tmp544 -
                  _tmp427 * _tmp485 + _tmp428 * _tmp462 - _tmp429 * _tmp496 - _tmp430 * _tmp485 -
                  _tmp432 * _tmp548 + _tmp433 * _tmp540 + _tmp434 * _tmp538 - _tmp435 * _tmp548 +
                  _tmp437 * _tmp545 - _tmp439 * _tmp496 * _tmp85 + _tmp475 * _tmp547);
  _res(3, 1) =
      -_tmp440 * (_tmp436 * _tmp479 - _tmp441 * _tmp485 - _tmp442 * _tmp529 - _tmp443 * _tmp485 -
                  _tmp444 * _tmp538 + _tmp445 * _tmp462 + _tmp446 * _tmp539 - _tmp447 * _tmp529 +
                  _tmp448 * _tmp543 + _tmp475 * _tmp549 - _tmp546);
  _res(0, 2) = 0;
  _res(1, 2) =
      -_tmp163 *
      (-_tmp110 * (-_tmp206 * _tmp576 + _tmp241 * _tmp585 + _tmp311 * _tmp613 - _tmp313 * _tmp614 +
                   _tmp314 * _tmp572 - _tmp315 * _tmp613 + _tmp316 * _tmp583 - _tmp317 * _tmp588) -
       _tmp137 * (_tmp122 * _tmp572 - _tmp125 * _tmp592 - _tmp374 * _tmp576 + _tmp376 * _tmp624 -
                  _tmp378 * _tmp588 + _tmp379 * _tmp581 - _tmp381 * _tmp624 + _tmp383 * _tmp585) -
       _tmp149 * (_tmp100 * _tmp630 + _tmp101 * _tmp631 + _tmp145 * _tmp572 - _tmp145 * _tmp590 +
                  _tmp384 * _tmp576 - _tmp385 * _tmp613 - _tmp399 * _tmp585 - _tmp400 * _tmp583) -
       _tmp162 * (_tmp100 * _tmp627 + _tmp101 * _tmp628 + _tmp159 * _tmp572 - _tmp159 * _tmp590 -
                  _tmp366 * _tmp585 + _tmp367 * _tmp576 - _tmp368 * _tmp613 - _tmp371 * _tmp583) -
       _tmp322 * _tmp568 + _tmp322 * _tmp633 - _tmp330 * _tmp568 + _tmp330 * _tmp633 +
       _tmp335 * _tmp559 - _tmp372 * _tmp567 - _tmp407 * _tmp634 + _tmp409 * _tmp632 -
       _tmp410 * _tmp618 - _tmp417 * _tmp567 + _tmp418 * _tmp559 + _tmp420 * _tmp632 -
       _tmp486 * _tmp615);
  _res(2, 2) =
      -_tmp423 * (_tmp119 * _tmp636 - _tmp373 * _tmp618 + _tmp400 * _tmp634 - _tmp422 * _tmp614 +
                  _tmp424 * _tmp635 + _tmp426 * _tmp631 - _tmp427 * _tmp632 - _tmp429 * _tmp592 -
                  _tmp430 * _tmp632 - _tmp432 * _tmp635 + _tmp433 * _tmp628 + _tmp434 * _tmp624 -
                  _tmp435 * _tmp635 + _tmp438 * _tmp585 + _tmp547 * _tmp615);
  _res(3, 2) =
      -_tmp440 * (_tmp122 * _tmp618 + _tmp145 * _tmp634 - _tmp441 * _tmp632 - _tmp442 * _tmp613 -
                  _tmp443 * _tmp632 - _tmp444 * _tmp624 + _tmp446 * _tmp627 - _tmp447 * _tmp613 +
                  _tmp448 * _tmp630 + _tmp549 * _tmp615 - _tmp636);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
