// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_DeltaRot_Nl18
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost2WrtDeltarotNl18(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 3535

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (1059)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp1 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp2 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp5 = (Scalar(1) / Scalar(2)) * _tmp4;
  const Scalar _tmp6 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp7 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp8 = _tmp1 - _tmp3 + _tmp5 + _tmp7;
  const Scalar _tmp9 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp10 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp11 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp12 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp13 = _tmp10 - _tmp11 + _tmp12 + _tmp9;
  const Scalar _tmp14 = Scalar(0.043999999999999997) * _tmp13;
  const Scalar _tmp15 = _tmp14 * _tmp8;
  const Scalar _tmp16 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp17 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp18 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp19 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp20 = -Scalar(1) / Scalar(2) * _tmp16 - Scalar(1) / Scalar(2) * _tmp17 -
                        Scalar(1) / Scalar(2) * _tmp18 + (Scalar(1) / Scalar(2)) * _tmp19;
  const Scalar _tmp21 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp22 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp23 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp24 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp25 = -_tmp21 + _tmp22 + _tmp23 + _tmp24;
  const Scalar _tmp26 = Scalar(0.043999999999999997) * _tmp25;
  const Scalar _tmp27 = _tmp20 * _tmp26;
  const Scalar _tmp28 = -_tmp15 - _tmp27;
  const Scalar _tmp29 = (Scalar(1) / Scalar(2)) * _tmp21;
  const Scalar _tmp30 = (Scalar(1) / Scalar(2)) * _tmp22;
  const Scalar _tmp31 = (Scalar(1) / Scalar(2)) * _tmp23;
  const Scalar _tmp32 = (Scalar(1) / Scalar(2)) * _tmp24;
  const Scalar _tmp33 = _tmp29 - _tmp30 - _tmp31 - _tmp32;
  const Scalar _tmp34 = Scalar(0.41999999999999998) * _tmp13;
  const Scalar _tmp35 = _tmp33 * _tmp34;
  const Scalar _tmp36 = -_tmp16 - _tmp17 - _tmp18 + _tmp19;
  const Scalar _tmp37 = Scalar(0.41999999999999998) * _tmp36;
  const Scalar _tmp38 = _tmp37 * _tmp8;
  const Scalar _tmp39 = _tmp0 - _tmp2 + _tmp4 + _tmp6;
  const Scalar _tmp40 = Scalar(0.41999999999999998) * _tmp39;
  const Scalar _tmp41 = _tmp20 * _tmp40;
  const Scalar _tmp42 = (Scalar(1) / Scalar(2)) * _tmp9;
  const Scalar _tmp43 = (Scalar(1) / Scalar(2)) * _tmp10;
  const Scalar _tmp44 = (Scalar(1) / Scalar(2)) * _tmp11;
  const Scalar _tmp45 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp46 = -_tmp42 - _tmp43 + _tmp44 - _tmp45;
  const Scalar _tmp47 = Scalar(0.41999999999999998) * _tmp46;
  const Scalar _tmp48 = _tmp25 * _tmp47;
  const Scalar _tmp49 = _tmp41 + _tmp48;
  const Scalar _tmp50 = -_tmp35 - _tmp38 + _tmp49;
  const Scalar _tmp51 = _tmp28 + _tmp50;
  const Scalar _tmp52 = _tmp40 * _tmp8;
  const Scalar _tmp53 = Scalar(0.41999999999999998) * _tmp25;
  const Scalar _tmp54 = _tmp33 * _tmp53;
  const Scalar _tmp55 = -_tmp54;
  const Scalar _tmp56 = _tmp13 * _tmp47;
  const Scalar _tmp57 = _tmp20 * _tmp37;
  const Scalar _tmp58 = -_tmp57;
  const Scalar _tmp59 = -_tmp56 + _tmp58;
  const Scalar _tmp60 = -_tmp52 + _tmp55 + _tmp59;
  const Scalar _tmp61 = 2 * _tmp39;
  const Scalar _tmp62 = _tmp13 * _tmp61;
  const Scalar _tmp63 = 2 * _tmp36;
  const Scalar _tmp64 = _tmp25 * _tmp63;
  const Scalar _tmp65 = Scalar(0.20999999999999999) * _tmp62 + Scalar(0.20999999999999999) * _tmp64;
  const Scalar _tmp66 = -2 * std::pow(_tmp13, Scalar(2));
  const Scalar _tmp67 = -2 * std::pow(_tmp25, Scalar(2));
  const Scalar _tmp68 = -Scalar(0.010999999999999999) * _tmp66 -
                        Scalar(0.010999999999999999) * _tmp67 + Scalar(-0.010999999999999999);
  const Scalar _tmp69 = _tmp25 * _tmp61;
  const Scalar _tmp70 = _tmp13 * _tmp63;
  const Scalar _tmp71 = Scalar(0.20999999999999999) * _tmp69 - Scalar(0.20999999999999999) * _tmp70;
  const Scalar _tmp72 = _tmp68 - _tmp71;
  const Scalar _tmp73 = _tmp65 + _tmp72;
  const Scalar _tmp74 = -_tmp73 - position_vector(2, 0) + Scalar(8.3701287145205097);
  const Scalar _tmp75 = 2 * _tmp74;
  const Scalar _tmp76 = _tmp33 * _tmp40;
  const Scalar _tmp77 = _tmp36 * _tmp47;
  const Scalar _tmp78 = _tmp76 + _tmp77;
  const Scalar _tmp79 = _tmp20 * _tmp34;
  const Scalar _tmp80 = _tmp53 * _tmp8;
  const Scalar _tmp81 = _tmp79 + _tmp80;
  const Scalar _tmp82 = _tmp78 + _tmp81;
  const Scalar _tmp83 = Scalar(0.021999999999999999) * _tmp13;
  const Scalar _tmp84 = _tmp46 * _tmp83;
  const Scalar _tmp85 = Scalar(0.021999999999999999) * _tmp39;
  const Scalar _tmp86 = _tmp8 * _tmp85;
  const Scalar _tmp87 = Scalar(0.021999999999999999) * _tmp33;
  const Scalar _tmp88 = _tmp25 * _tmp87;
  const Scalar _tmp89 = Scalar(0.021999999999999999) * _tmp36;
  const Scalar _tmp90 = _tmp20 * _tmp89;
  const Scalar _tmp91 = -_tmp90;
  const Scalar _tmp92 = _tmp84 + _tmp86 - _tmp88 + _tmp91;
  const Scalar _tmp93 = Scalar(0.83999999999999997) * _tmp39;
  const Scalar _tmp94 = _tmp46 * _tmp93;
  const Scalar _tmp95 = Scalar(0.83999999999999997) * _tmp25;
  const Scalar _tmp96 = _tmp20 * _tmp95;
  const Scalar _tmp97 = _tmp94 + _tmp96;
  const Scalar _tmp98 = _tmp92 + _tmp97;
  const Scalar _tmp99 = 2 * _tmp13 * _tmp25;
  const Scalar _tmp100 = _tmp39 * _tmp63;
  const Scalar _tmp101 =
      Scalar(0.20999999999999999) * _tmp100 + Scalar(0.20999999999999999) * _tmp99;
  const Scalar _tmp102 = -_tmp101;
  const Scalar _tmp103 = 1 - 2 * std::pow(_tmp39, Scalar(2));
  const Scalar _tmp104 =
      Scalar(0.20999999999999999) * _tmp103 + Scalar(0.20999999999999999) * _tmp67;
  const Scalar _tmp105 = _tmp62 - _tmp64;
  const Scalar _tmp106 = -Scalar(0.010999999999999999) * _tmp105;
  const Scalar _tmp107 = _tmp104 + _tmp106;
  const Scalar _tmp108 = _tmp102 + _tmp107;
  const Scalar _tmp109 = _tmp108 + position_vector(1, 0);
  const Scalar _tmp110 = Scalar(4.83288938413423) - _tmp109;
  const Scalar _tmp111 = 2 * _tmp110;
  const Scalar _tmp112 = -_tmp79;
  const Scalar _tmp113 = -_tmp80;
  const Scalar _tmp114 = _tmp112 + _tmp113 + _tmp78;
  const Scalar _tmp115 = _tmp13 * _tmp87;
  const Scalar _tmp116 = _tmp20 * _tmp85;
  const Scalar _tmp117 = Scalar(0.021999999999999999) * _tmp25;
  const Scalar _tmp118 = _tmp117 * _tmp46;
  const Scalar _tmp119 = _tmp8 * _tmp89;
  const Scalar _tmp120 = _tmp115 + _tmp116 + _tmp118 + _tmp119;
  const Scalar _tmp121 = -_tmp94;
  const Scalar _tmp122 = Scalar(0.83999999999999997) * _tmp13;
  const Scalar _tmp123 = _tmp122 * _tmp8;
  const Scalar _tmp124 = _tmp121 - _tmp123;
  const Scalar _tmp125 = _tmp120 + _tmp124;
  const Scalar _tmp126 =
      Scalar(0.20999999999999999) * _tmp103 + Scalar(0.20999999999999999) * _tmp66;
  const Scalar _tmp127 = -_tmp126;
  const Scalar _tmp128 = _tmp69 + _tmp70;
  const Scalar _tmp129 = -Scalar(0.010999999999999999) * _tmp128;
  const Scalar _tmp130 =
      -Scalar(0.20999999999999999) * _tmp100 + Scalar(0.20999999999999999) * _tmp99;
  const Scalar _tmp131 = _tmp129 + _tmp130;
  const Scalar _tmp132 = _tmp127 + _tmp131;
  const Scalar _tmp133 = _tmp132 + position_vector(0, 0);
  const Scalar _tmp134 = -_tmp133 + Scalar(-1.7965602546229);
  const Scalar _tmp135 = 2 * _tmp134;
  const Scalar _tmp136 = _tmp111 * (_tmp82 + _tmp98) + _tmp135 * (_tmp114 + _tmp125);
  const Scalar _tmp137 = std::pow(_tmp110, Scalar(2)) + std::pow(_tmp134, Scalar(2));
  const Scalar _tmp138 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp137 + std::pow(_tmp74, Scalar(2))));
  const Scalar _tmp139 = std::sqrt(_tmp137);
  const Scalar _tmp140 = Scalar(1.0) / (fh1);
  const Scalar _tmp141 =
      Scalar(0.5) *
      std::cosh(Scalar(0.1034955) * _tmp140 *
                (-_tmp139 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp140 * fv1))) /
      _tmp139;
  const Scalar _tmp142 = _tmp56 + _tmp57;
  const Scalar _tmp143 = _tmp142 + _tmp52 + _tmp54;
  const Scalar _tmp144 = _tmp143 + _tmp51;
  const Scalar _tmp145 = -_tmp65;
  const Scalar _tmp146 = _tmp145 + _tmp72;
  const Scalar _tmp147 = -_tmp146 - position_vector(2, 0) + Scalar(8.4718465805053693);
  const Scalar _tmp148 = 2 * _tmp147;
  const Scalar _tmp149 = -_tmp76;
  const Scalar _tmp150 = -_tmp77;
  const Scalar _tmp151 = _tmp149 + _tmp150 + _tmp81;
  const Scalar _tmp152 = _tmp129 - _tmp130;
  const Scalar _tmp153 = _tmp127 + _tmp152;
  const Scalar _tmp154 = _tmp153 + position_vector(0, 0);
  const Scalar _tmp155 = -_tmp154 + Scalar(-1.9874742031097401);
  const Scalar _tmp156 = 2 * _tmp155;
  const Scalar _tmp157 = -_tmp96;
  const Scalar _tmp158 = _tmp121 + _tmp157;
  const Scalar _tmp159 = _tmp158 + _tmp82;
  const Scalar _tmp160 = _tmp159 + _tmp92;
  const Scalar _tmp161 = -_tmp104 + _tmp106;
  const Scalar _tmp162 = _tmp102 + _tmp161;
  const Scalar _tmp163 = _tmp162 + position_vector(1, 0);
  const Scalar _tmp164 = -_tmp163 + Scalar(-8.3196563720703107);
  const Scalar _tmp165 = 2 * _tmp164;
  const Scalar _tmp166 = _tmp156 * (_tmp125 + _tmp151) + _tmp160 * _tmp165;
  const Scalar _tmp167 = std::pow(_tmp155, Scalar(2)) + std::pow(_tmp164, Scalar(2));
  const Scalar _tmp168 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(std::pow(_tmp147, Scalar(2)) + _tmp167));
  const Scalar _tmp169 = _tmp68 + _tmp71;
  const Scalar _tmp170 = _tmp169 + _tmp65;
  const Scalar _tmp171 = _tmp101 + _tmp107;
  const Scalar _tmp172 = _tmp171 + position_vector(1, 0);
  const Scalar _tmp173 = _tmp172 + Scalar(-4.7744369927459998);
  const Scalar _tmp174 = _tmp126 + _tmp131;
  const Scalar _tmp175 = _tmp174 + position_vector(0, 0);
  const Scalar _tmp176 = _tmp175 + Scalar(-2.7171519410699099);
  const Scalar _tmp177 = std::pow(_tmp173, Scalar(2)) + std::pow(_tmp176, Scalar(2));
  const Scalar _tmp178 = std::pow(_tmp177, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp179 = _tmp173 * _tmp178;
  const Scalar _tmp180 = _tmp163 + Scalar(8.3196563720703107);
  const Scalar _tmp181 = _tmp154 + Scalar(1.9874742031097401);
  const Scalar _tmp182 = Scalar(1.0) / (_tmp181);
  const Scalar _tmp183 = _tmp180 * _tmp182;
  const Scalar _tmp184 = _tmp176 * _tmp178;
  const Scalar _tmp185 = _tmp146 * _tmp184;
  const Scalar _tmp186 = _tmp145 + _tmp169;
  const Scalar _tmp187 = _tmp101 + _tmp161;
  const Scalar _tmp188 = _tmp187 + position_vector(1, 0);
  const Scalar _tmp189 = _tmp188 + Scalar(8.3885017487099702);
  const Scalar _tmp190 = _tmp126 + _tmp152;
  const Scalar _tmp191 = _tmp190 + position_vector(0, 0);
  const Scalar _tmp192 = _tmp191 + Scalar(-2.5193355532036801);
  const Scalar _tmp193 = std::pow(_tmp189, Scalar(2)) + std::pow(_tmp192, Scalar(2));
  const Scalar _tmp194 = std::pow(_tmp193, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp195 = _tmp189 * _tmp194;
  const Scalar _tmp196 = _tmp192 * _tmp194;
  const Scalar _tmp197 = _tmp146 * _tmp196;
  const Scalar _tmp198 = -_tmp183 * _tmp197 + _tmp186 * _tmp195;
  const Scalar _tmp199 = _tmp183 * _tmp196 - _tmp195;
  const Scalar _tmp200 = Scalar(1.0) / (_tmp199);
  const Scalar _tmp201 = -_tmp179 + _tmp183 * _tmp184;
  const Scalar _tmp202 = _tmp200 * _tmp201;
  const Scalar _tmp203 = _tmp170 * _tmp179 - _tmp183 * _tmp185 - _tmp198 * _tmp202;
  const Scalar _tmp204 = Scalar(1.0) * _tmp162;
  const Scalar _tmp205 = -_tmp204;
  const Scalar _tmp206 = _tmp187 + _tmp205;
  const Scalar _tmp207 = Scalar(1.0) / (_tmp206);
  const Scalar _tmp208 = Scalar(1.0) * _tmp153;
  const Scalar _tmp209 = -_tmp190 + _tmp208;
  const Scalar _tmp210 = _tmp207 * _tmp209;
  const Scalar _tmp211 = -_tmp186 * _tmp196 + _tmp197;
  const Scalar _tmp212 = -_tmp170 * _tmp184 + _tmp185 - _tmp202 * _tmp211 - _tmp203 * _tmp210;
  const Scalar _tmp213 = Scalar(1.0) / (_tmp212);
  const Scalar _tmp214 = std::pow(_tmp181, Scalar(2));
  const Scalar _tmp215 = std::pow(_tmp180, Scalar(2)) + _tmp214;
  const Scalar _tmp216 = std::sqrt(_tmp215);
  const Scalar _tmp217 = Scalar(1.0) / (_tmp216);
  const Scalar _tmp218 = _tmp153 * _tmp217;
  const Scalar _tmp219 = _tmp181 * _tmp217;
  const Scalar _tmp220 = -_tmp162 * _tmp219 + _tmp180 * _tmp218;
  const Scalar _tmp221 = _tmp182 * _tmp216;
  const Scalar _tmp222 = _tmp220 * _tmp221;
  const Scalar _tmp223 = _tmp171 * _tmp178;
  const Scalar _tmp224 = _tmp187 * _tmp196 - _tmp190 * _tmp195 + _tmp196 * _tmp222;
  const Scalar _tmp225 =
      -_tmp174 * _tmp179 + _tmp176 * _tmp223 + _tmp184 * _tmp222 - _tmp202 * _tmp224;
  const Scalar _tmp226 = Scalar(1.0) / (_tmp225);
  const Scalar _tmp227 = _tmp183 * _tmp200;
  const Scalar _tmp228 = _tmp146 * _tmp183;
  const Scalar _tmp229 = _tmp198 * _tmp227 + _tmp228;
  const Scalar _tmp230 = -_tmp146 - _tmp210 * _tmp229 + _tmp211 * _tmp227;
  const Scalar _tmp231 = _tmp213 * _tmp225;
  const Scalar _tmp232 = -_tmp222 + _tmp224 * _tmp227 - _tmp230 * _tmp231;
  const Scalar _tmp233 = _tmp226 * _tmp232;
  const Scalar _tmp234 = _tmp212 * _tmp233;
  const Scalar _tmp235 = _tmp230 + _tmp234;
  const Scalar _tmp236 = _tmp213 * _tmp235;
  const Scalar _tmp237 = -_tmp183 - _tmp201 * _tmp236;
  const Scalar _tmp238 = _tmp196 * _tmp200;
  const Scalar _tmp239 = _tmp184 * _tmp236 + _tmp237 * _tmp238 + Scalar(1.0);
  const Scalar _tmp240 = _tmp221 * _tmp239;
  const Scalar _tmp241 = _tmp133 + Scalar(1.7965602546229);
  const Scalar _tmp242 = _tmp109 + Scalar(-4.83288938413423);
  const Scalar _tmp243 = std::pow(_tmp241, Scalar(2)) + std::pow(_tmp242, Scalar(2));
  const Scalar _tmp244 = std::pow(_tmp243, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp245 = (Scalar(1) / Scalar(2)) * _tmp244;
  const Scalar _tmp246 = -_tmp118;
  const Scalar _tmp247 = -_tmp116;
  const Scalar _tmp248 = -_tmp115 - _tmp119 + _tmp246 + _tmp247;
  const Scalar _tmp249 = _tmp123 + _tmp94;
  const Scalar _tmp250 = _tmp151 + _tmp249;
  const Scalar _tmp251 = _tmp248 + _tmp250;
  const Scalar _tmp252 = 2 * _tmp241;
  const Scalar _tmp253 = -_tmp84;
  const Scalar _tmp254 = _tmp253 - _tmp86 + _tmp88 + _tmp90;
  const Scalar _tmp255 = _tmp112 + _tmp149;
  const Scalar _tmp256 = _tmp113 + _tmp150 + _tmp255;
  const Scalar _tmp257 = _tmp158 + _tmp256;
  const Scalar _tmp258 = _tmp254 + _tmp257;
  const Scalar _tmp259 = 2 * _tmp242;
  const Scalar _tmp260 = _tmp251 * _tmp252 + _tmp258 * _tmp259;
  const Scalar _tmp261 = _tmp241 * _tmp260;
  const Scalar _tmp262 = _tmp245 * _tmp261 * fh1;
  const Scalar _tmp263 = _tmp254 + _tmp97;
  const Scalar _tmp264 = _tmp256 + _tmp263;
  const Scalar _tmp265 = 2 * _tmp180;
  const Scalar _tmp266 = _tmp114 + _tmp249;
  const Scalar _tmp267 = _tmp248 + _tmp266;
  const Scalar _tmp268 = 2 * _tmp181;
  const Scalar _tmp269 = _tmp264 * _tmp265 + _tmp267 * _tmp268;
  const Scalar _tmp270 = _tmp182 * _tmp217;
  const Scalar _tmp271 = Scalar(1.0) * _tmp200;
  const Scalar _tmp272 = _tmp226 * _tmp271;
  const Scalar _tmp273 = _tmp196 * _tmp272;
  const Scalar _tmp274 = Scalar(1.0) * _tmp226;
  const Scalar _tmp275 = _tmp184 * _tmp274 - _tmp201 * _tmp273;
  const Scalar _tmp276 = std::pow(_tmp243, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp277 = _tmp241 * _tmp276;
  const Scalar _tmp278 = _tmp132 * _tmp276;
  const Scalar _tmp279 = -_tmp108 * _tmp277 + _tmp242 * _tmp278;
  const Scalar _tmp280 = _tmp279 * fh1;
  const Scalar _tmp281 = _tmp275 * _tmp280;
  const Scalar _tmp282 = _tmp270 * _tmp281;
  const Scalar _tmp283 = (Scalar(1) / Scalar(2)) * _tmp282;
  const Scalar _tmp284 = _tmp198 * _tmp271;
  const Scalar _tmp285 = _tmp210 * _tmp284 - _tmp211 * _tmp271;
  const Scalar _tmp286 = -_tmp224 * _tmp271 - _tmp231 * _tmp285;
  const Scalar _tmp287 = _tmp226 * _tmp286;
  const Scalar _tmp288 = _tmp212 * _tmp287;
  const Scalar _tmp289 = _tmp285 + _tmp288;
  const Scalar _tmp290 = std::pow(_tmp177, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp291 = (Scalar(1) / Scalar(2)) * _tmp290;
  const Scalar _tmp292 = _tmp159 + _tmp254;
  const Scalar _tmp293 = 2 * _tmp173;
  const Scalar _tmp294 = _tmp124 + _tmp248;
  const Scalar _tmp295 = _tmp151 + _tmp294;
  const Scalar _tmp296 = 2 * _tmp176;
  const Scalar _tmp297 = _tmp292 * _tmp293 + _tmp295 * _tmp296;
  const Scalar _tmp298 = _tmp176 * _tmp297;
  const Scalar _tmp299 = _tmp291 * _tmp298;
  const Scalar _tmp300 = Scalar(1.0) / (_tmp214);
  const Scalar _tmp301 = _tmp180 * _tmp300;
  const Scalar _tmp302 = _tmp267 * _tmp301;
  const Scalar _tmp303 = _tmp178 * _tmp292;
  const Scalar _tmp304 = _tmp182 * _tmp264;
  const Scalar _tmp305 = _tmp178 * _tmp295;
  const Scalar _tmp306 = _tmp173 * _tmp291;
  const Scalar _tmp307 = _tmp297 * _tmp306;
  const Scalar _tmp308 = -_tmp183 * _tmp299 + _tmp183 * _tmp305 - _tmp184 * _tmp302 +
                         _tmp184 * _tmp304 - _tmp303 + _tmp307;
  const Scalar _tmp309 = _tmp200 * _tmp308;
  const Scalar _tmp310 = -_tmp41 - _tmp48;
  const Scalar _tmp311 = _tmp310 + _tmp35 + _tmp38;
  const Scalar _tmp312 = _tmp15 + _tmp27;
  const Scalar _tmp313 = _tmp312 + _tmp60;
  const Scalar _tmp314 = _tmp311 + _tmp313;
  const Scalar _tmp315 = _tmp143 + _tmp312;
  const Scalar _tmp316 = _tmp315 + _tmp50;
  const Scalar _tmp317 = Scalar(1.6799999999999999) * _tmp13;
  const Scalar _tmp318 = Scalar(1.6799999999999999) * _tmp39;
  const Scalar _tmp319 = _tmp318 * _tmp46;
  const Scalar _tmp320 = _tmp317 * _tmp8 + _tmp319;
  const Scalar _tmp321 = _tmp207 * _tmp320;
  const Scalar _tmp322 = _tmp263 + _tmp82;
  const Scalar _tmp323 = 2 * _tmp189;
  const Scalar _tmp324 = _tmp114 + _tmp294;
  const Scalar _tmp325 = 2 * _tmp192;
  const Scalar _tmp326 = _tmp322 * _tmp323 + _tmp324 * _tmp325;
  const Scalar _tmp327 = std::pow(_tmp193, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp328 = (Scalar(1) / Scalar(2)) * _tmp327;
  const Scalar _tmp329 = _tmp189 * _tmp328;
  const Scalar _tmp330 = _tmp326 * _tmp329;
  const Scalar _tmp331 = _tmp192 * _tmp328;
  const Scalar _tmp332 = _tmp326 * _tmp331;
  const Scalar _tmp333 = _tmp194 * _tmp322;
  const Scalar _tmp334 = _tmp194 * _tmp324;
  const Scalar _tmp335 = -_tmp183 * _tmp332 + _tmp183 * _tmp334 - _tmp196 * _tmp302 +
                         _tmp196 * _tmp304 + _tmp330 - _tmp333;
  const Scalar _tmp336 = std::pow(_tmp199, Scalar(-2));
  const Scalar _tmp337 = _tmp201 * _tmp336;
  const Scalar _tmp338 = _tmp211 * _tmp337;
  const Scalar _tmp339 = _tmp146 * _tmp331;
  const Scalar _tmp340 = _tmp313 + _tmp50;
  const Scalar _tmp341 = _tmp146 * _tmp334;
  const Scalar _tmp342 = _tmp186 * _tmp332 - _tmp186 * _tmp334 + _tmp196 * _tmp314 -
                         _tmp196 * _tmp340 - _tmp326 * _tmp339 + _tmp341;
  const Scalar _tmp343 = _tmp122 * _tmp20;
  const Scalar _tmp344 = _tmp8 * _tmp95;
  const Scalar _tmp345 = Scalar(0.83999999999999997) * _tmp36;
  const Scalar _tmp346 = _tmp33 * _tmp93 + _tmp345 * _tmp46;
  const Scalar _tmp347 = _tmp343 + _tmp344 + _tmp346;
  const Scalar _tmp348 = std::pow(_tmp206, Scalar(-2));
  const Scalar _tmp349 = _tmp209 * _tmp348;
  const Scalar _tmp350 = _tmp203 * _tmp349;
  const Scalar _tmp351 = _tmp183 * _tmp314;
  const Scalar _tmp352 = -_tmp183 * _tmp341 - _tmp186 * _tmp330 + _tmp186 * _tmp333 +
                         _tmp195 * _tmp340 - _tmp196 * _tmp351 + _tmp197 * _tmp302 -
                         _tmp197 * _tmp304 + _tmp228 * _tmp332;
  const Scalar _tmp353 = _tmp146 * _tmp305;
  const Scalar _tmp354 = _tmp198 * _tmp337;
  const Scalar _tmp355 = _tmp146 * _tmp304;
  const Scalar _tmp356 = _tmp170 * _tmp303 - _tmp170 * _tmp307 + _tmp179 * _tmp316 -
                         _tmp183 * _tmp353 - _tmp184 * _tmp351 - _tmp184 * _tmp355 +
                         _tmp185 * _tmp302 - _tmp198 * _tmp309 - _tmp202 * _tmp352 +
                         _tmp228 * _tmp299 + _tmp335 * _tmp354;
  const Scalar _tmp357 = -_tmp146 * _tmp299 + _tmp170 * _tmp299 - _tmp170 * _tmp305 +
                         _tmp184 * _tmp314 - _tmp184 * _tmp316 - _tmp202 * _tmp342 -
                         _tmp203 * _tmp321 - _tmp210 * _tmp356 - _tmp211 * _tmp309 +
                         _tmp335 * _tmp338 + _tmp347 * _tmp350 + _tmp353;
  const Scalar _tmp358 = std::pow(_tmp212, Scalar(-2));
  const Scalar _tmp359 = _tmp357 * _tmp358;
  const Scalar _tmp360 = _tmp184 * _tmp359;
  const Scalar _tmp361 = _tmp213 * _tmp289;
  const Scalar _tmp362 = -_tmp201 * _tmp361 + Scalar(1.0);
  const Scalar _tmp363 = _tmp196 * _tmp362;
  const Scalar _tmp364 = _tmp335 * _tmp336;
  const Scalar _tmp365 = _tmp200 * _tmp362;
  const Scalar _tmp366 = _tmp201 * _tmp358;
  const Scalar _tmp367 = _tmp289 * _tmp366;
  const Scalar _tmp368 = _tmp217 * _tmp267;
  const Scalar _tmp369 = _tmp162 * _tmp181;
  const Scalar _tmp370 = std::pow(_tmp215, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp371 = (Scalar(1) / Scalar(2)) * _tmp370;
  const Scalar _tmp372 = _tmp369 * _tmp371;
  const Scalar _tmp373 = _tmp153 * _tmp180;
  const Scalar _tmp374 = _tmp371 * _tmp373;
  const Scalar _tmp375 = _tmp221 * (-_tmp162 * _tmp368 + _tmp180 * _tmp368 + _tmp218 * _tmp264 -
                                    _tmp219 * _tmp264 + _tmp269 * _tmp372 - _tmp269 * _tmp374);
  const Scalar _tmp376 = _tmp216 * _tmp300;
  const Scalar _tmp377 = _tmp220 * _tmp376;
  const Scalar _tmp378 = _tmp267 * _tmp377;
  const Scalar _tmp379 = _tmp220 * _tmp270;
  const Scalar _tmp380 = (Scalar(1) / Scalar(2)) * _tmp379;
  const Scalar _tmp381 = _tmp269 * _tmp380;
  const Scalar _tmp382 = -_tmp187 * _tmp332 + _tmp187 * _tmp334 + _tmp190 * _tmp330 -
                         _tmp190 * _tmp333 + _tmp192 * _tmp333 - _tmp195 * _tmp324 +
                         _tmp196 * _tmp375 - _tmp196 * _tmp378 + _tmp196 * _tmp381 -
                         _tmp222 * _tmp332 + _tmp222 * _tmp334;
  const Scalar _tmp383 = _tmp224 * _tmp337;
  const Scalar _tmp384 = -_tmp171 * _tmp299 - _tmp174 * _tmp303 + _tmp174 * _tmp307 +
                         _tmp176 * _tmp303 - _tmp179 * _tmp295 + _tmp184 * _tmp375 -
                         _tmp184 * _tmp378 + _tmp184 * _tmp381 - _tmp202 * _tmp382 -
                         _tmp222 * _tmp299 + _tmp222 * _tmp305 + _tmp223 * _tmp295 -
                         _tmp224 * _tmp309 + _tmp335 * _tmp383;
  const Scalar _tmp385 = _tmp213 * _tmp285;
  const Scalar _tmp386 = _tmp225 * _tmp358;
  const Scalar _tmp387 = _tmp285 * _tmp386;
  const Scalar _tmp388 = Scalar(1.0) * _tmp336;
  const Scalar _tmp389 = _tmp335 * _tmp388;
  const Scalar _tmp390 = Scalar(1.0) * _tmp207;
  const Scalar _tmp391 = _tmp198 * _tmp200;
  const Scalar _tmp392 = _tmp390 * _tmp391;
  const Scalar _tmp393 = _tmp271 * _tmp352;
  const Scalar _tmp394 = _tmp198 * _tmp389;
  const Scalar _tmp395 = _tmp347 * _tmp349;
  const Scalar _tmp396 = _tmp210 * _tmp393 - _tmp210 * _tmp394 + _tmp211 * _tmp389 -
                         _tmp271 * _tmp342 - _tmp284 * _tmp395 + _tmp320 * _tmp392;
  const Scalar _tmp397 = _tmp212 * _tmp226;
  const Scalar _tmp398 = _tmp397 * (_tmp224 * _tmp389 - _tmp231 * _tmp396 - _tmp271 * _tmp382 +
                                    _tmp357 * _tmp387 - _tmp384 * _tmp385);
  const Scalar _tmp399 = _tmp212 * _tmp286;
  const Scalar _tmp400 = std::pow(_tmp225, Scalar(-2));
  const Scalar _tmp401 = _tmp384 * _tmp400;
  const Scalar _tmp402 = _tmp399 * _tmp401;
  const Scalar _tmp403 = _tmp287 * _tmp357;
  const Scalar _tmp404 = _tmp396 + _tmp398 - _tmp402 + _tmp403;
  const Scalar _tmp405 = _tmp201 * _tmp213;
  const Scalar _tmp406 = -_tmp308 * _tmp361 + _tmp357 * _tmp367 - _tmp404 * _tmp405;
  const Scalar _tmp407 = _tmp184 * _tmp213;
  const Scalar _tmp408 = _tmp242 * _tmp276;
  const Scalar _tmp409 = _tmp408 * fh1;
  const Scalar _tmp410 = _tmp221 * _tmp409;
  const Scalar _tmp411 = _tmp204 * _tmp210 + _tmp208;
  const Scalar _tmp412 = 0;
  const Scalar _tmp413 = _tmp213 * _tmp412;
  const Scalar _tmp414 = _tmp202 * _tmp413;
  const Scalar _tmp415 = _tmp196 * _tmp202;
  const Scalar _tmp416 = _tmp412 * _tmp415;
  const Scalar _tmp417 = _tmp196 * _tmp413;
  const Scalar _tmp418 = _tmp335 * _tmp337;
  const Scalar _tmp419 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp420 = _tmp221 * _tmp419;
  const Scalar _tmp421 = _tmp230 * _tmp386;
  const Scalar _tmp422 = _tmp200 * _tmp304;
  const Scalar _tmp423 = _tmp183 * _tmp198;
  const Scalar _tmp424 = -_tmp146 * _tmp302 + _tmp198 * _tmp422 + _tmp227 * _tmp352 -
                         _tmp302 * _tmp391 + _tmp351 + _tmp355 - _tmp364 * _tmp423;
  const Scalar _tmp425 = _tmp207 * _tmp229;
  const Scalar _tmp426 = _tmp200 * _tmp211;
  const Scalar _tmp427 = _tmp183 * _tmp211;
  const Scalar _tmp428 = _tmp229 * _tmp349;
  const Scalar _tmp429 = _tmp144 - _tmp210 * _tmp424 + _tmp211 * _tmp422 + _tmp227 * _tmp342 -
                         _tmp302 * _tmp426 - _tmp320 * _tmp425 + _tmp347 * _tmp428 -
                         _tmp364 * _tmp427;
  const Scalar _tmp430 = _tmp200 * _tmp224;
  const Scalar _tmp431 = _tmp183 * _tmp224;
  const Scalar _tmp432 = _tmp213 * _tmp230;
  const Scalar _tmp433 = _tmp397 * (_tmp224 * _tmp422 + _tmp227 * _tmp382 - _tmp231 * _tmp429 -
                                    _tmp302 * _tmp430 + _tmp357 * _tmp421 - _tmp364 * _tmp431 -
                                    _tmp375 + _tmp378 - _tmp381 - _tmp384 * _tmp432);
  const Scalar _tmp434 = _tmp212 * _tmp232;
  const Scalar _tmp435 = _tmp401 * _tmp434;
  const Scalar _tmp436 = _tmp233 * _tmp357;
  const Scalar _tmp437 = _tmp429 + _tmp433 - _tmp435 + _tmp436;
  const Scalar _tmp438 = _tmp200 * _tmp237;
  const Scalar _tmp439 = _tmp196 * _tmp237;
  const Scalar _tmp440 = _tmp235 * _tmp366;
  const Scalar _tmp441 =
      -_tmp236 * _tmp308 + _tmp302 - _tmp304 + _tmp357 * _tmp440 - _tmp405 * _tmp437;
  const Scalar _tmp442 = _tmp277 * fh1;
  const Scalar _tmp443 = _tmp221 * _tmp442;
  const Scalar _tmp444 = _tmp184 * _tmp361 + _tmp196 * _tmp365;
  const Scalar _tmp445 = _tmp409 * _tmp444;
  const Scalar _tmp446 = _tmp270 * _tmp445;
  const Scalar _tmp447 = (Scalar(1) / Scalar(2)) * _tmp269;
  const Scalar _tmp448 = _tmp239 * _tmp442;
  const Scalar _tmp449 = _tmp270 * _tmp448;
  const Scalar _tmp450 = _tmp184 * _tmp413 - _tmp202 * _tmp417;
  const Scalar _tmp451 = _tmp419 * _tmp450;
  const Scalar _tmp452 = _tmp270 * _tmp451;
  const Scalar _tmp453 = (Scalar(1) / Scalar(2)) * _tmp452;
  const Scalar _tmp454 = _tmp281 * _tmp376;
  const Scalar _tmp455 = _tmp267 * _tmp376;
  const Scalar _tmp456 = _tmp376 * _tmp451;
  const Scalar _tmp457 = _tmp276 * fh1;
  const Scalar _tmp458 = _tmp251 * _tmp457;
  const Scalar _tmp459 = _tmp201 * _tmp271;
  const Scalar _tmp460 = _tmp196 * _tmp459;
  const Scalar _tmp461 = _tmp196 * _tmp274;
  const Scalar _tmp462 = Scalar(0.5) * _tmp226;
  const Scalar _tmp463 = _tmp290 * _tmp462;
  const Scalar _tmp464 = Scalar(1.0) * _tmp184;
  const Scalar _tmp465 = _tmp192 * _tmp202 * _tmp327 * _tmp462;
  const Scalar _tmp466 = _tmp201 * _tmp272;
  const Scalar _tmp467 = _tmp221 * _tmp280;
  const Scalar _tmp468 = _tmp258 * _tmp457;
  const Scalar _tmp469 = _tmp221 * _tmp444;
  const Scalar _tmp470 = _tmp245 * _tmp260;
  const Scalar _tmp471 = _tmp242 * fh1;
  const Scalar _tmp472 = _tmp469 * _tmp471;
  const Scalar _tmp473 = _tmp132 * _tmp242;
  const Scalar _tmp474 = _tmp245 * _tmp473;
  const Scalar _tmp475 = _tmp108 * _tmp241;
  const Scalar _tmp476 = _tmp245 * _tmp475;
  const Scalar _tmp477 = _tmp108 * _tmp276;
  const Scalar _tmp478 = _tmp251 * _tmp408 - _tmp251 * _tmp477 - _tmp258 * _tmp277 +
                         _tmp258 * _tmp278 - _tmp260 * _tmp474 + _tmp260 * _tmp476;
  const Scalar _tmp479 = _tmp478 * fh1;
  const Scalar _tmp480 = _tmp221 * _tmp275;
  const Scalar _tmp481 =
      _tmp240 * _tmp262 - _tmp240 * _tmp458 + _tmp267 * _tmp454 + _tmp267 * _tmp456 -
      _tmp269 * _tmp283 - _tmp269 * _tmp453 -
      _tmp410 * (_tmp238 * _tmp406 - _tmp289 * _tmp360 - _tmp299 * _tmp361 + _tmp305 * _tmp361 -
                 _tmp332 * _tmp365 + _tmp334 * _tmp365 - _tmp363 * _tmp364 + _tmp404 * _tmp407) -
      _tmp420 * (-_tmp299 * _tmp413 + _tmp305 * _tmp413 - _tmp309 * _tmp417 + _tmp332 * _tmp414 -
                 _tmp334 * _tmp414 + _tmp359 * _tmp416 - _tmp360 * _tmp412 + _tmp417 * _tmp418) -
      _tmp443 * (-_tmp235 * _tmp360 - _tmp236 * _tmp299 + _tmp236 * _tmp305 + _tmp238 * _tmp441 -
                 _tmp332 * _tmp438 + _tmp334 * _tmp438 - _tmp364 * _tmp439 + _tmp407 * _tmp437) +
      _tmp445 * _tmp455 - _tmp446 * _tmp447 - _tmp447 * _tmp449 + _tmp448 * _tmp455 -
      _tmp467 * (-_tmp273 * _tmp308 + _tmp274 * _tmp305 - _tmp298 * _tmp463 + _tmp326 * _tmp465 -
                 _tmp334 * _tmp466 + _tmp401 * _tmp460 - _tmp401 * _tmp464 + _tmp418 * _tmp461) -
      _tmp468 * _tmp469 + _tmp470 * _tmp472 - _tmp479 * _tmp480;
  const Scalar _tmp482 =
      -_tmp240 * _tmp442 - _tmp280 * _tmp480 - _tmp409 * _tmp469 - _tmp420 * _tmp450;
  const Scalar _tmp483 = std::pow(_tmp482, Scalar(-2));
  const Scalar _tmp484 = Scalar(1.0) / (_tmp482);
  const Scalar _tmp485 = _tmp171 + _tmp205;
  const Scalar _tmp486 = _tmp210 * _tmp485;
  const Scalar _tmp487 = -_tmp174 + _tmp208 - _tmp486;
  const Scalar _tmp488 = Scalar(1.0) / (_tmp487);
  const Scalar _tmp489 = Scalar(1.0) * _tmp488;
  const Scalar _tmp490 = _tmp207 * _tmp489;
  const Scalar _tmp491 = _tmp485 * _tmp490 - _tmp489;
  const Scalar _tmp492 = Scalar(3.29616) * _tmp128 + _tmp132 * fv1 + _tmp442 * _tmp73;
  const Scalar _tmp493 = Scalar(1.0) * _tmp492;
  const Scalar _tmp494 = _tmp73 * fh1;
  const Scalar _tmp495 = -Scalar(3.29616) * _tmp105 - _tmp108 * fv1 - _tmp408 * _tmp494;
  const Scalar _tmp496 = _tmp486 * _tmp489 + Scalar(1.0);
  const Scalar _tmp497 = _tmp210 * _tmp489;
  const Scalar _tmp498 = -Scalar(1.0) * _tmp390 * _tmp496 + Scalar(1.0) * _tmp497;
  const Scalar _tmp499 = _tmp485 * _tmp488;
  const Scalar _tmp500 = -_tmp203 * _tmp361 - _tmp284 + _tmp288 * _tmp499;
  const Scalar _tmp501 = _tmp288 * _tmp489 - _tmp390 * _tmp500;
  const Scalar _tmp502 = Scalar(1.0) * _tmp409;
  const Scalar _tmp503 = -_tmp203 * _tmp236 + _tmp229 + _tmp234 * _tmp499;
  const Scalar _tmp504 = _tmp234 * _tmp489 - _tmp390 * _tmp503;
  const Scalar _tmp505 = Scalar(1.0) * _tmp442;
  const Scalar _tmp506 = _tmp397 * _tmp489;
  const Scalar _tmp507 = -_tmp203 * _tmp274 + _tmp485 * _tmp506;
  const Scalar _tmp508 = -Scalar(1.0) * _tmp390 * _tmp507 + Scalar(1.0) * _tmp506;
  const Scalar _tmp509 = _tmp411 * _tmp488;
  const Scalar _tmp510 = -_tmp203 * _tmp413 + _tmp205 - _tmp485 * _tmp509;
  const Scalar _tmp511 = Scalar(1.0) * _tmp419;
  const Scalar _tmp512 = _tmp280 * _tmp508 + _tmp491 * _tmp493 + _tmp495 * _tmp498 +
                         _tmp501 * _tmp502 + _tmp504 * _tmp505 +
                         _tmp511 * (-_tmp390 * _tmp510 - _tmp411 * _tmp489 + Scalar(1.0));
  const Scalar _tmp513 = std::asinh(_tmp484 * _tmp512);
  const Scalar _tmp514 = Scalar(9.6622558468725703) * _tmp513;
  const Scalar _tmp515 = std::sqrt(_tmp167);
  const Scalar _tmp516 = -_tmp482 * _tmp514 - _tmp515;
  const Scalar _tmp517 = Scalar(0.1034955) * _tmp483 * _tmp516;
  const Scalar _tmp518 = (Scalar(1) / Scalar(2)) / _tmp515;
  const Scalar _tmp519 = Scalar(9.6622558468725703) * _tmp482;
  const Scalar _tmp520 =
      std::pow(Scalar(_tmp483 * std::pow(_tmp512, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp521 = _tmp483 * _tmp512;
  const Scalar _tmp522 = -_tmp343;
  const Scalar _tmp523 = Scalar(1.6799999999999999) * _tmp25;
  const Scalar _tmp524 = -_tmp20 * _tmp523 - _tmp319 + _tmp347;
  const Scalar _tmp525 = _tmp210 * _tmp524;
  const Scalar _tmp526 = _tmp321 * _tmp485;
  const Scalar _tmp527 = _tmp349 * _tmp485;
  const Scalar _tmp528 = _tmp347 * _tmp527;
  const Scalar _tmp529 = _tmp320 - _tmp344 + _tmp346 + _tmp522 - _tmp525 - _tmp526 + _tmp528;
  const Scalar _tmp530 = std::pow(_tmp487, Scalar(-2));
  const Scalar _tmp531 = Scalar(1.0) * _tmp530;
  const Scalar _tmp532 = _tmp529 * _tmp531;
  const Scalar _tmp533 = _tmp288 * _tmp488;
  const Scalar _tmp534 = _tmp485 * _tmp530;
  const Scalar _tmp535 = _tmp288 * _tmp534;
  const Scalar _tmp536 = _tmp203 * _tmp358;
  const Scalar _tmp537 = _tmp357 * _tmp536;
  const Scalar _tmp538 = _tmp203 * _tmp213;
  const Scalar _tmp539 = _tmp289 * _tmp537 - _tmp356 * _tmp361 - _tmp393 + _tmp394 +
                         _tmp398 * _tmp499 - _tmp402 * _tmp499 + _tmp403 * _tmp499 -
                         _tmp404 * _tmp538 + _tmp524 * _tmp533 - _tmp529 * _tmp535;
  const Scalar _tmp540 = Scalar(1.0) * _tmp348;
  const Scalar _tmp541 = _tmp347 * _tmp540;
  const Scalar _tmp542 = Scalar(1.0) * _tmp501;
  const Scalar _tmp543 = _tmp210 * _tmp532;
  const Scalar _tmp544 = _tmp395 * _tmp489;
  const Scalar _tmp545 =
      -_tmp486 * _tmp532 + _tmp489 * _tmp525 + _tmp489 * _tmp526 - _tmp489 * _tmp528;
  const Scalar _tmp546 = Scalar(1.0) * _tmp495;
  const Scalar _tmp547 = _tmp347 * _tmp348;
  const Scalar _tmp548 = _tmp485 * _tmp489;
  const Scalar _tmp549 = _tmp390 * _tmp534;
  const Scalar _tmp550 = _tmp529 * _tmp549;
  const Scalar _tmp551 = Scalar(0.5) * _tmp244;
  const Scalar _tmp552 = _tmp504 * fh1;
  const Scalar _tmp553 = Scalar(6.59232) * _tmp13;
  const Scalar _tmp554 = _tmp46 * _tmp553;
  const Scalar _tmp555 = Scalar(6.59232) * _tmp39;
  const Scalar _tmp556 = Scalar(6.59232) * _tmp25;
  const Scalar _tmp557 = _tmp245 * _tmp494;
  const Scalar _tmp558 = Scalar(6.59232) * _tmp36;
  const Scalar _tmp559 = _tmp20 * _tmp558;
  const Scalar _tmp560 = _tmp311 + _tmp315;
  const Scalar _tmp561 = _tmp276 * _tmp494;
  const Scalar _tmp562 = _tmp242 * _tmp260 * _tmp557 - _tmp258 * _tmp561 - _tmp258 * fv1 +
                         _tmp33 * _tmp556 - _tmp409 * _tmp560 - _tmp554 - _tmp555 * _tmp8 + _tmp559;
  const Scalar _tmp563 = Scalar(1.0) * _tmp504;
  const Scalar _tmp564 = _tmp411 * _tmp530;
  const Scalar _tmp565 = _tmp485 * _tmp564;
  const Scalar _tmp566 = Scalar(1.0) * _tmp210;
  const Scalar _tmp567 = _tmp204 * _tmp321 - _tmp204 * _tmp395 + _tmp264 * _tmp566 + _tmp267;
  const Scalar _tmp568 = _tmp160 - _tmp356 * _tmp413 + _tmp412 * _tmp537 - _tmp499 * _tmp567 -
                         _tmp509 * _tmp524 + _tmp529 * _tmp565;
  const Scalar _tmp569 = _tmp20 * _tmp555;
  const Scalar _tmp570 = _tmp46 * _tmp556;
  const Scalar _tmp571 = _tmp251 * _tmp561 + _tmp251 * fv1 - _tmp261 * _tmp557 + _tmp33 * _tmp553 +
                         _tmp442 * _tmp560 + _tmp558 * _tmp8 + _tmp569 + _tmp570;
  const Scalar _tmp572 = Scalar(1.0) * _tmp491;
  const Scalar _tmp573 = _tmp234 * _tmp488;
  const Scalar _tmp574 = _tmp234 * _tmp534;
  const Scalar _tmp575 = _tmp235 * _tmp537 - _tmp236 * _tmp356 + _tmp424 + _tmp433 * _tmp499 -
                         _tmp435 * _tmp499 + _tmp436 * _tmp499 - _tmp437 * _tmp538 +
                         _tmp524 * _tmp573 - _tmp529 * _tmp574;
  const Scalar _tmp576 = _tmp471 * _tmp501;
  const Scalar _tmp577 = _tmp212 * _tmp548;
  const Scalar _tmp578 = _tmp397 * _tmp532;
  const Scalar _tmp579 = Scalar(1.0) * _tmp203;
  const Scalar _tmp580 = _tmp226 * _tmp489;
  const Scalar _tmp581 = _tmp357 * _tmp580;
  const Scalar _tmp582 = -_tmp274 * _tmp356 - _tmp401 * _tmp577 + _tmp401 * _tmp579 -
                         _tmp485 * _tmp578 + _tmp485 * _tmp581 + _tmp506 * _tmp524;
  const Scalar _tmp583 = _tmp212 * _tmp489;
  const Scalar _tmp584 = _tmp401 * _tmp583;
  const Scalar _tmp585 = Scalar(1.0) * _tmp280;
  const Scalar _tmp586 =
      _tmp520 *
      (-_tmp481 * _tmp521 +
       _tmp484 *
           (-_tmp260 * _tmp551 * _tmp576 - _tmp261 * _tmp551 * _tmp552 + _tmp458 * _tmp563 +
            _tmp468 * _tmp542 + _tmp479 * _tmp508 +
            _tmp493 * (_tmp490 * _tmp524 + _tmp532 - _tmp547 * _tmp548 - _tmp550) +
            _tmp498 * _tmp562 +
            _tmp502 * (-_tmp288 * _tmp532 - _tmp390 * _tmp539 + _tmp398 * _tmp489 -
                       _tmp402 * _tmp489 + _tmp403 * _tmp489 + _tmp500 * _tmp541) +
            _tmp505 * (-_tmp234 * _tmp532 - _tmp390 * _tmp575 + _tmp433 * _tmp489 -
                       _tmp435 * _tmp489 + _tmp436 * _tmp489 + _tmp503 * _tmp541) +
            _tmp511 *
                (-_tmp390 * _tmp568 + _tmp411 * _tmp532 - _tmp489 * _tmp567 + _tmp510 * _tmp541) +
            _tmp546 *
                (_tmp321 * _tmp489 - _tmp390 * _tmp545 + _tmp496 * _tmp541 - _tmp543 - _tmp544) +
            _tmp571 * _tmp572 +
            _tmp585 * (-_tmp390 * _tmp582 + _tmp507 * _tmp541 - _tmp578 + _tmp581 - _tmp584)));
  const Scalar _tmp587 = Scalar(0.1034955) * _tmp484;
  const Scalar _tmp588 = _tmp516 * _tmp587;
  const Scalar _tmp589 = std::cosh(_tmp588);
  const Scalar _tmp590 = Scalar(1.0) * _tmp513;
  const Scalar _tmp591 = Scalar(1.0) * std::cosh(_tmp590);
  const Scalar _tmp592 = -Scalar(9.6622558468725703) * std::sinh(_tmp588) -
                         Scalar(9.6622558468725703) * std::sinh(_tmp590);
  const Scalar _tmp593 = _tmp274 * fh1;
  const Scalar _tmp594 = _tmp279 * _tmp593;
  const Scalar _tmp595 = _tmp412 * _tmp419;
  const Scalar _tmp596 = _tmp359 * _tmp595;
  const Scalar _tmp597 = _tmp413 * _tmp419;
  const Scalar _tmp598 = _tmp337 * _tmp597;
  const Scalar _tmp599 = _tmp280 * _tmp459;
  const Scalar _tmp600 = _tmp272 * _tmp280;
  const Scalar _tmp601 = _tmp365 * _tmp471;
  const Scalar _tmp602 = _tmp200 * _tmp442;
  const Scalar _tmp603 = _tmp200 * _tmp409;
  const Scalar _tmp604 = _tmp362 * _tmp409;
  const Scalar _tmp605 = _tmp237 * _tmp442;
  const Scalar _tmp606 = _tmp202 * _tmp596 - _tmp262 * _tmp438 - _tmp308 * _tmp600 -
                         _tmp309 * _tmp597 + _tmp335 * _tmp598 - _tmp364 * _tmp604 -
                         _tmp364 * _tmp605 + _tmp365 * _tmp468 + _tmp401 * _tmp599 +
                         _tmp406 * _tmp603 + _tmp418 * _tmp594 + _tmp438 * _tmp458 +
                         _tmp441 * _tmp602 - _tmp466 * _tmp479 - _tmp470 * _tmp601;
  const Scalar _tmp607 =
      -_tmp201 * _tmp600 - _tmp202 * _tmp597 + _tmp365 * _tmp409 + _tmp438 * _tmp442;
  const Scalar _tmp608 = Scalar(1.0) / (_tmp607);
  const Scalar _tmp609 = _tmp207 * _tmp419;
  const Scalar _tmp610 = _tmp207 * _tmp495;
  const Scalar _tmp611 = _tmp489 * _tmp492;
  const Scalar _tmp612 = _tmp207 * _tmp485;
  const Scalar _tmp613 = _tmp207 * _tmp409;
  const Scalar _tmp614 = _tmp207 * _tmp280;
  const Scalar _tmp615 = _tmp207 * _tmp503;
  const Scalar _tmp616 = _tmp442 * _tmp615 + _tmp496 * _tmp610 + _tmp500 * _tmp613 +
                         _tmp507 * _tmp614 + _tmp510 * _tmp609 - _tmp611 * _tmp612;
  const Scalar _tmp617 = std::asinh(_tmp608 * _tmp616);
  const Scalar _tmp618 = Scalar(9.6622558468725703) * _tmp617;
  const Scalar _tmp619 = Scalar(2.5193355532036801) - _tmp191;
  const Scalar _tmp620 = 2 * _tmp619;
  const Scalar _tmp621 = -_tmp188 + Scalar(-8.3885017487099702);
  const Scalar _tmp622 = 2 * _tmp621;
  const Scalar _tmp623 = _tmp620 * (_tmp120 + _tmp250) + _tmp622 * (_tmp257 + _tmp92);
  const Scalar _tmp624 = std::pow(_tmp619, Scalar(2)) + std::pow(_tmp621, Scalar(2));
  const Scalar _tmp625 = std::sqrt(_tmp624);
  const Scalar _tmp626 = (Scalar(1) / Scalar(2)) / _tmp625;
  const Scalar _tmp627 = Scalar(9.6622558468725703) * _tmp607;
  const Scalar _tmp628 = std::pow(_tmp607, Scalar(-2));
  const Scalar _tmp629 =
      std::pow(Scalar(std::pow(_tmp616, Scalar(2)) * _tmp628 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp630 = _tmp207 * _tmp442;
  const Scalar _tmp631 = _tmp280 * _tmp507;
  const Scalar _tmp632 = _tmp489 * _tmp571;
  const Scalar _tmp633 = _tmp207 * _tmp507;
  const Scalar _tmp634 = _tmp495 * _tmp496;
  const Scalar _tmp635 = _tmp442 * _tmp503;
  const Scalar _tmp636 = _tmp207 * _tmp500;
  const Scalar _tmp637 = _tmp409 * _tmp500;
  const Scalar _tmp638 = _tmp207 * _tmp496;
  const Scalar _tmp639 = _tmp471 * _tmp636;
  const Scalar _tmp640 = _tmp419 * _tmp510;
  const Scalar _tmp641 = _tmp348 * _tmp640;
  const Scalar _tmp642 = _tmp207 * _tmp611;
  const Scalar _tmp643 = _tmp485 * _tmp611;
  const Scalar _tmp644 = _tmp616 * _tmp628;
  const Scalar _tmp645 =
      _tmp629 *
      (-_tmp606 * _tmp644 +
       _tmp608 * (-_tmp262 * _tmp615 - _tmp347 * _tmp641 + _tmp458 * _tmp615 + _tmp468 * _tmp636 -
                  _tmp470 * _tmp639 + _tmp479 * _tmp633 + _tmp492 * _tmp550 - _tmp524 * _tmp642 +
                  _tmp539 * _tmp613 + _tmp545 * _tmp610 - _tmp547 * _tmp631 - _tmp547 * _tmp634 -
                  _tmp547 * _tmp635 - _tmp547 * _tmp637 + _tmp547 * _tmp643 + _tmp562 * _tmp638 +
                  _tmp568 * _tmp609 + _tmp575 * _tmp630 + _tmp582 * _tmp614 - _tmp612 * _tmp632));
  const Scalar _tmp646 = Scalar(0.1034955) * _tmp608;
  const Scalar _tmp647 = -_tmp607 * _tmp618 - _tmp625;
  const Scalar _tmp648 = Scalar(0.1034955) * _tmp628 * _tmp647;
  const Scalar _tmp649 = _tmp646 * _tmp647;
  const Scalar _tmp650 = std::cosh(_tmp649);
  const Scalar _tmp651 = Scalar(1.0) * _tmp617;
  const Scalar _tmp652 = Scalar(1.0) * std::cosh(_tmp651);
  const Scalar _tmp653 = _tmp28 + _tmp311;
  const Scalar _tmp654 = -_tmp186 - position_vector(2, 0) + Scalar(8.4690207536791995);
  const Scalar _tmp655 = 2 * _tmp654;
  const Scalar _tmp656 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp624 + std::pow(_tmp654, Scalar(2))));
  const Scalar _tmp657 = -Scalar(9.6622558468725703) * std::sinh(_tmp649) -
                         Scalar(9.6622558468725703) * std::sinh(_tmp651);
  const Scalar _tmp658 = -_tmp170 - position_vector(2, 0) + Scalar(8.3641088633305802);
  const Scalar _tmp659 = 2 * _tmp658;
  const Scalar _tmp660 = Scalar(4.7744369927459998) - _tmp172;
  const Scalar _tmp661 = 2 * _tmp660;
  const Scalar _tmp662 = Scalar(2.7171519410699099) - _tmp175;
  const Scalar _tmp663 = 2 * _tmp662;
  const Scalar _tmp664 = _tmp661 * (_tmp256 + _tmp98) + _tmp663 * (_tmp120 + _tmp266);
  const Scalar _tmp665 = std::pow(_tmp660, Scalar(2)) + std::pow(_tmp662, Scalar(2));
  const Scalar _tmp666 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(std::pow(_tmp658, Scalar(2)) + _tmp665));
  const Scalar _tmp667 = _tmp213 * _tmp409;
  const Scalar _tmp668 = _tmp289 * _tmp409;
  const Scalar _tmp669 = _tmp361 * _tmp471;
  const Scalar _tmp670 = _tmp213 * _tmp442;
  const Scalar _tmp671 = _tmp235 * _tmp442;
  const Scalar _tmp672 = -_tmp236 * _tmp262 + _tmp236 * _tmp458 - _tmp359 * _tmp668 -
                         _tmp359 * _tmp671 + _tmp361 * _tmp468 - _tmp401 * _tmp585 +
                         _tmp404 * _tmp667 + _tmp437 * _tmp670 - _tmp470 * _tmp669 +
                         _tmp478 * _tmp593 - _tmp596;
  const Scalar _tmp673 = _tmp236 * _tmp442 + _tmp361 * _tmp409 + _tmp594 + _tmp597;
  const Scalar _tmp674 = std::pow(_tmp673, Scalar(-2));
  const Scalar _tmp675 = std::sqrt(_tmp665);
  const Scalar _tmp676 = Scalar(1.0) / (_tmp673);
  const Scalar _tmp677 = -_tmp280 * _tmp506 - _tmp409 * _tmp533 + _tmp419 * _tmp509 -
                         _tmp442 * _tmp573 - _tmp495 * _tmp497 + _tmp611;
  const Scalar _tmp678 = std::asinh(_tmp676 * _tmp677);
  const Scalar _tmp679 = Scalar(9.6622558468725703) * _tmp678;
  const Scalar _tmp680 = -_tmp673 * _tmp679 - _tmp675;
  const Scalar _tmp681 = Scalar(0.1034955) * _tmp674 * _tmp680;
  const Scalar _tmp682 = (Scalar(1) / Scalar(2)) / _tmp675;
  const Scalar _tmp683 = Scalar(9.6622558468725703) * _tmp673;
  const Scalar _tmp684 =
      std::pow(Scalar(_tmp674 * std::pow(_tmp677, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp685 = _tmp288 * _tmp409;
  const Scalar _tmp686 = _tmp529 * _tmp530;
  const Scalar _tmp687 = _tmp234 * _tmp442;
  const Scalar _tmp688 = _tmp442 * _tmp488;
  const Scalar _tmp689 = _tmp419 * _tmp488;
  const Scalar _tmp690 = _tmp419 * _tmp564;
  const Scalar _tmp691 = _tmp409 * _tmp488;
  const Scalar _tmp692 = _tmp471 * _tmp533;
  const Scalar _tmp693 = _tmp489 * _tmp610;
  const Scalar _tmp694 = _tmp493 * _tmp530;
  const Scalar _tmp695 = _tmp674 * _tmp677;
  const Scalar _tmp696 =
      _tmp684 *
      (-_tmp672 * _tmp695 +
       _tmp676 * (_tmp262 * _tmp573 + _tmp280 * _tmp578 - _tmp280 * _tmp581 + _tmp280 * _tmp584 -
                  _tmp320 * _tmp693 - _tmp398 * _tmp691 + _tmp402 * _tmp691 - _tmp403 * _tmp691 -
                  _tmp433 * _tmp688 + _tmp435 * _tmp688 - _tmp436 * _tmp688 - _tmp458 * _tmp573 -
                  _tmp468 * _tmp533 + _tmp470 * _tmp692 - _tmp479 * _tmp506 + _tmp495 * _tmp543 +
                  _tmp495 * _tmp544 - _tmp497 * _tmp562 - _tmp529 * _tmp690 - _tmp529 * _tmp694 +
                  _tmp567 * _tmp689 + _tmp632 + _tmp685 * _tmp686 + _tmp686 * _tmp687));
  const Scalar _tmp697 = Scalar(0.1034955) * _tmp676;
  const Scalar _tmp698 = _tmp680 * _tmp697;
  const Scalar _tmp699 = std::cosh(_tmp698);
  const Scalar _tmp700 = Scalar(1.0) * _tmp678;
  const Scalar _tmp701 = Scalar(1.0) * std::cosh(_tmp700);
  const Scalar _tmp702 = -Scalar(9.6622558468725703) * std::sinh(_tmp698) -
                         Scalar(9.6622558468725703) * std::sinh(_tmp700);
  const Scalar _tmp703 = _tmp39 * _tmp47;
  const Scalar _tmp704 = -_tmp29 + _tmp30 + _tmp31 + _tmp32;
  const Scalar _tmp705 = _tmp37 * _tmp704;
  const Scalar _tmp706 = _tmp703 + _tmp705;
  const Scalar _tmp707 = _tmp20 * _tmp53;
  const Scalar _tmp708 = -_tmp1 + _tmp3 - _tmp5 - _tmp7;
  const Scalar _tmp709 = _tmp34 * _tmp708;
  const Scalar _tmp710 = _tmp707 + _tmp709;
  const Scalar _tmp711 = _tmp706 + _tmp710;
  const Scalar _tmp712 = _tmp704 * _tmp83;
  const Scalar _tmp713 = _tmp708 * _tmp89;
  const Scalar _tmp714 = _tmp116 + _tmp246 + _tmp712 - _tmp713;
  const Scalar _tmp715 = _tmp704 * _tmp93;
  const Scalar _tmp716 = _tmp708 * _tmp95;
  const Scalar _tmp717 = _tmp715 + _tmp716;
  const Scalar _tmp718 = _tmp714 + _tmp717;
  const Scalar _tmp719 = _tmp708 * _tmp85;
  const Scalar _tmp720 = _tmp117 * _tmp704;
  const Scalar _tmp721 = _tmp719 + _tmp720 + _tmp84 + _tmp90;
  const Scalar _tmp722 = -_tmp715;
  const Scalar _tmp723 = _tmp522 + _tmp722;
  const Scalar _tmp724 = -_tmp709;
  const Scalar _tmp725 = -_tmp707;
  const Scalar _tmp726 = _tmp724 + _tmp725;
  const Scalar _tmp727 = _tmp706 + _tmp726;
  const Scalar _tmp728 = _tmp723 + _tmp727;
  const Scalar _tmp729 = _tmp111 * (_tmp711 + _tmp718) + _tmp135 * (_tmp721 + _tmp728);
  const Scalar _tmp730 = _tmp34 * _tmp704;
  const Scalar _tmp731 = _tmp37 * _tmp708;
  const Scalar _tmp732 = _tmp310 - _tmp730 - _tmp731;
  const Scalar _tmp733 = _tmp40 * _tmp708;
  const Scalar _tmp734 = _tmp53 * _tmp704;
  const Scalar _tmp735 = _tmp59 + _tmp733 + _tmp734;
  const Scalar _tmp736 = _tmp14 * _tmp20;
  const Scalar _tmp737 = _tmp26 * _tmp708;
  const Scalar _tmp738 = -_tmp736 - _tmp737;
  const Scalar _tmp739 = _tmp735 + _tmp738;
  const Scalar _tmp740 = _tmp49 + _tmp730 + _tmp731;
  const Scalar _tmp741 = _tmp736 + _tmp737;
  const Scalar _tmp742 = _tmp735 + _tmp741;
  const Scalar _tmp743 = _tmp740 + _tmp742;
  const Scalar _tmp744 = -_tmp733;
  const Scalar _tmp745 = _tmp142 - _tmp734 + _tmp744;
  const Scalar _tmp746 = _tmp732 + _tmp745;
  const Scalar _tmp747 = _tmp741 + _tmp746;
  const Scalar _tmp748 = _tmp253 - _tmp719 - _tmp720 + _tmp91;
  const Scalar _tmp749 = _tmp343 + _tmp715;
  const Scalar _tmp750 = _tmp748 + _tmp749;
  const Scalar _tmp751 = _tmp727 + _tmp750;
  const Scalar _tmp752 = _tmp301 * _tmp751;
  const Scalar _tmp753 = _tmp118 + _tmp247 - _tmp712 + _tmp713;
  const Scalar _tmp754 = _tmp717 + _tmp753;
  const Scalar _tmp755 = _tmp711 + _tmp754;
  const Scalar _tmp756 = _tmp194 * _tmp755;
  const Scalar _tmp757 = _tmp728 + _tmp748;
  const Scalar _tmp758 = _tmp323 * _tmp755 + _tmp325 * _tmp757;
  const Scalar _tmp759 = _tmp329 * _tmp758;
  const Scalar _tmp760 = -_tmp703 - _tmp705;
  const Scalar _tmp761 = _tmp726 + _tmp760;
  const Scalar _tmp762 = _tmp754 + _tmp761;
  const Scalar _tmp763 = _tmp182 * _tmp762;
  const Scalar _tmp764 = _tmp331 * _tmp758;
  const Scalar _tmp765 = _tmp194 * _tmp757;
  const Scalar _tmp766 = -_tmp183 * _tmp764 + _tmp183 * _tmp765 - _tmp196 * _tmp752 +
                         _tmp196 * _tmp763 - _tmp756 + _tmp759;
  const Scalar _tmp767 = -_tmp716 + _tmp722;
  const Scalar _tmp768 = _tmp711 + _tmp767;
  const Scalar _tmp769 = _tmp753 + _tmp768;
  const Scalar _tmp770 = _tmp710 + _tmp760;
  const Scalar _tmp771 = _tmp723 + _tmp770;
  const Scalar _tmp772 = _tmp748 + _tmp771;
  const Scalar _tmp773 = _tmp293 * _tmp769 + _tmp296 * _tmp772;
  const Scalar _tmp774 = _tmp176 * _tmp773;
  const Scalar _tmp775 = _tmp291 * _tmp774;
  const Scalar _tmp776 = _tmp318 * _tmp704;
  const Scalar _tmp777 = _tmp20 * _tmp317 + _tmp776;
  const Scalar _tmp778 = _tmp207 * _tmp777;
  const Scalar _tmp779 = _tmp178 * _tmp772;
  const Scalar _tmp780 = _tmp306 * _tmp773;
  const Scalar _tmp781 = _tmp178 * _tmp769;
  const Scalar _tmp782 = -_tmp183 * _tmp775 + _tmp183 * _tmp779 - _tmp184 * _tmp752 +
                         _tmp184 * _tmp763 + _tmp780 - _tmp781;
  const Scalar _tmp783 = _tmp200 * _tmp782;
  const Scalar _tmp784 = _tmp732 + _tmp742;
  const Scalar _tmp785 = _tmp146 * _tmp765;
  const Scalar _tmp786 = -_tmp146 * _tmp764 + _tmp186 * _tmp764 - _tmp186 * _tmp765 +
                         _tmp196 * _tmp747 - _tmp196 * _tmp784 + _tmp785;
  const Scalar _tmp787 = _tmp146 * _tmp779;
  const Scalar _tmp788 = _tmp122 * _tmp708;
  const Scalar _tmp789 = _tmp345 * _tmp704 + _tmp94;
  const Scalar _tmp790 = _tmp788 + _tmp789 + _tmp96;
  const Scalar _tmp791 = _tmp183 * _tmp747;
  const Scalar _tmp792 = -_tmp183 * _tmp785 + _tmp186 * _tmp756 - _tmp186 * _tmp759 +
                         _tmp195 * _tmp784 - _tmp196 * _tmp791 + _tmp197 * _tmp752 -
                         _tmp197 * _tmp763 + _tmp228 * _tmp764;
  const Scalar _tmp793 = -_tmp170 * _tmp780 + _tmp170 * _tmp781 + _tmp179 * _tmp743 -
                         _tmp183 * _tmp787 - _tmp184 * _tmp791 + _tmp185 * _tmp752 -
                         _tmp185 * _tmp763 - _tmp198 * _tmp783 - _tmp202 * _tmp792 +
                         _tmp228 * _tmp775 + _tmp354 * _tmp766;
  const Scalar _tmp794 = -_tmp146 * _tmp775 + _tmp170 * _tmp775 - _tmp170 * _tmp779 -
                         _tmp184 * _tmp743 + _tmp184 * _tmp747 - _tmp202 * _tmp786 -
                         _tmp203 * _tmp778 - _tmp210 * _tmp793 - _tmp211 * _tmp783 +
                         _tmp338 * _tmp766 + _tmp350 * _tmp790 + _tmp787;
  const Scalar _tmp795 = _tmp358 * _tmp794;
  const Scalar _tmp796 = _tmp289 * _tmp795;
  const Scalar _tmp797 = _tmp287 * _tmp794;
  const Scalar _tmp798 = _tmp388 * _tmp766;
  const Scalar _tmp799 = _tmp198 * _tmp798;
  const Scalar _tmp800 = _tmp284 * _tmp349;
  const Scalar _tmp801 = _tmp271 * _tmp792;
  const Scalar _tmp802 = -_tmp210 * _tmp799 + _tmp210 * _tmp801 + _tmp211 * _tmp798 -
                         _tmp271 * _tmp786 + _tmp392 * _tmp777 - _tmp790 * _tmp800;
  const Scalar _tmp803 = _tmp265 * _tmp762 + _tmp268 * _tmp751;
  const Scalar _tmp804 = _tmp380 * _tmp803;
  const Scalar _tmp805 = _tmp377 * _tmp751;
  const Scalar _tmp806 = _tmp162 * _tmp217;
  const Scalar _tmp807 = _tmp180 * _tmp217;
  const Scalar _tmp808 = _tmp221 * (_tmp218 * _tmp762 - _tmp219 * _tmp762 + _tmp372 * _tmp803 -
                                    _tmp374 * _tmp803 - _tmp751 * _tmp806 + _tmp751 * _tmp807);
  const Scalar _tmp809 = -_tmp187 * _tmp764 + _tmp187 * _tmp765 - _tmp190 * _tmp756 +
                         _tmp190 * _tmp759 + _tmp192 * _tmp756 - _tmp195 * _tmp757 +
                         _tmp196 * _tmp804 - _tmp196 * _tmp805 + _tmp196 * _tmp808 -
                         _tmp222 * _tmp764 + _tmp222 * _tmp765;
  const Scalar _tmp810 = -_tmp171 * _tmp775 + _tmp174 * _tmp780 - _tmp174 * _tmp781 +
                         _tmp176 * _tmp781 - _tmp179 * _tmp772 + _tmp184 * _tmp804 -
                         _tmp184 * _tmp805 + _tmp184 * _tmp808 - _tmp202 * _tmp809 -
                         _tmp222 * _tmp775 + _tmp222 * _tmp779 + _tmp223 * _tmp772 -
                         _tmp224 * _tmp783 + _tmp383 * _tmp766;
  const Scalar _tmp811 = _tmp397 * (_tmp224 * _tmp798 - _tmp231 * _tmp802 - _tmp271 * _tmp809 -
                                    _tmp385 * _tmp810 + _tmp387 * _tmp794);
  const Scalar _tmp812 = _tmp400 * _tmp810;
  const Scalar _tmp813 = _tmp399 * _tmp812;
  const Scalar _tmp814 = _tmp797 + _tmp802 + _tmp811 - _tmp813;
  const Scalar _tmp815 = _tmp201 * _tmp796 - _tmp361 * _tmp782 - _tmp405 * _tmp814;
  const Scalar _tmp816 = _tmp336 * _tmp766;
  const Scalar _tmp817 = _tmp376 * _tmp751;
  const Scalar _tmp818 = _tmp750 + _tmp770;
  const Scalar _tmp819 = _tmp761 + _tmp767;
  const Scalar _tmp820 = _tmp753 + _tmp819;
  const Scalar _tmp821 = _tmp252 * _tmp818 + _tmp259 * _tmp820;
  const Scalar _tmp822 = _tmp245 * _tmp821;
  const Scalar _tmp823 = -_tmp277 * _tmp820 + _tmp278 * _tmp820 + _tmp408 * _tmp818 -
                         _tmp473 * _tmp822 + _tmp475 * _tmp822 - _tmp477 * _tmp818;
  const Scalar _tmp824 = _tmp823 * fh1;
  const Scalar _tmp825 = _tmp457 * _tmp820;
  const Scalar _tmp826 = _tmp241 * fh1;
  const Scalar _tmp827 = _tmp822 * _tmp826;
  const Scalar _tmp828 = _tmp337 * _tmp766;
  const Scalar _tmp829 = _tmp412 * _tmp795;
  const Scalar _tmp830 = (Scalar(1) / Scalar(2)) * _tmp803;
  const Scalar _tmp831 = _tmp233 * _tmp794;
  const Scalar _tmp832 = _tmp434 * _tmp812;
  const Scalar _tmp833 = _tmp200 * _tmp763;
  const Scalar _tmp834 = -_tmp146 * _tmp752 + _tmp146 * _tmp763 + _tmp198 * _tmp833 +
                         _tmp227 * _tmp792 - _tmp391 * _tmp752 - _tmp423 * _tmp816 + _tmp791;
  const Scalar _tmp835 = _tmp739 + _tmp740;
  const Scalar _tmp836 = -_tmp210 * _tmp834 + _tmp211 * _tmp833 + _tmp227 * _tmp786 -
                         _tmp425 * _tmp777 - _tmp426 * _tmp752 - _tmp427 * _tmp816 +
                         _tmp428 * _tmp790 + _tmp835;
  const Scalar _tmp837 = _tmp397 * (_tmp224 * _tmp833 + _tmp227 * _tmp809 - _tmp231 * _tmp836 +
                                    _tmp421 * _tmp794 - _tmp430 * _tmp752 - _tmp431 * _tmp816 -
                                    _tmp432 * _tmp810 - _tmp804 + _tmp805 - _tmp808);
  const Scalar _tmp838 = _tmp831 - _tmp832 + _tmp836 + _tmp837;
  const Scalar _tmp839 = _tmp235 * _tmp795;
  const Scalar _tmp840 =
      _tmp201 * _tmp839 - _tmp236 * _tmp782 - _tmp405 * _tmp838 + _tmp752 - _tmp763;
  const Scalar _tmp841 = _tmp457 * _tmp818;
  const Scalar _tmp842 =
      _tmp240 * _tmp827 - _tmp240 * _tmp841 + _tmp281 * _tmp817 - _tmp283 * _tmp803 -
      _tmp410 * (-_tmp184 * _tmp796 + _tmp238 * _tmp815 - _tmp361 * _tmp775 + _tmp361 * _tmp779 -
                 _tmp363 * _tmp816 - _tmp365 * _tmp764 + _tmp365 * _tmp765 + _tmp407 * _tmp814) -
      _tmp420 * (-_tmp184 * _tmp829 - _tmp413 * _tmp775 + _tmp413 * _tmp779 + _tmp414 * _tmp764 -
                 _tmp414 * _tmp765 + _tmp415 * _tmp829 - _tmp417 * _tmp783 + _tmp417 * _tmp828) -
      _tmp443 * (-_tmp184 * _tmp839 - _tmp236 * _tmp775 + _tmp236 * _tmp779 + _tmp238 * _tmp840 +
                 _tmp407 * _tmp838 - _tmp438 * _tmp764 + _tmp438 * _tmp765 - _tmp439 * _tmp816) +
      _tmp445 * _tmp817 - _tmp446 * _tmp830 + _tmp448 * _tmp817 - _tmp449 * _tmp830 +
      _tmp451 * _tmp817 - _tmp453 * _tmp803 -
      _tmp467 * (-_tmp273 * _tmp782 + _tmp274 * _tmp779 + _tmp460 * _tmp812 + _tmp461 * _tmp828 -
                 _tmp463 * _tmp774 - _tmp464 * _tmp812 + _tmp465 * _tmp758 - _tmp466 * _tmp765) -
      _tmp469 * _tmp825 + _tmp472 * _tmp822 - _tmp480 * _tmp824;
  const Scalar _tmp843 = _tmp714 + _tmp768;
  const Scalar _tmp844 = _tmp156 * (_tmp721 + _tmp771) + _tmp165 * _tmp843;
  const Scalar _tmp845 = -_tmp523 * _tmp708 - _tmp776 + _tmp790;
  const Scalar _tmp846 = _tmp210 * _tmp845;
  const Scalar _tmp847 = _tmp485 * _tmp778;
  const Scalar _tmp848 = _tmp527 * _tmp790;
  const Scalar _tmp849 = _tmp157 + _tmp777 - _tmp788 + _tmp789 - _tmp846 - _tmp847 + _tmp848;
  const Scalar _tmp850 = _tmp531 * _tmp849;
  const Scalar _tmp851 = _tmp540 * _tmp790;
  const Scalar _tmp852 = _tmp488 * _tmp845;
  const Scalar _tmp853 = _tmp203 * _tmp796 + _tmp288 * _tmp852 - _tmp361 * _tmp793 +
                         _tmp499 * _tmp797 + _tmp499 * _tmp811 - _tmp499 * _tmp813 -
                         _tmp535 * _tmp849 - _tmp538 * _tmp814 + _tmp799 - _tmp801;
  const Scalar _tmp854 = Scalar(6.59232) * _tmp704;
  const Scalar _tmp855 = _tmp740 + _tmp745;
  const Scalar _tmp856 = _tmp741 + _tmp855;
  const Scalar _tmp857 = _tmp494 * _tmp822;
  const Scalar _tmp858 = -_tmp241 * _tmp857 + _tmp25 * _tmp854 + _tmp442 * _tmp856 + _tmp554 +
                         _tmp555 * _tmp708 + _tmp559 + _tmp561 * _tmp818 + _tmp818 * fv1;
  const Scalar _tmp859 = _tmp549 * _tmp849;
  const Scalar _tmp860 = _tmp348 * _tmp790;
  const Scalar _tmp861 = _tmp204 * _tmp349;
  const Scalar _tmp862 = _tmp204 * _tmp778 + _tmp566 * _tmp762 + _tmp751 - _tmp790 * _tmp861;
  const Scalar _tmp863 = _tmp203 * _tmp829 - _tmp413 * _tmp793 - _tmp499 * _tmp862 -
                         _tmp509 * _tmp845 + _tmp565 * _tmp849 + _tmp843;
  const Scalar _tmp864 = -_tmp13 * _tmp854 + _tmp242 * _tmp857 - _tmp409 * _tmp856 +
                         _tmp558 * _tmp708 - _tmp561 * _tmp820 - _tmp569 + _tmp570 - _tmp820 * fv1;
  const Scalar _tmp865 = _tmp551 * _tmp821;
  const Scalar _tmp866 = _tmp241 * _tmp552;
  const Scalar _tmp867 = _tmp580 * _tmp794;
  const Scalar _tmp868 = _tmp397 * _tmp850;
  const Scalar _tmp869 = -_tmp274 * _tmp793 + _tmp485 * _tmp867 - _tmp485 * _tmp868 +
                         _tmp506 * _tmp845 - _tmp577 * _tmp812 + _tmp579 * _tmp812;
  const Scalar _tmp870 = _tmp583 * _tmp812;
  const Scalar _tmp871 =
      -_tmp486 * _tmp850 + _tmp489 * _tmp846 + _tmp489 * _tmp847 - _tmp489 * _tmp848;
  const Scalar _tmp872 = _tmp349 * _tmp489;
  const Scalar _tmp873 = _tmp790 * _tmp872;
  const Scalar _tmp874 = _tmp210 * _tmp850;
  const Scalar _tmp875 = _tmp203 * _tmp839 + _tmp234 * _tmp852 - _tmp236 * _tmp793 +
                         _tmp499 * _tmp831 - _tmp499 * _tmp832 + _tmp499 * _tmp837 -
                         _tmp538 * _tmp838 - _tmp574 * _tmp849 + _tmp834;
  const Scalar _tmp876 =
      _tmp520 *
      (_tmp484 * (_tmp493 * (_tmp490 * _tmp845 - _tmp548 * _tmp860 + _tmp850 - _tmp859) +
                  _tmp498 * _tmp864 +
                  _tmp502 * (-_tmp288 * _tmp850 - _tmp390 * _tmp853 + _tmp489 * _tmp797 +
                             _tmp489 * _tmp811 - _tmp489 * _tmp813 + _tmp500 * _tmp851) +
                  _tmp505 * (-_tmp234 * _tmp850 - _tmp390 * _tmp875 + _tmp489 * _tmp831 -
                             _tmp489 * _tmp832 + _tmp489 * _tmp837 + _tmp503 * _tmp851) +
                  _tmp508 * _tmp824 +
                  _tmp511 * (-_tmp390 * _tmp863 + _tmp411 * _tmp850 - _tmp489 * _tmp862 +
                             _tmp510 * _tmp851) +
                  _tmp542 * _tmp825 +
                  _tmp546 * (-_tmp390 * _tmp871 + _tmp489 * _tmp778 + _tmp496 * _tmp851 - _tmp873 -
                             _tmp874) +
                  _tmp563 * _tmp841 + _tmp572 * _tmp858 - _tmp576 * _tmp865 +
                  _tmp585 * (-_tmp390 * _tmp869 + _tmp507 * _tmp851 + _tmp867 - _tmp868 - _tmp870) -
                  _tmp865 * _tmp866) -
       _tmp521 * _tmp842);
  const Scalar _tmp877 = _tmp419 * _tmp829;
  const Scalar _tmp878 = _tmp202 * _tmp877 + _tmp365 * _tmp825 - _tmp438 * _tmp827 +
                         _tmp438 * _tmp841 - _tmp466 * _tmp824 + _tmp594 * _tmp828 -
                         _tmp597 * _tmp783 + _tmp598 * _tmp766 + _tmp599 * _tmp812 -
                         _tmp600 * _tmp782 - _tmp601 * _tmp822 + _tmp602 * _tmp840 +
                         _tmp603 * _tmp815 - _tmp604 * _tmp816 - _tmp605 * _tmp816;
  const Scalar _tmp879 = _tmp721 + _tmp749;
  const Scalar _tmp880 = _tmp620 * (_tmp770 + _tmp879) + _tmp622 * (_tmp714 + _tmp819);
  const Scalar _tmp881 = _tmp615 * _tmp826;
  const Scalar _tmp882 = _tmp489 * _tmp858;
  const Scalar _tmp883 =
      _tmp629 *
      (_tmp608 * (_tmp492 * _tmp859 + _tmp609 * _tmp863 + _tmp610 * _tmp871 - _tmp612 * _tmp882 +
                  _tmp613 * _tmp853 + _tmp614 * _tmp869 + _tmp615 * _tmp841 + _tmp630 * _tmp875 -
                  _tmp631 * _tmp860 + _tmp633 * _tmp824 - _tmp634 * _tmp860 - _tmp635 * _tmp860 +
                  _tmp636 * _tmp825 - _tmp637 * _tmp860 + _tmp638 * _tmp864 - _tmp639 * _tmp822 -
                  _tmp640 * _tmp860 - _tmp642 * _tmp845 + _tmp643 * _tmp860 - _tmp822 * _tmp881) -
       _tmp644 * _tmp878);
  const Scalar _tmp884 = -_tmp236 * _tmp827 + _tmp236 * _tmp841 + _tmp361 * _tmp825 -
                         _tmp409 * _tmp796 - _tmp442 * _tmp839 - _tmp585 * _tmp812 +
                         _tmp593 * _tmp823 + _tmp667 * _tmp814 - _tmp669 * _tmp822 +
                         _tmp670 * _tmp838 - _tmp877;
  const Scalar _tmp885 = _tmp661 * (_tmp718 + _tmp761) + _tmp663 * (_tmp727 + _tmp879);
  const Scalar _tmp886 = _tmp530 * _tmp849;
  const Scalar _tmp887 =
      _tmp684 *
      (_tmp676 * (-_tmp280 * _tmp867 + _tmp280 * _tmp868 + _tmp280 * _tmp870 + _tmp495 * _tmp873 +
                  _tmp495 * _tmp874 - _tmp497 * _tmp864 - _tmp506 * _tmp824 - _tmp533 * _tmp825 +
                  _tmp573 * _tmp827 - _tmp573 * _tmp841 + _tmp685 * _tmp886 + _tmp687 * _tmp886 -
                  _tmp688 * _tmp831 + _tmp688 * _tmp832 - _tmp688 * _tmp837 + _tmp689 * _tmp862 -
                  _tmp690 * _tmp849 - _tmp691 * _tmp797 - _tmp691 * _tmp811 + _tmp691 * _tmp813 +
                  _tmp692 * _tmp822 - _tmp693 * _tmp777 - _tmp694 * _tmp849 + _tmp882) -
       _tmp695 * _tmp884);
  const Scalar _tmp888 = _tmp53 * _tmp708;
  const Scalar _tmp889 = _tmp42 + _tmp43 - _tmp44 + _tmp45;
  const Scalar _tmp890 = _tmp37 * _tmp889;
  const Scalar _tmp891 = _tmp255 - _tmp888 - _tmp890;
  const Scalar _tmp892 = _tmp40 * _tmp889;
  const Scalar _tmp893 = _tmp33 * _tmp37;
  const Scalar _tmp894 = _tmp707 + _tmp724 + _tmp892 - _tmp893;
  const Scalar _tmp895 = _tmp14 * _tmp33;
  const Scalar _tmp896 = _tmp26 * _tmp889;
  const Scalar _tmp897 = -_tmp895 - _tmp896;
  const Scalar _tmp898 = _tmp708 * _tmp83;
  const Scalar _tmp899 = _tmp85 * _tmp889;
  const Scalar _tmp900 = _tmp117 * _tmp20;
  const Scalar _tmp901 = _tmp33 * _tmp89;
  const Scalar _tmp902 = _tmp898 + _tmp899 + _tmp900 + _tmp901;
  const Scalar _tmp903 = _tmp20 * _tmp93;
  const Scalar _tmp904 = -_tmp903;
  const Scalar _tmp905 = _tmp122 * _tmp33;
  const Scalar _tmp906 = _tmp904 - _tmp905;
  const Scalar _tmp907 = _tmp34 * _tmp889;
  const Scalar _tmp908 = _tmp55 - _tmp907;
  const Scalar _tmp909 = _tmp57 + _tmp733;
  const Scalar _tmp910 = _tmp908 + _tmp909;
  const Scalar _tmp911 = _tmp906 + _tmp910;
  const Scalar _tmp912 = _tmp20 * _tmp83;
  const Scalar _tmp913 = _tmp39 * _tmp87;
  const Scalar _tmp914 = _tmp117 * _tmp708;
  const Scalar _tmp915 = _tmp889 * _tmp89;
  const Scalar _tmp916 = _tmp912 + _tmp913 - _tmp914 - _tmp915;
  const Scalar _tmp917 = _tmp889 * _tmp95;
  const Scalar _tmp918 = _tmp903 + _tmp917;
  const Scalar _tmp919 = _tmp916 + _tmp918;
  const Scalar _tmp920 = _tmp54 + _tmp907;
  const Scalar _tmp921 = _tmp909 + _tmp920;
  const Scalar _tmp922 = _tmp111 * (_tmp919 + _tmp921) + _tmp135 * (_tmp902 + _tmp911);
  const Scalar _tmp923 = -_tmp898 - _tmp899 - _tmp900 - _tmp901;
  const Scalar _tmp924 = _tmp903 + _tmp905;
  const Scalar _tmp925 = _tmp910 + _tmp924;
  const Scalar _tmp926 = _tmp923 + _tmp925;
  const Scalar _tmp927 = _tmp904 - _tmp917;
  const Scalar _tmp928 = -_tmp912 - _tmp913 + _tmp914 + _tmp915;
  const Scalar _tmp929 = _tmp921 + _tmp928;
  const Scalar _tmp930 = _tmp927 + _tmp929;
  const Scalar _tmp931 = _tmp58 + _tmp744;
  const Scalar _tmp932 = _tmp920 + _tmp931;
  const Scalar _tmp933 = _tmp906 + _tmp932;
  const Scalar _tmp934 = _tmp923 + _tmp933;
  const Scalar _tmp935 = _tmp293 * _tmp930 + _tmp296 * _tmp934;
  const Scalar _tmp936 = _tmp176 * _tmp935;
  const Scalar _tmp937 = _tmp291 * _tmp936;
  const Scalar _tmp938 = _tmp911 + _tmp923;
  const Scalar _tmp939 = _tmp194 * _tmp938;
  const Scalar _tmp940 = _tmp178 * _tmp934;
  const Scalar _tmp941 = _tmp301 * _tmp926;
  const Scalar _tmp942 = _tmp918 + _tmp929;
  const Scalar _tmp943 = _tmp194 * _tmp942;
  const Scalar _tmp944 = _tmp908 + _tmp931;
  const Scalar _tmp945 = _tmp918 + _tmp928 + _tmp944;
  const Scalar _tmp946 = _tmp182 * _tmp945;
  const Scalar _tmp947 = _tmp323 * _tmp942 + _tmp325 * _tmp938;
  const Scalar _tmp948 = _tmp331 * _tmp947;
  const Scalar _tmp949 = _tmp329 * _tmp947;
  const Scalar _tmp950 = _tmp183 * _tmp939 - _tmp183 * _tmp948 - _tmp196 * _tmp941 +
                         _tmp196 * _tmp946 - _tmp943 + _tmp949;
  const Scalar _tmp951 = _tmp337 * _tmp950;
  const Scalar _tmp952 = _tmp377 * _tmp926;
  const Scalar _tmp953 = _tmp306 * _tmp935;
  const Scalar _tmp954 =
      (Scalar(1) / Scalar(2)) * _tmp265 * _tmp945 + (Scalar(1) / Scalar(2)) * _tmp268 * _tmp926;
  const Scalar _tmp955 = _tmp370 * _tmp954;
  const Scalar _tmp956 = _tmp221 * (_tmp218 * _tmp945 - _tmp219 * _tmp945 + _tmp369 * _tmp955 -
                                    _tmp373 * _tmp955 - _tmp806 * _tmp926 + _tmp807 * _tmp926);
  const Scalar _tmp957 = _tmp379 * _tmp954;
  const Scalar _tmp958 = _tmp187 * _tmp939 - _tmp187 * _tmp948 - _tmp190 * _tmp943 +
                         _tmp190 * _tmp949 + _tmp192 * _tmp943 - _tmp195 * _tmp938 -
                         _tmp196 * _tmp952 + _tmp196 * _tmp956 + _tmp196 * _tmp957 +
                         _tmp222 * _tmp939 - _tmp222 * _tmp948;
  const Scalar _tmp959 = _tmp178 * _tmp930;
  const Scalar _tmp960 = -_tmp183 * _tmp937 + _tmp183 * _tmp940 - _tmp184 * _tmp941 +
                         _tmp184 * _tmp946 + _tmp953 - _tmp959;
  const Scalar _tmp961 = _tmp200 * _tmp960;
  const Scalar _tmp962 = -_tmp171 * _tmp937 + _tmp174 * _tmp953 - _tmp174 * _tmp959 +
                         _tmp176 * _tmp959 - _tmp179 * _tmp934 - _tmp184 * _tmp952 +
                         _tmp184 * _tmp956 + _tmp184 * _tmp957 - _tmp202 * _tmp958 -
                         _tmp222 * _tmp937 + _tmp222 * _tmp940 + _tmp223 * _tmp934 +
                         _tmp224 * _tmp951 - _tmp224 * _tmp961;
  const Scalar _tmp963 = _tmp400 * _tmp962;
  const Scalar _tmp964 = _tmp399 * _tmp963;
  const Scalar _tmp965 = _tmp20 * _tmp318;
  const Scalar _tmp966 = _tmp317 * _tmp33 + _tmp965;
  const Scalar _tmp967 = _tmp207 * _tmp966;
  const Scalar _tmp968 = _tmp122 * _tmp889;
  const Scalar _tmp969 = _tmp33 * _tmp95;
  const Scalar _tmp970 = _tmp20 * _tmp345 + _tmp708 * _tmp93;
  const Scalar _tmp971 = _tmp968 + _tmp969 + _tmp970;
  const Scalar _tmp972 = _tmp895 + _tmp896;
  const Scalar _tmp973 = _tmp76 + _tmp79 + _tmp888 + _tmp890;
  const Scalar _tmp974 = _tmp894 + _tmp973;
  const Scalar _tmp975 = _tmp972 + _tmp974;
  const Scalar _tmp976 = _tmp891 + _tmp972;
  const Scalar _tmp977 = _tmp709 + _tmp725 - _tmp892 + _tmp893;
  const Scalar _tmp978 = _tmp976 + _tmp977;
  const Scalar _tmp979 = _tmp184 * _tmp978;
  const Scalar _tmp980 = _tmp894 + _tmp976;
  const Scalar _tmp981 = _tmp183 * _tmp978;
  const Scalar _tmp982 = _tmp186 * _tmp943 - _tmp186 * _tmp949 + _tmp195 * _tmp980 -
                         _tmp196 * _tmp981 + _tmp197 * _tmp941 - _tmp197 * _tmp946 -
                         _tmp228 * _tmp939 + _tmp228 * _tmp948;
  const Scalar _tmp983 = -_tmp170 * _tmp953 + _tmp170 * _tmp959 + _tmp179 * _tmp975 -
                         _tmp183 * _tmp979 + _tmp185 * _tmp941 - _tmp185 * _tmp946 +
                         _tmp198 * _tmp951 - _tmp198 * _tmp961 - _tmp202 * _tmp982 +
                         _tmp228 * _tmp937 - _tmp228 * _tmp940;
  const Scalar _tmp984 = _tmp146 * _tmp939 - _tmp186 * _tmp939 + _tmp186 * _tmp948 +
                         _tmp196 * _tmp978 - _tmp196 * _tmp980 - _tmp339 * _tmp947;
  const Scalar _tmp985 = -_tmp146 * _tmp937 + _tmp146 * _tmp940 + _tmp170 * _tmp937 -
                         _tmp170 * _tmp940 - _tmp184 * _tmp975 - _tmp202 * _tmp984 -
                         _tmp203 * _tmp967 - _tmp210 * _tmp983 + _tmp211 * _tmp951 -
                         _tmp211 * _tmp961 + _tmp350 * _tmp971 + _tmp979;
  const Scalar _tmp986 = _tmp287 * _tmp985;
  const Scalar _tmp987 = _tmp388 * _tmp950;
  const Scalar _tmp988 = _tmp271 * _tmp982;
  const Scalar _tmp989 = _tmp198 * _tmp987;
  const Scalar _tmp990 = _tmp210 * _tmp988 - _tmp210 * _tmp989 + _tmp211 * _tmp987 -
                         _tmp271 * _tmp984 + _tmp392 * _tmp966 - _tmp800 * _tmp971;
  const Scalar _tmp991 = _tmp397 * (_tmp224 * _tmp987 - _tmp231 * _tmp990 - _tmp271 * _tmp958 -
                                    _tmp385 * _tmp962 + _tmp387 * _tmp985);
  const Scalar _tmp992 = -_tmp964 + _tmp986 + _tmp990 + _tmp991;
  const Scalar _tmp993 = _tmp358 * _tmp985;
  const Scalar _tmp994 = _tmp184 * _tmp993;
  const Scalar _tmp995 = -_tmp361 * _tmp960 + _tmp367 * _tmp985 - _tmp405 * _tmp992;
  const Scalar _tmp996 = _tmp336 * _tmp950;
  const Scalar _tmp997 = _tmp924 + _tmp932;
  const Scalar _tmp998 = _tmp923 + _tmp997;
  const Scalar _tmp999 = _tmp276 * _tmp998;
  const Scalar _tmp1000 = _tmp999 * fh1;
  const Scalar _tmp1001 = _tmp200 * _tmp946;
  const Scalar _tmp1002 = _tmp1001 * _tmp198 - _tmp146 * _tmp941 + _tmp146 * _tmp946 +
                          _tmp227 * _tmp982 - _tmp391 * _tmp941 - _tmp423 * _tmp996 + _tmp981;
  const Scalar _tmp1003 = _tmp897 + _tmp974;
  const Scalar _tmp1004 = _tmp1001 * _tmp211 - _tmp1002 * _tmp210 + _tmp1003 + _tmp227 * _tmp984 -
                          _tmp425 * _tmp966 - _tmp426 * _tmp941 - _tmp427 * _tmp996 +
                          _tmp428 * _tmp971;
  const Scalar _tmp1005 = _tmp397 * (_tmp1001 * _tmp224 - _tmp1004 * _tmp231 + _tmp227 * _tmp958 +
                                     _tmp421 * _tmp985 - _tmp430 * _tmp941 - _tmp431 * _tmp996 -
                                     _tmp432 * _tmp962 + _tmp952 - _tmp956 - _tmp957);
  const Scalar _tmp1006 = _tmp434 * _tmp963;
  const Scalar _tmp1007 = _tmp233 * _tmp985;
  const Scalar _tmp1008 = _tmp1004 + _tmp1005 - _tmp1006 + _tmp1007;
  const Scalar _tmp1009 =
      -_tmp1008 * _tmp405 - _tmp236 * _tmp960 + _tmp440 * _tmp985 + _tmp941 - _tmp946;
  const Scalar _tmp1010 = _tmp927 + _tmp944;
  const Scalar _tmp1011 = _tmp1010 + _tmp928;
  const Scalar _tmp1012 = _tmp1011 * _tmp259 + _tmp252 * _tmp998;
  const Scalar _tmp1013 = -_tmp1011 * _tmp277 + _tmp1011 * _tmp278 - _tmp1012 * _tmp474 +
                          _tmp1012 * _tmp476 - _tmp108 * _tmp999 + _tmp242 * _tmp999;
  const Scalar _tmp1014 = _tmp1013 * fh1;
  const Scalar _tmp1015 = _tmp376 * _tmp926;
  const Scalar _tmp1016 = _tmp1011 * _tmp457;
  const Scalar _tmp1017 = _tmp1012 * _tmp245;
  const Scalar _tmp1018 = _tmp1017 * _tmp826;
  const Scalar _tmp1019 =
      -_tmp1000 * _tmp240 - _tmp1014 * _tmp480 + _tmp1015 * _tmp445 + _tmp1015 * _tmp448 -
      _tmp1016 * _tmp469 + _tmp1017 * _tmp472 + _tmp1018 * _tmp240 - _tmp282 * _tmp954 -
      _tmp410 * (_tmp238 * _tmp995 - _tmp289 * _tmp994 - _tmp361 * _tmp937 + _tmp361 * _tmp940 -
                 _tmp363 * _tmp996 + _tmp365 * _tmp939 - _tmp365 * _tmp948 + _tmp407 * _tmp992) -
      _tmp420 * (-_tmp412 * _tmp994 - _tmp413 * _tmp937 + _tmp413 * _tmp940 - _tmp414 * _tmp939 +
                 _tmp414 * _tmp948 + _tmp416 * _tmp993 + _tmp417 * _tmp951 - _tmp417 * _tmp961) -
      _tmp443 * (_tmp1008 * _tmp407 + _tmp1009 * _tmp238 - _tmp235 * _tmp994 - _tmp236 * _tmp937 +
                 _tmp236 * _tmp940 + _tmp438 * _tmp939 - _tmp438 * _tmp948 - _tmp439 * _tmp996) -
      _tmp446 * _tmp954 - _tmp449 * _tmp954 - _tmp452 * _tmp954 + _tmp454 * _tmp926 +
      _tmp456 * _tmp926 -
      _tmp467 * (-_tmp273 * _tmp960 + _tmp274 * _tmp940 + _tmp460 * _tmp963 + _tmp461 * _tmp951 -
                 _tmp463 * _tmp936 - _tmp464 * _tmp963 + _tmp465 * _tmp947 - _tmp466 * _tmp939);
  const Scalar _tmp1020 = _tmp916 + _tmp921 + _tmp927;
  const Scalar _tmp1021 = _tmp1020 * _tmp165 + _tmp156 * (_tmp902 + _tmp933);
  const Scalar _tmp1022 = _tmp1012 * _tmp557;
  const Scalar _tmp1023 = _tmp972 + _tmp973 + _tmp977;
  const Scalar _tmp1024 = -_tmp1011 * _tmp561 - _tmp1011 * fv1 + _tmp1022 * _tmp242 -
                          _tmp1023 * _tmp409 - _tmp20 * _tmp553 - _tmp33 * _tmp555 +
                          _tmp556 * _tmp708 + _tmp558 * _tmp889;
  const Scalar _tmp1025 = _tmp540 * _tmp971;
  const Scalar _tmp1026 = -_tmp523 * _tmp889 - _tmp965 + _tmp971;
  const Scalar _tmp1027 = _tmp1026 * _tmp210;
  const Scalar _tmp1028 = _tmp485 * _tmp967;
  const Scalar _tmp1029 = _tmp527 * _tmp971;
  const Scalar _tmp1030 = -_tmp1027 - _tmp1028 + _tmp1029 + _tmp966 - _tmp968 - _tmp969 + _tmp970;
  const Scalar _tmp1031 = _tmp1030 * _tmp531;
  const Scalar _tmp1032 = _tmp1031 * _tmp210;
  const Scalar _tmp1033 =
      _tmp1027 * _tmp489 + _tmp1028 * _tmp489 - _tmp1029 * _tmp489 - _tmp1031 * _tmp486;
  const Scalar _tmp1034 = _tmp872 * _tmp971;
  const Scalar _tmp1035 = _tmp204 * _tmp967 + _tmp566 * _tmp945 - _tmp861 * _tmp971 + _tmp926;
  const Scalar _tmp1036 = _tmp536 * _tmp985;
  const Scalar _tmp1037 = _tmp1020 - _tmp1026 * _tmp509 + _tmp1030 * _tmp565 - _tmp1035 * _tmp499 +
                          _tmp1036 * _tmp412 - _tmp413 * _tmp983;
  const Scalar _tmp1038 = _tmp1002 + _tmp1005 * _tmp499 - _tmp1006 * _tmp499 + _tmp1007 * _tmp499 -
                          _tmp1008 * _tmp538 + _tmp1026 * _tmp573 - _tmp1030 * _tmp574 +
                          _tmp1036 * _tmp235 - _tmp236 * _tmp983;
  const Scalar _tmp1039 = _tmp580 * _tmp985;
  const Scalar _tmp1040 = _tmp583 * _tmp963;
  const Scalar _tmp1041 = _tmp1031 * _tmp397;
  const Scalar _tmp1042 = _tmp1026 * _tmp506 + _tmp1039 * _tmp485 - _tmp1041 * _tmp485 -
                          _tmp274 * _tmp983 - _tmp577 * _tmp963 + _tmp579 * _tmp963;
  const Scalar _tmp1043 = _tmp1012 * _tmp551;
  const Scalar _tmp1044 = -_tmp1022 * _tmp241 + _tmp1023 * _tmp442 + _tmp20 * _tmp556 +
                          _tmp33 * _tmp558 + _tmp494 * _tmp999 + _tmp553 * _tmp708 +
                          _tmp555 * _tmp889 + _tmp998 * fv1;
  const Scalar _tmp1045 = _tmp1026 * _tmp533 - _tmp1030 * _tmp535 + _tmp1036 * _tmp289 -
                          _tmp361 * _tmp983 - _tmp499 * _tmp964 + _tmp499 * _tmp986 +
                          _tmp499 * _tmp991 - _tmp538 * _tmp992 - _tmp988 + _tmp989;
  const Scalar _tmp1046 = _tmp1030 * _tmp549;
  const Scalar _tmp1047 = _tmp348 * _tmp971;
  const Scalar _tmp1048 =
      _tmp520 *
      (-_tmp1019 * _tmp521 +
       _tmp484 *
           (_tmp1000 * _tmp563 + _tmp1014 * _tmp508 + _tmp1016 * _tmp542 + _tmp1024 * _tmp498 -
            _tmp1043 * _tmp576 - _tmp1043 * _tmp866 + _tmp1044 * _tmp572 +
            _tmp493 * (_tmp1026 * _tmp490 + _tmp1031 - _tmp1046 - _tmp1047 * _tmp548) +
            _tmp502 * (_tmp1025 * _tmp500 - _tmp1031 * _tmp288 - _tmp1045 * _tmp390 -
                       _tmp489 * _tmp964 + _tmp489 * _tmp986 + _tmp489 * _tmp991) +
            _tmp505 * (_tmp1005 * _tmp489 - _tmp1006 * _tmp489 + _tmp1007 * _tmp489 +
                       _tmp1025 * _tmp503 - _tmp1031 * _tmp234 - _tmp1038 * _tmp390) +
            _tmp511 * (_tmp1025 * _tmp510 + _tmp1031 * _tmp411 - _tmp1035 * _tmp489 -
                       _tmp1037 * _tmp390) +
            _tmp546 * (_tmp1025 * _tmp496 - _tmp1032 - _tmp1033 * _tmp390 - _tmp1034 +
                       _tmp489 * _tmp967) +
            _tmp585 * (_tmp1025 * _tmp507 + _tmp1039 - _tmp1040 - _tmp1041 - _tmp1042 * _tmp390)));
  const Scalar _tmp1049 = _tmp595 * _tmp993;
  const Scalar _tmp1050 = _tmp1000 * _tmp438 + _tmp1009 * _tmp602 - _tmp1014 * _tmp466 +
                          _tmp1016 * _tmp365 - _tmp1017 * _tmp601 - _tmp1018 * _tmp438 +
                          _tmp1049 * _tmp202 + _tmp594 * _tmp951 + _tmp597 * _tmp951 -
                          _tmp597 * _tmp961 + _tmp599 * _tmp963 - _tmp600 * _tmp960 +
                          _tmp603 * _tmp995 - _tmp604 * _tmp996 - _tmp605 * _tmp996;
  const Scalar _tmp1051 = _tmp897 + _tmp977;
  const Scalar _tmp1052 = _tmp620 * (_tmp902 + _tmp997) + _tmp622 * (_tmp1010 + _tmp916);
  const Scalar _tmp1053 = _tmp1044 * _tmp489;
  const Scalar _tmp1054 =
      _tmp629 *
      (-_tmp1050 * _tmp644 +
       _tmp608 *
           (_tmp1000 * _tmp615 + _tmp1014 * _tmp633 + _tmp1016 * _tmp636 - _tmp1017 * _tmp639 -
            _tmp1017 * _tmp881 + _tmp1024 * _tmp638 - _tmp1026 * _tmp642 + _tmp1033 * _tmp610 +
            _tmp1037 * _tmp609 + _tmp1038 * _tmp630 + _tmp1042 * _tmp614 + _tmp1045 * _tmp613 +
            _tmp1046 * _tmp492 - _tmp1047 * _tmp631 - _tmp1047 * _tmp634 - _tmp1047 * _tmp635 -
            _tmp1047 * _tmp637 + _tmp1047 * _tmp643 - _tmp1053 * _tmp612 - _tmp641 * _tmp971));
  const Scalar _tmp1055 = _tmp1030 * _tmp530;
  const Scalar _tmp1056 = _tmp1000 * _tmp236 + _tmp1008 * _tmp670 + _tmp1013 * _tmp593 +
                          _tmp1016 * _tmp361 - _tmp1017 * _tmp669 - _tmp1018 * _tmp236 - _tmp1049 -
                          _tmp585 * _tmp963 + _tmp667 * _tmp992 - _tmp668 * _tmp993 -
                          _tmp671 * _tmp993;
  const Scalar _tmp1057 =
      _tmp684 *
      (-_tmp1056 * _tmp695 +
       _tmp676 *
           (-_tmp1000 * _tmp573 - _tmp1005 * _tmp688 + _tmp1006 * _tmp688 - _tmp1007 * _tmp688 -
            _tmp1014 * _tmp506 - _tmp1016 * _tmp533 + _tmp1017 * _tmp692 + _tmp1018 * _tmp573 -
            _tmp1024 * _tmp497 - _tmp1030 * _tmp690 - _tmp1030 * _tmp694 + _tmp1032 * _tmp495 +
            _tmp1034 * _tmp495 + _tmp1035 * _tmp689 - _tmp1039 * _tmp280 + _tmp1040 * _tmp280 +
            _tmp1041 * _tmp280 + _tmp1053 + _tmp1055 * _tmp685 + _tmp1055 * _tmp687 +
            _tmp691 * _tmp964 - _tmp691 * _tmp986 - _tmp691 * _tmp991 - _tmp693 * _tmp966));
  const Scalar _tmp1058 = _tmp661 * (_tmp919 + _tmp944) + _tmp663 * (_tmp902 + _tmp925);

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = _tmp136 * _tmp141 - _tmp138 * (_tmp136 + _tmp75 * (_tmp51 + _tmp60));
  _res(1, 0) =
      -_tmp168 * (_tmp144 * _tmp148 + _tmp166) + _tmp481 * _tmp592 +
      _tmp519 * (-_tmp586 * _tmp591 -
                 _tmp589 * (-_tmp481 * _tmp517 + _tmp587 * (-_tmp166 * _tmp518 - _tmp481 * _tmp514 -
                                                            _tmp519 * _tmp586)));
  _res(2, 0) =
      _tmp606 * _tmp657 +
      _tmp627 * (-_tmp645 * _tmp652 -
                 _tmp650 * (-_tmp606 * _tmp648 + _tmp646 * (-_tmp606 * _tmp618 - _tmp623 * _tmp626 -
                                                            _tmp627 * _tmp645))) -
      _tmp656 * (_tmp623 + _tmp655 * (_tmp143 + _tmp653));
  _res(3, 0) =
      -_tmp666 * (_tmp659 * (_tmp60 + _tmp653) + _tmp664) + _tmp672 * _tmp702 +
      _tmp683 * (-_tmp696 * _tmp701 -
                 _tmp699 * (-_tmp672 * _tmp681 + _tmp697 * (-_tmp664 * _tmp682 - _tmp672 * _tmp679 -
                                                            _tmp683 * _tmp696)));
  _res(0, 1) = -_tmp138 * (_tmp729 + _tmp75 * (_tmp732 + _tmp739)) + _tmp141 * _tmp729;
  _res(1, 1) =
      -_tmp168 * (_tmp148 * _tmp835 + _tmp844) +
      _tmp519 *
          (-_tmp589 * (-_tmp517 * _tmp842 +
                       _tmp587 * (-_tmp514 * _tmp842 - _tmp518 * _tmp844 - _tmp519 * _tmp876)) -
           _tmp591 * _tmp876) +
      _tmp592 * _tmp842;
  _res(2, 1) =
      _tmp627 *
          (-_tmp650 * (_tmp646 * (-_tmp618 * _tmp878 - _tmp626 * _tmp880 - _tmp627 * _tmp883) -
                       _tmp648 * _tmp878) -
           _tmp652 * _tmp883) -
      _tmp656 * (_tmp655 * (_tmp738 + _tmp855) + _tmp880) + _tmp657 * _tmp878;
  _res(3, 1) =
      -_tmp666 * (_tmp659 * (_tmp738 + _tmp746) + _tmp885) +
      _tmp683 *
          (-_tmp699 * (-_tmp681 * _tmp884 +
                       _tmp697 * (-_tmp679 * _tmp884 - _tmp682 * _tmp885 - _tmp683 * _tmp887)) -
           _tmp701 * _tmp887) +
      _tmp702 * _tmp884;
  _res(0, 2) = -_tmp138 * (_tmp75 * (_tmp891 + _tmp894 + _tmp897) + _tmp922) + _tmp141 * _tmp922;
  _res(1, 2) =
      _tmp1019 * _tmp592 - _tmp168 * (_tmp1003 * _tmp148 + _tmp1021) +
      _tmp519 *
          (-_tmp1048 * _tmp591 -
           _tmp589 * (-_tmp1019 * _tmp517 +
                      _tmp587 * (-_tmp1019 * _tmp514 - _tmp1021 * _tmp518 - _tmp1048 * _tmp519)));
  _res(2, 2) =
      _tmp1050 * _tmp657 +
      _tmp627 *
          (-_tmp1054 * _tmp652 -
           _tmp650 * (-_tmp1050 * _tmp648 +
                      _tmp646 * (-_tmp1050 * _tmp618 - _tmp1052 * _tmp626 - _tmp1054 * _tmp627))) -
      _tmp656 * (_tmp1052 + _tmp655 * (_tmp1051 + _tmp973));
  _res(3, 2) =
      _tmp1056 * _tmp702 - _tmp666 * (_tmp1058 + _tmp659 * (_tmp1051 + _tmp891)) +
      _tmp683 *
          (-_tmp1057 * _tmp701 -
           _tmp699 * (-_tmp1056 * _tmp681 +
                      _tmp697 * (-_tmp1056 * _tmp679 - _tmp1057 * _tmp683 - _tmp1058 * _tmp682)));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
