// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost1_wrt_DeltaRot_Nl22
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost1WrtDeltarotNl22(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 3473

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (1014)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp1 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp2 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp5 = (Scalar(1) / Scalar(2)) * _tmp4;
  const Scalar _tmp6 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp7 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp8 = -_tmp1 - _tmp3 + _tmp5 - _tmp7;
  const Scalar _tmp9 = _tmp0 + _tmp2 - _tmp4 + _tmp6;
  const Scalar _tmp10 = Scalar(0.021999999999999999) * _tmp9;
  const Scalar _tmp11 = _tmp10 * _tmp8;
  const Scalar _tmp12 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp13 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp14 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp15 = (Scalar(1) / Scalar(2)) * _tmp14;
  const Scalar _tmp16 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp17 = (Scalar(1) / Scalar(2)) * _tmp16;
  const Scalar _tmp18 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp19 = (Scalar(1) / Scalar(2)) * _tmp18;
  const Scalar _tmp20 = _tmp13 - _tmp15 + _tmp17 + _tmp19;
  const Scalar _tmp21 = _tmp12 - _tmp14 + _tmp16 + _tmp18;
  const Scalar _tmp22 = Scalar(0.021999999999999999) * _tmp21;
  const Scalar _tmp23 = _tmp20 * _tmp22;
  const Scalar _tmp24 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp25 = (Scalar(1) / Scalar(2)) * _tmp24;
  const Scalar _tmp26 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp27 = (Scalar(1) / Scalar(2)) * _tmp26;
  const Scalar _tmp28 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp29 = (Scalar(1) / Scalar(2)) * _tmp28;
  const Scalar _tmp30 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp31 = (Scalar(1) / Scalar(2)) * _tmp30;
  const Scalar _tmp32 = _tmp25 - _tmp27 - _tmp29 - _tmp31;
  const Scalar _tmp33 = -_tmp24 + _tmp26 + _tmp28 + _tmp30;
  const Scalar _tmp34 = Scalar(0.021999999999999999) * _tmp33;
  const Scalar _tmp35 = _tmp32 * _tmp34;
  const Scalar _tmp36 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp37 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp38 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp39 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp40 = -Scalar(1) / Scalar(2) * _tmp36 - Scalar(1) / Scalar(2) * _tmp37 -
                        Scalar(1) / Scalar(2) * _tmp38 + (Scalar(1) / Scalar(2)) * _tmp39;
  const Scalar _tmp41 = -_tmp36 - _tmp37 - _tmp38 + _tmp39;
  const Scalar _tmp42 = Scalar(0.021999999999999999) * _tmp41;
  const Scalar _tmp43 = _tmp40 * _tmp42;
  const Scalar _tmp44 = -_tmp43;
  const Scalar _tmp45 = _tmp11 + _tmp23 - _tmp35 + _tmp44;
  const Scalar _tmp46 = Scalar(0.83999999999999997) * _tmp33;
  const Scalar _tmp47 = _tmp40 * _tmp46;
  const Scalar _tmp48 = Scalar(0.83999999999999997) * _tmp21;
  const Scalar _tmp49 = _tmp48 * _tmp8;
  const Scalar _tmp50 = _tmp47 + _tmp49;
  const Scalar _tmp51 = _tmp45 + _tmp50;
  const Scalar _tmp52 = Scalar(0.41999999999999998) * _tmp9;
  const Scalar _tmp53 = _tmp40 * _tmp52;
  const Scalar _tmp54 = Scalar(0.41999999999999998) * _tmp33;
  const Scalar _tmp55 = _tmp20 * _tmp54;
  const Scalar _tmp56 = _tmp53 + _tmp55;
  const Scalar _tmp57 = Scalar(0.41999999999999998) * _tmp21;
  const Scalar _tmp58 = _tmp32 * _tmp57;
  const Scalar _tmp59 = Scalar(0.41999999999999998) * _tmp41;
  const Scalar _tmp60 = _tmp59 * _tmp8;
  const Scalar _tmp61 = _tmp58 + _tmp60;
  const Scalar _tmp62 = _tmp56 + _tmp61;
  const Scalar _tmp63 = -2 * std::pow(_tmp33, Scalar(2));
  const Scalar _tmp64 = -2 * std::pow(_tmp21, Scalar(2));
  const Scalar _tmp65 = Scalar(0.20999999999999999) * _tmp63 +
                        Scalar(0.20999999999999999) * _tmp64 + Scalar(0.20999999999999999);
  const Scalar _tmp66 = 2 * _tmp9;
  const Scalar _tmp67 = _tmp33 * _tmp66;
  const Scalar _tmp68 = 2 * _tmp41;
  const Scalar _tmp69 = _tmp21 * _tmp68;
  const Scalar _tmp70 = Scalar(0.20999999999999999) * _tmp67 + Scalar(0.20999999999999999) * _tmp69;
  const Scalar _tmp71 = _tmp21 * _tmp66;
  const Scalar _tmp72 = _tmp33 * _tmp68;
  const Scalar _tmp73 = _tmp71 - _tmp72;
  const Scalar _tmp74 = -Scalar(0.010999999999999999) * _tmp73;
  const Scalar _tmp75 = -_tmp70 + _tmp74;
  const Scalar _tmp76 = _tmp65 + _tmp75;
  const Scalar _tmp77 = _tmp76 + position_vector(1, 0);
  const Scalar _tmp78 = Scalar(4.83288938413423) - _tmp77;
  const Scalar _tmp79 = 2 * _tmp78;
  const Scalar _tmp80 = _tmp22 * _tmp40;
  const Scalar _tmp81 = _tmp10 * _tmp32;
  const Scalar _tmp82 = _tmp34 * _tmp8;
  const Scalar _tmp83 = _tmp20 * _tmp42;
  const Scalar _tmp84 = _tmp80 + _tmp81 + _tmp82 + _tmp83;
  const Scalar _tmp85 = -_tmp49;
  const Scalar _tmp86 = Scalar(0.83999999999999997) * _tmp9;
  const Scalar _tmp87 = _tmp20 * _tmp86;
  const Scalar _tmp88 = _tmp85 - _tmp87;
  const Scalar _tmp89 = -_tmp53;
  const Scalar _tmp90 = -_tmp55;
  const Scalar _tmp91 = _tmp61 + _tmp89 + _tmp90;
  const Scalar _tmp92 = _tmp88 + _tmp91;
  const Scalar _tmp93 = 1 - 2 * std::pow(_tmp9, Scalar(2));
  const Scalar _tmp94 = Scalar(0.20999999999999999) * _tmp64 + Scalar(0.20999999999999999) * _tmp93;
  const Scalar _tmp95 = -_tmp94;
  const Scalar _tmp96 = 2 * _tmp21 * _tmp33;
  const Scalar _tmp97 = _tmp68 * _tmp9;
  const Scalar _tmp98 = _tmp96 + _tmp97;
  const Scalar _tmp99 = -Scalar(0.010999999999999999) * _tmp98;
  const Scalar _tmp100 =
      Scalar(0.20999999999999999) * _tmp67 - Scalar(0.20999999999999999) * _tmp69;
  const Scalar _tmp101 = _tmp100 + _tmp99;
  const Scalar _tmp102 = _tmp101 + _tmp95;
  const Scalar _tmp103 = _tmp102 + position_vector(0, 0);
  const Scalar _tmp104 = -_tmp103 + Scalar(-1.7965602546229);
  const Scalar _tmp105 = 2 * _tmp104;
  const Scalar _tmp106 =
      std::sqrt(Scalar(std::pow(_tmp104, Scalar(2)) + std::pow(_tmp78, Scalar(2))));
  const Scalar _tmp107 = Scalar(1.0) / (fh1);
  const Scalar _tmp108 =
      Scalar(0.5) *
      std::sinh(Scalar(0.1034955) * _tmp107 *
                (-_tmp106 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp107 * fv1))) /
      _tmp106;
  const Scalar _tmp109 = _tmp52 * _tmp8;
  const Scalar _tmp110 = _tmp40 * _tmp57;
  const Scalar _tmp111 = _tmp54 * _tmp8;
  const Scalar _tmp112 = -_tmp110 - _tmp111;
  const Scalar _tmp113 = _tmp109 + _tmp112;
  const Scalar _tmp114 = _tmp32 * _tmp52;
  const Scalar _tmp115 = _tmp20 * _tmp59;
  const Scalar _tmp116 = _tmp114 + _tmp115;
  const Scalar _tmp117 = _tmp20 * _tmp57;
  const Scalar _tmp118 = _tmp32 * _tmp54;
  const Scalar _tmp119 = _tmp40 * _tmp59;
  const Scalar _tmp120 = _tmp118 + _tmp119;
  const Scalar _tmp121 = Scalar(0.043999999999999997) * _tmp9;
  const Scalar _tmp122 = _tmp121 * _tmp20;
  const Scalar _tmp123 = Scalar(0.043999999999999997) * _tmp33;
  const Scalar _tmp124 = _tmp123 * _tmp40;
  const Scalar _tmp125 = _tmp122 + _tmp124;
  const Scalar _tmp126 = _tmp117 + _tmp120 + _tmp125;
  const Scalar _tmp127 = _tmp113 + _tmp116 + _tmp126;
  const Scalar _tmp128 = -_tmp47;
  const Scalar _tmp129 = _tmp128 + _tmp85;
  const Scalar _tmp130 = -_tmp11;
  const Scalar _tmp131 = _tmp130 - _tmp23 + _tmp35 + _tmp43;
  const Scalar _tmp132 = _tmp129 + _tmp131;
  const Scalar _tmp133 = _tmp132 + _tmp62;
  const Scalar _tmp134 = _tmp70 + _tmp74;
  const Scalar _tmp135 = _tmp134 + _tmp65;
  const Scalar _tmp136 = _tmp135 + position_vector(1, 0);
  const Scalar _tmp137 = _tmp136 + Scalar(-4.7744369927459998);
  const Scalar _tmp138 = 2 * _tmp137;
  const Scalar _tmp139 = -_tmp58;
  const Scalar _tmp140 = -_tmp60;
  const Scalar _tmp141 = _tmp139 + _tmp140 + _tmp56;
  const Scalar _tmp142 = _tmp141 + _tmp88;
  const Scalar _tmp143 = -_tmp82;
  const Scalar _tmp144 = -_tmp80;
  const Scalar _tmp145 = _tmp143 + _tmp144 - _tmp81 - _tmp83;
  const Scalar _tmp146 = _tmp142 + _tmp145;
  const Scalar _tmp147 = _tmp101 + _tmp94;
  const Scalar _tmp148 = _tmp147 + position_vector(0, 0);
  const Scalar _tmp149 = _tmp148 + Scalar(-2.7171519410699099);
  const Scalar _tmp150 = 2 * _tmp149;
  const Scalar _tmp151 = _tmp133 * _tmp138 + _tmp146 * _tmp150;
  const Scalar _tmp152 = Scalar(1.0) / (_tmp149);
  const Scalar _tmp153 = std::pow(_tmp149, Scalar(2));
  const Scalar _tmp154 = std::pow(_tmp137, Scalar(2)) + _tmp153;
  const Scalar _tmp155 = std::sqrt(_tmp154);
  const Scalar _tmp156 = Scalar(1.0) / (_tmp155);
  const Scalar _tmp157 = (Scalar(1) / Scalar(2)) * _tmp152 * _tmp156;
  const Scalar _tmp158 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp159 = -_tmp100 + _tmp99;
  const Scalar _tmp160 = _tmp159 + _tmp95;
  const Scalar _tmp161 = _tmp160 + position_vector(0, 0);
  const Scalar _tmp162 = _tmp161 + Scalar(1.9874742031097401);
  const Scalar _tmp163 = -_tmp65;
  const Scalar _tmp164 = _tmp163 + _tmp75;
  const Scalar _tmp165 = _tmp164 + position_vector(1, 0);
  const Scalar _tmp166 = _tmp165 + Scalar(8.3196563720703107);
  const Scalar _tmp167 = std::pow(_tmp162, Scalar(2)) + std::pow(_tmp166, Scalar(2));
  const Scalar _tmp168 = std::pow(_tmp167, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp169 = _tmp162 * _tmp168;
  const Scalar _tmp170 =
      Scalar(0.20999999999999999) * _tmp96 - Scalar(0.20999999999999999) * _tmp97;
  const Scalar _tmp171 =
      -Scalar(0.010999999999999999) * _tmp63 - Scalar(0.010999999999999999) * _tmp93;
  const Scalar _tmp172 =
      Scalar(0.20999999999999999) * _tmp71 + Scalar(0.20999999999999999) * _tmp72;
  const Scalar _tmp173 = _tmp171 - _tmp172;
  const Scalar _tmp174 = _tmp170 + _tmp173;
  const Scalar _tmp175 = _tmp134 + _tmp163;
  const Scalar _tmp176 = _tmp175 + position_vector(1, 0);
  const Scalar _tmp177 = _tmp176 + Scalar(8.3885017487099702);
  const Scalar _tmp178 = _tmp159 + _tmp94;
  const Scalar _tmp179 = _tmp178 + position_vector(0, 0);
  const Scalar _tmp180 = _tmp179 + Scalar(-2.5193355532036801);
  const Scalar _tmp181 = std::pow(_tmp177, Scalar(2)) + std::pow(_tmp180, Scalar(2));
  const Scalar _tmp182 = std::pow(_tmp181, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp183 = _tmp180 * _tmp182;
  const Scalar _tmp184 = _tmp177 * _tmp182;
  const Scalar _tmp185 = _tmp137 * _tmp152;
  const Scalar _tmp186 = _tmp183 * _tmp185 - _tmp184;
  const Scalar _tmp187 = _tmp166 * _tmp168;
  const Scalar _tmp188 = _tmp169 * _tmp185 - _tmp187;
  const Scalar _tmp189 = Scalar(1.0) / (_tmp188);
  const Scalar _tmp190 = -_tmp170;
  const Scalar _tmp191 = _tmp173 + _tmp190;
  const Scalar _tmp192 = _tmp171 + _tmp172;
  const Scalar _tmp193 = _tmp170 + _tmp192;
  const Scalar _tmp194 = _tmp169 * _tmp193;
  const Scalar _tmp195 = -_tmp185 * _tmp194 + _tmp187 * _tmp191;
  const Scalar _tmp196 = _tmp189 * _tmp195;
  const Scalar _tmp197 = _tmp183 * _tmp193;
  const Scalar _tmp198 = _tmp174 * _tmp184 - _tmp185 * _tmp197 - _tmp186 * _tmp196;
  const Scalar _tmp199 = Scalar(1.0) * _tmp135;
  const Scalar _tmp200 = -_tmp199;
  const Scalar _tmp201 = _tmp164 + _tmp200;
  const Scalar _tmp202 = Scalar(1.0) / (_tmp201);
  const Scalar _tmp203 = Scalar(1.0) * _tmp147;
  const Scalar _tmp204 = -_tmp160 + _tmp203;
  const Scalar _tmp205 = _tmp202 * _tmp204;
  const Scalar _tmp206 = -_tmp169 * _tmp191 + _tmp194;
  const Scalar _tmp207 = _tmp189 * _tmp206;
  const Scalar _tmp208 = -_tmp174 * _tmp183 - _tmp186 * _tmp207 + _tmp197 - _tmp198 * _tmp205;
  const Scalar _tmp209 = Scalar(1.0) / (_tmp208);
  const Scalar _tmp210 = _tmp199 * _tmp205 + _tmp203;
  const Scalar _tmp211 = 0;
  const Scalar _tmp212 = _tmp209 * _tmp211;
  const Scalar _tmp213 = _tmp186 * _tmp189;
  const Scalar _tmp214 = _tmp212 * _tmp213;
  const Scalar _tmp215 = -_tmp169 * _tmp214 + _tmp183 * _tmp212;
  const Scalar _tmp216 = _tmp158 * _tmp215;
  const Scalar _tmp217 = _tmp157 * _tmp216;
  const Scalar _tmp218 = _tmp77 + Scalar(-4.83288938413423);
  const Scalar _tmp219 = _tmp102 * _tmp218;
  const Scalar _tmp220 = _tmp49 + _tmp87;
  const Scalar _tmp221 = _tmp145 + _tmp220;
  const Scalar _tmp222 = _tmp141 + _tmp221;
  const Scalar _tmp223 = _tmp103 + Scalar(1.7965602546229);
  const Scalar _tmp224 = 2 * _tmp223;
  const Scalar _tmp225 = _tmp139 + _tmp89;
  const Scalar _tmp226 = _tmp140 + _tmp225 + _tmp90;
  const Scalar _tmp227 = _tmp132 + _tmp226;
  const Scalar _tmp228 = 2 * _tmp218;
  const Scalar _tmp229 = _tmp222 * _tmp224 + _tmp227 * _tmp228;
  const Scalar _tmp230 = std::pow(_tmp218, Scalar(2)) + std::pow(_tmp223, Scalar(2));
  const Scalar _tmp231 = std::pow(_tmp230, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp232 = (Scalar(1) / Scalar(2)) * _tmp231;
  const Scalar _tmp233 = _tmp229 * _tmp232;
  const Scalar _tmp234 = std::pow(_tmp230, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp235 = _tmp102 * _tmp234;
  const Scalar _tmp236 = _tmp223 * _tmp76;
  const Scalar _tmp237 = _tmp218 * _tmp234;
  const Scalar _tmp238 = _tmp223 * _tmp234;
  const Scalar _tmp239 = _tmp234 * _tmp76;
  const Scalar _tmp240 = -_tmp219 * _tmp233 + _tmp222 * _tmp237 - _tmp222 * _tmp239 +
                         _tmp227 * _tmp235 - _tmp227 * _tmp238 + _tmp233 * _tmp236;
  const Scalar _tmp241 = _tmp164 * _tmp168;
  const Scalar _tmp242 = _tmp147 * _tmp156;
  const Scalar _tmp243 = _tmp135 * _tmp156;
  const Scalar _tmp244 = _tmp137 * _tmp242 - _tmp149 * _tmp243;
  const Scalar _tmp245 = _tmp152 * _tmp155;
  const Scalar _tmp246 = _tmp244 * _tmp245;
  const Scalar _tmp247 = -_tmp160 * _tmp187 + _tmp162 * _tmp241 + _tmp169 * _tmp246;
  const Scalar _tmp248 =
      _tmp175 * _tmp183 - _tmp178 * _tmp184 + _tmp183 * _tmp246 - _tmp213 * _tmp247;
  const Scalar _tmp249 = Scalar(1.0) / (_tmp248);
  const Scalar _tmp250 = Scalar(1.0) * _tmp189;
  const Scalar _tmp251 = _tmp249 * _tmp250;
  const Scalar _tmp252 = _tmp169 * _tmp251;
  const Scalar _tmp253 = Scalar(1.0) * _tmp249;
  const Scalar _tmp254 = _tmp183 * _tmp253 - _tmp186 * _tmp252;
  const Scalar _tmp255 = _tmp245 * fh1;
  const Scalar _tmp256 = _tmp254 * _tmp255;
  const Scalar _tmp257 = _tmp185 * _tmp193;
  const Scalar _tmp258 = _tmp131 + _tmp50;
  const Scalar _tmp259 = _tmp258 + _tmp62;
  const Scalar _tmp260 = 2 * _tmp177;
  const Scalar _tmp261 = _tmp145 + _tmp92;
  const Scalar _tmp262 = 2 * _tmp180;
  const Scalar _tmp263 = _tmp259 * _tmp260 + _tmp261 * _tmp262;
  const Scalar _tmp264 = std::pow(_tmp181, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp265 = (Scalar(1) / Scalar(2)) * _tmp264;
  const Scalar _tmp266 = _tmp180 * _tmp265;
  const Scalar _tmp267 = _tmp263 * _tmp266;
  const Scalar _tmp268 = _tmp110 + _tmp111;
  const Scalar _tmp269 = _tmp109 + _tmp268;
  const Scalar _tmp270 = -_tmp114 - _tmp115;
  const Scalar _tmp271 = _tmp126 + _tmp269 + _tmp270;
  const Scalar _tmp272 = _tmp185 * _tmp271;
  const Scalar _tmp273 = _tmp182 * _tmp259;
  const Scalar _tmp274 = Scalar(1.0) / (_tmp153);
  const Scalar _tmp275 = _tmp137 * _tmp274;
  const Scalar _tmp276 = _tmp146 * _tmp275;
  const Scalar _tmp277 = -_tmp117;
  const Scalar _tmp278 = -_tmp118;
  const Scalar _tmp279 = -_tmp119;
  const Scalar _tmp280 = _tmp278 + _tmp279;
  const Scalar _tmp281 = _tmp125 + _tmp277 + _tmp280;
  const Scalar _tmp282 = -_tmp109;
  const Scalar _tmp283 = _tmp112 + _tmp282;
  const Scalar _tmp284 = _tmp116 + _tmp283;
  const Scalar _tmp285 = _tmp281 + _tmp284;
  const Scalar _tmp286 = _tmp221 + _tmp91;
  const Scalar _tmp287 = _tmp168 * _tmp286;
  const Scalar _tmp288 = _tmp193 * _tmp287;
  const Scalar _tmp289 = _tmp226 + _tmp258;
  const Scalar _tmp290 = 2 * _tmp166;
  const Scalar _tmp291 = 2 * _tmp162;
  const Scalar _tmp292 = _tmp286 * _tmp291 + _tmp289 * _tmp290;
  const Scalar _tmp293 = std::pow(_tmp167, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp294 = (Scalar(1) / Scalar(2)) * _tmp293;
  const Scalar _tmp295 = _tmp162 * _tmp294;
  const Scalar _tmp296 = _tmp292 * _tmp295;
  const Scalar _tmp297 = _tmp166 * _tmp294;
  const Scalar _tmp298 = _tmp292 * _tmp297;
  const Scalar _tmp299 = _tmp133 * _tmp152;
  const Scalar _tmp300 = _tmp193 * _tmp299;
  const Scalar _tmp301 = _tmp168 * _tmp289;
  const Scalar _tmp302 = -_tmp169 * _tmp272 - _tmp169 * _tmp300 - _tmp185 * _tmp288 +
                         _tmp187 * _tmp285 - _tmp191 * _tmp298 + _tmp191 * _tmp301 +
                         _tmp194 * _tmp276 + _tmp257 * _tmp296;
  const Scalar _tmp303 = _tmp268 + _tmp282;
  const Scalar _tmp304 = _tmp270 + _tmp281 + _tmp303;
  const Scalar _tmp305 = _tmp177 * _tmp265;
  const Scalar _tmp306 = _tmp263 * _tmp305;
  const Scalar _tmp307 = _tmp182 * _tmp261;
  const Scalar _tmp308 = -_tmp183 * _tmp276 + _tmp183 * _tmp299 - _tmp185 * _tmp267 +
                         _tmp185 * _tmp307 - _tmp273 + _tmp306;
  const Scalar _tmp309 = -_tmp169 * _tmp276 + _tmp169 * _tmp299 + _tmp185 * _tmp287 -
                         _tmp185 * _tmp296 + _tmp298 - _tmp301;
  const Scalar _tmp310 = std::pow(_tmp188, Scalar(-2));
  const Scalar _tmp311 = _tmp195 * _tmp310;
  const Scalar _tmp312 = _tmp186 * _tmp311;
  const Scalar _tmp313 = _tmp174 * _tmp273 - _tmp174 * _tmp306 - _tmp183 * _tmp272 +
                         _tmp184 * _tmp304 - _tmp196 * _tmp308 + _tmp197 * _tmp276 -
                         _tmp197 * _tmp299 - _tmp213 * _tmp302 + _tmp257 * _tmp267 -
                         _tmp257 * _tmp307 + _tmp309 * _tmp312;
  const Scalar _tmp314 = _tmp206 * _tmp310;
  const Scalar _tmp315 = _tmp186 * _tmp314;
  const Scalar _tmp316 = _tmp174 * _tmp182;
  const Scalar _tmp317 = _tmp169 * _tmp271 - _tmp169 * _tmp285 - _tmp191 * _tmp287 +
                         _tmp191 * _tmp296 - _tmp193 * _tmp296 + _tmp288;
  const Scalar _tmp318 = _tmp40 * _tmp86;
  const Scalar _tmp319 = -_tmp318;
  const Scalar _tmp320 = _tmp20 * _tmp46;
  const Scalar _tmp321 = Scalar(1.6799999999999999) * _tmp21;
  const Scalar _tmp322 = _tmp321 * _tmp8;
  const Scalar _tmp323 = Scalar(1.6799999999999999) * _tmp33;
  const Scalar _tmp324 = _tmp322 + _tmp323 * _tmp40;
  const Scalar _tmp325 = Scalar(0.83999999999999997) * _tmp41;
  const Scalar _tmp326 = -_tmp32 * _tmp48 - _tmp325 * _tmp8;
  const Scalar _tmp327 = _tmp319 - _tmp320 + _tmp324 + _tmp326;
  const Scalar _tmp328 = std::pow(_tmp201, Scalar(-2));
  const Scalar _tmp329 = _tmp204 * _tmp328;
  const Scalar _tmp330 = _tmp327 * _tmp329;
  const Scalar _tmp331 = Scalar(1.6799999999999999) * _tmp9;
  const Scalar _tmp332 = _tmp318 + _tmp320 + _tmp326;
  const Scalar _tmp333 = -_tmp20 * _tmp331 - _tmp322 + _tmp332;
  const Scalar _tmp334 = _tmp198 * _tmp202;
  const Scalar _tmp335 = _tmp174 * _tmp267 + _tmp183 * _tmp271 - _tmp183 * _tmp304 -
                         _tmp193 * _tmp267 + _tmp193 * _tmp307 + _tmp198 * _tmp330 -
                         _tmp205 * _tmp313 - _tmp207 * _tmp308 - _tmp213 * _tmp317 -
                         _tmp261 * _tmp316 + _tmp309 * _tmp315 - _tmp333 * _tmp334;
  const Scalar _tmp336 = std::pow(_tmp208, Scalar(-2));
  const Scalar _tmp337 = _tmp335 * _tmp336;
  const Scalar _tmp338 = _tmp169 * _tmp211 * _tmp213;
  const Scalar _tmp339 = _tmp183 * _tmp211;
  const Scalar _tmp340 = _tmp169 * _tmp189;
  const Scalar _tmp341 = _tmp212 * _tmp340;
  const Scalar _tmp342 = _tmp169 * _tmp310;
  const Scalar _tmp343 = _tmp186 * _tmp342;
  const Scalar _tmp344 = _tmp212 * _tmp343;
  const Scalar _tmp345 = _tmp158 * _tmp245;
  const Scalar _tmp346 = Scalar(1.0) * _tmp202;
  const Scalar _tmp347 = _tmp204 * _tmp346;
  const Scalar _tmp348 = _tmp196 * _tmp347 - _tmp206 * _tmp250;
  const Scalar _tmp349 = _tmp209 * _tmp248;
  const Scalar _tmp350 = -_tmp247 * _tmp250 - _tmp348 * _tmp349;
  const Scalar _tmp351 = _tmp208 * _tmp249;
  const Scalar _tmp352 = _tmp350 * _tmp351;
  const Scalar _tmp353 = _tmp348 + _tmp352;
  const Scalar _tmp354 = _tmp209 * _tmp353;
  const Scalar _tmp355 = -_tmp186 * _tmp354 + Scalar(1.0);
  const Scalar _tmp356 = _tmp189 * _tmp355;
  const Scalar _tmp357 = _tmp169 * _tmp356 + _tmp183 * _tmp354;
  const Scalar _tmp358 = _tmp255 * _tmp357;
  const Scalar _tmp359 = _tmp218 * _tmp233;
  const Scalar _tmp360 = _tmp218 * _tmp235 - _tmp238 * _tmp76;
  const Scalar _tmp361 = _tmp360 * fh1;
  const Scalar _tmp362 = _tmp254 * _tmp361;
  const Scalar _tmp363 = _tmp157 * _tmp362;
  const Scalar _tmp364 = _tmp222 * _tmp234;
  const Scalar _tmp365 = _tmp185 * _tmp196 + _tmp257;
  const Scalar _tmp366 = _tmp185 * _tmp207 - _tmp193 - _tmp205 * _tmp365;
  const Scalar _tmp367 = _tmp189 * _tmp247;
  const Scalar _tmp368 = _tmp185 * _tmp367 - _tmp246 - _tmp349 * _tmp366;
  const Scalar _tmp369 = _tmp351 * _tmp368;
  const Scalar _tmp370 = _tmp366 + _tmp369;
  const Scalar _tmp371 = _tmp209 * _tmp370;
  const Scalar _tmp372 = -_tmp185 - _tmp186 * _tmp371;
  const Scalar _tmp373 = _tmp183 * _tmp371 + _tmp340 * _tmp372 + Scalar(1.0);
  const Scalar _tmp374 = _tmp255 * _tmp373;
  const Scalar _tmp375 = _tmp227 * _tmp234;
  const Scalar _tmp376 = _tmp237 * fh1;
  const Scalar _tmp377 = _tmp357 * _tmp376;
  const Scalar _tmp378 = _tmp157 * _tmp377;
  const Scalar _tmp379 = _tmp189 * _tmp372;
  const Scalar _tmp380 = _tmp183 * _tmp370;
  const Scalar _tmp381 = _tmp342 * _tmp372;
  const Scalar _tmp382 = _tmp248 * _tmp366;
  const Scalar _tmp383 = (Scalar(1) / Scalar(2)) / (_tmp154 * std::sqrt(_tmp154));
  const Scalar _tmp384 = _tmp151 * _tmp383;
  const Scalar _tmp385 = _tmp137 * _tmp147;
  const Scalar _tmp386 = _tmp135 * _tmp149;
  const Scalar _tmp387 = _tmp137 * _tmp156;
  const Scalar _tmp388 = _tmp149 * _tmp156;
  const Scalar _tmp389 = _tmp245 * (_tmp133 * _tmp242 - _tmp133 * _tmp388 - _tmp146 * _tmp243 +
                                    _tmp146 * _tmp387 - _tmp384 * _tmp385 + _tmp384 * _tmp386);
  const Scalar _tmp390 = _tmp155 * _tmp274;
  const Scalar _tmp391 = _tmp244 * _tmp390;
  const Scalar _tmp392 = _tmp146 * _tmp391;
  const Scalar _tmp393 = _tmp157 * _tmp244;
  const Scalar _tmp394 = _tmp151 * _tmp393;
  const Scalar _tmp395 = _tmp160 * _tmp298 - _tmp160 * _tmp301 + _tmp162 * _tmp301 -
                         _tmp164 * _tmp296 + _tmp169 * _tmp389 - _tmp169 * _tmp392 +
                         _tmp169 * _tmp394 - _tmp187 * _tmp286 + _tmp241 * _tmp286 +
                         _tmp246 * _tmp287 - _tmp246 * _tmp296;
  const Scalar _tmp396 = _tmp185 * _tmp189;
  const Scalar _tmp397 = _tmp247 * _tmp310;
  const Scalar _tmp398 = _tmp186 * _tmp397;
  const Scalar _tmp399 = -_tmp175 * _tmp267 + _tmp175 * _tmp307 - _tmp178 * _tmp273 +
                         _tmp178 * _tmp306 + _tmp180 * _tmp273 + _tmp183 * _tmp389 -
                         _tmp183 * _tmp392 + _tmp183 * _tmp394 - _tmp184 * _tmp261 -
                         _tmp213 * _tmp395 - _tmp246 * _tmp267 + _tmp246 * _tmp307 -
                         _tmp308 * _tmp367 + _tmp309 * _tmp398;
  const Scalar _tmp400 = _tmp209 * _tmp366;
  const Scalar _tmp401 = _tmp202 * _tmp365;
  const Scalar _tmp402 = _tmp185 * _tmp311;
  const Scalar _tmp403 = -_tmp193 * _tmp276 - _tmp196 * _tmp276 + _tmp196 * _tmp299 + _tmp272 +
                         _tmp300 + _tmp302 * _tmp396 - _tmp309 * _tmp402;
  const Scalar _tmp404 = _tmp185 * _tmp309;
  const Scalar _tmp405 = -_tmp122 - _tmp124 - _tmp205 * _tmp403 - _tmp207 * _tmp276 +
                         _tmp207 * _tmp299 + _tmp277 + _tmp280 + _tmp284 - _tmp314 * _tmp404 +
                         _tmp317 * _tmp396 + _tmp330 * _tmp365 - _tmp333 * _tmp401;
  const Scalar _tmp406 = _tmp351 * (-_tmp276 * _tmp367 + _tmp299 * _tmp367 + _tmp337 * _tmp382 -
                                    _tmp349 * _tmp405 - _tmp389 + _tmp392 - _tmp394 +
                                    _tmp395 * _tmp396 - _tmp397 * _tmp404 - _tmp399 * _tmp400);
  const Scalar _tmp407 = std::pow(_tmp248, Scalar(-2));
  const Scalar _tmp408 = _tmp399 * _tmp407;
  const Scalar _tmp409 = _tmp208 * _tmp408;
  const Scalar _tmp410 = _tmp368 * _tmp409;
  const Scalar _tmp411 = _tmp249 * _tmp368;
  const Scalar _tmp412 = _tmp335 * _tmp411;
  const Scalar _tmp413 = _tmp405 + _tmp406 - _tmp410 + _tmp412;
  const Scalar _tmp414 = _tmp186 * _tmp209;
  const Scalar _tmp415 = _tmp186 * _tmp336;
  const Scalar _tmp416 = _tmp370 * _tmp415;
  const Scalar _tmp417 =
      _tmp276 - _tmp299 - _tmp308 * _tmp371 + _tmp335 * _tmp416 - _tmp413 * _tmp414;
  const Scalar _tmp418 = _tmp183 * _tmp209;
  const Scalar _tmp419 = _tmp238 * fh1;
  const Scalar _tmp420 = _tmp245 * _tmp419;
  const Scalar _tmp421 = _tmp146 * _tmp390;
  const Scalar _tmp422 = Scalar(0.5) * _tmp249;
  const Scalar _tmp423 = _tmp162 * _tmp213 * _tmp293 * _tmp422;
  const Scalar _tmp424 = _tmp253 * _tmp343;
  const Scalar _tmp425 = Scalar(1.0) * _tmp183;
  const Scalar _tmp426 = _tmp186 * _tmp250;
  const Scalar _tmp427 = _tmp169 * _tmp426;
  const Scalar _tmp428 = _tmp180 * _tmp264 * _tmp422;
  const Scalar _tmp429 = _tmp186 * _tmp251;
  const Scalar _tmp430 = _tmp245 * _tmp361;
  const Scalar _tmp431 = _tmp373 * _tmp419;
  const Scalar _tmp432 = _tmp157 * _tmp431;
  const Scalar _tmp433 = _tmp223 * _tmp233;
  const Scalar _tmp434 = _tmp249 * _tmp350;
  const Scalar _tmp435 = _tmp335 * _tmp434;
  const Scalar _tmp436 = Scalar(1.0) * _tmp309;
  const Scalar _tmp437 = _tmp209 * _tmp348;
  const Scalar _tmp438 = _tmp311 * _tmp347;
  const Scalar _tmp439 = _tmp189 * _tmp347;
  const Scalar _tmp440 = _tmp195 * _tmp250;
  const Scalar _tmp441 = _tmp196 * _tmp346;
  const Scalar _tmp442 = -_tmp250 * _tmp317 + _tmp302 * _tmp439 - _tmp309 * _tmp438 +
                         _tmp314 * _tmp436 - _tmp330 * _tmp440 + _tmp333 * _tmp441;
  const Scalar _tmp443 = _tmp248 * _tmp348;
  const Scalar _tmp444 = _tmp351 * (-_tmp250 * _tmp395 + _tmp337 * _tmp443 - _tmp349 * _tmp442 +
                                    _tmp397 * _tmp436 - _tmp399 * _tmp437);
  const Scalar _tmp445 = _tmp350 * _tmp409;
  const Scalar _tmp446 = _tmp435 + _tmp442 + _tmp444 - _tmp445;
  const Scalar _tmp447 = _tmp353 * _tmp415;
  const Scalar _tmp448 = -_tmp308 * _tmp354 + _tmp335 * _tmp447 - _tmp414 * _tmp446;
  const Scalar _tmp449 = _tmp342 * _tmp355;
  const Scalar _tmp450 = _tmp183 * _tmp353;
  const Scalar _tmp451 = _tmp245 * _tmp376;
  const Scalar _tmp452 =
      -_tmp151 * _tmp217 - _tmp151 * _tmp363 - _tmp151 * _tmp378 - _tmp151 * _tmp432 +
      _tmp216 * _tmp421 - _tmp240 * _tmp256 -
      _tmp345 * (-_tmp212 * _tmp267 + _tmp212 * _tmp307 - _tmp214 * _tmp287 + _tmp214 * _tmp296 -
                 _tmp308 * _tmp341 + _tmp309 * _tmp344 + _tmp337 * _tmp338 - _tmp337 * _tmp339) +
      _tmp358 * _tmp359 - _tmp358 * _tmp375 + _tmp362 * _tmp421 - _tmp364 * _tmp374 +
      _tmp374 * _tmp433 + _tmp377 * _tmp421 -
      _tmp420 * (-_tmp267 * _tmp371 + _tmp287 * _tmp379 - _tmp296 * _tmp379 + _tmp307 * _tmp371 -
                 _tmp309 * _tmp381 - _tmp337 * _tmp380 + _tmp340 * _tmp417 + _tmp413 * _tmp418) +
      _tmp421 * _tmp431 -
      _tmp430 * (-_tmp252 * _tmp308 + _tmp253 * _tmp307 - _tmp263 * _tmp428 - _tmp287 * _tmp429 +
                 _tmp292 * _tmp423 + _tmp309 * _tmp424 - _tmp408 * _tmp425 + _tmp408 * _tmp427) -
      _tmp451 * (-_tmp267 * _tmp354 + _tmp287 * _tmp356 - _tmp296 * _tmp356 + _tmp307 * _tmp354 -
                 _tmp309 * _tmp449 - _tmp337 * _tmp450 + _tmp340 * _tmp448 + _tmp418 * _tmp446);
  const Scalar _tmp453 = Scalar(2.7171519410699099) - _tmp148;
  const Scalar _tmp454 = Scalar(4.7744369927459998) - _tmp136;
  const Scalar _tmp455 =
      std::sqrt(Scalar(std::pow(_tmp453, Scalar(2)) + std::pow(_tmp454, Scalar(2))));
  const Scalar _tmp456 =
      -_tmp215 * _tmp345 - _tmp254 * _tmp430 - _tmp357 * _tmp451 - _tmp373 * _tmp420;
  const Scalar _tmp457 = Scalar(1.0) / (_tmp456);
  const Scalar _tmp458 = _tmp175 + _tmp200;
  const Scalar _tmp459 = _tmp202 * _tmp458;
  const Scalar _tmp460 = _tmp204 * _tmp459;
  const Scalar _tmp461 = -_tmp178 + _tmp203 - _tmp460;
  const Scalar _tmp462 = Scalar(1.0) / (_tmp461);
  const Scalar _tmp463 = Scalar(1.0) * _tmp462;
  const Scalar _tmp464 = _tmp351 * _tmp463;
  const Scalar _tmp465 = -_tmp198 * _tmp253 + _tmp458 * _tmp464;
  const Scalar _tmp466 = Scalar(1.0) * fh1;
  const Scalar _tmp467 = _tmp466 * (-_tmp346 * _tmp465 + _tmp464);
  const Scalar _tmp468 = _tmp459 * _tmp463 - _tmp463;
  const Scalar _tmp469 = fh1 * (_tmp190 + _tmp192);
  const Scalar _tmp470 = _tmp102 * fv1 + _tmp238 * _tmp469 + Scalar(3.29616) * _tmp98;
  const Scalar _tmp471 = Scalar(1.0) * _tmp470;
  const Scalar _tmp472 = _tmp198 * _tmp209;
  const Scalar _tmp473 = _tmp458 * _tmp462;
  const Scalar _tmp474 = _tmp352 * _tmp473 - _tmp353 * _tmp472 - _tmp440;
  const Scalar _tmp475 = -_tmp346 * _tmp474 + _tmp352 * _tmp463;
  const Scalar _tmp476 = _tmp466 * _tmp475;
  const Scalar _tmp477 = _tmp200 - _tmp210 * _tmp473 - _tmp211 * _tmp472;
  const Scalar _tmp478 = Scalar(1.0) * _tmp158;
  const Scalar _tmp479 = -_tmp237 * _tmp469 - Scalar(3.29616) * _tmp73 - _tmp76 * fv1;
  const Scalar _tmp480 = _tmp460 * _tmp463 + Scalar(1.0);
  const Scalar _tmp481 = _tmp205 * _tmp463;
  const Scalar _tmp482 = -Scalar(1.0) * _tmp346 * _tmp480 + Scalar(1.0) * _tmp481;
  const Scalar _tmp483 = _tmp365 + _tmp369 * _tmp473 - _tmp370 * _tmp472;
  const Scalar _tmp484 = -_tmp346 * _tmp483 + _tmp369 * _tmp463;
  const Scalar _tmp485 = _tmp466 * _tmp484;
  const Scalar _tmp486 =
      _tmp237 * _tmp476 + _tmp238 * _tmp485 + _tmp360 * _tmp467 + _tmp468 * _tmp471 +
      _tmp478 * (-_tmp210 * _tmp463 - _tmp346 * _tmp477 + Scalar(1.0)) + _tmp479 * _tmp482;
  const Scalar _tmp487 = std::asinh(_tmp457 * _tmp486);
  const Scalar _tmp488 = Scalar(9.6622558468725703) * _tmp487;
  const Scalar _tmp489 = -_tmp455 - _tmp456 * _tmp488;
  const Scalar _tmp490 = Scalar(0.1034955) * _tmp457;
  const Scalar _tmp491 = _tmp489 * _tmp490;
  const Scalar _tmp492 = Scalar(1.0) * _tmp487;
  const Scalar _tmp493 = Scalar(8.3641088633305802) * _tmp457 -
                         Scalar(9.6622558468725703) * std::cosh(_tmp491) +
                         Scalar(9.6622558468725703) * std::cosh(_tmp492);
  const Scalar _tmp494 = _tmp226 + _tmp51;
  const Scalar _tmp495 = 2 * _tmp454;
  const Scalar _tmp496 = _tmp220 + _tmp84;
  const Scalar _tmp497 = 2 * _tmp453;
  const Scalar _tmp498 = (Scalar(1) / Scalar(2)) / _tmp455;
  const Scalar _tmp499 = Scalar(9.6622558468725703) * _tmp456;
  const Scalar _tmp500 = std::pow(_tmp456, Scalar(-2));
  const Scalar _tmp501 =
      std::pow(Scalar(std::pow(_tmp486, Scalar(2)) * _tmp500 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp502 = _tmp486 * _tmp500;
  const Scalar _tmp503 = Scalar(0.5) * _tmp231;
  const Scalar _tmp504 = _tmp229 * _tmp503;
  const Scalar _tmp505 = _tmp223 * fh1;
  const Scalar _tmp506 = _tmp484 * _tmp505;
  const Scalar _tmp507 = _tmp202 * _tmp333;
  const Scalar _tmp508 = _tmp133 * _tmp347 + _tmp146 - _tmp199 * _tmp330 + _tmp199 * _tmp507;
  const Scalar _tmp509 = _tmp333 * _tmp459;
  const Scalar _tmp510 = _tmp205 * _tmp324;
  const Scalar _tmp511 = _tmp330 * _tmp458;
  const Scalar _tmp512 = _tmp332 - _tmp509 - _tmp510 + _tmp511;
  const Scalar _tmp513 = std::pow(_tmp461, Scalar(-2));
  const Scalar _tmp514 = Scalar(1.0) * _tmp513;
  const Scalar _tmp515 = _tmp512 * _tmp514;
  const Scalar _tmp516 = _tmp198 * _tmp211;
  const Scalar _tmp517 = _tmp210 * _tmp462;
  const Scalar _tmp518 = _tmp512 * _tmp513;
  const Scalar _tmp519 = _tmp210 * _tmp458;
  const Scalar _tmp520 = -_tmp212 * _tmp313 - _tmp324 * _tmp517 + _tmp337 * _tmp516 -
                         _tmp473 * _tmp508 + _tmp494 + _tmp518 * _tmp519;
  const Scalar _tmp521 = Scalar(1.0) * _tmp328;
  const Scalar _tmp522 = _tmp327 * _tmp521;
  const Scalar _tmp523 = _tmp330 * _tmp463;
  const Scalar _tmp524 = _tmp347 * _tmp518;
  const Scalar _tmp525 =
      -_tmp458 * _tmp524 + _tmp463 * _tmp509 + _tmp463 * _tmp510 - _tmp463 * _tmp511;
  const Scalar _tmp526 = Scalar(1.0) * _tmp479;
  const Scalar _tmp527 = Scalar(6.59232) * _tmp9;
  const Scalar _tmp528 = Scalar(6.59232) * _tmp21;
  const Scalar _tmp529 = _tmp40 * _tmp528;
  const Scalar _tmp530 = Scalar(6.59232) * _tmp33;
  const Scalar _tmp531 = _tmp530 * _tmp8;
  const Scalar _tmp532 = _tmp223 * _tmp469;
  const Scalar _tmp533 = Scalar(6.59232) * _tmp41;
  const Scalar _tmp534 = _tmp127 * _tmp419 + _tmp20 * _tmp533 + _tmp222 * fv1 - _tmp233 * _tmp532 +
                         _tmp32 * _tmp527 + _tmp364 * _tmp469 + _tmp529 + _tmp531;
  const Scalar _tmp535 = Scalar(1.0) * _tmp468;
  const Scalar _tmp536 = _tmp198 * _tmp370;
  const Scalar _tmp537 = _tmp369 * _tmp458;
  const Scalar _tmp538 = _tmp369 * _tmp462;
  const Scalar _tmp539 = -_tmp313 * _tmp371 + _tmp324 * _tmp538 + _tmp337 * _tmp536 + _tmp403 +
                         _tmp406 * _tmp473 - _tmp410 * _tmp473 + _tmp412 * _tmp473 -
                         _tmp413 * _tmp472 - _tmp518 * _tmp537;
  const Scalar _tmp540 = _tmp238 * _tmp466;
  const Scalar _tmp541 = _tmp346 * _tmp458;
  const Scalar _tmp542 = _tmp202 * _tmp463;
  const Scalar _tmp543 = _tmp327 * _tmp328;
  const Scalar _tmp544 = _tmp458 * _tmp463;
  const Scalar _tmp545 = Scalar(1.0) * _tmp198;
  const Scalar _tmp546 = _tmp351 * _tmp515;
  const Scalar _tmp547 = _tmp249 * _tmp463;
  const Scalar _tmp548 = _tmp335 * _tmp547;
  const Scalar _tmp549 = -_tmp253 * _tmp313 + _tmp324 * _tmp464 + _tmp408 * _tmp545 -
                         _tmp409 * _tmp544 - _tmp458 * _tmp546 + _tmp458 * _tmp548;
  const Scalar _tmp550 = _tmp409 * _tmp463;
  const Scalar _tmp551 = _tmp360 * _tmp466;
  const Scalar _tmp552 = _tmp198 * _tmp353;
  const Scalar _tmp553 = _tmp352 * _tmp458;
  const Scalar _tmp554 = _tmp352 * _tmp462;
  const Scalar _tmp555 = -_tmp250 * _tmp302 + _tmp311 * _tmp436 - _tmp313 * _tmp354 +
                         _tmp324 * _tmp554 + _tmp337 * _tmp552 + _tmp435 * _tmp473 +
                         _tmp444 * _tmp473 - _tmp445 * _tmp473 - _tmp446 * _tmp472 -
                         _tmp518 * _tmp553;
  const Scalar _tmp556 = _tmp237 * _tmp466;
  const Scalar _tmp557 = _tmp218 * fh1;
  const Scalar _tmp558 = _tmp475 * _tmp557;
  const Scalar _tmp559 = _tmp527 * _tmp8;
  const Scalar _tmp560 = Scalar(6.59232) * _tmp32;
  const Scalar _tmp561 = _tmp218 * _tmp469;
  const Scalar _tmp562 = _tmp40 * _tmp533;
  const Scalar _tmp563 = _tmp234 * _tmp469;
  const Scalar _tmp564 = -_tmp127 * _tmp376 - _tmp20 * _tmp528 - _tmp227 * _tmp563 - _tmp227 * fv1 +
                         _tmp233 * _tmp561 + _tmp33 * _tmp560 - _tmp559 + _tmp562;
  const Scalar _tmp565 =
      _tmp501 *
      (-_tmp452 * _tmp502 +
       _tmp457 * (_tmp240 * _tmp467 + _tmp364 * _tmp485 + _tmp375 * _tmp476 +
                  _tmp471 * (_tmp324 * _tmp542 + _tmp515 - _tmp518 * _tmp541 - _tmp543 * _tmp544) +
                  _tmp478 * (_tmp210 * _tmp515 - _tmp346 * _tmp520 - _tmp463 * _tmp508 +
                             _tmp477 * _tmp522) +
                  _tmp482 * _tmp564 - _tmp504 * _tmp506 - _tmp504 * _tmp558 +
                  _tmp526 * (-_tmp346 * _tmp525 + _tmp463 * _tmp507 + _tmp480 * _tmp522 - _tmp523 -
                             _tmp524) +
                  _tmp534 * _tmp535 +
                  _tmp540 * (-_tmp346 * _tmp539 - _tmp369 * _tmp515 + _tmp406 * _tmp463 -
                             _tmp410 * _tmp463 + _tmp412 * _tmp463 + _tmp483 * _tmp522) +
                  _tmp551 * (-_tmp346 * _tmp549 + _tmp465 * _tmp522 - _tmp546 + _tmp548 - _tmp550) +
                  _tmp556 * (-_tmp346 * _tmp555 - _tmp352 * _tmp515 + _tmp435 * _tmp463 +
                             _tmp444 * _tmp463 - _tmp445 * _tmp463 + _tmp474 * _tmp522)));
  const Scalar _tmp566 = Scalar(0.1034955) * _tmp489 * _tmp500;
  const Scalar _tmp567 = std::sinh(_tmp491);
  const Scalar _tmp568 = Scalar(0.86564762886483004) * _tmp500;
  const Scalar _tmp569 = Scalar(1.0) * std::sinh(_tmp492);
  const Scalar _tmp570 = _tmp158 * _tmp212;
  const Scalar _tmp571 =
      -_tmp213 * _tmp570 + _tmp356 * _tmp376 - _tmp361 * _tmp429 + _tmp379 * _tmp419;
  const Scalar _tmp572 = Scalar(1.0) / (_tmp571);
  const Scalar _tmp573 = _tmp202 * _tmp480;
  const Scalar _tmp574 = _tmp202 * fh1;
  const Scalar _tmp575 = _tmp238 * _tmp574;
  const Scalar _tmp576 = _tmp465 * _tmp574;
  const Scalar _tmp577 = _tmp463 * _tmp470;
  const Scalar _tmp578 = _tmp158 * _tmp202;
  const Scalar _tmp579 = _tmp474 * _tmp574;
  const Scalar _tmp580 = _tmp237 * _tmp579 + _tmp360 * _tmp576 - _tmp459 * _tmp577 +
                         _tmp477 * _tmp578 + _tmp479 * _tmp573 + _tmp483 * _tmp575;
  const Scalar _tmp581 = std::asinh(_tmp572 * _tmp580);
  const Scalar _tmp582 = Scalar(9.6622558468725703) * _tmp571;
  const Scalar _tmp583 = -_tmp165 + Scalar(-8.3196563720703107);
  const Scalar _tmp584 = -_tmp161 + Scalar(-1.9874742031097401);
  const Scalar _tmp585 =
      std::sqrt(Scalar(std::pow(_tmp583, Scalar(2)) + std::pow(_tmp584, Scalar(2))));
  const Scalar _tmp586 = -_tmp581 * _tmp582 - _tmp585;
  const Scalar _tmp587 = Scalar(0.1034955) * _tmp572;
  const Scalar _tmp588 = _tmp586 * _tmp587;
  const Scalar _tmp589 = std::sinh(_tmp588);
  const Scalar _tmp590 = 2 * _tmp584;
  const Scalar _tmp591 = _tmp129 + _tmp45;
  const Scalar _tmp592 = 2 * _tmp583;
  const Scalar _tmp593 = (Scalar(1) / Scalar(2)) / _tmp585;
  const Scalar _tmp594 = _tmp251 * _tmp361;
  const Scalar _tmp595 = _tmp189 * _tmp570;
  const Scalar _tmp596 = _tmp372 * _tmp419;
  const Scalar _tmp597 = _tmp309 * _tmp310;
  const Scalar _tmp598 = _tmp186 * _tmp570;
  const Scalar _tmp599 = _tmp379 * fh1;
  const Scalar _tmp600 = _tmp158 * _tmp211;
  const Scalar _tmp601 = _tmp337 * _tmp600;
  const Scalar _tmp602 = _tmp253 * fh1;
  const Scalar _tmp603 = _tmp360 * _tmp602;
  const Scalar _tmp604 = _tmp186 * _tmp603;
  const Scalar _tmp605 = _tmp189 * _tmp419;
  const Scalar _tmp606 = _tmp361 * _tmp426;
  const Scalar _tmp607 = _tmp355 * _tmp376;
  const Scalar _tmp608 = _tmp189 * _tmp376;
  const Scalar _tmp609 = _tmp356 * fh1;
  const Scalar _tmp610 = _tmp240 * fh1;
  const Scalar _tmp611 = _tmp213 * _tmp601 - _tmp308 * _tmp594 - _tmp308 * _tmp595 -
                         _tmp359 * _tmp609 + _tmp364 * _tmp599 + _tmp375 * _tmp609 +
                         _tmp408 * _tmp606 + _tmp417 * _tmp605 - _tmp429 * _tmp610 -
                         _tmp433 * _tmp599 + _tmp448 * _tmp608 - _tmp596 * _tmp597 +
                         _tmp597 * _tmp598 + _tmp597 * _tmp604 - _tmp597 * _tmp607;
  const Scalar _tmp612 = Scalar(9.6622558468725703) * _tmp581;
  const Scalar _tmp613 = _tmp360 * _tmp574;
  const Scalar _tmp614 = _tmp483 * _tmp574;
  const Scalar _tmp615 = _tmp419 * _tmp483;
  const Scalar _tmp616 = _tmp458 * _tmp577;
  const Scalar _tmp617 = _tmp376 * _tmp474;
  const Scalar _tmp618 = _tmp158 * _tmp477;
  const Scalar _tmp619 = _tmp328 * _tmp618;
  const Scalar _tmp620 = _tmp479 * _tmp480;
  const Scalar _tmp621 = _tmp471 * _tmp518;
  const Scalar _tmp622 = _tmp202 * _tmp479;
  const Scalar _tmp623 = _tmp237 * _tmp574;
  const Scalar _tmp624 = _tmp463 * _tmp534;
  const Scalar _tmp625 = _tmp202 * _tmp577;
  const Scalar _tmp626 = _tmp218 * _tmp579;
  const Scalar _tmp627 = _tmp361 * _tmp465;
  const Scalar _tmp628 = std::pow(_tmp571, Scalar(-2));
  const Scalar _tmp629 = _tmp580 * _tmp628;
  const Scalar _tmp630 =
      std::pow(Scalar(std::pow(_tmp580, Scalar(2)) * _tmp628 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp631 =
      _tmp630 *
      (_tmp572 * (-_tmp233 * _tmp626 + _tmp240 * _tmp576 - _tmp324 * _tmp625 - _tmp327 * _tmp619 +
                  _tmp364 * _tmp614 + _tmp375 * _tmp579 - _tmp433 * _tmp614 + _tmp459 * _tmp621 -
                  _tmp459 * _tmp624 + _tmp520 * _tmp578 + _tmp525 * _tmp622 + _tmp539 * _tmp575 -
                  _tmp543 * _tmp615 + _tmp543 * _tmp616 - _tmp543 * _tmp617 - _tmp543 * _tmp620 -
                  _tmp543 * _tmp627 + _tmp549 * _tmp613 + _tmp555 * _tmp623 + _tmp564 * _tmp573) -
       _tmp611 * _tmp629);
  const Scalar _tmp632 = Scalar(0.1034955) * _tmp586;
  const Scalar _tmp633 = _tmp628 * _tmp632;
  const Scalar _tmp634 = Scalar(1.0) * _tmp581;
  const Scalar _tmp635 = Scalar(1.0) * std::sinh(_tmp634);
  const Scalar _tmp636 = Scalar(0.87679799777269396) * _tmp628;
  const Scalar _tmp637 = Scalar(8.4718465805053746) * _tmp572 -
                         Scalar(9.6622558468725703) * std::cosh(_tmp588) +
                         Scalar(9.6622558468725703) * std::cosh(_tmp634);
  const Scalar _tmp638 = _tmp371 * fh1;
  const Scalar _tmp639 = _tmp223 * _tmp638;
  const Scalar _tmp640 = _tmp354 * fh1;
  const Scalar _tmp641 = _tmp209 * _tmp376;
  const Scalar _tmp642 = _tmp370 * _tmp419;
  const Scalar _tmp643 = _tmp209 * _tmp419;
  const Scalar _tmp644 = _tmp353 * _tmp376;
  const Scalar _tmp645 = -_tmp233 * _tmp639 + _tmp240 * _tmp602 - _tmp337 * _tmp642 -
                         _tmp337 * _tmp644 - _tmp359 * _tmp640 + _tmp364 * _tmp638 +
                         _tmp375 * _tmp640 - _tmp408 * _tmp551 + _tmp413 * _tmp643 +
                         _tmp446 * _tmp641 - _tmp601;
  const Scalar _tmp646 = _tmp354 * _tmp376 + _tmp371 * _tmp419 + _tmp570 + _tmp603;
  const Scalar _tmp647 = Scalar(1.0) / (_tmp646);
  const Scalar _tmp648 = -_tmp176 + Scalar(-8.3885017487099702);
  const Scalar _tmp649 = Scalar(2.5193355532036801) - _tmp179;
  const Scalar _tmp650 =
      std::sqrt(Scalar(std::pow(_tmp648, Scalar(2)) + std::pow(_tmp649, Scalar(2))));
  const Scalar _tmp651 = _tmp158 * _tmp462;
  const Scalar _tmp652 = _tmp210 * _tmp651 - _tmp361 * _tmp464 - _tmp376 * _tmp554 -
                         _tmp419 * _tmp538 - _tmp479 * _tmp481 + _tmp577;
  const Scalar _tmp653 = std::asinh(_tmp647 * _tmp652);
  const Scalar _tmp654 = Scalar(9.6622558468725703) * _tmp653;
  const Scalar _tmp655 = -_tmp646 * _tmp654 - _tmp650;
  const Scalar _tmp656 = Scalar(0.1034955) * _tmp647;
  const Scalar _tmp657 = _tmp655 * _tmp656;
  const Scalar _tmp658 = Scalar(1.0) * _tmp653;
  const Scalar _tmp659 = Scalar(8.4690207536792048) * _tmp647 -
                         Scalar(9.6622558468725703) * std::cosh(_tmp657) +
                         Scalar(9.6622558468725703) * std::cosh(_tmp658);
  const Scalar _tmp660 = std::pow(_tmp646, Scalar(-2));
  const Scalar _tmp661 = _tmp645 * _tmp660;
  const Scalar _tmp662 = Scalar(1.0) * std::sinh(_tmp658);
  const Scalar _tmp663 =
      std::pow(Scalar(std::pow(_tmp652, Scalar(2)) * _tmp660 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp664 = _tmp376 * _tmp462;
  const Scalar _tmp665 = _tmp538 * fh1;
  const Scalar _tmp666 = _tmp419 * _tmp462;
  const Scalar _tmp667 = _tmp352 * _tmp376;
  const Scalar _tmp668 = _tmp158 * _tmp210;
  const Scalar _tmp669 = _tmp505 * _tmp538;
  const Scalar _tmp670 = _tmp554 * _tmp557;
  const Scalar _tmp671 = _tmp554 * fh1;
  const Scalar _tmp672 = _tmp463 * _tmp622;
  const Scalar _tmp673 = _tmp369 * _tmp419;
  const Scalar _tmp674 =
      _tmp663 *
      (_tmp647 * (_tmp233 * _tmp669 + _tmp233 * _tmp670 - _tmp333 * _tmp672 + _tmp361 * _tmp546 -
                  _tmp361 * _tmp548 + _tmp361 * _tmp550 - _tmp364 * _tmp665 - _tmp375 * _tmp671 -
                  _tmp406 * _tmp666 + _tmp410 * _tmp666 - _tmp412 * _tmp666 - _tmp435 * _tmp664 -
                  _tmp444 * _tmp664 + _tmp445 * _tmp664 - _tmp464 * _tmp610 + _tmp479 * _tmp523 +
                  _tmp479 * _tmp524 - _tmp481 * _tmp564 + _tmp508 * _tmp651 + _tmp518 * _tmp667 -
                  _tmp518 * _tmp668 + _tmp518 * _tmp673 - _tmp621 + _tmp624) -
       _tmp652 * _tmp661);
  const Scalar _tmp675 = Scalar(0.1034955) * _tmp655;
  const Scalar _tmp676 = 2 * _tmp649;
  const Scalar _tmp677 = 2 * _tmp648;
  const Scalar _tmp678 = (Scalar(1) / Scalar(2)) / _tmp650;
  const Scalar _tmp679 = Scalar(9.6622558468725703) * _tmp646;
  const Scalar _tmp680 = std::sinh(_tmp657);
  const Scalar _tmp681 = -_tmp13 + _tmp15 - _tmp17 - _tmp19;
  const Scalar _tmp682 = Scalar(0.41999999999999998) * _tmp681;
  const Scalar _tmp683 = _tmp682 * _tmp9;
  const Scalar _tmp684 = _tmp40 * _tmp54;
  const Scalar _tmp685 = _tmp683 + _tmp684;
  const Scalar _tmp686 = _tmp57 * _tmp8;
  const Scalar _tmp687 = -_tmp25 + _tmp27 + _tmp29 + _tmp31;
  const Scalar _tmp688 = _tmp59 * _tmp687;
  const Scalar _tmp689 = _tmp686 + _tmp688;
  const Scalar _tmp690 = _tmp685 + _tmp689;
  const Scalar _tmp691 = _tmp48 * _tmp687;
  const Scalar _tmp692 = _tmp46 * _tmp681;
  const Scalar _tmp693 = _tmp691 + _tmp692;
  const Scalar _tmp694 = _tmp10 * _tmp687;
  const Scalar _tmp695 = _tmp42 * _tmp681;
  const Scalar _tmp696 = _tmp143 + _tmp694 - _tmp695 + _tmp80;
  const Scalar _tmp697 = _tmp693 + _tmp696;
  const Scalar _tmp698 = _tmp22 * _tmp681;
  const Scalar _tmp699 = _tmp34 * _tmp687;
  const Scalar _tmp700 = _tmp11 + _tmp43 + _tmp698 + _tmp699;
  const Scalar _tmp701 = -_tmp684;
  const Scalar _tmp702 = -_tmp683;
  const Scalar _tmp703 = _tmp701 + _tmp702;
  const Scalar _tmp704 = _tmp689 + _tmp703;
  const Scalar _tmp705 = -_tmp691;
  const Scalar _tmp706 = _tmp319 + _tmp705;
  const Scalar _tmp707 = _tmp704 + _tmp706;
  const Scalar _tmp708 = _tmp52 * _tmp687;
  const Scalar _tmp709 = _tmp41 * _tmp682;
  const Scalar _tmp710 = _tmp708 + _tmp709;
  const Scalar _tmp711 = _tmp21 * _tmp682;
  const Scalar _tmp712 = -_tmp711;
  const Scalar _tmp713 = _tmp54 * _tmp687;
  const Scalar _tmp714 = -_tmp713;
  const Scalar _tmp715 = _tmp121 * _tmp40;
  const Scalar _tmp716 = _tmp123 * _tmp681;
  const Scalar _tmp717 = _tmp715 + _tmp716;
  const Scalar _tmp718 = _tmp119 + _tmp712 + _tmp714 + _tmp717;
  const Scalar _tmp719 = _tmp269 + _tmp710 + _tmp718;
  const Scalar _tmp720 = _tmp144 - _tmp694 + _tmp695 + _tmp82;
  const Scalar _tmp721 = -_tmp692 + _tmp705;
  const Scalar _tmp722 = -_tmp686 - _tmp688;
  const Scalar _tmp723 = _tmp703 + _tmp722;
  const Scalar _tmp724 = _tmp721 + _tmp723;
  const Scalar _tmp725 = _tmp720 + _tmp724;
  const Scalar _tmp726 = _tmp318 + _tmp691;
  const Scalar _tmp727 = _tmp685 + _tmp722;
  const Scalar _tmp728 = _tmp726 + _tmp727;
  const Scalar _tmp729 = _tmp130 + _tmp44 - _tmp698 - _tmp699;
  const Scalar _tmp730 = _tmp728 + _tmp729;
  const Scalar _tmp731 = _tmp224 * _tmp730 + _tmp228 * _tmp725;
  const Scalar _tmp732 = _tmp232 * _tmp731;
  const Scalar _tmp733 = -_tmp376 * _tmp719 - _tmp527 * _tmp687 - _tmp529 + _tmp531 +
                         _tmp533 * _tmp681 + _tmp561 * _tmp732 - _tmp563 * _tmp725 - _tmp725 * fv1;
  const Scalar _tmp734 = _tmp321 * _tmp687;
  const Scalar _tmp735 = _tmp323 * _tmp681 + _tmp734;
  const Scalar _tmp736 = _tmp205 * _tmp735;
  const Scalar _tmp737 = _tmp681 * _tmp86;
  const Scalar _tmp738 = -_tmp325 * _tmp687 + _tmp85;
  const Scalar _tmp739 = _tmp47 + _tmp737 + _tmp738;
  const Scalar _tmp740 = -_tmp331 * _tmp40 - _tmp734 + _tmp739;
  const Scalar _tmp741 = _tmp459 * _tmp740;
  const Scalar _tmp742 = _tmp128 + _tmp735 - _tmp737 + _tmp738;
  const Scalar _tmp743 = _tmp329 * _tmp742;
  const Scalar _tmp744 = _tmp458 * _tmp743;
  const Scalar _tmp745 = -_tmp736 + _tmp739 - _tmp741 + _tmp744;
  const Scalar _tmp746 = _tmp514 * _tmp745;
  const Scalar _tmp747 = _tmp351 * _tmp746;
  const Scalar _tmp748 = _tmp704 + _tmp726;
  const Scalar _tmp749 = _tmp729 + _tmp748;
  const Scalar _tmp750 = _tmp693 + _tmp720;
  const Scalar _tmp751 = _tmp723 + _tmp750;
  const Scalar _tmp752 = _tmp290 * _tmp751 + _tmp291 * _tmp749;
  const Scalar _tmp753 = _tmp295 * _tmp752;
  const Scalar _tmp754 = _tmp168 * _tmp749;
  const Scalar _tmp755 = _tmp297 * _tmp752;
  const Scalar _tmp756 = _tmp690 + _tmp721;
  const Scalar _tmp757 = _tmp720 + _tmp756;
  const Scalar _tmp758 = _tmp152 * _tmp757;
  const Scalar _tmp759 = _tmp168 * _tmp751;
  const Scalar _tmp760 = _tmp706 + _tmp727;
  const Scalar _tmp761 = _tmp729 + _tmp760;
  const Scalar _tmp762 = _tmp275 * _tmp761;
  const Scalar _tmp763 = _tmp169 * _tmp758 - _tmp169 * _tmp762 - _tmp185 * _tmp753 +
                         _tmp185 * _tmp754 + _tmp755 - _tmp759;
  const Scalar _tmp764 = _tmp138 * _tmp757 + _tmp150 * _tmp761;
  const Scalar _tmp765 = _tmp383 * _tmp764;
  const Scalar _tmp766 = _tmp156 * _tmp761;
  const Scalar _tmp767 = _tmp245 * (-_tmp135 * _tmp766 + _tmp137 * _tmp766 + _tmp242 * _tmp757 -
                                    _tmp385 * _tmp765 + _tmp386 * _tmp765 - _tmp388 * _tmp757);
  const Scalar _tmp768 = _tmp391 * _tmp761;
  const Scalar _tmp769 = _tmp393 * _tmp764;
  const Scalar _tmp770 = _tmp160 * _tmp755 - _tmp160 * _tmp759 + _tmp162 * _tmp759 -
                         _tmp164 * _tmp753 + _tmp169 * _tmp767 - _tmp169 * _tmp768 +
                         _tmp169 * _tmp769 - _tmp187 * _tmp749 + _tmp241 * _tmp749 -
                         _tmp246 * _tmp753 + _tmp246 * _tmp754;
  const Scalar _tmp771 = _tmp690 + _tmp750;
  const Scalar _tmp772 = _tmp182 * _tmp771;
  const Scalar _tmp773 = _tmp707 + _tmp729;
  const Scalar _tmp774 = _tmp260 * _tmp771 + _tmp262 * _tmp773;
  const Scalar _tmp775 = _tmp305 * _tmp774;
  const Scalar _tmp776 = _tmp182 * _tmp773;
  const Scalar _tmp777 = _tmp266 * _tmp774;
  const Scalar _tmp778 = _tmp183 * _tmp758 - _tmp183 * _tmp762 + _tmp185 * _tmp776 -
                         _tmp185 * _tmp777 - _tmp772 + _tmp775;
  const Scalar _tmp779 = _tmp175 * _tmp776 - _tmp175 * _tmp777 - _tmp178 * _tmp772 +
                         _tmp178 * _tmp775 + _tmp180 * _tmp772 + _tmp183 * _tmp767 -
                         _tmp183 * _tmp768 + _tmp183 * _tmp769 - _tmp184 * _tmp773 -
                         _tmp213 * _tmp770 + _tmp246 * _tmp776 - _tmp246 * _tmp777 -
                         _tmp367 * _tmp778 + _tmp398 * _tmp763;
  const Scalar _tmp780 = _tmp208 * _tmp407;
  const Scalar _tmp781 = _tmp779 * _tmp780;
  const Scalar _tmp782 = _tmp463 * _tmp781;
  const Scalar _tmp783 = _tmp407 * _tmp545;
  const Scalar _tmp784 = -_tmp708 - _tmp709;
  const Scalar _tmp785 = _tmp279 + _tmp711 + _tmp713 + _tmp717;
  const Scalar _tmp786 = _tmp283 + _tmp784 + _tmp785;
  const Scalar _tmp787 = _tmp113 + _tmp784;
  const Scalar _tmp788 = _tmp718 + _tmp787;
  const Scalar _tmp789 = _tmp193 * _tmp754;
  const Scalar _tmp790 = _tmp303 + _tmp710 + _tmp785;
  const Scalar _tmp791 = _tmp185 * _tmp790;
  const Scalar _tmp792 = -_tmp169 * _tmp791 - _tmp185 * _tmp789 + _tmp187 * _tmp788 -
                         _tmp191 * _tmp755 + _tmp191 * _tmp759 - _tmp194 * _tmp758 +
                         _tmp194 * _tmp762 + _tmp257 * _tmp753;
  const Scalar _tmp793 = _tmp193 * _tmp776;
  const Scalar _tmp794 = _tmp174 * _tmp772 - _tmp174 * _tmp775 - _tmp183 * _tmp791 +
                         _tmp184 * _tmp786 - _tmp185 * _tmp793 - _tmp196 * _tmp778 -
                         _tmp197 * _tmp758 + _tmp197 * _tmp762 - _tmp213 * _tmp792 +
                         _tmp257 * _tmp777 + _tmp312 * _tmp763;
  const Scalar _tmp795 = -_tmp169 * _tmp788 + _tmp169 * _tmp790 + _tmp191 * _tmp753 -
                         _tmp191 * _tmp754 - _tmp193 * _tmp753 + _tmp789;
  const Scalar _tmp796 = _tmp174 * _tmp777 - _tmp183 * _tmp786 + _tmp183 * _tmp790 -
                         _tmp193 * _tmp777 + _tmp198 * _tmp743 - _tmp205 * _tmp794 -
                         _tmp207 * _tmp778 - _tmp213 * _tmp795 + _tmp315 * _tmp763 -
                         _tmp316 * _tmp773 - _tmp334 * _tmp740 + _tmp793;
  const Scalar _tmp797 = _tmp547 * _tmp796;
  const Scalar _tmp798 = -_tmp253 * _tmp794 - _tmp458 * _tmp747 - _tmp458 * _tmp782 +
                         _tmp458 * _tmp797 + _tmp464 * _tmp735 + _tmp779 * _tmp783;
  const Scalar _tmp799 = _tmp521 * _tmp742;
  const Scalar _tmp800 = _tmp503 * _tmp731;
  const Scalar _tmp801 = -_tmp219 * _tmp732 + _tmp235 * _tmp725 + _tmp236 * _tmp732 +
                         _tmp237 * _tmp730 - _tmp238 * _tmp725 - _tmp239 * _tmp730;
  const Scalar _tmp802 = _tmp513 * _tmp745;
  const Scalar _tmp803 = _tmp347 * _tmp802;
  const Scalar _tmp804 =
      -_tmp458 * _tmp803 + _tmp463 * _tmp736 + _tmp463 * _tmp741 - _tmp463 * _tmp744;
  const Scalar _tmp805 = _tmp463 * _tmp743;
  const Scalar _tmp806 = _tmp234 * _tmp730;
  const Scalar _tmp807 = _tmp368 * _tmp781;
  const Scalar _tmp808 = _tmp336 * _tmp796;
  const Scalar _tmp809 = _tmp185 * _tmp763;
  const Scalar _tmp810 = _tmp193 * _tmp758 - _tmp193 * _tmp762 + _tmp196 * _tmp758 -
                         _tmp196 * _tmp762 - _tmp311 * _tmp809 + _tmp396 * _tmp792 + _tmp791;
  const Scalar _tmp811 = _tmp119 - _tmp205 * _tmp810 + _tmp207 * _tmp758 - _tmp207 * _tmp762 -
                         _tmp314 * _tmp809 + _tmp365 * _tmp743 + _tmp396 * _tmp795 -
                         _tmp401 * _tmp740 + _tmp712 + _tmp714 - _tmp715 - _tmp716 + _tmp787;
  const Scalar _tmp812 = _tmp351 * (-_tmp349 * _tmp811 + _tmp367 * _tmp758 - _tmp367 * _tmp762 +
                                    _tmp382 * _tmp808 + _tmp396 * _tmp770 - _tmp397 * _tmp809 -
                                    _tmp400 * _tmp779 - _tmp767 + _tmp768 - _tmp769);
  const Scalar _tmp813 = _tmp411 * _tmp796;
  const Scalar _tmp814 = -_tmp807 + _tmp811 + _tmp812 + _tmp813;
  const Scalar _tmp815 = -_tmp371 * _tmp794 - _tmp472 * _tmp814 - _tmp473 * _tmp807 +
                         _tmp473 * _tmp812 + _tmp473 * _tmp813 + _tmp536 * _tmp808 -
                         _tmp537 * _tmp802 + _tmp538 * _tmp735 + _tmp810;
  const Scalar _tmp816 = _tmp350 * _tmp781;
  const Scalar _tmp817 = _tmp434 * _tmp796;
  const Scalar _tmp818 = Scalar(1.0) * _tmp763;
  const Scalar _tmp819 = -_tmp250 * _tmp795 + _tmp314 * _tmp818 - _tmp438 * _tmp763 +
                         _tmp439 * _tmp792 - _tmp440 * _tmp743 + _tmp441 * _tmp740;
  const Scalar _tmp820 = _tmp351 * (-_tmp250 * _tmp770 - _tmp349 * _tmp819 + _tmp397 * _tmp818 -
                                    _tmp437 * _tmp779 + _tmp443 * _tmp808);
  const Scalar _tmp821 = -_tmp816 + _tmp817 + _tmp819 + _tmp820;
  const Scalar _tmp822 = -_tmp250 * _tmp792 + _tmp311 * _tmp818 - _tmp354 * _tmp794 -
                         _tmp472 * _tmp821 - _tmp473 * _tmp816 + _tmp473 * _tmp817 +
                         _tmp473 * _tmp820 + _tmp552 * _tmp808 - _tmp553 * _tmp802 +
                         _tmp554 * _tmp735;
  const Scalar _tmp823 = _tmp328 * _tmp742;
  const Scalar _tmp824 = _tmp199 * _tmp202;
  const Scalar _tmp825 = -_tmp199 * _tmp743 + _tmp347 * _tmp757 + _tmp740 * _tmp824 + _tmp761;
  const Scalar _tmp826 = _tmp697 + _tmp723;
  const Scalar _tmp827 = -_tmp212 * _tmp794 - _tmp473 * _tmp825 + _tmp516 * _tmp808 -
                         _tmp517 * _tmp735 + _tmp519 * _tmp802 + _tmp826;
  const Scalar _tmp828 = _tmp234 * _tmp725;
  const Scalar _tmp829 = _tmp419 * _tmp719 + _tmp528 * _tmp681 + _tmp530 * _tmp687 -
                         _tmp532 * _tmp732 + _tmp559 + _tmp562 + _tmp563 * _tmp730 + _tmp730 * fv1;
  const Scalar _tmp830 = _tmp218 * _tmp732;
  const Scalar _tmp831 = -_tmp354 * _tmp778 - _tmp414 * _tmp821 + _tmp447 * _tmp796;
  const Scalar _tmp832 = _tmp407 * _tmp779;
  const Scalar _tmp833 = _tmp426 * _tmp832;
  const Scalar _tmp834 = _tmp390 * _tmp761;
  const Scalar _tmp835 = _tmp216 * _tmp390;
  const Scalar _tmp836 = _tmp223 * _tmp732;
  const Scalar _tmp837 =
      -_tmp371 * _tmp778 - _tmp414 * _tmp814 + _tmp416 * _tmp796 - _tmp758 + _tmp762;
  const Scalar _tmp838 =
      -_tmp217 * _tmp764 - _tmp256 * _tmp801 -
      _tmp345 * (_tmp212 * _tmp776 - _tmp212 * _tmp777 + _tmp214 * _tmp753 - _tmp214 * _tmp754 +
                 _tmp338 * _tmp808 - _tmp339 * _tmp808 - _tmp341 * _tmp778 + _tmp344 * _tmp763) -
      _tmp358 * _tmp828 + _tmp358 * _tmp830 + _tmp362 * _tmp834 - _tmp363 * _tmp764 -
      _tmp374 * _tmp806 + _tmp374 * _tmp836 + _tmp377 * _tmp834 - _tmp378 * _tmp764 -
      _tmp420 * (_tmp340 * _tmp837 + _tmp371 * _tmp776 - _tmp371 * _tmp777 - _tmp379 * _tmp753 +
                 _tmp379 * _tmp754 - _tmp380 * _tmp808 - _tmp381 * _tmp763 + _tmp418 * _tmp814) -
      _tmp430 * (_tmp169 * _tmp833 - _tmp252 * _tmp778 + _tmp253 * _tmp776 + _tmp423 * _tmp752 +
                 _tmp424 * _tmp763 - _tmp425 * _tmp832 - _tmp428 * _tmp774 - _tmp429 * _tmp754) +
      _tmp431 * _tmp834 - _tmp432 * _tmp764 -
      _tmp451 * (_tmp340 * _tmp831 + _tmp354 * _tmp776 - _tmp354 * _tmp777 - _tmp356 * _tmp753 +
                 _tmp356 * _tmp754 + _tmp418 * _tmp821 - _tmp449 * _tmp763 - _tmp450 * _tmp808) +
      _tmp761 * _tmp835;
  const Scalar _tmp839 =
      _tmp457 * (_tmp467 * _tmp801 +
                 _tmp471 * (-_tmp541 * _tmp802 + _tmp542 * _tmp735 - _tmp544 * _tmp823 + _tmp746) +
                 _tmp476 * _tmp828 +
                 _tmp478 * (_tmp210 * _tmp746 - _tmp346 * _tmp827 - _tmp463 * _tmp825 +
                            _tmp477 * _tmp799) +
                 _tmp482 * _tmp733 + _tmp485 * _tmp806 - _tmp506 * _tmp800 +
                 _tmp526 * (-_tmp346 * _tmp804 + _tmp480 * _tmp799 + _tmp542 * _tmp740 - _tmp803 -
                            _tmp805) +
                 _tmp535 * _tmp829 +
                 _tmp540 * (-_tmp346 * _tmp815 - _tmp369 * _tmp746 - _tmp463 * _tmp807 +
                            _tmp463 * _tmp812 + _tmp463 * _tmp813 + _tmp483 * _tmp799) +
                 _tmp551 * (-_tmp346 * _tmp798 + _tmp465 * _tmp799 - _tmp747 - _tmp782 + _tmp797) +
                 _tmp556 * (-_tmp346 * _tmp822 - _tmp352 * _tmp746 - _tmp463 * _tmp816 +
                            _tmp463 * _tmp817 + _tmp463 * _tmp820 + _tmp474 * _tmp799) -
                 _tmp558 * _tmp800) -
      _tmp502 * _tmp838;
  const Scalar _tmp840 = _tmp501 * _tmp569;
  const Scalar _tmp841 = _tmp499 * _tmp501;
  const Scalar _tmp842 = _tmp310 * _tmp763;
  const Scalar _tmp843 = _tmp600 * _tmp808;
  const Scalar _tmp844 = _tmp801 * fh1;
  const Scalar _tmp845 = _tmp213 * _tmp843 + _tmp361 * _tmp833 - _tmp429 * _tmp844 -
                         _tmp594 * _tmp778 - _tmp595 * _tmp778 - _tmp596 * _tmp842 +
                         _tmp598 * _tmp842 + _tmp599 * _tmp806 - _tmp599 * _tmp836 +
                         _tmp604 * _tmp842 + _tmp605 * _tmp837 - _tmp607 * _tmp842 +
                         _tmp608 * _tmp831 + _tmp609 * _tmp828 - _tmp609 * _tmp830;
  const Scalar _tmp846 = _tmp628 * _tmp845;
  const Scalar _tmp847 = _tmp471 * _tmp802;
  const Scalar _tmp848 = _tmp463 * _tmp829;
  const Scalar _tmp849 =
      _tmp630 *
      (_tmp572 * (_tmp459 * _tmp847 - _tmp459 * _tmp848 + _tmp573 * _tmp733 + _tmp575 * _tmp815 +
                  _tmp576 * _tmp801 + _tmp578 * _tmp827 + _tmp579 * _tmp828 + _tmp613 * _tmp798 +
                  _tmp614 * _tmp806 - _tmp614 * _tmp836 - _tmp615 * _tmp823 + _tmp616 * _tmp823 -
                  _tmp617 * _tmp823 - _tmp619 * _tmp742 - _tmp620 * _tmp823 + _tmp622 * _tmp804 +
                  _tmp623 * _tmp822 - _tmp625 * _tmp735 - _tmp626 * _tmp732 - _tmp627 * _tmp823) -
       _tmp580 * _tmp846);
  const Scalar _tmp850 = -_tmp551 * _tmp832 + _tmp602 * _tmp801 + _tmp638 * _tmp806 -
                         _tmp639 * _tmp732 + _tmp640 * _tmp828 - _tmp640 * _tmp830 +
                         _tmp641 * _tmp821 - _tmp642 * _tmp808 + _tmp643 * _tmp814 -
                         _tmp644 * _tmp808 - _tmp843;
  const Scalar _tmp851 = _tmp660 * _tmp850;
  const Scalar _tmp852 =
      _tmp663 *
      (_tmp647 * (_tmp361 * _tmp747 + _tmp361 * _tmp782 - _tmp361 * _tmp797 - _tmp464 * _tmp844 +
                  _tmp479 * _tmp803 + _tmp479 * _tmp805 - _tmp481 * _tmp733 + _tmp651 * _tmp825 +
                  _tmp664 * _tmp816 - _tmp664 * _tmp817 - _tmp664 * _tmp820 - _tmp665 * _tmp806 +
                  _tmp666 * _tmp807 - _tmp666 * _tmp812 - _tmp666 * _tmp813 + _tmp667 * _tmp802 -
                  _tmp668 * _tmp802 + _tmp669 * _tmp732 + _tmp670 * _tmp732 - _tmp671 * _tmp828 -
                  _tmp672 * _tmp740 + _tmp673 * _tmp802 - _tmp847 + _tmp848) -
       _tmp652 * _tmp851);
  const Scalar _tmp853 = _tmp1 + _tmp3 - _tmp5 + _tmp7;
  const Scalar _tmp854 = _tmp52 * _tmp853;
  const Scalar _tmp855 = -_tmp854;
  const Scalar _tmp856 = _tmp119 + _tmp278 + _tmp711 + _tmp855;
  const Scalar _tmp857 = _tmp40 * _tmp48;
  const Scalar _tmp858 = -_tmp857;
  const Scalar _tmp859 = _tmp32 * _tmp86;
  const Scalar _tmp860 = _tmp858 - _tmp859;
  const Scalar _tmp861 = _tmp10 * _tmp681;
  const Scalar _tmp862 = _tmp22 * _tmp853;
  const Scalar _tmp863 = _tmp34 * _tmp40;
  const Scalar _tmp864 = _tmp32 * _tmp42;
  const Scalar _tmp865 = _tmp861 + _tmp862 + _tmp863 + _tmp864;
  const Scalar _tmp866 = _tmp860 + _tmp865;
  const Scalar _tmp867 = _tmp10 * _tmp40;
  const Scalar _tmp868 = _tmp22 * _tmp32;
  const Scalar _tmp869 = _tmp34 * _tmp681;
  const Scalar _tmp870 = _tmp42 * _tmp853;
  const Scalar _tmp871 = _tmp867 + _tmp868 - _tmp869 - _tmp870;
  const Scalar _tmp872 = _tmp120 + _tmp711 + _tmp854;
  const Scalar _tmp873 = _tmp46 * _tmp853;
  const Scalar _tmp874 = _tmp857 + _tmp873;
  const Scalar _tmp875 = _tmp872 + _tmp874;
  const Scalar _tmp876 = _tmp57 * _tmp853;
  const Scalar _tmp877 = _tmp32 * _tmp59;
  const Scalar _tmp878 = _tmp683 + _tmp701 - _tmp876 + _tmp877;
  const Scalar _tmp879 = _tmp54 * _tmp681;
  const Scalar _tmp880 = _tmp59 * _tmp853;
  const Scalar _tmp881 = _tmp121 * _tmp32;
  const Scalar _tmp882 = _tmp123 * _tmp853;
  const Scalar _tmp883 = _tmp881 + _tmp882;
  const Scalar _tmp884 = _tmp53 + _tmp58 + _tmp879 + _tmp880 + _tmp883;
  const Scalar _tmp885 = _tmp878 + _tmp884;
  const Scalar _tmp886 = -_tmp861 - _tmp862 - _tmp863 - _tmp864;
  const Scalar _tmp887 = _tmp860 + _tmp886;
  const Scalar _tmp888 = _tmp118 + _tmp279 + _tmp712 + _tmp854;
  const Scalar _tmp889 = _tmp887 + _tmp888;
  const Scalar _tmp890 = _tmp390 * _tmp889;
  const Scalar _tmp891 = _tmp858 - _tmp873;
  const Scalar _tmp892 = -_tmp867 - _tmp868 + _tmp869 + _tmp870;
  const Scalar _tmp893 = _tmp891 + _tmp892;
  const Scalar _tmp894 = _tmp872 + _tmp893;
  const Scalar _tmp895 = _tmp138 * _tmp894 + _tmp150 * _tmp889;
  const Scalar _tmp896 = _tmp280 + _tmp712 + _tmp855;
  const Scalar _tmp897 = _tmp893 + _tmp896;
  const Scalar _tmp898 = _tmp234 * _tmp897;
  const Scalar _tmp899 = _tmp857 + _tmp859;
  const Scalar _tmp900 = _tmp886 + _tmp899;
  const Scalar _tmp901 = _tmp888 + _tmp900;
  const Scalar _tmp902 = _tmp234 * _tmp901;
  const Scalar _tmp903 = _tmp224 * _tmp901 + _tmp228 * _tmp897;
  const Scalar _tmp904 = _tmp232 * _tmp903;
  const Scalar _tmp905 = _tmp102 * _tmp898 + _tmp218 * _tmp902 - _tmp219 * _tmp904 -
                         _tmp223 * _tmp898 + _tmp236 * _tmp904 - _tmp76 * _tmp902;
  const Scalar _tmp906 = _tmp393 * _tmp895;
  const Scalar _tmp907 = _tmp856 + _tmp900;
  const Scalar _tmp908 = _tmp168 * _tmp907;
  const Scalar _tmp909 = _tmp383 * _tmp895;
  const Scalar _tmp910 = _tmp245 * (_tmp242 * _tmp894 - _tmp243 * _tmp889 - _tmp385 * _tmp909 +
                                    _tmp386 * _tmp909 + _tmp387 * _tmp889 - _tmp388 * _tmp894);
  const Scalar _tmp911 = _tmp391 * _tmp889;
  const Scalar _tmp912 = _tmp874 + _tmp896;
  const Scalar _tmp913 = _tmp892 + _tmp912;
  const Scalar _tmp914 = _tmp290 * _tmp913 + _tmp291 * _tmp907;
  const Scalar _tmp915 = _tmp297 * _tmp914;
  const Scalar _tmp916 = _tmp168 * _tmp913;
  const Scalar _tmp917 = _tmp295 * _tmp914;
  const Scalar _tmp918 = _tmp160 * _tmp915 - _tmp160 * _tmp916 + _tmp162 * _tmp916 -
                         _tmp164 * _tmp917 + _tmp169 * _tmp906 + _tmp169 * _tmp910 -
                         _tmp169 * _tmp911 - _tmp187 * _tmp907 + _tmp241 * _tmp907 +
                         _tmp246 * _tmp908 - _tmp246 * _tmp917;
  const Scalar _tmp919 = _tmp275 * _tmp889;
  const Scalar _tmp920 = _tmp152 * _tmp894;
  const Scalar _tmp921 = -_tmp169 * _tmp919 + _tmp169 * _tmp920 + _tmp185 * _tmp908 -
                         _tmp185 * _tmp917 + _tmp915 - _tmp916;
  const Scalar _tmp922 = _tmp856 + _tmp887;
  const Scalar _tmp923 = _tmp182 * _tmp922;
  const Scalar _tmp924 = _tmp875 + _tmp892;
  const Scalar _tmp925 = _tmp182 * _tmp924;
  const Scalar _tmp926 = _tmp260 * _tmp924 + _tmp262 * _tmp922;
  const Scalar _tmp927 = _tmp305 * _tmp926;
  const Scalar _tmp928 = _tmp266 * _tmp926;
  const Scalar _tmp929 = -_tmp183 * _tmp919 + _tmp183 * _tmp920 + _tmp185 * _tmp923 -
                         _tmp185 * _tmp928 - _tmp925 + _tmp927;
  const Scalar _tmp930 = _tmp175 * _tmp923 - _tmp175 * _tmp928 - _tmp178 * _tmp925 +
                         _tmp178 * _tmp927 + _tmp180 * _tmp925 + _tmp183 * _tmp906 +
                         _tmp183 * _tmp910 - _tmp183 * _tmp911 - _tmp184 * _tmp922 -
                         _tmp213 * _tmp918 + _tmp246 * _tmp923 - _tmp246 * _tmp928 -
                         _tmp367 * _tmp929 + _tmp398 * _tmp921;
  const Scalar _tmp931 = _tmp407 * _tmp930;
  const Scalar _tmp932 = _tmp251 * _tmp929;
  const Scalar _tmp933 = _tmp218 * _tmp904;
  const Scalar _tmp934 = -_tmp879;
  const Scalar _tmp935 = -_tmp880;
  const Scalar _tmp936 = _tmp225 + _tmp883 + _tmp934 + _tmp935;
  const Scalar _tmp937 = _tmp684 + _tmp702 + _tmp876 - _tmp877;
  const Scalar _tmp938 = _tmp936 + _tmp937;
  const Scalar _tmp939 = _tmp884 + _tmp937;
  const Scalar _tmp940 = _tmp183 * _tmp939;
  const Scalar _tmp941 = _tmp193 * _tmp923;
  const Scalar _tmp942 = _tmp169 * _tmp939;
  const Scalar _tmp943 = _tmp193 * _tmp908;
  const Scalar _tmp944 = _tmp878 + _tmp936;
  const Scalar _tmp945 = -_tmp185 * _tmp942 - _tmp185 * _tmp943 + _tmp187 * _tmp944 -
                         _tmp191 * _tmp915 + _tmp191 * _tmp916 + _tmp194 * _tmp919 -
                         _tmp194 * _tmp920 + _tmp257 * _tmp917;
  const Scalar _tmp946 = _tmp174 * _tmp925 - _tmp174 * _tmp927 + _tmp184 * _tmp938 -
                         _tmp185 * _tmp940 - _tmp185 * _tmp941 - _tmp196 * _tmp929 +
                         _tmp197 * _tmp919 - _tmp197 * _tmp920 - _tmp213 * _tmp945 +
                         _tmp257 * _tmp928 + _tmp312 * _tmp921;
  const Scalar _tmp947 = -_tmp169 * _tmp944 - _tmp191 * _tmp908 + _tmp191 * _tmp917 -
                         _tmp193 * _tmp917 + _tmp942 + _tmp943;
  const Scalar _tmp948 = _tmp321 * _tmp40;
  const Scalar _tmp949 = _tmp853 * _tmp86;
  const Scalar _tmp950 = _tmp32 * _tmp46;
  const Scalar _tmp951 = -_tmp325 * _tmp40 - _tmp48 * _tmp681;
  const Scalar _tmp952 = _tmp949 + _tmp950 + _tmp951;
  const Scalar _tmp953 = -_tmp32 * _tmp331 - _tmp948 + _tmp952;
  const Scalar _tmp954 = _tmp323 * _tmp853 + _tmp948;
  const Scalar _tmp955 = -_tmp949 - _tmp950 + _tmp951 + _tmp954;
  const Scalar _tmp956 = _tmp329 * _tmp955;
  const Scalar _tmp957 = -_tmp174 * _tmp923 + _tmp174 * _tmp928 - _tmp183 * _tmp938 -
                         _tmp193 * _tmp928 + _tmp198 * _tmp956 - _tmp205 * _tmp946 -
                         _tmp207 * _tmp929 - _tmp213 * _tmp947 + _tmp315 * _tmp921 -
                         _tmp334 * _tmp953 + _tmp940 + _tmp941;
  const Scalar _tmp958 = _tmp336 * _tmp957;
  const Scalar _tmp959 = _tmp780 * _tmp930;
  const Scalar _tmp960 = _tmp368 * _tmp959;
  const Scalar _tmp961 = _tmp185 * _tmp921;
  const Scalar _tmp962 = _tmp185 * _tmp939 - _tmp193 * _tmp919 + _tmp193 * _tmp920 -
                         _tmp196 * _tmp919 + _tmp196 * _tmp920 + _tmp396 * _tmp945 -
                         _tmp402 * _tmp921;
  const Scalar _tmp963 = -_tmp205 * _tmp962 - _tmp207 * _tmp919 + _tmp207 * _tmp920 + _tmp225 -
                         _tmp314 * _tmp961 + _tmp365 * _tmp956 + _tmp396 * _tmp947 -
                         _tmp401 * _tmp953 + _tmp878 - _tmp881 - _tmp882 + _tmp934 + _tmp935;
  const Scalar _tmp964 = _tmp351 * (-_tmp349 * _tmp963 - _tmp367 * _tmp919 + _tmp367 * _tmp920 +
                                    _tmp382 * _tmp958 + _tmp396 * _tmp918 - _tmp397 * _tmp961 -
                                    _tmp400 * _tmp930 - _tmp906 - _tmp910 + _tmp911);
  const Scalar _tmp965 = _tmp411 * _tmp957;
  const Scalar _tmp966 = -_tmp960 + _tmp963 + _tmp964 + _tmp965;
  const Scalar _tmp967 =
      -_tmp371 * _tmp929 - _tmp414 * _tmp966 + _tmp416 * _tmp957 + _tmp919 - _tmp920;
  const Scalar _tmp968 = _tmp350 * _tmp959;
  const Scalar _tmp969 = _tmp434 * _tmp957;
  const Scalar _tmp970 = Scalar(1.0) * _tmp921;
  const Scalar _tmp971 = -_tmp250 * _tmp947 + _tmp314 * _tmp970 - _tmp438 * _tmp921 +
                         _tmp439 * _tmp945 - _tmp440 * _tmp956 + _tmp441 * _tmp953;
  const Scalar _tmp972 = _tmp351 * (-_tmp250 * _tmp918 - _tmp349 * _tmp971 + _tmp397 * _tmp970 -
                                    _tmp437 * _tmp930 + _tmp443 * _tmp958);
  const Scalar _tmp973 = -_tmp968 + _tmp969 + _tmp971 + _tmp972;
  const Scalar _tmp974 = -_tmp354 * _tmp929 - _tmp414 * _tmp973 + _tmp447 * _tmp957;
  const Scalar _tmp975 = _tmp223 * _tmp904;
  const Scalar _tmp976 =
      -_tmp217 * _tmp895 - _tmp256 * _tmp905 -
      _tmp345 * (_tmp212 * _tmp923 - _tmp212 * _tmp928 - _tmp214 * _tmp908 + _tmp214 * _tmp917 +
                 _tmp338 * _tmp958 - _tmp339 * _tmp958 - _tmp341 * _tmp929 + _tmp344 * _tmp921) -
      _tmp358 * _tmp898 + _tmp358 * _tmp933 + _tmp362 * _tmp890 - _tmp363 * _tmp895 -
      _tmp374 * _tmp902 + _tmp374 * _tmp975 + _tmp377 * _tmp890 - _tmp378 * _tmp895 -
      _tmp420 * (_tmp340 * _tmp967 + _tmp371 * _tmp923 - _tmp371 * _tmp928 + _tmp379 * _tmp908 -
                 _tmp379 * _tmp917 - _tmp380 * _tmp958 - _tmp381 * _tmp921 + _tmp418 * _tmp966) -
      _tmp430 * (-_tmp169 * _tmp932 + _tmp253 * _tmp923 + _tmp423 * _tmp914 + _tmp424 * _tmp921 -
                 _tmp425 * _tmp931 + _tmp427 * _tmp931 - _tmp428 * _tmp926 - _tmp429 * _tmp908) +
      _tmp431 * _tmp890 - _tmp432 * _tmp895 -
      _tmp451 * (_tmp340 * _tmp974 + _tmp354 * _tmp923 - _tmp354 * _tmp928 + _tmp356 * _tmp908 -
                 _tmp356 * _tmp917 + _tmp418 * _tmp973 - _tmp449 * _tmp921 - _tmp450 * _tmp958) +
      _tmp835 * _tmp889;
  const Scalar _tmp977 = _tmp521 * _tmp955;
  const Scalar _tmp978 = -_tmp199 * _tmp956 + _tmp347 * _tmp894 + _tmp824 * _tmp953 + _tmp889;
  const Scalar _tmp979 = _tmp205 * _tmp954;
  const Scalar _tmp980 = _tmp458 * _tmp956;
  const Scalar _tmp981 = _tmp459 * _tmp953;
  const Scalar _tmp982 = _tmp952 - _tmp979 + _tmp980 - _tmp981;
  const Scalar _tmp983 = _tmp513 * _tmp982;
  const Scalar _tmp984 = _tmp871 + _tmp912;
  const Scalar _tmp985 = -_tmp212 * _tmp946 - _tmp473 * _tmp978 + _tmp516 * _tmp958 -
                         _tmp517 * _tmp954 + _tmp519 * _tmp983 + _tmp984;
  const Scalar _tmp986 = _tmp514 * _tmp982;
  const Scalar _tmp987 = -_tmp250 * _tmp945 + _tmp311 * _tmp970 - _tmp354 * _tmp946 -
                         _tmp472 * _tmp973 - _tmp473 * _tmp968 + _tmp473 * _tmp969 +
                         _tmp473 * _tmp972 + _tmp552 * _tmp958 - _tmp553 * _tmp983 +
                         _tmp554 * _tmp954;
  const Scalar _tmp988 = -_tmp371 * _tmp946 - _tmp472 * _tmp966 - _tmp473 * _tmp960 +
                         _tmp473 * _tmp964 + _tmp473 * _tmp965 + _tmp536 * _tmp958 -
                         _tmp537 * _tmp983 + _tmp538 * _tmp954 + _tmp962;
  const Scalar _tmp989 = _tmp503 * _tmp903;
  const Scalar _tmp990 = _tmp885 * fh1;
  const Scalar _tmp991 = -_tmp21 * _tmp560 - _tmp237 * _tmp990 - _tmp40 * _tmp527 -
                         _tmp469 * _tmp898 + _tmp530 * _tmp681 + _tmp533 * _tmp853 +
                         _tmp561 * _tmp904 - _tmp897 * fv1;
  const Scalar _tmp992 = _tmp347 * _tmp983;
  const Scalar _tmp993 =
      -_tmp458 * _tmp992 + _tmp463 * _tmp979 - _tmp463 * _tmp980 + _tmp463 * _tmp981;
  const Scalar _tmp994 = _tmp463 * _tmp956;
  const Scalar _tmp995 = _tmp328 * _tmp955;
  const Scalar _tmp996 = _tmp238 * _tmp990 + _tmp40 * _tmp530 + _tmp41 * _tmp560 +
                         _tmp469 * _tmp902 + _tmp527 * _tmp681 + _tmp528 * _tmp853 -
                         _tmp532 * _tmp904 + _tmp901 * fv1;
  const Scalar _tmp997 = _tmp547 * _tmp957;
  const Scalar _tmp998 = _tmp351 * _tmp986;
  const Scalar _tmp999 = -_tmp253 * _tmp946 + _tmp458 * _tmp997 - _tmp458 * _tmp998 +
                         _tmp464 * _tmp954 - _tmp544 * _tmp959 + _tmp783 * _tmp930;
  const Scalar _tmp1000 = _tmp463 * _tmp959;
  const Scalar _tmp1001 =
      _tmp457 * (_tmp467 * _tmp905 +
                 _tmp471 * (-_tmp541 * _tmp983 + _tmp542 * _tmp954 - _tmp544 * _tmp995 + _tmp986) +
                 _tmp476 * _tmp898 +
                 _tmp478 * (_tmp210 * _tmp986 - _tmp346 * _tmp985 - _tmp463 * _tmp978 +
                            _tmp477 * _tmp977) +
                 _tmp482 * _tmp991 + _tmp485 * _tmp902 - _tmp506 * _tmp989 +
                 _tmp526 * (-_tmp346 * _tmp993 + _tmp480 * _tmp977 + _tmp542 * _tmp953 - _tmp992 -
                            _tmp994) +
                 _tmp535 * _tmp996 +
                 _tmp540 * (-_tmp346 * _tmp988 - _tmp369 * _tmp986 - _tmp463 * _tmp960 +
                            _tmp463 * _tmp964 + _tmp463 * _tmp965 + _tmp483 * _tmp977) +
                 _tmp551 * (-_tmp1000 - _tmp346 * _tmp999 + _tmp465 * _tmp977 + _tmp997 - _tmp998) +
                 _tmp556 * (-_tmp346 * _tmp987 - _tmp352 * _tmp986 - _tmp463 * _tmp968 +
                            _tmp463 * _tmp969 + _tmp463 * _tmp972 + _tmp474 * _tmp977) -
                 _tmp558 * _tmp989) -
      _tmp502 * _tmp976;
  const Scalar _tmp1002 = _tmp865 + _tmp899;
  const Scalar _tmp1003 = _tmp310 * _tmp921;
  const Scalar _tmp1004 = _tmp905 * fh1;
  const Scalar _tmp1005 = _tmp600 * _tmp958;
  const Scalar _tmp1006 = -_tmp1003 * _tmp596 + _tmp1003 * _tmp598 + _tmp1003 * _tmp604 -
                          _tmp1003 * _tmp607 - _tmp1004 * _tmp429 + _tmp1005 * _tmp213 -
                          _tmp361 * _tmp932 - _tmp595 * _tmp929 + _tmp599 * _tmp902 -
                          _tmp599 * _tmp975 + _tmp605 * _tmp967 + _tmp606 * _tmp931 +
                          _tmp608 * _tmp974 + _tmp609 * _tmp898 - _tmp609 * _tmp933;
  const Scalar _tmp1007 = _tmp471 * _tmp983;
  const Scalar _tmp1008 = _tmp463 * _tmp996;
  const Scalar _tmp1009 =
      _tmp630 *
      (-_tmp1006 * _tmp629 +
       _tmp572 * (_tmp1007 * _tmp459 - _tmp1008 * _tmp459 + _tmp573 * _tmp991 + _tmp575 * _tmp988 +
                  _tmp576 * _tmp905 + _tmp578 * _tmp985 + _tmp579 * _tmp898 + _tmp613 * _tmp999 +
                  _tmp614 * _tmp902 - _tmp614 * _tmp975 - _tmp615 * _tmp995 + _tmp616 * _tmp995 -
                  _tmp617 * _tmp995 - _tmp618 * _tmp995 - _tmp620 * _tmp995 + _tmp622 * _tmp993 +
                  _tmp623 * _tmp987 - _tmp625 * _tmp954 - _tmp626 * _tmp904 - _tmp627 * _tmp995));
  const Scalar _tmp1010 = _tmp871 + _tmp891;
  const Scalar _tmp1011 = -_tmp1005 - _tmp551 * _tmp931 + _tmp602 * _tmp905 + _tmp638 * _tmp902 -
                          _tmp639 * _tmp904 + _tmp640 * _tmp898 - _tmp640 * _tmp933 +
                          _tmp641 * _tmp973 - _tmp642 * _tmp958 + _tmp643 * _tmp966 -
                          _tmp644 * _tmp958;
  const Scalar _tmp1012 = _tmp1011 * _tmp660;
  const Scalar _tmp1013 =
      _tmp663 *
      (-_tmp1012 * _tmp652 +
       _tmp647 * (_tmp1000 * _tmp361 - _tmp1004 * _tmp464 - _tmp1007 + _tmp1008 -
                  _tmp361 * _tmp997 + _tmp361 * _tmp998 + _tmp479 * _tmp992 + _tmp479 * _tmp994 -
                  _tmp481 * _tmp991 + _tmp651 * _tmp978 + _tmp664 * _tmp968 - _tmp664 * _tmp969 -
                  _tmp664 * _tmp972 - _tmp665 * _tmp902 + _tmp666 * _tmp960 - _tmp666 * _tmp964 -
                  _tmp666 * _tmp965 + _tmp667 * _tmp983 - _tmp668 * _tmp983 + _tmp669 * _tmp904 +
                  _tmp670 * _tmp904 - _tmp671 * _tmp898 - _tmp672 * _tmp953 + _tmp673 * _tmp983));

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = -_tmp108 * (_tmp105 * (_tmp84 + _tmp92) + _tmp79 * (_tmp51 + _tmp62)) + _tmp127;
  _res(1, 0) =
      _tmp271 - _tmp452 * _tmp493 -
      _tmp499 *
          (-_tmp452 * _tmp568 + _tmp565 * _tmp569 -
           _tmp567 * (-_tmp452 * _tmp566 +
                      _tmp490 * (-_tmp452 * _tmp488 -
                                 _tmp498 * (_tmp494 * _tmp495 + _tmp497 * (_tmp496 + _tmp91)) -
                                 _tmp499 * _tmp565)));
  _res(2, 0) = _tmp285 -
               _tmp582 * (-_tmp589 * (_tmp587 * (-_tmp582 * _tmp631 -
                                                 _tmp593 * (_tmp590 * (_tmp142 + _tmp84) +
                                                            _tmp592 * (_tmp591 + _tmp62)) -
                                                 _tmp611 * _tmp612) -
                                      _tmp611 * _tmp633) -
                          _tmp611 * _tmp636 + _tmp631 * _tmp635) -
               _tmp611 * _tmp637;
  _res(3, 0) = _tmp304 - _tmp645 * _tmp659 -
               _tmp679 * (-Scalar(0.876505537412406) * _tmp661 + _tmp662 * _tmp674 -
                          _tmp680 * (_tmp656 * (-_tmp645 * _tmp654 - _tmp674 * _tmp679 -
                                                _tmp678 * (_tmp676 * (_tmp141 + _tmp496) +
                                                           _tmp677 * (_tmp226 + _tmp591))) -
                                     _tmp661 * _tmp675));
  _res(0, 1) = -_tmp108 * (_tmp105 * (_tmp700 + _tmp707) + _tmp79 * (_tmp690 + _tmp697)) + _tmp719;
  _res(1, 1) =
      -_tmp493 * _tmp838 -
      _tmp499 *
          (-_tmp567 * (_tmp490 * (-_tmp488 * _tmp838 -
                                  _tmp498 * (_tmp495 * _tmp826 + _tmp497 * (_tmp700 + _tmp748)) -
                                  _tmp839 * _tmp841) -
                       _tmp566 * _tmp838) -
           _tmp568 * _tmp838 + _tmp839 * _tmp840) +
      _tmp790;
  _res(2, 1) = -_tmp582 * (-_tmp589 * (_tmp587 * (-_tmp582 * _tmp849 -
                                                  _tmp593 * (_tmp590 * (_tmp700 + _tmp760) +
                                                             _tmp592 * (_tmp696 + _tmp756)) -
                                                  _tmp612 * _tmp845) -
                                       _tmp632 * _tmp846) +
                           _tmp635 * _tmp849 - Scalar(0.87679799777269396) * _tmp846) -
               _tmp637 * _tmp845 + _tmp788;
  _res(3, 1) = -_tmp659 * _tmp850 -
               _tmp679 * (_tmp662 * _tmp852 -
                          _tmp680 * (_tmp656 * (-_tmp654 * _tmp850 -
                                                _tmp678 * (_tmp676 * (_tmp700 + _tmp728) +
                                                           _tmp677 * (_tmp696 + _tmp724)) -
                                                _tmp679 * _tmp852) -
                                     _tmp675 * _tmp851) -
                          Scalar(0.876505537412406) * _tmp851) +
               _tmp786;
  _res(0, 2) = -_tmp108 * (_tmp105 * (_tmp856 + _tmp866) + _tmp79 * (_tmp871 + _tmp875)) + _tmp885;
  _res(1, 2) =
      -_tmp493 * _tmp976 -
      _tmp499 *
          (_tmp1001 * _tmp840 -
           _tmp567 * (_tmp490 * (-_tmp1001 * _tmp841 - _tmp488 * _tmp976 -
                                 _tmp498 * (_tmp495 * _tmp984 + _tmp497 * (_tmp1002 + _tmp856))) -
                      _tmp566 * _tmp976) -
           _tmp568 * _tmp976) +
      _tmp939;
  _res(2, 2) = -_tmp1006 * _tmp637 -
               _tmp582 * (-_tmp1006 * _tmp636 + _tmp1009 * _tmp635 -
                          _tmp589 * (-_tmp1006 * _tmp633 +
                                     _tmp587 * (-_tmp1006 * _tmp612 - _tmp1009 * _tmp582 -
                                                _tmp593 * (_tmp590 * (_tmp866 + _tmp888) +
                                                           _tmp592 * (_tmp1010 + _tmp872))))) +
               _tmp944;
  _res(3, 2) = -_tmp1011 * _tmp659 -
               _tmp679 * (-Scalar(0.876505537412406) * _tmp1012 + _tmp1013 * _tmp662 -
                          _tmp680 * (-_tmp1012 * _tmp675 +
                                     _tmp656 * (-_tmp1011 * _tmp654 - _tmp1013 * _tmp679 -
                                                _tmp678 * (_tmp676 * (_tmp1002 + _tmp888) +
                                                           _tmp677 * (_tmp1010 + _tmp896))))) +
               _tmp938;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
