// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Dense>

#include <sym/rot3.h>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: IK_residual_func_cost2_wrt_DeltaRot_Nl13
 *
 * Args:
 *     fh1: Scalar
 *     fv1: Scalar
 *     DeltaRot: Rot3
 *     position_vector: Matrix31
 *     Rot_init: Rot3
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix43
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 4, 3> IkResidualFuncCost2WrtDeltarotNl13(
    const Scalar fh1, const Scalar fv1, const sym::Rot3<Scalar>& DeltaRot,
    const Eigen::Matrix<Scalar, 3, 1>& position_vector, const sym::Rot3<Scalar>& Rot_init,
    const Scalar epsilon) {
  // Total ops: 3534

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _DeltaRot = DeltaRot.Data();
  const Eigen::Matrix<Scalar, 4, 1>& _Rot_init = Rot_init.Data();

  // Intermediate terms (1051)
  const Scalar _tmp0 = _DeltaRot[1] * _Rot_init[3];
  const Scalar _tmp1 = (Scalar(1) / Scalar(2)) * _tmp0;
  const Scalar _tmp2 = _DeltaRot[0] * _Rot_init[2];
  const Scalar _tmp3 = (Scalar(1) / Scalar(2)) * _tmp2;
  const Scalar _tmp4 = _DeltaRot[2] * _Rot_init[0];
  const Scalar _tmp5 = (Scalar(1) / Scalar(2)) * _tmp4;
  const Scalar _tmp6 = _DeltaRot[3] * _Rot_init[1];
  const Scalar _tmp7 = (Scalar(1) / Scalar(2)) * _tmp6;
  const Scalar _tmp8 = -_tmp1 - _tmp3 + _tmp5 - _tmp7;
  const Scalar _tmp9 = _DeltaRot[1] * _Rot_init[0];
  const Scalar _tmp10 = _DeltaRot[0] * _Rot_init[1];
  const Scalar _tmp11 = _DeltaRot[2] * _Rot_init[3];
  const Scalar _tmp12 = _DeltaRot[3] * _Rot_init[2];
  const Scalar _tmp13 = -_tmp10 + _tmp11 + _tmp12 + _tmp9;
  const Scalar _tmp14 = Scalar(0.83999999999999997) * _tmp13;
  const Scalar _tmp15 = _tmp14 * _tmp8;
  const Scalar _tmp16 = _DeltaRot[1] * _Rot_init[1];
  const Scalar _tmp17 = _DeltaRot[0] * _Rot_init[0];
  const Scalar _tmp18 = _DeltaRot[2] * _Rot_init[2];
  const Scalar _tmp19 = _DeltaRot[3] * _Rot_init[3];
  const Scalar _tmp20 = -Scalar(1) / Scalar(2) * _tmp16 - Scalar(1) / Scalar(2) * _tmp17 -
                        Scalar(1) / Scalar(2) * _tmp18 + (Scalar(1) / Scalar(2)) * _tmp19;
  const Scalar _tmp21 = _DeltaRot[1] * _Rot_init[2];
  const Scalar _tmp22 = _DeltaRot[0] * _Rot_init[3];
  const Scalar _tmp23 = _DeltaRot[2] * _Rot_init[1];
  const Scalar _tmp24 = _DeltaRot[3] * _Rot_init[0];
  const Scalar _tmp25 = -_tmp21 + _tmp22 + _tmp23 + _tmp24;
  const Scalar _tmp26 = Scalar(0.83999999999999997) * _tmp25;
  const Scalar _tmp27 = _tmp20 * _tmp26;
  const Scalar _tmp28 = -_tmp16 - _tmp17 - _tmp18 + _tmp19;
  const Scalar _tmp29 = Scalar(0.41999999999999998) * _tmp28;
  const Scalar _tmp30 = _tmp29 * _tmp8;
  const Scalar _tmp31 = -_tmp30;
  const Scalar _tmp32 = (Scalar(1) / Scalar(2)) * _tmp9;
  const Scalar _tmp33 = (Scalar(1) / Scalar(2)) * _tmp10;
  const Scalar _tmp34 = (Scalar(1) / Scalar(2)) * _tmp11;
  const Scalar _tmp35 = (Scalar(1) / Scalar(2)) * _tmp12;
  const Scalar _tmp36 = _tmp32 - _tmp33 + _tmp34 + _tmp35;
  const Scalar _tmp37 = Scalar(0.41999999999999998) * _tmp25;
  const Scalar _tmp38 = _tmp36 * _tmp37;
  const Scalar _tmp39 = -_tmp38;
  const Scalar _tmp40 = _tmp0 + _tmp2 - _tmp4 + _tmp6;
  const Scalar _tmp41 = Scalar(0.41999999999999998) * _tmp40;
  const Scalar _tmp42 = _tmp20 * _tmp41;
  const Scalar _tmp43 = -_tmp42;
  const Scalar _tmp44 = (Scalar(1) / Scalar(2)) * _tmp21;
  const Scalar _tmp45 = (Scalar(1) / Scalar(2)) * _tmp22;
  const Scalar _tmp46 = (Scalar(1) / Scalar(2)) * _tmp23;
  const Scalar _tmp47 = (Scalar(1) / Scalar(2)) * _tmp24;
  const Scalar _tmp48 = _tmp44 - _tmp45 - _tmp46 - _tmp47;
  const Scalar _tmp49 = Scalar(0.41999999999999998) * _tmp13;
  const Scalar _tmp50 = _tmp48 * _tmp49;
  const Scalar _tmp51 = -_tmp50;
  const Scalar _tmp52 = _tmp43 + _tmp51;
  const Scalar _tmp53 = _tmp31 + _tmp39 + _tmp52;
  const Scalar _tmp54 = _tmp15 + _tmp27 + _tmp53;
  const Scalar _tmp55 = Scalar(0.021999999999999999) * _tmp20;
  const Scalar _tmp56 = _tmp28 * _tmp55;
  const Scalar _tmp57 = -_tmp56;
  const Scalar _tmp58 = Scalar(0.021999999999999999) * _tmp40;
  const Scalar _tmp59 = _tmp58 * _tmp8;
  const Scalar _tmp60 = Scalar(0.021999999999999999) * _tmp13;
  const Scalar _tmp61 = _tmp36 * _tmp60;
  const Scalar _tmp62 = Scalar(0.021999999999999999) * _tmp25;
  const Scalar _tmp63 = _tmp48 * _tmp62;
  const Scalar _tmp64 = _tmp57 + _tmp59 + _tmp61 - _tmp63;
  const Scalar _tmp65 = -2 * std::pow(_tmp25, Scalar(2));
  const Scalar _tmp66 = -2 * std::pow(_tmp13, Scalar(2));
  const Scalar _tmp67 = Scalar(0.20999999999999999) * _tmp65 +
                        Scalar(0.20999999999999999) * _tmp66 + Scalar(0.20999999999999999);
  const Scalar _tmp68 = 2 * _tmp13 * _tmp40;
  const Scalar _tmp69 = 2 * _tmp28;
  const Scalar _tmp70 = _tmp25 * _tmp69;
  const Scalar _tmp71 = _tmp68 - _tmp70;
  const Scalar _tmp72 = -Scalar(0.010999999999999999) * _tmp71;
  const Scalar _tmp73 = 2 * _tmp25;
  const Scalar _tmp74 = _tmp40 * _tmp73;
  const Scalar _tmp75 = _tmp13 * _tmp69;
  const Scalar _tmp76 = Scalar(0.20999999999999999) * _tmp74 + Scalar(0.20999999999999999) * _tmp75;
  const Scalar _tmp77 = _tmp72 + _tmp76;
  const Scalar _tmp78 = _tmp67 + _tmp77;
  const Scalar _tmp79 = _tmp78 + position_vector(1, 0);
  const Scalar _tmp80 = Scalar(4.7744369927459998) - _tmp79;
  const Scalar _tmp81 = 2 * _tmp80;
  const Scalar _tmp82 = _tmp48 * _tmp58;
  const Scalar _tmp83 = _tmp13 * _tmp55;
  const Scalar _tmp84 = _tmp62 * _tmp8;
  const Scalar _tmp85 = Scalar(0.021999999999999999) * _tmp28;
  const Scalar _tmp86 = _tmp36 * _tmp85;
  const Scalar _tmp87 = _tmp82 + _tmp83 + _tmp84 + _tmp86;
  const Scalar _tmp88 = _tmp30 + _tmp39 + _tmp43 + _tmp50;
  const Scalar _tmp89 = Scalar(0.83999999999999997) * _tmp40;
  const Scalar _tmp90 = _tmp36 * _tmp89;
  const Scalar _tmp91 = _tmp15 + _tmp90;
  const Scalar _tmp92 = Scalar(0.20999999999999999) * _tmp74 - Scalar(0.20999999999999999) * _tmp75;
  const Scalar _tmp93 = 1 - 2 * std::pow(_tmp40, Scalar(2));
  const Scalar _tmp94 = Scalar(0.20999999999999999) * _tmp66 + Scalar(0.20999999999999999) * _tmp93;
  const Scalar _tmp95 = _tmp13 * _tmp73;
  const Scalar _tmp96 = _tmp40 * _tmp69;
  const Scalar _tmp97 = _tmp95 + _tmp96;
  const Scalar _tmp98 = -Scalar(0.010999999999999999) * _tmp97;
  const Scalar _tmp99 = _tmp94 + _tmp98;
  const Scalar _tmp100 = _tmp92 + _tmp99;
  const Scalar _tmp101 = _tmp100 + position_vector(0, 0);
  const Scalar _tmp102 = Scalar(2.7171519410699099) - _tmp101;
  const Scalar _tmp103 = 2 * _tmp102;
  const Scalar _tmp104 = _tmp103 * (_tmp87 + _tmp88 + _tmp91) + _tmp81 * (_tmp54 + _tmp64);
  const Scalar _tmp105 = std::pow(_tmp102, Scalar(2)) + std::pow(_tmp80, Scalar(2));
  const Scalar _tmp106 = std::sqrt(_tmp105);
  const Scalar _tmp107 = Scalar(1.0) / (fh1);
  const Scalar _tmp108 =
      Scalar(0.5) *
      std::cosh(Scalar(0.1034955) * _tmp107 *
                (-_tmp106 - Scalar(9.6622558468725703) * fh1 * std::asinh(_tmp107 * fv1))) /
      _tmp106;
  const Scalar _tmp109 = Scalar(0.043999999999999997) * _tmp40;
  const Scalar _tmp110 = _tmp109 * _tmp36;
  const Scalar _tmp111 = _tmp20 * _tmp25;
  const Scalar _tmp112 = Scalar(0.043999999999999997) * _tmp111;
  const Scalar _tmp113 = -_tmp110 - _tmp112;
  const Scalar _tmp114 = _tmp36 * _tmp49;
  const Scalar _tmp115 = _tmp37 * _tmp48;
  const Scalar _tmp116 = -_tmp115;
  const Scalar _tmp117 = _tmp41 * _tmp8;
  const Scalar _tmp118 = _tmp20 * _tmp29;
  const Scalar _tmp119 = -_tmp118;
  const Scalar _tmp120 = -_tmp117 + _tmp119;
  const Scalar _tmp121 = -_tmp114 + _tmp116 + _tmp120;
  const Scalar _tmp122 = _tmp113 + _tmp121;
  const Scalar _tmp123 = _tmp41 * _tmp48;
  const Scalar _tmp124 = _tmp29 * _tmp36;
  const Scalar _tmp125 = _tmp20 * _tmp49;
  const Scalar _tmp126 = _tmp37 * _tmp8;
  const Scalar _tmp127 = -_tmp125 - _tmp126;
  const Scalar _tmp128 = _tmp123 + _tmp124 + _tmp127;
  const Scalar _tmp129 =
      Scalar(0.20999999999999999) * _tmp68 + Scalar(0.20999999999999999) * _tmp70;
  const Scalar _tmp130 =
      -Scalar(0.010999999999999999) * _tmp65 - Scalar(0.010999999999999999) * _tmp93;
  const Scalar _tmp131 =
      Scalar(0.20999999999999999) * _tmp95 - Scalar(0.20999999999999999) * _tmp96;
  const Scalar _tmp132 = _tmp130 + _tmp131;
  const Scalar _tmp133 = _tmp129 + _tmp132;
  const Scalar _tmp134 = -_tmp133 - position_vector(2, 0) + Scalar(8.3641088633305802);
  const Scalar _tmp135 = 2 * _tmp134;
  const Scalar _tmp136 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp105 + std::pow(_tmp134, Scalar(2))));
  const Scalar _tmp137 = -_tmp59;
  const Scalar _tmp138 = _tmp137 + _tmp56 - _tmp61 + _tmp63;
  const Scalar _tmp139 = -_tmp27;
  const Scalar _tmp140 = -_tmp15;
  const Scalar _tmp141 = _tmp139 + _tmp140;
  const Scalar _tmp142 = _tmp138 + _tmp141;
  const Scalar _tmp143 = _tmp42 + _tmp50;
  const Scalar _tmp144 = _tmp143 + _tmp30;
  const Scalar _tmp145 = _tmp144 + _tmp38;
  const Scalar _tmp146 = _tmp142 + _tmp145;
  const Scalar _tmp147 = _tmp79 + Scalar(-4.7744369927459998);
  const Scalar _tmp148 = 2 * _tmp147;
  const Scalar _tmp149 = _tmp140 - _tmp90;
  const Scalar _tmp150 = _tmp31 + _tmp42 + _tmp51;
  const Scalar _tmp151 = _tmp150 + _tmp38;
  const Scalar _tmp152 = -_tmp83;
  const Scalar _tmp153 = -_tmp84;
  const Scalar _tmp154 = _tmp152 + _tmp153 - _tmp82 - _tmp86;
  const Scalar _tmp155 = _tmp149 + _tmp151 + _tmp154;
  const Scalar _tmp156 = _tmp101 + Scalar(-2.7171519410699099);
  const Scalar _tmp157 = 2 * _tmp156;
  const Scalar _tmp158 = _tmp146 * _tmp148 + _tmp155 * _tmp157;
  const Scalar _tmp159 = std::pow(_tmp147, Scalar(2)) + std::pow(_tmp156, Scalar(2));
  const Scalar _tmp160 = std::pow(_tmp159, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp161 = (Scalar(1) / Scalar(2)) * _tmp160;
  const Scalar _tmp162 = _tmp158 * _tmp161;
  const Scalar _tmp163 = -_tmp129;
  const Scalar _tmp164 = _tmp132 + _tmp163;
  const Scalar _tmp165 = -_tmp67;
  const Scalar _tmp166 = _tmp165 + _tmp77;
  const Scalar _tmp167 = _tmp166 + position_vector(1, 0);
  const Scalar _tmp168 = _tmp167 + Scalar(8.3885017487099702);
  const Scalar _tmp169 = -_tmp92;
  const Scalar _tmp170 = _tmp169 + _tmp99;
  const Scalar _tmp171 = _tmp170 + position_vector(0, 0);
  const Scalar _tmp172 = _tmp171 + Scalar(-2.5193355532036801);
  const Scalar _tmp173 = std::pow(_tmp168, Scalar(2)) + std::pow(_tmp172, Scalar(2));
  const Scalar _tmp174 = std::pow(_tmp173, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp175 = _tmp172 * _tmp174;
  const Scalar _tmp176 = _tmp130 - _tmp131;
  const Scalar _tmp177 = _tmp163 + _tmp176;
  const Scalar _tmp178 = _tmp174 * _tmp177;
  const Scalar _tmp179 = _tmp172 * _tmp178;
  const Scalar _tmp180 = _tmp129 + _tmp176;
  const Scalar _tmp181 = _tmp72 - _tmp76;
  const Scalar _tmp182 = _tmp181 + _tmp67;
  const Scalar _tmp183 = _tmp182 + position_vector(1, 0);
  const Scalar _tmp184 = _tmp183 + Scalar(-4.83288938413423);
  const Scalar _tmp185 = -_tmp94 + _tmp98;
  const Scalar _tmp186 = _tmp185 + _tmp92;
  const Scalar _tmp187 = _tmp186 + position_vector(0, 0);
  const Scalar _tmp188 = _tmp187 + Scalar(1.7965602546229);
  const Scalar _tmp189 = std::pow(_tmp184, Scalar(2)) + std::pow(_tmp188, Scalar(2));
  const Scalar _tmp190 = std::pow(_tmp189, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp191 = _tmp184 * _tmp190;
  const Scalar _tmp192 = _tmp188 * _tmp190;
  const Scalar _tmp193 = _tmp165 + _tmp181;
  const Scalar _tmp194 = _tmp193 + position_vector(1, 0);
  const Scalar _tmp195 = _tmp194 + Scalar(8.3196563720703107);
  const Scalar _tmp196 = _tmp169 + _tmp185;
  const Scalar _tmp197 = _tmp196 + position_vector(0, 0);
  const Scalar _tmp198 = _tmp197 + Scalar(1.9874742031097401);
  const Scalar _tmp199 = Scalar(1.0) / (_tmp198);
  const Scalar _tmp200 = _tmp195 * _tmp199;
  const Scalar _tmp201 = _tmp177 * _tmp200;
  const Scalar _tmp202 = _tmp180 * _tmp191 - _tmp192 * _tmp201;
  const Scalar _tmp203 = -_tmp191 + _tmp192 * _tmp200;
  const Scalar _tmp204 = Scalar(1.0) / (_tmp203);
  const Scalar _tmp205 = _tmp168 * _tmp174;
  const Scalar _tmp206 = _tmp175 * _tmp200 - _tmp205;
  const Scalar _tmp207 = _tmp204 * _tmp206;
  const Scalar _tmp208 = _tmp164 * _tmp205 - _tmp179 * _tmp200 - _tmp202 * _tmp207;
  const Scalar _tmp209 = Scalar(1.0) * _tmp193;
  const Scalar _tmp210 = -_tmp209;
  const Scalar _tmp211 = _tmp182 + _tmp210;
  const Scalar _tmp212 = Scalar(1.0) / (_tmp211);
  const Scalar _tmp213 = Scalar(1.0) * _tmp196;
  const Scalar _tmp214 = -_tmp186 + _tmp213;
  const Scalar _tmp215 = _tmp212 * _tmp214;
  const Scalar _tmp216 = _tmp177 * _tmp192;
  const Scalar _tmp217 = -_tmp180 * _tmp192 + _tmp216;
  const Scalar _tmp218 = -_tmp164 * _tmp175 + _tmp179 - _tmp207 * _tmp217 - _tmp208 * _tmp215;
  const Scalar _tmp219 = Scalar(1.0) / (_tmp218);
  const Scalar _tmp220 = std::pow(_tmp198, Scalar(2));
  const Scalar _tmp221 = std::pow(_tmp195, Scalar(2)) + _tmp220;
  const Scalar _tmp222 = std::sqrt(_tmp221);
  const Scalar _tmp223 = Scalar(1.0) / (_tmp222);
  const Scalar _tmp224 = _tmp196 * _tmp223;
  const Scalar _tmp225 = _tmp198 * _tmp223;
  const Scalar _tmp226 = -_tmp193 * _tmp225 + _tmp195 * _tmp224;
  const Scalar _tmp227 = _tmp199 * _tmp222;
  const Scalar _tmp228 = _tmp226 * _tmp227;
  const Scalar _tmp229 = _tmp182 * _tmp192 - _tmp186 * _tmp191 + _tmp192 * _tmp228;
  const Scalar _tmp230 = _tmp200 * _tmp204;
  const Scalar _tmp231 =
      _tmp166 * _tmp175 - _tmp170 * _tmp205 + _tmp175 * _tmp228 - _tmp207 * _tmp229;
  const Scalar _tmp232 = _tmp201 + _tmp202 * _tmp230;
  const Scalar _tmp233 = -_tmp177 - _tmp215 * _tmp232 + _tmp217 * _tmp230;
  const Scalar _tmp234 = _tmp219 * _tmp233;
  const Scalar _tmp235 = -_tmp228 + _tmp229 * _tmp230 - _tmp231 * _tmp234;
  const Scalar _tmp236 = Scalar(1.0) / (_tmp231);
  const Scalar _tmp237 = _tmp218 * _tmp236;
  const Scalar _tmp238 = _tmp235 * _tmp237;
  const Scalar _tmp239 = _tmp233 + _tmp238;
  const Scalar _tmp240 = _tmp219 * _tmp239;
  const Scalar _tmp241 = _tmp206 * _tmp219;
  const Scalar _tmp242 = -_tmp200 - _tmp239 * _tmp241;
  const Scalar _tmp243 = _tmp192 * _tmp204;
  const Scalar _tmp244 = _tmp175 * _tmp240 + _tmp242 * _tmp243 + Scalar(1.0);
  const Scalar _tmp245 = _tmp227 * _tmp244;
  const Scalar _tmp246 = _tmp156 * fh1;
  const Scalar _tmp247 = _tmp245 * _tmp246;
  const Scalar _tmp248 = _tmp138 + _tmp54;
  const Scalar _tmp249 = 2 * _tmp195;
  const Scalar _tmp250 = _tmp154 + _tmp88;
  const Scalar _tmp251 = _tmp250 + _tmp91;
  const Scalar _tmp252 = 2 * _tmp198;
  const Scalar _tmp253 =
      (Scalar(1) / Scalar(2)) * _tmp248 * _tmp249 + (Scalar(1) / Scalar(2)) * _tmp251 * _tmp252;
  const Scalar _tmp254 = _tmp199 * _tmp223;
  const Scalar _tmp255 = Scalar(1.0) * _tmp204;
  const Scalar _tmp256 = _tmp202 * _tmp255;
  const Scalar _tmp257 = _tmp215 * _tmp256 - _tmp217 * _tmp255;
  const Scalar _tmp258 = _tmp219 * _tmp257;
  const Scalar _tmp259 = -_tmp229 * _tmp255 - _tmp231 * _tmp258;
  const Scalar _tmp260 = _tmp236 * _tmp259;
  const Scalar _tmp261 = _tmp218 * _tmp260;
  const Scalar _tmp262 = _tmp257 + _tmp261;
  const Scalar _tmp263 = _tmp219 * _tmp262;
  const Scalar _tmp264 = -_tmp241 * _tmp262 + Scalar(1.0);
  const Scalar _tmp265 = _tmp175 * _tmp263 + _tmp243 * _tmp264;
  const Scalar _tmp266 = std::pow(_tmp159, Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp267 = _tmp147 * _tmp266;
  const Scalar _tmp268 = _tmp267 * fh1;
  const Scalar _tmp269 = _tmp265 * _tmp268;
  const Scalar _tmp270 = _tmp254 * _tmp269;
  const Scalar _tmp271 = _tmp266 * fh1;
  const Scalar _tmp272 = _tmp146 * _tmp271;
  const Scalar _tmp273 = _tmp227 * _tmp265;
  const Scalar _tmp274 = Scalar(1.0) * _tmp236;
  const Scalar _tmp275 = _tmp236 * _tmp255;
  const Scalar _tmp276 = _tmp192 * _tmp275;
  const Scalar _tmp277 = _tmp175 * _tmp274 - _tmp206 * _tmp276;
  const Scalar _tmp278 = _tmp266 * _tmp78;
  const Scalar _tmp279 = _tmp100 * _tmp267 - _tmp156 * _tmp278;
  const Scalar _tmp280 = _tmp279 * fh1;
  const Scalar _tmp281 = _tmp277 * _tmp280;
  const Scalar _tmp282 = _tmp254 * _tmp281;
  const Scalar _tmp283 = Scalar(1.0) / (_tmp220);
  const Scalar _tmp284 = _tmp222 * _tmp283;
  const Scalar _tmp285 = _tmp251 * _tmp284;
  const Scalar _tmp286 = Scalar(43.164000000000001) - fv1;
  const Scalar _tmp287 = _tmp209 * _tmp215 + _tmp213;
  const Scalar _tmp288 = 0;
  const Scalar _tmp289 = _tmp219 * _tmp288;
  const Scalar _tmp290 = _tmp207 * _tmp289;
  const Scalar _tmp291 = _tmp175 * _tmp289 - _tmp192 * _tmp290;
  const Scalar _tmp292 = _tmp286 * _tmp291;
  const Scalar _tmp293 = _tmp284 * _tmp292;
  const Scalar _tmp294 = _tmp15 + _tmp38;
  const Scalar _tmp295 = _tmp150 + _tmp294 + _tmp90;
  const Scalar _tmp296 = _tmp154 + _tmp295;
  const Scalar _tmp297 = 2 * _tmp188;
  const Scalar _tmp298 = _tmp142 + _tmp53;
  const Scalar _tmp299 = 2 * _tmp184;
  const Scalar _tmp300 = _tmp296 * _tmp297 + _tmp298 * _tmp299;
  const Scalar _tmp301 = std::pow(_tmp189, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp302 = (Scalar(1) / Scalar(2)) * _tmp301;
  const Scalar _tmp303 = _tmp184 * _tmp302;
  const Scalar _tmp304 = _tmp300 * _tmp303;
  const Scalar _tmp305 = _tmp190 * _tmp298;
  const Scalar _tmp306 = _tmp188 * _tmp302;
  const Scalar _tmp307 = _tmp300 * _tmp306;
  const Scalar _tmp308 = _tmp195 * _tmp283;
  const Scalar _tmp309 = _tmp251 * _tmp308;
  const Scalar _tmp310 = _tmp190 * _tmp296;
  const Scalar _tmp311 = _tmp199 * _tmp248;
  const Scalar _tmp312 = std::pow(_tmp203, Scalar(-2));
  const Scalar _tmp313 = _tmp312 * (-_tmp192 * _tmp309 + _tmp192 * _tmp311 - _tmp200 * _tmp307 +
                                    _tmp200 * _tmp310 + _tmp304 - _tmp305);
  const Scalar _tmp314 = _tmp192 * _tmp313;
  const Scalar _tmp315 = _tmp149 + _tmp250;
  const Scalar _tmp316 = _tmp174 * _tmp315;
  const Scalar _tmp317 = _tmp206 * _tmp313;
  const Scalar _tmp318 = _tmp144 + _tmp27 + _tmp294;
  const Scalar _tmp319 = _tmp138 + _tmp318;
  const Scalar _tmp320 = 2 * _tmp168;
  const Scalar _tmp321 = 2 * _tmp172;
  const Scalar _tmp322 = _tmp315 * _tmp321 + _tmp319 * _tmp320;
  const Scalar _tmp323 = std::pow(_tmp173, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp324 = (Scalar(1) / Scalar(2)) * _tmp323;
  const Scalar _tmp325 = _tmp168 * _tmp324;
  const Scalar _tmp326 = _tmp322 * _tmp325;
  const Scalar _tmp327 = _tmp172 * _tmp324;
  const Scalar _tmp328 = _tmp322 * _tmp327;
  const Scalar _tmp329 = _tmp174 * _tmp319;
  const Scalar _tmp330 = -_tmp175 * _tmp309 + _tmp175 * _tmp311 + _tmp200 * _tmp316 -
                         _tmp200 * _tmp328 + _tmp326 - _tmp329;
  const Scalar _tmp331 = _tmp204 * _tmp330;
  const Scalar _tmp332 = _tmp178 * _tmp315;
  const Scalar _tmp333 = _tmp125 + _tmp126;
  const Scalar _tmp334 = -_tmp123 - _tmp124 + _tmp333;
  const Scalar _tmp335 = _tmp110 + _tmp112;
  const Scalar _tmp336 = _tmp121 + _tmp335;
  const Scalar _tmp337 = _tmp334 + _tmp336;
  const Scalar _tmp338 = _tmp128 + _tmp336;
  const Scalar _tmp339 = _tmp192 * _tmp338;
  const Scalar _tmp340 = _tmp117 + _tmp118;
  const Scalar _tmp341 = _tmp114 + _tmp115 + _tmp340;
  const Scalar _tmp342 = _tmp128 + _tmp341;
  const Scalar _tmp343 = _tmp335 + _tmp342;
  const Scalar _tmp344 = _tmp177 * _tmp311;
  const Scalar _tmp345 = -_tmp180 * _tmp304 + _tmp180 * _tmp305 + _tmp191 * _tmp343 -
                         _tmp192 * _tmp344 - _tmp200 * _tmp339 + _tmp201 * _tmp307 -
                         _tmp201 * _tmp310 + _tmp216 * _tmp309;
  const Scalar _tmp346 = _tmp175 * _tmp338;
  const Scalar _tmp347 = -_tmp164 * _tmp326 + _tmp164 * _tmp329 + _tmp179 * _tmp309 -
                         _tmp179 * _tmp311 - _tmp200 * _tmp332 - _tmp200 * _tmp346 +
                         _tmp201 * _tmp328 + _tmp202 * _tmp317 - _tmp202 * _tmp331 +
                         _tmp205 * _tmp337 - _tmp207 * _tmp345;
  const Scalar _tmp348 = Scalar(1.6799999999999999) * _tmp13;
  const Scalar _tmp349 = _tmp348 * _tmp8;
  const Scalar _tmp350 = std::pow(_tmp211, Scalar(-2));
  const Scalar _tmp351 = _tmp350 * (-Scalar(1.6799999999999999) * _tmp111 - _tmp349);
  const Scalar _tmp352 = _tmp214 * _tmp351;
  const Scalar _tmp353 = _tmp177 * _tmp327;
  const Scalar _tmp354 = _tmp164 * _tmp327;
  const Scalar _tmp355 = _tmp164 * _tmp174;
  const Scalar _tmp356 = _tmp20 * _tmp89;
  const Scalar _tmp357 = -_tmp356;
  const Scalar _tmp358 = _tmp26 * _tmp36;
  const Scalar _tmp359 = Scalar(0.83999999999999997) * _tmp28;
  const Scalar _tmp360 = _tmp14 * _tmp48 + _tmp359 * _tmp8;
  const Scalar _tmp361 = _tmp357 - _tmp358 + _tmp360;
  const Scalar _tmp362 = _tmp208 * _tmp212;
  const Scalar _tmp363 = -_tmp177 * _tmp307 + _tmp177 * _tmp310 + _tmp180 * _tmp307 -
                         _tmp180 * _tmp310 - _tmp192 * _tmp343 + _tmp339;
  const Scalar _tmp364 = -_tmp175 * _tmp337 - _tmp207 * _tmp363 + _tmp208 * _tmp352 -
                         _tmp215 * _tmp347 + _tmp217 * _tmp317 - _tmp217 * _tmp331 -
                         _tmp315 * _tmp355 - _tmp322 * _tmp353 + _tmp322 * _tmp354 + _tmp332 +
                         _tmp346 - _tmp361 * _tmp362;
  const Scalar _tmp365 = std::pow(_tmp218, Scalar(-2));
  const Scalar _tmp366 = _tmp364 * _tmp365;
  const Scalar _tmp367 = _tmp175 * _tmp239;
  const Scalar _tmp368 = _tmp204 * _tmp242;
  const Scalar _tmp369 = _tmp166 * _tmp174;
  const Scalar _tmp370 = _tmp226 * _tmp284;
  const Scalar _tmp371 = _tmp251 * _tmp370;
  const Scalar _tmp372 = _tmp223 * _tmp251;
  const Scalar _tmp373 = std::pow(_tmp221, Scalar(Scalar(-3) / Scalar(2)));
  const Scalar _tmp374 = _tmp253 * _tmp373;
  const Scalar _tmp375 = _tmp193 * _tmp198;
  const Scalar _tmp376 = _tmp195 * _tmp196;
  const Scalar _tmp377 = _tmp227 * (-_tmp193 * _tmp372 + _tmp195 * _tmp372 + _tmp224 * _tmp248 -
                                    _tmp225 * _tmp248 + _tmp374 * _tmp375 - _tmp374 * _tmp376);
  const Scalar _tmp378 = _tmp226 * _tmp254;
  const Scalar _tmp379 = _tmp253 * _tmp378;
  const Scalar _tmp380 = -_tmp182 * _tmp307 + _tmp182 * _tmp310 + _tmp186 * _tmp304 -
                         _tmp186 * _tmp305 + _tmp188 * _tmp305 - _tmp191 * _tmp296 -
                         _tmp192 * _tmp371 + _tmp192 * _tmp377 + _tmp192 * _tmp379 -
                         _tmp228 * _tmp307 + _tmp228 * _tmp310;
  const Scalar _tmp381 = _tmp166 * _tmp327;
  const Scalar _tmp382 = _tmp170 * _tmp326 - _tmp170 * _tmp329 + _tmp172 * _tmp329 -
                         _tmp175 * _tmp371 + _tmp175 * _tmp377 + _tmp175 * _tmp379 -
                         _tmp205 * _tmp315 - _tmp207 * _tmp380 + _tmp228 * _tmp316 -
                         _tmp228 * _tmp328 + _tmp229 * _tmp317 - _tmp229 * _tmp331 +
                         _tmp315 * _tmp369 - _tmp322 * _tmp381;
  const Scalar _tmp383 = std::pow(_tmp231, Scalar(-2));
  const Scalar _tmp384 = _tmp382 * _tmp383;
  const Scalar _tmp385 = _tmp218 * _tmp235;
  const Scalar _tmp386 = _tmp384 * _tmp385;
  const Scalar _tmp387 = _tmp231 * _tmp233;
  const Scalar _tmp388 = _tmp204 * _tmp311;
  const Scalar _tmp389 = _tmp204 * _tmp309;
  const Scalar _tmp390 = _tmp200 * _tmp229;
  const Scalar _tmp391 = _tmp200 * _tmp217;
  const Scalar _tmp392 = _tmp212 * _tmp232;
  const Scalar _tmp393 = _tmp202 * _tmp313;
  const Scalar _tmp394 = -_tmp177 * _tmp309 + _tmp200 * _tmp338 - _tmp200 * _tmp393 +
                         _tmp202 * _tmp388 - _tmp202 * _tmp389 + _tmp230 * _tmp345 + _tmp344;
  const Scalar _tmp395 = _tmp334 + _tmp341;
  const Scalar _tmp396 = _tmp113 + _tmp395;
  const Scalar _tmp397 = -_tmp215 * _tmp394 + _tmp217 * _tmp388 - _tmp217 * _tmp389 +
                         _tmp230 * _tmp363 + _tmp232 * _tmp352 - _tmp313 * _tmp391 -
                         _tmp361 * _tmp392 + _tmp396;
  const Scalar _tmp398 = _tmp219 * _tmp231;
  const Scalar _tmp399 = _tmp237 * (_tmp229 * _tmp388 - _tmp229 * _tmp389 + _tmp230 * _tmp380 -
                                    _tmp234 * _tmp382 - _tmp313 * _tmp390 + _tmp366 * _tmp387 +
                                    _tmp371 - _tmp377 - _tmp379 - _tmp397 * _tmp398);
  const Scalar _tmp400 = _tmp235 * _tmp236;
  const Scalar _tmp401 = _tmp364 * _tmp400;
  const Scalar _tmp402 = -_tmp386 + _tmp397 + _tmp399 + _tmp401;
  const Scalar _tmp403 = _tmp175 * _tmp219;
  const Scalar _tmp404 = _tmp206 * _tmp239;
  const Scalar _tmp405 =
      -_tmp240 * _tmp330 - _tmp241 * _tmp402 + _tmp309 - _tmp311 + _tmp366 * _tmp404;
  const Scalar _tmp406 = _tmp240 * _tmp327;
  const Scalar _tmp407 = _tmp156 * _tmp266;
  const Scalar _tmp408 = _tmp407 * fh1;
  const Scalar _tmp409 = _tmp227 * _tmp408;
  const Scalar _tmp410 = _tmp254 * _tmp292;
  const Scalar _tmp411 = _tmp100 * _tmp147;
  const Scalar _tmp412 = _tmp156 * _tmp78;
  const Scalar _tmp413 = _tmp100 * _tmp266;
  const Scalar _tmp414 = -_tmp146 * _tmp407 + _tmp146 * _tmp413 + _tmp155 * _tmp267 -
                         _tmp155 * _tmp278 - _tmp162 * _tmp411 + _tmp162 * _tmp412;
  const Scalar _tmp415 = _tmp414 * fh1;
  const Scalar _tmp416 = _tmp227 * _tmp277;
  const Scalar _tmp417 = _tmp244 * _tmp408;
  const Scalar _tmp418 = _tmp254 * _tmp417;
  const Scalar _tmp419 = _tmp218 * _tmp259;
  const Scalar _tmp420 = _tmp384 * _tmp419;
  const Scalar _tmp421 = _tmp212 * _tmp256;
  const Scalar _tmp422 = _tmp255 * _tmp345;
  const Scalar _tmp423 = Scalar(1.0) * _tmp215;
  const Scalar _tmp424 = Scalar(1.0) * _tmp217;
  const Scalar _tmp425 = _tmp215 * _tmp422 - _tmp255 * _tmp363 - _tmp256 * _tmp352 +
                         _tmp313 * _tmp424 + _tmp361 * _tmp421 - _tmp393 * _tmp423;
  const Scalar _tmp426 = _tmp231 * _tmp257;
  const Scalar _tmp427 = Scalar(1.0) * _tmp229;
  const Scalar _tmp428 = _tmp237 * (-_tmp255 * _tmp380 - _tmp258 * _tmp382 + _tmp313 * _tmp427 +
                                    _tmp366 * _tmp426 - _tmp398 * _tmp425);
  const Scalar _tmp429 = _tmp260 * _tmp364;
  const Scalar _tmp430 = -_tmp420 + _tmp425 + _tmp428 + _tmp429;
  const Scalar _tmp431 = _tmp206 * _tmp262;
  const Scalar _tmp432 = -_tmp241 * _tmp430 - _tmp263 * _tmp330 + _tmp366 * _tmp431;
  const Scalar _tmp433 = _tmp175 * _tmp262;
  const Scalar _tmp434 = _tmp204 * _tmp264;
  const Scalar _tmp435 = _tmp227 * _tmp268;
  const Scalar _tmp436 = _tmp147 * fh1;
  const Scalar _tmp437 = _tmp162 * _tmp436;
  const Scalar _tmp438 = _tmp206 * _tmp255;
  const Scalar _tmp439 = _tmp192 * _tmp438;
  const Scalar _tmp440 = Scalar(0.5) * _tmp236;
  const Scalar _tmp441 = _tmp188 * _tmp207 * _tmp301 * _tmp440;
  const Scalar _tmp442 = _tmp172 * _tmp323 * _tmp440;
  const Scalar _tmp443 = _tmp206 * _tmp275;
  const Scalar _tmp444 = Scalar(1.0) * _tmp175;
  const Scalar _tmp445 = _tmp227 * _tmp280;
  const Scalar _tmp446 = _tmp288 * _tmp366;
  const Scalar _tmp447 = _tmp241 * _tmp288;
  const Scalar _tmp448 = _tmp289 * _tmp327;
  const Scalar _tmp449 = _tmp192 * _tmp207;
  const Scalar _tmp450 = _tmp192 * _tmp289;
  const Scalar _tmp451 = _tmp227 * _tmp286;
  const Scalar _tmp452 = _tmp155 * _tmp271;
  const Scalar _tmp453 =
      _tmp162 * _tmp247 - _tmp245 * _tmp452 + _tmp251 * _tmp293 - _tmp253 * _tmp270 -
      _tmp253 * _tmp282 - _tmp253 * _tmp410 - _tmp253 * _tmp418 + _tmp269 * _tmp285 -
      _tmp272 * _tmp273 + _tmp273 * _tmp437 + _tmp281 * _tmp285 + _tmp285 * _tmp417 -
      _tmp409 * (_tmp240 * _tmp316 - _tmp242 * _tmp314 + _tmp243 * _tmp405 - _tmp307 * _tmp368 +
                 _tmp310 * _tmp368 - _tmp322 * _tmp406 - _tmp366 * _tmp367 + _tmp402 * _tmp403) -
      _tmp415 * _tmp416 -
      _tmp435 * (_tmp243 * _tmp432 + _tmp263 * _tmp316 - _tmp263 * _tmp328 - _tmp264 * _tmp314 -
                 _tmp307 * _tmp434 + _tmp310 * _tmp434 - _tmp366 * _tmp433 + _tmp403 * _tmp430) -
      _tmp445 *
          (_tmp192 * _tmp274 * _tmp317 + _tmp274 * _tmp316 - _tmp276 * _tmp330 + _tmp300 * _tmp441 -
           _tmp310 * _tmp443 - _tmp322 * _tmp442 + _tmp384 * _tmp439 - _tmp384 * _tmp444) -
      _tmp451 * (-_tmp175 * _tmp446 + _tmp289 * _tmp316 + _tmp290 * _tmp307 - _tmp290 * _tmp310 +
                 _tmp314 * _tmp447 - _tmp322 * _tmp448 - _tmp331 * _tmp450 + _tmp446 * _tmp449);
  const Scalar _tmp454 =
      -_tmp245 * _tmp408 - _tmp265 * _tmp435 - _tmp280 * _tmp416 - _tmp291 * _tmp451;
  const Scalar _tmp455 = Scalar(1.0) / (_tmp454);
  const Scalar _tmp456 = _tmp208 * _tmp219;
  const Scalar _tmp457 = _tmp166 + _tmp210;
  const Scalar _tmp458 = _tmp215 * _tmp457;
  const Scalar _tmp459 = -_tmp170 + _tmp213 - _tmp458;
  const Scalar _tmp460 = Scalar(1.0) / (_tmp459);
  const Scalar _tmp461 = _tmp457 * _tmp460;
  const Scalar _tmp462 = -_tmp256 + _tmp261 * _tmp461 - _tmp262 * _tmp456;
  const Scalar _tmp463 = Scalar(1.0) * _tmp212;
  const Scalar _tmp464 = Scalar(1.0) * _tmp460;
  const Scalar _tmp465 = _tmp261 * _tmp464 - _tmp462 * _tmp463;
  const Scalar _tmp466 = Scalar(1.0) * _tmp268;
  const Scalar _tmp467 = _tmp237 * _tmp464;
  const Scalar _tmp468 = -_tmp208 * _tmp274 + _tmp457 * _tmp467;
  const Scalar _tmp469 = -Scalar(1.0) * _tmp463 * _tmp468 + Scalar(1.0) * _tmp467;
  const Scalar _tmp470 = _tmp133 * fh1;
  const Scalar _tmp471 = -_tmp267 * _tmp470 - Scalar(5.1796800000000003) * _tmp71 - _tmp78 * fv1;
  const Scalar _tmp472 = _tmp215 * _tmp464;
  const Scalar _tmp473 = _tmp458 * _tmp464 + Scalar(1.0);
  const Scalar _tmp474 = -Scalar(1.0) * _tmp463 * _tmp473 + Scalar(1.0) * _tmp472;
  const Scalar _tmp475 = _tmp210 - _tmp287 * _tmp461 - _tmp288 * _tmp456;
  const Scalar _tmp476 = Scalar(1.0) * _tmp286;
  const Scalar _tmp477 = _tmp232 + _tmp238 * _tmp461 - _tmp239 * _tmp456;
  const Scalar _tmp478 = _tmp238 * _tmp464 - _tmp463 * _tmp477;
  const Scalar _tmp479 = Scalar(1.0) * _tmp408;
  const Scalar _tmp480 = _tmp212 * _tmp457;
  const Scalar _tmp481 = _tmp464 * _tmp480 - _tmp464;
  const Scalar _tmp482 = _tmp100 * fv1 + _tmp407 * _tmp470 + Scalar(5.1796800000000003) * _tmp97;
  const Scalar _tmp483 = Scalar(1.0) * _tmp482;
  const Scalar _tmp484 = _tmp280 * _tmp469 + _tmp465 * _tmp466 + _tmp471 * _tmp474 +
                         _tmp476 * (-_tmp287 * _tmp464 - _tmp463 * _tmp475 + Scalar(1.0)) +
                         _tmp478 * _tmp479 + _tmp481 * _tmp483;
  const Scalar _tmp485 = std::asinh(_tmp455 * _tmp484);
  const Scalar _tmp486 = Scalar(9.6622558468725703) * _tmp454;
  const Scalar _tmp487 = -_tmp194 + Scalar(-8.3196563720703107);
  const Scalar _tmp488 = -_tmp197 + Scalar(-1.9874742031097401);
  const Scalar _tmp489 = std::pow(_tmp487, Scalar(2)) + std::pow(_tmp488, Scalar(2));
  const Scalar _tmp490 = std::sqrt(_tmp489);
  const Scalar _tmp491 = -_tmp485 * _tmp486 - _tmp490;
  const Scalar _tmp492 = Scalar(0.1034955) * _tmp455;
  const Scalar _tmp493 = _tmp491 * _tmp492;
  const Scalar _tmp494 = Scalar(1.0) * _tmp485;
  const Scalar _tmp495 = -std::sinh(_tmp493) - std::sinh(_tmp494);
  const Scalar _tmp496 = Scalar(9.6622558468725703) * _tmp495;
  const Scalar _tmp497 = -_tmp177 - position_vector(2, 0) + Scalar(8.4718465805053693);
  const Scalar _tmp498 = 2 * _tmp497;
  const Scalar _tmp499 = _tmp149 + _tmp87;
  const Scalar _tmp500 = 2 * _tmp488;
  const Scalar _tmp501 = _tmp141 + _tmp64;
  const Scalar _tmp502 = _tmp145 + _tmp501;
  const Scalar _tmp503 = 2 * _tmp487;
  const Scalar _tmp504 = _tmp500 * (_tmp151 + _tmp499) + _tmp502 * _tmp503;
  const Scalar _tmp505 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp489 + std::pow(_tmp497, Scalar(2))));
  const Scalar _tmp506 = std::cosh(_tmp493);
  const Scalar _tmp507 = std::pow(_tmp454, Scalar(-2));
  const Scalar _tmp508 = Scalar(0.1034955) * _tmp491 * _tmp507;
  const Scalar _tmp509 = (Scalar(1) / Scalar(2)) / _tmp490;
  const Scalar _tmp510 = Scalar(9.6622558468725703) * _tmp485;
  const Scalar _tmp511 = _tmp484 * _tmp507;
  const Scalar _tmp512 = Scalar(1.6799999999999999) * _tmp40;
  const Scalar _tmp513 = _tmp352 * _tmp457;
  const Scalar _tmp514 = _tmp361 * _tmp480;
  const Scalar _tmp515 = _tmp356 + _tmp358 + _tmp360;
  const Scalar _tmp516 = _tmp215 * _tmp515;
  const Scalar _tmp517 = _tmp349 + _tmp36 * _tmp512 + _tmp513 - _tmp514 - _tmp516;
  const Scalar _tmp518 = std::pow(_tmp459, Scalar(-2));
  const Scalar _tmp519 = Scalar(1.0) * _tmp518;
  const Scalar _tmp520 = _tmp517 * _tmp519;
  const Scalar _tmp521 = _tmp208 * _tmp366;
  const Scalar _tmp522 = _tmp457 * _tmp518;
  const Scalar _tmp523 = _tmp238 * _tmp522;
  const Scalar _tmp524 = _tmp460 * _tmp515;
  const Scalar _tmp525 = _tmp238 * _tmp524 + _tmp239 * _tmp521 - _tmp240 * _tmp347 -
                         _tmp386 * _tmp461 + _tmp394 + _tmp399 * _tmp461 + _tmp401 * _tmp461 -
                         _tmp402 * _tmp456 - _tmp517 * _tmp523;
  const Scalar _tmp526 = Scalar(1.0) * _tmp477;
  const Scalar _tmp527 = Scalar(1.0) * _tmp478;
  const Scalar _tmp528 = Scalar(0.5) * _tmp160;
  const Scalar _tmp529 = _tmp436 * _tmp465;
  const Scalar _tmp530 = _tmp528 * _tmp529;
  const Scalar _tmp531 = _tmp237 * _tmp520;
  const Scalar _tmp532 = Scalar(1.0) * _tmp351;
  const Scalar _tmp533 = _tmp218 * _tmp464;
  const Scalar _tmp534 = _tmp384 * _tmp533;
  const Scalar _tmp535 = _tmp236 * _tmp464;
  const Scalar _tmp536 = _tmp364 * _tmp535;
  const Scalar _tmp537 = _tmp457 * _tmp464;
  const Scalar _tmp538 = _tmp218 * _tmp537;
  const Scalar _tmp539 = Scalar(1.0) * _tmp208;
  const Scalar _tmp540 = -_tmp274 * _tmp347 - _tmp384 * _tmp538 + _tmp384 * _tmp539 -
                         _tmp457 * _tmp531 + _tmp457 * _tmp536 + _tmp467 * _tmp515;
  const Scalar _tmp541 = Scalar(1.0) * _tmp280;
  const Scalar _tmp542 = Scalar(10.359360000000001) * _tmp40;
  const Scalar _tmp543 = _tmp542 * _tmp8;
  const Scalar _tmp544 = Scalar(10.359360000000001) * _tmp13;
  const Scalar _tmp545 = Scalar(10.359360000000001) * _tmp25;
  const Scalar _tmp546 = _tmp147 * _tmp470;
  const Scalar _tmp547 = _tmp266 * _tmp470;
  const Scalar _tmp548 = Scalar(10.359360000000001) * _tmp28;
  const Scalar _tmp549 = _tmp20 * _tmp548;
  const Scalar _tmp550 = _tmp335 + _tmp395;
  const Scalar _tmp551 = -_tmp146 * _tmp547 - _tmp146 * fv1 + _tmp162 * _tmp546 -
                         _tmp268 * _tmp550 - _tmp36 * _tmp544 + _tmp48 * _tmp545 - _tmp543 +
                         _tmp549;
  const Scalar _tmp552 = _tmp20 * _tmp544;
  const Scalar _tmp553 = _tmp545 * _tmp8;
  const Scalar _tmp554 = _tmp156 * _tmp470;
  const Scalar _tmp555 = _tmp155 * _tmp547 + _tmp155 * fv1 - _tmp162 * _tmp554 + _tmp36 * _tmp548 +
                         _tmp408 * _tmp550 + _tmp48 * _tmp542 + _tmp552 + _tmp553;
  const Scalar _tmp556 = Scalar(1.0) * _tmp481;
  const Scalar _tmp557 = _tmp351 * _tmp475;
  const Scalar _tmp558 = _tmp287 * _tmp460;
  const Scalar _tmp559 = _tmp209 * _tmp212;
  const Scalar _tmp560 = -_tmp209 * _tmp352 + _tmp248 * _tmp423 + _tmp251 + _tmp361 * _tmp559;
  const Scalar _tmp561 = _tmp287 * _tmp518;
  const Scalar _tmp562 = _tmp457 * _tmp561;
  const Scalar _tmp563 = _tmp208 * _tmp446 - _tmp289 * _tmp347 - _tmp461 * _tmp560 + _tmp502 -
                         _tmp515 * _tmp558 + _tmp517 * _tmp562;
  const Scalar _tmp564 = _tmp212 * _tmp464;
  const Scalar _tmp565 =
      -_tmp458 * _tmp520 - _tmp464 * _tmp513 + _tmp464 * _tmp514 + _tmp464 * _tmp516;
  const Scalar _tmp566 = _tmp352 * _tmp464;
  const Scalar _tmp567 = _tmp215 * _tmp520;
  const Scalar _tmp568 = Scalar(1.0) * _tmp471;
  const Scalar _tmp569 = _tmp261 * _tmp522;
  const Scalar _tmp570 = _tmp261 * _tmp524 + _tmp262 * _tmp521 - _tmp263 * _tmp347 +
                         Scalar(1.0) * _tmp393 - _tmp420 * _tmp461 - _tmp422 + _tmp428 * _tmp461 +
                         _tmp429 * _tmp461 - _tmp430 * _tmp456 - _tmp517 * _tmp569;
  const Scalar _tmp571 = _tmp463 * _tmp522;
  const Scalar _tmp572 = _tmp246 * _tmp478;
  const Scalar _tmp573 = _tmp528 * _tmp572;
  const Scalar _tmp574 = Scalar(1.0) * _tmp465;
  const Scalar _tmp575 =
      -_tmp453 * _tmp511 +
      _tmp455 * (-_tmp158 * _tmp530 - _tmp158 * _tmp573 + _tmp272 * _tmp574 + _tmp415 * _tmp469 +
                 _tmp452 * _tmp527 +
                 _tmp466 * (-_tmp261 * _tmp520 - _tmp420 * _tmp464 + _tmp428 * _tmp464 +
                            _tmp429 * _tmp464 + _tmp462 * _tmp532 - _tmp463 * _tmp570) +
                 _tmp474 * _tmp551 +
                 _tmp476 * (_tmp287 * _tmp520 - _tmp463 * _tmp563 - _tmp464 * _tmp560 +
                            Scalar(1.0) * _tmp557) +
                 _tmp479 * (-_tmp238 * _tmp520 + _tmp351 * _tmp526 - _tmp386 * _tmp464 +
                            _tmp399 * _tmp464 + _tmp401 * _tmp464 - _tmp463 * _tmp525) +
                 _tmp483 * (-_tmp351 * _tmp537 + _tmp515 * _tmp564 - _tmp517 * _tmp571 + _tmp520) +
                 _tmp541 * (-_tmp463 * _tmp540 + _tmp468 * _tmp532 - _tmp531 - _tmp534 + _tmp536) +
                 _tmp555 * _tmp556 +
                 _tmp568 * (_tmp361 * _tmp564 - _tmp463 * _tmp565 + _tmp473 * _tmp532 - _tmp566 -
                            _tmp567));
  const Scalar _tmp576 =
      std::pow(Scalar(std::pow(_tmp484, Scalar(2)) * _tmp507 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp577 = _tmp486 * _tmp576;
  const Scalar _tmp578 = Scalar(1.0) * std::cosh(_tmp494);
  const Scalar _tmp579 = _tmp576 * _tmp578;
  const Scalar _tmp580 = _tmp286 * _tmp289;
  const Scalar _tmp581 =
      -_tmp207 * _tmp580 + _tmp268 * _tmp434 - _tmp280 * _tmp443 + _tmp368 * _tmp408;
  const Scalar _tmp582 = Scalar(9.6622558468725703) * _tmp581;
  const Scalar _tmp583 = Scalar(1.0) / (_tmp581);
  const Scalar _tmp584 = _tmp464 * _tmp482;
  const Scalar _tmp585 = _tmp212 * _tmp584;
  const Scalar _tmp586 = _tmp212 * _tmp462;
  const Scalar _tmp587 = _tmp212 * _tmp473;
  const Scalar _tmp588 = _tmp212 * _tmp280;
  const Scalar _tmp589 = _tmp212 * _tmp286;
  const Scalar _tmp590 = _tmp483 * _tmp518;
  const Scalar _tmp591 = _tmp517 * _tmp590;
  const Scalar _tmp592 = _tmp212 * _tmp408;
  const Scalar _tmp593 = _tmp464 * _tmp555;
  const Scalar _tmp594 = _tmp212 * _tmp477;
  const Scalar _tmp595 = _tmp246 * _tmp594;
  const Scalar _tmp596 = _tmp212 * _tmp268;
  const Scalar _tmp597 = _tmp212 * _tmp471;
  const Scalar _tmp598 = _tmp280 * _tmp468;
  const Scalar _tmp599 = _tmp457 * _tmp584;
  const Scalar _tmp600 = _tmp408 * _tmp477;
  const Scalar _tmp601 = _tmp212 * _tmp468;
  const Scalar _tmp602 = _tmp268 * _tmp462;
  const Scalar _tmp603 = _tmp242 * _tmp408;
  const Scalar _tmp604 = _tmp274 * fh1;
  const Scalar _tmp605 = _tmp279 * _tmp604;
  const Scalar _tmp606 = _tmp246 * _tmp368;
  const Scalar _tmp607 = _tmp204 * _tmp268;
  const Scalar _tmp608 = _tmp264 * _tmp268;
  const Scalar _tmp609 = _tmp434 * _tmp436;
  const Scalar _tmp610 = _tmp286 * _tmp446;
  const Scalar _tmp611 = _tmp204 * _tmp408;
  const Scalar _tmp612 = _tmp286 * _tmp447;
  const Scalar _tmp613 = _tmp275 * _tmp280;
  const Scalar _tmp614 = _tmp280 * _tmp438;
  const Scalar _tmp615 = -_tmp162 * _tmp606 - _tmp162 * _tmp609 + _tmp207 * _tmp610 +
                         _tmp272 * _tmp434 - _tmp313 * _tmp603 - _tmp313 * _tmp608 +
                         _tmp313 * _tmp612 + _tmp317 * _tmp605 - _tmp330 * _tmp613 -
                         _tmp331 * _tmp580 + _tmp368 * _tmp452 + _tmp384 * _tmp614 +
                         _tmp405 * _tmp611 - _tmp415 * _tmp443 + _tmp432 * _tmp607;
  const Scalar _tmp616 = std::pow(_tmp581, Scalar(-2));
  const Scalar _tmp617 = _tmp408 * _tmp594 + _tmp462 * _tmp596 + _tmp468 * _tmp588 +
                         _tmp473 * _tmp597 + _tmp475 * _tmp589 - _tmp480 * _tmp584;
  const Scalar _tmp618 = _tmp616 * _tmp617;
  const Scalar _tmp619 =
      std::pow(Scalar(_tmp616 * std::pow(_tmp617, Scalar(2)) + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp620 =
      _tmp619 *
      (_tmp583 * (-_tmp162 * _tmp595 + _tmp272 * _tmp586 - _tmp286 * _tmp557 -
                  _tmp351 * _tmp471 * _tmp473 - _tmp351 * _tmp598 + _tmp351 * _tmp599 -
                  _tmp351 * _tmp600 - _tmp351 * _tmp602 + _tmp415 * _tmp601 - _tmp437 * _tmp586 +
                  _tmp452 * _tmp594 + _tmp480 * _tmp591 - _tmp480 * _tmp593 - _tmp515 * _tmp585 +
                  _tmp525 * _tmp592 + _tmp540 * _tmp588 + _tmp551 * _tmp587 + _tmp563 * _tmp589 +
                  _tmp565 * _tmp597 + _tmp570 * _tmp596) -
       _tmp615 * _tmp618);
  const Scalar _tmp621 = Scalar(4.83288938413423) - _tmp183;
  const Scalar _tmp622 = 2 * _tmp621;
  const Scalar _tmp623 = -_tmp187 + Scalar(-1.7965602546229);
  const Scalar _tmp624 = 2 * _tmp623;
  const Scalar _tmp625 = _tmp622 * (_tmp318 + _tmp64) + _tmp624 * (_tmp499 + _tmp88);
  const Scalar _tmp626 = std::pow(_tmp621, Scalar(2)) + std::pow(_tmp623, Scalar(2));
  const Scalar _tmp627 = std::sqrt(_tmp626);
  const Scalar _tmp628 = (Scalar(1) / Scalar(2)) / _tmp627;
  const Scalar _tmp629 = std::asinh(_tmp583 * _tmp617);
  const Scalar _tmp630 = Scalar(9.6622558468725703) * _tmp629;
  const Scalar _tmp631 = Scalar(0.1034955) * _tmp583;
  const Scalar _tmp632 = -_tmp582 * _tmp629 - _tmp627;
  const Scalar _tmp633 = Scalar(0.1034955) * _tmp616 * _tmp632;
  const Scalar _tmp634 = _tmp631 * _tmp632;
  const Scalar _tmp635 = std::cosh(_tmp634);
  const Scalar _tmp636 = Scalar(1.0) * _tmp629;
  const Scalar _tmp637 = Scalar(1.0) * std::cosh(_tmp636);
  const Scalar _tmp638 = -_tmp180 - position_vector(2, 0) + Scalar(8.3701287145205097);
  const Scalar _tmp639 = 2 * _tmp638;
  const Scalar _tmp640 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp626 + std::pow(_tmp638, Scalar(2))));
  const Scalar _tmp641 = -Scalar(9.6622558468725703) * std::sinh(_tmp634) -
                         Scalar(9.6622558468725703) * std::sinh(_tmp636);
  const Scalar _tmp642 = _tmp262 * _tmp268;
  const Scalar _tmp643 = _tmp239 * _tmp408;
  const Scalar _tmp644 = _tmp219 * _tmp408;
  const Scalar _tmp645 = _tmp240 * _tmp246;
  const Scalar _tmp646 = _tmp219 * _tmp268;
  const Scalar _tmp647 = -_tmp162 * _tmp645 + _tmp240 * _tmp452 + _tmp263 * _tmp272 -
                         _tmp263 * _tmp437 - _tmp366 * _tmp642 - _tmp366 * _tmp643 -
                         _tmp384 * _tmp541 + _tmp402 * _tmp644 + _tmp414 * _tmp604 +
                         _tmp430 * _tmp646 - _tmp610;
  const Scalar _tmp648 = -_tmp167 + Scalar(-8.3885017487099702);
  const Scalar _tmp649 = Scalar(2.5193355532036801) - _tmp171;
  const Scalar _tmp650 = std::pow(_tmp648, Scalar(2)) + std::pow(_tmp649, Scalar(2));
  const Scalar _tmp651 = std::sqrt(_tmp650);
  const Scalar _tmp652 = _tmp268 * _tmp460;
  const Scalar _tmp653 = _tmp408 * _tmp460;
  const Scalar _tmp654 = _tmp286 * _tmp460;
  const Scalar _tmp655 = -_tmp238 * _tmp653 - _tmp261 * _tmp652 - _tmp280 * _tmp467 +
                         _tmp287 * _tmp654 - _tmp471 * _tmp472 + _tmp584;
  const Scalar _tmp656 = _tmp240 * _tmp408 + _tmp263 * _tmp268 + _tmp580 + _tmp605;
  const Scalar _tmp657 = Scalar(1.0) / (_tmp656);
  const Scalar _tmp658 = std::asinh(_tmp655 * _tmp657);
  const Scalar _tmp659 = Scalar(9.6622558468725703) * _tmp656;
  const Scalar _tmp660 = -_tmp651 - _tmp658 * _tmp659;
  const Scalar _tmp661 = Scalar(0.1034955) * _tmp657;
  const Scalar _tmp662 = _tmp660 * _tmp661;
  const Scalar _tmp663 = Scalar(1.0) * _tmp658;
  const Scalar _tmp664 = -Scalar(9.6622558468725703) * std::sinh(_tmp662) -
                         Scalar(9.6622558468725703) * std::sinh(_tmp663);
  const Scalar _tmp665 = -_tmp164 - position_vector(2, 0) + Scalar(8.4690207536791995);
  const Scalar _tmp666 = 2 * _tmp665;
  const Scalar _tmp667 = 2 * _tmp649;
  const Scalar _tmp668 = 2 * _tmp648;
  const Scalar _tmp669 = _tmp667 * (_tmp295 + _tmp87) + _tmp668 * (_tmp501 + _tmp53);
  const Scalar _tmp670 =
      (Scalar(1) / Scalar(2)) / std::sqrt(Scalar(_tmp650 + std::pow(_tmp665, Scalar(2))));
  const Scalar _tmp671 = _tmp261 * _tmp460;
  const Scalar _tmp672 = _tmp238 * _tmp460;
  const Scalar _tmp673 = _tmp246 * _tmp672;
  const Scalar _tmp674 = _tmp286 * _tmp561;
  const Scalar _tmp675 = _tmp517 * _tmp518;
  const Scalar _tmp676 = _tmp261 * _tmp268;
  const Scalar _tmp677 = _tmp238 * _tmp408;
  const Scalar _tmp678 = _tmp464 * _tmp597;
  const Scalar _tmp679 = std::pow(_tmp656, Scalar(-2));
  const Scalar _tmp680 = _tmp655 * _tmp679;
  const Scalar _tmp681 =
      std::pow(Scalar(std::pow(_tmp655, Scalar(2)) * _tmp679 + 1), Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp682 =
      _tmp681 *
      (-_tmp647 * _tmp680 +
       _tmp657 * (_tmp162 * _tmp673 - _tmp272 * _tmp671 + _tmp280 * _tmp531 + _tmp280 * _tmp534 -
                  _tmp280 * _tmp536 - _tmp361 * _tmp678 + _tmp386 * _tmp653 - _tmp399 * _tmp653 -
                  _tmp401 * _tmp653 - _tmp415 * _tmp467 + _tmp420 * _tmp652 - _tmp428 * _tmp652 -
                  _tmp429 * _tmp652 + _tmp437 * _tmp671 - _tmp452 * _tmp672 + _tmp471 * _tmp566 +
                  _tmp471 * _tmp567 - _tmp472 * _tmp551 - _tmp517 * _tmp674 + _tmp560 * _tmp654 -
                  _tmp591 + _tmp593 + _tmp675 * _tmp676 + _tmp675 * _tmp677));
  const Scalar _tmp683 = Scalar(1.0) * std::cosh(_tmp663);
  const Scalar _tmp684 = std::cosh(_tmp662);
  const Scalar _tmp685 = Scalar(0.1034955) * _tmp660 * _tmp679;
  const Scalar _tmp686 = (Scalar(1) / Scalar(2)) / _tmp651;
  const Scalar _tmp687 = Scalar(9.6622558468725703) * _tmp658;
  const Scalar _tmp688 = _tmp109 * _tmp20;
  const Scalar _tmp689 = -_tmp32 + _tmp33 - _tmp34 - _tmp35;
  const Scalar _tmp690 = _tmp25 * _tmp689;
  const Scalar _tmp691 = Scalar(0.043999999999999997) * _tmp690;
  const Scalar _tmp692 = -_tmp688 - _tmp691;
  const Scalar _tmp693 = -_tmp44 + _tmp45 + _tmp46 + _tmp47;
  const Scalar _tmp694 = _tmp41 * _tmp693;
  const Scalar _tmp695 = _tmp29 * _tmp689;
  const Scalar _tmp696 = _tmp127 - _tmp694 - _tmp695;
  const Scalar _tmp697 = _tmp49 * _tmp689;
  const Scalar _tmp698 = -_tmp697;
  const Scalar _tmp699 = _tmp37 * _tmp693;
  const Scalar _tmp700 = _tmp340 + _tmp698 - _tmp699;
  const Scalar _tmp701 = _tmp696 + _tmp700;
  const Scalar _tmp702 = _tmp14 * _tmp693;
  const Scalar _tmp703 = _tmp356 + _tmp702;
  const Scalar _tmp704 = _tmp49 * _tmp8;
  const Scalar _tmp705 = _tmp29 * _tmp693;
  const Scalar _tmp706 = _tmp704 + _tmp705;
  const Scalar _tmp707 = Scalar(0.41999999999999998) * _tmp111;
  const Scalar _tmp708 = -_tmp707;
  const Scalar _tmp709 = _tmp40 * _tmp689;
  const Scalar _tmp710 = Scalar(0.41999999999999998) * _tmp709;
  const Scalar _tmp711 = -_tmp710;
  const Scalar _tmp712 = _tmp708 + _tmp711;
  const Scalar _tmp713 = _tmp706 + _tmp712;
  const Scalar _tmp714 = _tmp60 * _tmp689;
  const Scalar _tmp715 = _tmp62 * _tmp693;
  const Scalar _tmp716 = _tmp56 + _tmp59 + _tmp714 + _tmp715;
  const Scalar _tmp717 = _tmp713 + _tmp716;
  const Scalar _tmp718 = _tmp26 * _tmp689;
  const Scalar _tmp719 = _tmp702 + _tmp718;
  const Scalar _tmp720 = _tmp58 * _tmp693;
  const Scalar _tmp721 = _tmp689 * _tmp85;
  const Scalar _tmp722 = _tmp153 + _tmp720 - _tmp721 + _tmp83;
  const Scalar _tmp723 = -_tmp704 - _tmp705;
  const Scalar _tmp724 = _tmp712 + _tmp723;
  const Scalar _tmp725 = _tmp722 + _tmp724;
  const Scalar _tmp726 = _tmp103 * (_tmp703 + _tmp717) + _tmp81 * (_tmp719 + _tmp725);
  const Scalar _tmp727 = _tmp707 + _tmp710;
  const Scalar _tmp728 = _tmp706 + _tmp727;
  const Scalar _tmp729 = -_tmp702;
  const Scalar _tmp730 = -_tmp718 + _tmp729;
  const Scalar _tmp731 = _tmp728 + _tmp730;
  const Scalar _tmp732 = _tmp722 + _tmp731;
  const Scalar _tmp733 = _tmp357 + _tmp729;
  const Scalar _tmp734 = _tmp723 + _tmp727;
  const Scalar _tmp735 = _tmp716 + _tmp734;
  const Scalar _tmp736 = _tmp500 * (_tmp733 + _tmp735) + _tmp503 * _tmp732;
  const Scalar _tmp737 = _tmp152 - _tmp720 + _tmp721 + _tmp84;
  const Scalar _tmp738 = _tmp719 + _tmp728;
  const Scalar _tmp739 = _tmp737 + _tmp738;
  const Scalar _tmp740 = _tmp137 + _tmp57 - _tmp714 - _tmp715;
  const Scalar _tmp741 = _tmp733 + _tmp740;
  const Scalar _tmp742 = _tmp713 + _tmp741;
  const Scalar _tmp743 = _tmp320 * _tmp739 + _tmp321 * _tmp742;
  const Scalar _tmp744 = _tmp120 + _tmp697 + _tmp699;
  const Scalar _tmp745 = _tmp688 + _tmp691;
  const Scalar _tmp746 = _tmp744 + _tmp745;
  const Scalar _tmp747 = _tmp696 + _tmp746;
  const Scalar _tmp748 = _tmp701 + _tmp745;
  const Scalar _tmp749 = _tmp200 * _tmp748;
  const Scalar _tmp750 = _tmp325 * _tmp743;
  const Scalar _tmp751 = _tmp174 * _tmp739;
  const Scalar _tmp752 = _tmp724 + _tmp737;
  const Scalar _tmp753 = _tmp719 + _tmp752;
  const Scalar _tmp754 = _tmp199 * _tmp753;
  const Scalar _tmp755 = _tmp703 + _tmp740;
  const Scalar _tmp756 = _tmp734 + _tmp755;
  const Scalar _tmp757 = _tmp730 + _tmp752;
  const Scalar _tmp758 = _tmp297 * _tmp756 + _tmp299 * _tmp757;
  const Scalar _tmp759 = _tmp303 * _tmp758;
  const Scalar _tmp760 = _tmp713 + _tmp755;
  const Scalar _tmp761 = _tmp195 * _tmp760;
  const Scalar _tmp762 = _tmp283 * _tmp761;
  const Scalar _tmp763 = _tmp190 * _tmp756;
  const Scalar _tmp764 = _tmp190 * _tmp757;
  const Scalar _tmp765 = _tmp306 * _tmp758;
  const Scalar _tmp766 = _tmp333 + _tmp694 + _tmp695;
  const Scalar _tmp767 = _tmp700 + _tmp766;
  const Scalar _tmp768 = _tmp745 + _tmp767;
  const Scalar _tmp769 = -_tmp180 * _tmp759 + _tmp180 * _tmp764 + _tmp191 * _tmp768 -
                         _tmp192 * _tmp749 - _tmp201 * _tmp763 + _tmp201 * _tmp765 -
                         _tmp216 * _tmp754 + _tmp216 * _tmp762;
  const Scalar _tmp770 = _tmp327 * _tmp743;
  const Scalar _tmp771 = _tmp174 * _tmp742;
  const Scalar _tmp772 = _tmp175 * _tmp754 - _tmp175 * _tmp762 - _tmp200 * _tmp770 +
                         _tmp200 * _tmp771 + _tmp750 - _tmp751;
  const Scalar _tmp773 = _tmp204 * _tmp772;
  const Scalar _tmp774 = _tmp178 * _tmp742;
  const Scalar _tmp775 = _tmp312 * (_tmp192 * _tmp754 - _tmp192 * _tmp762 + _tmp200 * _tmp763 -
                                    _tmp200 * _tmp765 + _tmp759 - _tmp764);
  const Scalar _tmp776 = _tmp202 * _tmp775;
  const Scalar _tmp777 = -_tmp164 * _tmp750 + _tmp164 * _tmp751 - _tmp175 * _tmp749 -
                         _tmp179 * _tmp754 + _tmp179 * _tmp762 - _tmp200 * _tmp774 +
                         _tmp201 * _tmp770 - _tmp202 * _tmp773 + _tmp205 * _tmp747 +
                         _tmp206 * _tmp776 - _tmp207 * _tmp769;
  const Scalar _tmp778 = _tmp206 * _tmp217;
  const Scalar _tmp779 = _tmp177 * _tmp763 - _tmp177 * _tmp765 - _tmp180 * _tmp763 +
                         _tmp180 * _tmp765 + _tmp192 * _tmp748 - _tmp192 * _tmp768;
  const Scalar _tmp780 = _tmp348 * _tmp693;
  const Scalar _tmp781 = -Scalar(1.6799999999999999) * _tmp690 - _tmp780;
  const Scalar _tmp782 = _tmp350 * _tmp781;
  const Scalar _tmp783 = _tmp214 * _tmp782;
  const Scalar _tmp784 = _tmp689 * _tmp89;
  const Scalar _tmp785 = _tmp15 + _tmp359 * _tmp693;
  const Scalar _tmp786 = _tmp139 - _tmp784 + _tmp785;
  const Scalar _tmp787 = -_tmp175 * _tmp747 + _tmp175 * _tmp748 - _tmp207 * _tmp779 +
                         _tmp208 * _tmp783 - _tmp215 * _tmp777 - _tmp217 * _tmp773 -
                         _tmp353 * _tmp743 + _tmp354 * _tmp743 - _tmp355 * _tmp742 -
                         _tmp362 * _tmp786 + _tmp774 + _tmp775 * _tmp778;
  const Scalar _tmp788 = _tmp365 * _tmp787;
  const Scalar _tmp789 = _tmp400 * _tmp787;
  const Scalar _tmp790 = _tmp206 * _tmp229;
  const Scalar _tmp791 =
      (Scalar(1) / Scalar(2)) * _tmp249 * _tmp753 + (Scalar(1) / Scalar(2)) * _tmp252 * _tmp760;
  const Scalar _tmp792 = _tmp378 * _tmp791;
  const Scalar _tmp793 = _tmp370 * _tmp760;
  const Scalar _tmp794 = _tmp373 * _tmp791;
  const Scalar _tmp795 =
      _tmp227 * (-_tmp193 * _tmp223 * _tmp760 + _tmp223 * _tmp761 + _tmp224 * _tmp753 -
                 _tmp225 * _tmp753 + _tmp375 * _tmp794 - _tmp376 * _tmp794);
  const Scalar _tmp796 = _tmp182 * _tmp763 - _tmp182 * _tmp765 + _tmp186 * _tmp759 -
                         _tmp186 * _tmp764 + _tmp188 * _tmp764 - _tmp191 * _tmp756 +
                         _tmp192 * _tmp792 - _tmp192 * _tmp793 + _tmp192 * _tmp795 +
                         _tmp228 * _tmp763 - _tmp228 * _tmp765;
  const Scalar _tmp797 = _tmp170 * _tmp750 - _tmp170 * _tmp751 + _tmp172 * _tmp751 +
                         _tmp175 * _tmp792 - _tmp175 * _tmp793 + _tmp175 * _tmp795 -
                         _tmp205 * _tmp742 - _tmp207 * _tmp796 - _tmp228 * _tmp770 +
                         _tmp228 * _tmp771 - _tmp229 * _tmp773 + _tmp369 * _tmp742 -
                         _tmp381 * _tmp743 + _tmp775 * _tmp790;
  const Scalar _tmp798 = _tmp383 * _tmp797;
  const Scalar _tmp799 = _tmp385 * _tmp798;
  const Scalar _tmp800 = _tmp204 * _tmp762;
  const Scalar _tmp801 = _tmp204 * _tmp754;
  const Scalar _tmp802 = _tmp177 * _tmp754 - _tmp177 * _tmp762 - _tmp200 * _tmp776 -
                         _tmp202 * _tmp800 + _tmp202 * _tmp801 + _tmp230 * _tmp769 + _tmp749;
  const Scalar _tmp803 = _tmp692 + _tmp744;
  const Scalar _tmp804 = _tmp766 + _tmp803;
  const Scalar _tmp805 = -_tmp215 * _tmp802 - _tmp217 * _tmp800 + _tmp217 * _tmp801 +
                         _tmp230 * _tmp779 + _tmp232 * _tmp783 - _tmp391 * _tmp775 -
                         _tmp392 * _tmp786 + _tmp804;
  const Scalar _tmp806 = _tmp237 * (-_tmp229 * _tmp800 + _tmp229 * _tmp801 + _tmp230 * _tmp796 -
                                    _tmp234 * _tmp797 + _tmp387 * _tmp788 - _tmp390 * _tmp775 -
                                    _tmp398 * _tmp805 - _tmp792 + _tmp793 - _tmp795);
  const Scalar _tmp807 = _tmp789 - _tmp799 + _tmp805 + _tmp806;
  const Scalar _tmp808 =
      -_tmp240 * _tmp772 - _tmp241 * _tmp807 + _tmp404 * _tmp788 - _tmp754 + _tmp762;
  const Scalar _tmp809 = _tmp192 * _tmp775;
  const Scalar _tmp810 = _tmp284 * _tmp760;
  const Scalar _tmp811 = _tmp731 + _tmp737;
  const Scalar _tmp812 = _tmp734 + _tmp741;
  const Scalar _tmp813 = _tmp148 * _tmp811 + _tmp157 * _tmp812;
  const Scalar _tmp814 = _tmp161 * _tmp813;
  const Scalar _tmp815 = _tmp266 * _tmp811;
  const Scalar _tmp816 = _tmp100 * _tmp815 - _tmp156 * _tmp815 + _tmp267 * _tmp812 -
                         _tmp278 * _tmp812 - _tmp411 * _tmp814 + _tmp412 * _tmp814;
  const Scalar _tmp817 = _tmp816 * fh1;
  const Scalar _tmp818 = _tmp206 * _tmp274;
  const Scalar _tmp819 = _tmp255 * _tmp769;
  const Scalar _tmp820 = _tmp215 * _tmp819 - _tmp255 * _tmp779 - _tmp256 * _tmp783 +
                         _tmp421 * _tmp786 - _tmp423 * _tmp776 + _tmp424 * _tmp775;
  const Scalar _tmp821 = _tmp237 * (-_tmp255 * _tmp796 - _tmp258 * _tmp797 - _tmp398 * _tmp820 +
                                    _tmp426 * _tmp788 + _tmp427 * _tmp775);
  const Scalar _tmp822 = _tmp419 * _tmp798;
  const Scalar _tmp823 = _tmp260 * _tmp787;
  const Scalar _tmp824 = _tmp820 + _tmp821 - _tmp822 + _tmp823;
  const Scalar _tmp825 = -_tmp241 * _tmp824 - _tmp263 * _tmp772 + _tmp431 * _tmp788;
  const Scalar _tmp826 = _tmp436 * _tmp814;
  const Scalar _tmp827 = _tmp271 * _tmp812;
  const Scalar _tmp828 = _tmp815 * fh1;
  const Scalar _tmp829 = _tmp288 * _tmp788;
  const Scalar _tmp830 =
      -_tmp245 * _tmp827 + _tmp247 * _tmp814 + _tmp269 * _tmp810 - _tmp270 * _tmp791 +
      _tmp273 * _tmp826 - _tmp273 * _tmp828 + _tmp281 * _tmp810 - _tmp282 * _tmp791 +
      _tmp293 * _tmp760 -
      _tmp409 * (_tmp240 * _tmp771 - _tmp242 * _tmp809 + _tmp243 * _tmp808 - _tmp367 * _tmp788 +
                 _tmp368 * _tmp763 - _tmp368 * _tmp765 + _tmp403 * _tmp807 - _tmp406 * _tmp743) -
      _tmp410 * _tmp791 - _tmp416 * _tmp817 + _tmp417 * _tmp810 - _tmp418 * _tmp791 -
      _tmp435 * (_tmp243 * _tmp825 - _tmp263 * _tmp770 + _tmp263 * _tmp771 - _tmp264 * _tmp809 +
                 _tmp403 * _tmp824 - _tmp433 * _tmp788 + _tmp434 * _tmp763 - _tmp434 * _tmp765) -
      _tmp445 * (_tmp274 * _tmp771 - _tmp276 * _tmp772 + _tmp439 * _tmp798 + _tmp441 * _tmp758 -
                 _tmp442 * _tmp743 - _tmp443 * _tmp763 - _tmp444 * _tmp798 + _tmp809 * _tmp818) -
      _tmp451 * (-_tmp175 * _tmp829 + _tmp289 * _tmp771 - _tmp290 * _tmp763 + _tmp290 * _tmp765 +
                 _tmp447 * _tmp809 - _tmp448 * _tmp743 + _tmp449 * _tmp829 - _tmp450 * _tmp773);
  const Scalar _tmp831 = _tmp480 * _tmp786;
  const Scalar _tmp832 = _tmp457 * _tmp783;
  const Scalar _tmp833 = _tmp27 + _tmp784 + _tmp785;
  const Scalar _tmp834 = _tmp215 * _tmp833;
  const Scalar _tmp835 = _tmp20 * _tmp512 + _tmp780 - _tmp831 + _tmp832 - _tmp834;
  const Scalar _tmp836 = _tmp519 * _tmp835;
  const Scalar _tmp837 = _tmp350 * _tmp475;
  const Scalar _tmp838 = _tmp208 * _tmp788;
  const Scalar _tmp839 = -_tmp209 * _tmp783 + _tmp423 * _tmp753 + _tmp559 * _tmp786 + _tmp760;
  const Scalar _tmp840 = _tmp288 * _tmp838 - _tmp289 * _tmp777 - _tmp461 * _tmp839 -
                         _tmp558 * _tmp833 + _tmp562 * _tmp835 + _tmp732;
  const Scalar _tmp841 = _tmp350 * _tmp473;
  const Scalar _tmp842 = _tmp781 * _tmp841;
  const Scalar _tmp843 = _tmp464 * _tmp783;
  const Scalar _tmp844 = _tmp215 * _tmp836;
  const Scalar _tmp845 =
      -_tmp458 * _tmp836 + _tmp464 * _tmp831 - _tmp464 * _tmp832 + _tmp464 * _tmp834;
  const Scalar _tmp846 = _tmp208 * _tmp262;
  const Scalar _tmp847 = _tmp460 * _tmp833;
  const Scalar _tmp848 = _tmp261 * _tmp847 - _tmp263 * _tmp777 - _tmp456 * _tmp824 +
                         _tmp461 * _tmp821 - _tmp461 * _tmp822 + _tmp461 * _tmp823 -
                         _tmp569 * _tmp835 + Scalar(1.0) * _tmp776 + _tmp788 * _tmp846 - _tmp819;
  const Scalar _tmp849 = Scalar(1.0) * _tmp782;
  const Scalar _tmp850 = _tmp746 + _tmp766;
  const Scalar _tmp851 = _tmp408 * _tmp850 + _tmp543 + _tmp544 * _tmp689 + _tmp545 * _tmp693 +
                         _tmp547 * _tmp812 + _tmp549 - _tmp554 * _tmp814 + _tmp812 * fv1;
  const Scalar _tmp852 = -_tmp268 * _tmp850 - _tmp470 * _tmp815 - _tmp542 * _tmp693 +
                         _tmp546 * _tmp814 + _tmp548 * _tmp689 - _tmp552 + _tmp553 - _tmp811 * fv1;
  const Scalar _tmp853 = _tmp238 * _tmp847 + _tmp239 * _tmp838 - _tmp240 * _tmp777 -
                         _tmp456 * _tmp807 + _tmp461 * _tmp789 - _tmp461 * _tmp799 +
                         _tmp461 * _tmp806 - _tmp523 * _tmp835 + _tmp802;
  const Scalar _tmp854 = _tmp535 * _tmp787;
  const Scalar _tmp855 = _tmp237 * _tmp836;
  const Scalar _tmp856 = -_tmp274 * _tmp777 + _tmp457 * _tmp854 - _tmp457 * _tmp855 +
                         _tmp467 * _tmp833 - _tmp538 * _tmp798 + _tmp539 * _tmp798;
  const Scalar _tmp857 = _tmp533 * _tmp798;
  const Scalar _tmp858 =
      _tmp455 * (_tmp466 * (-_tmp261 * _tmp836 + _tmp462 * _tmp849 - _tmp463 * _tmp848 +
                            _tmp464 * _tmp821 - _tmp464 * _tmp822 + _tmp464 * _tmp823) +
                 _tmp469 * _tmp817 + _tmp474 * _tmp852 +
                 _tmp476 * (_tmp287 * _tmp836 - _tmp463 * _tmp840 - _tmp464 * _tmp839 +
                            Scalar(1.0) * _tmp781 * _tmp837) +
                 _tmp479 * (-_tmp238 * _tmp836 - _tmp463 * _tmp853 + _tmp464 * _tmp789 -
                            _tmp464 * _tmp799 + _tmp464 * _tmp806 + _tmp526 * _tmp782) +
                 _tmp483 * (-_tmp537 * _tmp782 + _tmp564 * _tmp833 - _tmp571 * _tmp835 + _tmp836) +
                 _tmp527 * _tmp827 - _tmp530 * _tmp813 +
                 _tmp541 * (-_tmp463 * _tmp856 + _tmp468 * _tmp849 + _tmp854 - _tmp855 - _tmp857) +
                 _tmp556 * _tmp851 +
                 _tmp568 * (-_tmp463 * _tmp845 + _tmp564 * _tmp786 + Scalar(1.0) * _tmp842 -
                            _tmp843 - _tmp844) -
                 _tmp573 * _tmp813 + _tmp574 * _tmp828) -
      _tmp511 * _tmp830;
  const Scalar _tmp859 = Scalar(9.6622558468725703) * _tmp830;
  const Scalar _tmp860 = _tmp206 * _tmp605;
  const Scalar _tmp861 = _tmp286 * _tmp829;
  const Scalar _tmp862 = _tmp207 * _tmp861 + _tmp368 * _tmp827 + _tmp434 * _tmp828 -
                         _tmp443 * _tmp817 - _tmp580 * _tmp773 - _tmp603 * _tmp775 -
                         _tmp606 * _tmp814 + _tmp607 * _tmp825 - _tmp608 * _tmp775 -
                         _tmp609 * _tmp814 + _tmp611 * _tmp808 + _tmp612 * _tmp775 -
                         _tmp613 * _tmp772 + _tmp614 * _tmp798 + _tmp775 * _tmp860;
  const Scalar _tmp863 = _tmp590 * _tmp835;
  const Scalar _tmp864 = _tmp464 * _tmp851;
  const Scalar _tmp865 = _tmp286 * _tmp837;
  const Scalar _tmp866 =
      _tmp619 *
      (_tmp583 * (-_tmp471 * _tmp842 + _tmp480 * _tmp863 - _tmp480 * _tmp864 - _tmp585 * _tmp833 -
                  _tmp586 * _tmp826 + _tmp586 * _tmp828 + _tmp587 * _tmp852 + _tmp588 * _tmp856 +
                  _tmp589 * _tmp840 + _tmp592 * _tmp853 + _tmp594 * _tmp827 - _tmp595 * _tmp814 +
                  _tmp596 * _tmp848 + _tmp597 * _tmp845 - _tmp598 * _tmp782 + _tmp599 * _tmp782 -
                  _tmp600 * _tmp782 + _tmp601 * _tmp817 - _tmp602 * _tmp782 - _tmp781 * _tmp865) -
       _tmp618 * _tmp862);
  const Scalar _tmp867 = _tmp622 * (_tmp722 + _tmp738) + _tmp624 * (_tmp717 + _tmp733);
  const Scalar _tmp868 = _tmp240 * _tmp271;
  const Scalar _tmp869 = -_tmp263 * _tmp826 + _tmp263 * _tmp828 - _tmp541 * _tmp798 +
                         _tmp604 * _tmp816 - _tmp642 * _tmp788 - _tmp643 * _tmp788 +
                         _tmp644 * _tmp807 - _tmp645 * _tmp814 + _tmp646 * _tmp824 +
                         _tmp812 * _tmp868 - _tmp861;
  const Scalar _tmp870 = _tmp667 * (_tmp703 + _tmp735) + _tmp668 * (_tmp725 + _tmp730);
  const Scalar _tmp871 = _tmp518 * _tmp676;
  const Scalar _tmp872 = _tmp518 * _tmp677;
  const Scalar _tmp873 =
      _tmp657 * (-_tmp280 * _tmp854 + _tmp280 * _tmp855 + _tmp280 * _tmp857 - _tmp467 * _tmp817 +
                 _tmp471 * _tmp843 + _tmp471 * _tmp844 - _tmp472 * _tmp852 - _tmp652 * _tmp821 +
                 _tmp652 * _tmp822 - _tmp652 * _tmp823 - _tmp653 * _tmp789 + _tmp653 * _tmp799 -
                 _tmp653 * _tmp806 + _tmp654 * _tmp839 + _tmp671 * _tmp826 - _tmp671 * _tmp828 -
                 _tmp672 * _tmp827 + _tmp673 * _tmp814 - _tmp674 * _tmp835 - _tmp678 * _tmp786 +
                 _tmp835 * _tmp871 + _tmp835 * _tmp872 - _tmp863 + _tmp864) -
      _tmp680 * _tmp869;
  const Scalar _tmp874 = _tmp659 * _tmp681;
  const Scalar _tmp875 = _tmp681 * _tmp683;
  const Scalar _tmp876 = _tmp109 * _tmp48;
  const Scalar _tmp877 = _tmp1 + _tmp3 - _tmp5 + _tmp7;
  const Scalar _tmp878 = _tmp25 * _tmp877;
  const Scalar _tmp879 = Scalar(0.043999999999999997) * _tmp878;
  const Scalar _tmp880 = -_tmp876 - _tmp879;
  const Scalar _tmp881 = _tmp49 * _tmp877;
  const Scalar _tmp882 = _tmp29 * _tmp48;
  const Scalar _tmp883 = _tmp708 + _tmp710 - _tmp881 + _tmp882;
  const Scalar _tmp884 = _tmp880 + _tmp883;
  const Scalar _tmp885 = Scalar(0.41999999999999998) * _tmp690;
  const Scalar _tmp886 = _tmp29 * _tmp877;
  const Scalar _tmp887 = _tmp52 - _tmp885 - _tmp886;
  const Scalar _tmp888 = _tmp40 * _tmp55;
  const Scalar _tmp889 = _tmp48 * _tmp60;
  const Scalar _tmp890 = _tmp62 * _tmp689;
  const Scalar _tmp891 = _tmp85 * _tmp877;
  const Scalar _tmp892 = _tmp888 + _tmp889 - _tmp890 - _tmp891;
  const Scalar _tmp893 = _tmp14 * _tmp20;
  const Scalar _tmp894 = Scalar(0.83999999999999997) * _tmp878;
  const Scalar _tmp895 = _tmp893 + _tmp894;
  const Scalar _tmp896 = _tmp119 + _tmp698;
  const Scalar _tmp897 = _tmp41 * _tmp877;
  const Scalar _tmp898 = _tmp116 - _tmp897;
  const Scalar _tmp899 = _tmp896 + _tmp898;
  const Scalar _tmp900 = _tmp895 + _tmp899;
  const Scalar _tmp901 = _tmp48 * _tmp89;
  const Scalar _tmp902 = _tmp893 + _tmp901;
  const Scalar _tmp903 = _tmp118 + _tmp697;
  const Scalar _tmp904 = _tmp898 + _tmp903;
  const Scalar _tmp905 = Scalar(0.021999999999999999) * _tmp709;
  const Scalar _tmp906 = _tmp60 * _tmp877;
  const Scalar _tmp907 = _tmp25 * _tmp55;
  const Scalar _tmp908 = _tmp48 * _tmp85;
  const Scalar _tmp909 = _tmp905 + _tmp906 + _tmp907 + _tmp908;
  const Scalar _tmp910 = _tmp904 + _tmp909;
  const Scalar _tmp911 = _tmp103 * (_tmp902 + _tmp910) + _tmp81 * (_tmp892 + _tmp900);
  const Scalar _tmp912 = -_tmp888 - _tmp889 + _tmp890 + _tmp891;
  const Scalar _tmp913 = _tmp115 + _tmp897;
  const Scalar _tmp914 = _tmp903 + _tmp913;
  const Scalar _tmp915 = _tmp895 + _tmp914;
  const Scalar _tmp916 = _tmp912 + _tmp915;
  const Scalar _tmp917 = -_tmp905 - _tmp906 - _tmp907 - _tmp908;
  const Scalar _tmp918 = -_tmp893;
  const Scalar _tmp919 = -_tmp901 + _tmp918;
  const Scalar _tmp920 = _tmp917 + _tmp919;
  const Scalar _tmp921 = _tmp904 + _tmp920;
  const Scalar _tmp922 = _tmp320 * _tmp916 + _tmp321 * _tmp921;
  const Scalar _tmp923 = _tmp896 + _tmp913;
  const Scalar _tmp924 = _tmp902 + _tmp917;
  const Scalar _tmp925 = _tmp923 + _tmp924;
  const Scalar _tmp926 = -_tmp894 + _tmp918;
  const Scalar _tmp927 = _tmp899 + _tmp926;
  const Scalar _tmp928 = _tmp912 + _tmp927;
  const Scalar _tmp929 = _tmp297 * _tmp925 + _tmp299 * _tmp928;
  const Scalar _tmp930 = _tmp306 * _tmp929;
  const Scalar _tmp931 = _tmp876 + _tmp879;
  const Scalar _tmp932 = _tmp887 + _tmp931;
  const Scalar _tmp933 = _tmp883 + _tmp932;
  const Scalar _tmp934 = _tmp192 * _tmp933;
  const Scalar _tmp935 = _tmp143 + _tmp885 + _tmp886;
  const Scalar _tmp936 = _tmp931 + _tmp935;
  const Scalar _tmp937 = _tmp883 + _tmp936;
  const Scalar _tmp938 = _tmp190 * _tmp925;
  const Scalar _tmp939 = -_tmp177 * _tmp930 + _tmp177 * _tmp938 + _tmp180 * _tmp930 -
                         _tmp180 * _tmp938 - _tmp192 * _tmp937 + _tmp934;
  const Scalar _tmp940 = _tmp707 + _tmp711 + _tmp881 - _tmp882;
  const Scalar _tmp941 = _tmp932 + _tmp940;
  const Scalar _tmp942 = _tmp190 * _tmp928;
  const Scalar _tmp943 = _tmp303 * _tmp929;
  const Scalar _tmp944 = _tmp904 + _tmp924;
  const Scalar _tmp945 = _tmp308 * _tmp944;
  const Scalar _tmp946 = _tmp900 + _tmp912;
  const Scalar _tmp947 = _tmp199 * _tmp946;
  const Scalar _tmp948 = _tmp312 * (-_tmp192 * _tmp945 + _tmp192 * _tmp947 - _tmp200 * _tmp930 +
                                    _tmp200 * _tmp938 - _tmp942 + _tmp943);
  const Scalar _tmp949 = _tmp202 * _tmp948;
  const Scalar _tmp950 = _tmp327 * _tmp922;
  const Scalar _tmp951 = _tmp180 * _tmp942 - _tmp180 * _tmp943 + _tmp191 * _tmp937 -
                         _tmp200 * _tmp934 + _tmp201 * _tmp930 - _tmp201 * _tmp938 +
                         _tmp216 * _tmp945 - _tmp216 * _tmp947;
  const Scalar _tmp952 = _tmp174 * _tmp916;
  const Scalar _tmp953 = _tmp325 * _tmp922;
  const Scalar _tmp954 = _tmp174 * _tmp921;
  const Scalar _tmp955 = -_tmp175 * _tmp945 + _tmp175 * _tmp947 - _tmp200 * _tmp950 +
                         _tmp200 * _tmp954 - _tmp952 + _tmp953;
  const Scalar _tmp956 = _tmp204 * _tmp955;
  const Scalar _tmp957 = _tmp178 * _tmp921;
  const Scalar _tmp958 = _tmp200 * _tmp933;
  const Scalar _tmp959 = _tmp164 * _tmp952 - _tmp164 * _tmp953 - _tmp175 * _tmp958 +
                         _tmp179 * _tmp945 - _tmp179 * _tmp947 - _tmp200 * _tmp957 +
                         _tmp201 * _tmp950 - _tmp202 * _tmp956 + _tmp205 * _tmp941 +
                         _tmp206 * _tmp949 - _tmp207 * _tmp951;
  const Scalar _tmp960 = _tmp20 * _tmp348;
  const Scalar _tmp961 = -Scalar(1.6799999999999999) * _tmp878 - _tmp960;
  const Scalar _tmp962 = _tmp350 * _tmp961;
  const Scalar _tmp963 = _tmp214 * _tmp962;
  const Scalar _tmp964 = _tmp877 * _tmp89;
  const Scalar _tmp965 = _tmp26 * _tmp48;
  const Scalar _tmp966 = _tmp14 * _tmp689 + _tmp20 * _tmp359;
  const Scalar _tmp967 = -_tmp964 - _tmp965 + _tmp966;
  const Scalar _tmp968 = _tmp175 * _tmp933 - _tmp175 * _tmp941 - _tmp207 * _tmp939 +
                         _tmp208 * _tmp963 - _tmp215 * _tmp959 - _tmp217 * _tmp956 -
                         _tmp353 * _tmp922 + _tmp354 * _tmp922 - _tmp355 * _tmp921 -
                         _tmp362 * _tmp967 + _tmp778 * _tmp948 + _tmp957;
  const Scalar _tmp969 = _tmp260 * _tmp968;
  const Scalar _tmp970 = Scalar(1.0) * _tmp961;
  const Scalar _tmp971 = _tmp350 * _tmp970;
  const Scalar _tmp972 =
      (Scalar(1) / Scalar(2)) * _tmp249 * _tmp946 + (Scalar(1) / Scalar(2)) * _tmp252 * _tmp944;
  const Scalar _tmp973 = _tmp378 * _tmp972;
  const Scalar _tmp974 = _tmp223 * _tmp944;
  const Scalar _tmp975 = _tmp373 * _tmp972;
  const Scalar _tmp976 = _tmp223 * _tmp946;
  const Scalar _tmp977 = _tmp227 * (-_tmp193 * _tmp974 + _tmp195 * _tmp974 + _tmp196 * _tmp976 -
                                    _tmp198 * _tmp976 + _tmp375 * _tmp975 - _tmp376 * _tmp975);
  const Scalar _tmp978 = _tmp370 * _tmp944;
  const Scalar _tmp979 = -_tmp182 * _tmp930 + _tmp182 * _tmp938 - _tmp186 * _tmp942 +
                         _tmp186 * _tmp943 + _tmp188 * _tmp942 - _tmp191 * _tmp925 +
                         _tmp192 * _tmp973 + _tmp192 * _tmp977 - _tmp192 * _tmp978 -
                         _tmp228 * _tmp930 + _tmp228 * _tmp938;
  const Scalar _tmp980 = -_tmp170 * _tmp952 + _tmp170 * _tmp953 + _tmp172 * _tmp952 +
                         _tmp175 * _tmp973 + _tmp175 * _tmp977 - _tmp175 * _tmp978 -
                         _tmp205 * _tmp921 - _tmp207 * _tmp979 - _tmp228 * _tmp950 +
                         _tmp228 * _tmp954 - _tmp229 * _tmp956 + _tmp369 * _tmp921 -
                         _tmp381 * _tmp922 + _tmp790 * _tmp948;
  const Scalar _tmp981 = _tmp383 * _tmp980;
  const Scalar _tmp982 = _tmp419 * _tmp981;
  const Scalar _tmp983 = _tmp255 * _tmp951;
  const Scalar _tmp984 = _tmp215 * _tmp983 - _tmp255 * _tmp939 - _tmp256 * _tmp963 +
                         _tmp421 * _tmp967 - _tmp423 * _tmp949 + _tmp424 * _tmp948;
  const Scalar _tmp985 = _tmp365 * _tmp968;
  const Scalar _tmp986 = _tmp237 * (-_tmp255 * _tmp979 - _tmp258 * _tmp980 - _tmp398 * _tmp984 +
                                    _tmp426 * _tmp985 + _tmp427 * _tmp948);
  const Scalar _tmp987 = _tmp969 - _tmp982 + _tmp984 + _tmp986;
  const Scalar _tmp988 = _tmp964 + _tmp965 + _tmp966;
  const Scalar _tmp989 = _tmp215 * _tmp988;
  const Scalar _tmp990 = _tmp480 * _tmp967;
  const Scalar _tmp991 = _tmp457 * _tmp963;
  const Scalar _tmp992 = _tmp48 * _tmp512 + _tmp960 - _tmp989 - _tmp990 + _tmp991;
  const Scalar _tmp993 = _tmp460 * _tmp988;
  const Scalar _tmp994 = _tmp261 * _tmp993 - _tmp263 * _tmp959 - _tmp456 * _tmp987 +
                         _tmp461 * _tmp969 - _tmp461 * _tmp982 + _tmp461 * _tmp986 -
                         _tmp569 * _tmp992 + _tmp846 * _tmp985 + Scalar(1.0) * _tmp949 - _tmp983;
  const Scalar _tmp995 = _tmp519 * _tmp992;
  const Scalar _tmp996 = _tmp237 * _tmp995;
  const Scalar _tmp997 = _tmp535 * _tmp968;
  const Scalar _tmp998 = -_tmp274 * _tmp959 - _tmp457 * _tmp996 + _tmp457 * _tmp997 +
                         _tmp467 * _tmp988 - _tmp538 * _tmp981 + _tmp539 * _tmp981;
  const Scalar _tmp999 = _tmp533 * _tmp981;
  const Scalar _tmp1000 = _tmp914 + _tmp926;
  const Scalar _tmp1001 = _tmp1000 + _tmp912;
  const Scalar _tmp1002 = _tmp920 + _tmp923;
  const Scalar _tmp1003 = _tmp1001 * _tmp148 + _tmp1002 * _tmp157;
  const Scalar _tmp1004 = _tmp1003 * _tmp161;
  const Scalar _tmp1005 = _tmp936 + _tmp940;
  const Scalar _tmp1006 = -_tmp1001 * _tmp547 - _tmp1001 * fv1 + _tmp1004 * _tmp546 -
                          _tmp1005 * _tmp268 - _tmp20 * _tmp542 - _tmp48 * _tmp544 +
                          _tmp548 * _tmp877 + Scalar(10.359360000000001) * _tmp690;
  const Scalar _tmp1007 = -_tmp209 * _tmp963 + _tmp423 * _tmp946 + _tmp559 * _tmp967 + _tmp944;
  const Scalar _tmp1008 = _tmp288 * _tmp985;
  const Scalar _tmp1009 = _tmp1000 + _tmp892;
  const Scalar _tmp1010 = -_tmp1007 * _tmp461 + _tmp1008 * _tmp208 + _tmp1009 - _tmp289 * _tmp959 -
                          _tmp558 * _tmp988 + _tmp562 * _tmp992;
  const Scalar _tmp1011 = _tmp1001 * _tmp271;
  const Scalar _tmp1012 = _tmp385 * _tmp981;
  const Scalar _tmp1013 = _tmp400 * _tmp968;
  const Scalar _tmp1014 = _tmp204 * _tmp947;
  const Scalar _tmp1015 = _tmp204 * _tmp945;
  const Scalar _tmp1016 = _tmp1014 * _tmp202 - _tmp1015 * _tmp202 - _tmp177 * _tmp945 +
                          _tmp177 * _tmp947 - _tmp200 * _tmp949 + _tmp230 * _tmp951 + _tmp958;
  const Scalar _tmp1017 = _tmp880 + _tmp940;
  const Scalar _tmp1018 = _tmp1017 + _tmp935;
  const Scalar _tmp1019 = _tmp1014 * _tmp217 - _tmp1015 * _tmp217 - _tmp1016 * _tmp215 + _tmp1018 +
                          _tmp230 * _tmp939 + _tmp232 * _tmp963 - _tmp391 * _tmp948 -
                          _tmp392 * _tmp967;
  const Scalar _tmp1020 = _tmp237 * (_tmp1014 * _tmp229 - _tmp1015 * _tmp229 - _tmp1019 * _tmp398 +
                                     _tmp230 * _tmp979 - _tmp234 * _tmp980 + _tmp387 * _tmp985 -
                                     _tmp390 * _tmp948 - _tmp973 - _tmp977 + _tmp978);
  const Scalar _tmp1021 = _tmp239 * _tmp985;
  const Scalar _tmp1022 = -_tmp1012 + _tmp1013 + _tmp1019 + _tmp1020;
  const Scalar _tmp1023 = -_tmp1012 * _tmp461 + _tmp1013 * _tmp461 + _tmp1016 + _tmp1020 * _tmp461 +
                          _tmp1021 * _tmp208 - _tmp1022 * _tmp456 + _tmp238 * _tmp993 -
                          _tmp240 * _tmp959 - _tmp523 * _tmp992;
  const Scalar _tmp1024 = -_tmp1001 * _tmp407 + _tmp1001 * _tmp413 + _tmp1002 * _tmp267 -
                          _tmp1002 * _tmp278 - _tmp1004 * _tmp411 + _tmp1004 * _tmp412;
  const Scalar _tmp1025 = _tmp1024 * fh1;
  const Scalar _tmp1026 = _tmp1002 * _tmp547 + _tmp1002 * fv1 - _tmp1004 * _tmp554 +
                          _tmp1005 * _tmp408 + Scalar(10.359360000000001) * _tmp111 +
                          _tmp48 * _tmp548 + _tmp544 * _tmp877 +
                          Scalar(10.359360000000001) * _tmp709;
  const Scalar _tmp1027 = _tmp1003 * _tmp528;
  const Scalar _tmp1028 = _tmp1002 * _tmp271;
  const Scalar _tmp1029 = _tmp215 * _tmp995;
  const Scalar _tmp1030 =
      -_tmp458 * _tmp995 + _tmp464 * _tmp989 + _tmp464 * _tmp990 - _tmp464 * _tmp991;
  const Scalar _tmp1031 = _tmp284 * _tmp944;
  const Scalar _tmp1032 = _tmp192 * _tmp948;
  const Scalar _tmp1033 = _tmp1004 * _tmp436;
  const Scalar _tmp1034 = -_tmp241 * _tmp987 - _tmp263 * _tmp955 + _tmp431 * _tmp985;
  const Scalar _tmp1035 = _tmp204 * _tmp938;
  const Scalar _tmp1036 =
      _tmp1021 * _tmp206 - _tmp1022 * _tmp241 - _tmp240 * _tmp955 + _tmp945 - _tmp947;
  const Scalar _tmp1037 =
      _tmp1004 * _tmp247 - _tmp1011 * _tmp273 - _tmp1025 * _tmp416 - _tmp1028 * _tmp245 +
      _tmp1031 * _tmp269 + _tmp1031 * _tmp281 + _tmp1031 * _tmp292 + _tmp1031 * _tmp417 +
      _tmp1033 * _tmp273 - _tmp270 * _tmp972 - _tmp282 * _tmp972 -
      _tmp409 *
          (-_tmp1021 * _tmp175 + _tmp1022 * _tmp403 - _tmp1032 * _tmp242 + _tmp1035 * _tmp242 +
           _tmp1036 * _tmp243 + _tmp240 * _tmp954 - _tmp368 * _tmp930 - _tmp406 * _tmp922) -
      _tmp410 * _tmp972 - _tmp418 * _tmp972 -
      _tmp435 * (-_tmp1032 * _tmp264 + _tmp1034 * _tmp243 + _tmp1035 * _tmp264 - _tmp263 * _tmp950 +
                 _tmp263 * _tmp954 + _tmp403 * _tmp987 - _tmp433 * _tmp985 - _tmp434 * _tmp930) -
      _tmp445 * (_tmp1032 * _tmp818 + _tmp274 * _tmp954 - _tmp276 * _tmp955 + _tmp439 * _tmp981 +
                 _tmp441 * _tmp929 - _tmp442 * _tmp922 - _tmp443 * _tmp938 - _tmp444 * _tmp981) -
      _tmp451 * (-_tmp1008 * _tmp175 + _tmp1008 * _tmp449 + _tmp1032 * _tmp447 + _tmp289 * _tmp954 +
                 _tmp290 * _tmp930 - _tmp290 * _tmp938 - _tmp448 * _tmp922 - _tmp450 * _tmp956);
  const Scalar _tmp1038 =
      _tmp576 *
      (-_tmp1037 * _tmp511 +
       _tmp455 *
           (_tmp1006 * _tmp474 + _tmp1011 * _tmp574 + _tmp1025 * _tmp469 + _tmp1026 * _tmp556 -
            _tmp1027 * _tmp529 - _tmp1027 * _tmp572 + _tmp1028 * _tmp527 +
            _tmp466 * (-_tmp261 * _tmp995 + _tmp462 * _tmp971 - _tmp463 * _tmp994 +
                       _tmp464 * _tmp969 - _tmp464 * _tmp982 + _tmp464 * _tmp986) +
            _tmp476 *
                (-_tmp1007 * _tmp464 - _tmp1010 * _tmp463 + _tmp287 * _tmp995 + _tmp837 * _tmp970) +
            _tmp479 * (-_tmp1012 * _tmp464 + _tmp1013 * _tmp464 + _tmp1020 * _tmp464 -
                       _tmp1023 * _tmp463 - _tmp238 * _tmp995 + _tmp477 * _tmp971) +
            _tmp483 * (-_tmp537 * _tmp962 + _tmp564 * _tmp988 - _tmp571 * _tmp992 + _tmp995) +
            _tmp541 * (-_tmp463 * _tmp998 + _tmp468 * _tmp971 - _tmp996 + _tmp997 - _tmp999) +
            _tmp568 * (-_tmp1029 - _tmp1030 * _tmp463 - _tmp464 * _tmp963 + _tmp564 * _tmp967 +
                       _tmp841 * _tmp970)));
  const Scalar _tmp1039 = _tmp909 + _tmp923;
  const Scalar _tmp1040 = _tmp1009 * _tmp503 + _tmp500 * (_tmp1039 + _tmp919);
  const Scalar _tmp1041 = _tmp622 * (_tmp892 + _tmp915) + _tmp624 * (_tmp910 + _tmp919);
  const Scalar _tmp1042 = _tmp1008 * _tmp286;
  const Scalar _tmp1043 = -_tmp1004 * _tmp606 + _tmp1011 * _tmp434 - _tmp1025 * _tmp443 +
                          _tmp1028 * _tmp368 - _tmp1033 * _tmp434 + _tmp1034 * _tmp607 +
                          _tmp1036 * _tmp611 + _tmp1042 * _tmp207 - _tmp580 * _tmp956 -
                          _tmp603 * _tmp948 - _tmp608 * _tmp948 + _tmp612 * _tmp948 -
                          _tmp613 * _tmp955 + _tmp614 * _tmp981 + _tmp860 * _tmp948;
  const Scalar _tmp1044 = _tmp471 * _tmp961;
  const Scalar _tmp1045 = _tmp590 * _tmp992;
  const Scalar _tmp1046 = _tmp1026 * _tmp464;
  const Scalar _tmp1047 =
      _tmp619 *
      (-_tmp1043 * _tmp618 +
       _tmp583 *
           (-_tmp1004 * _tmp595 + _tmp1006 * _tmp587 + _tmp1010 * _tmp589 + _tmp1011 * _tmp586 +
            _tmp1023 * _tmp592 + _tmp1025 * _tmp601 + _tmp1028 * _tmp594 + _tmp1030 * _tmp597 -
            _tmp1033 * _tmp586 - _tmp1044 * _tmp841 + _tmp1045 * _tmp480 - _tmp1046 * _tmp480 -
            _tmp585 * _tmp988 + _tmp588 * _tmp998 + _tmp596 * _tmp994 - _tmp598 * _tmp962 +
            _tmp599 * _tmp962 - _tmp600 * _tmp962 - _tmp602 * _tmp962 - _tmp865 * _tmp961));
  const Scalar _tmp1048 = _tmp667 * (_tmp1039 + _tmp902) + _tmp668 * (_tmp892 + _tmp927);
  const Scalar _tmp1049 = _tmp1002 * _tmp868 - _tmp1004 * _tmp645 + _tmp1011 * _tmp263 -
                          _tmp1021 * _tmp408 + _tmp1022 * _tmp644 + _tmp1024 * _tmp604 -
                          _tmp1033 * _tmp263 - _tmp1042 - _tmp541 * _tmp981 - _tmp642 * _tmp985 +
                          _tmp646 * _tmp987;
  const Scalar _tmp1050 =
      -_tmp1049 * _tmp680 +
      _tmp657 * (_tmp1004 * _tmp673 - _tmp1006 * _tmp472 + _tmp1007 * _tmp654 - _tmp1011 * _tmp671 +
                 _tmp1012 * _tmp653 - _tmp1013 * _tmp653 - _tmp1020 * _tmp653 - _tmp1025 * _tmp467 -
                 _tmp1028 * _tmp672 + _tmp1029 * _tmp471 + _tmp1033 * _tmp671 +
                 _tmp1044 * _tmp214 * _tmp350 * _tmp464 - _tmp1045 + _tmp1046 + _tmp280 * _tmp996 -
                 _tmp280 * _tmp997 + _tmp280 * _tmp999 - _tmp652 * _tmp969 + _tmp652 * _tmp982 -
                 _tmp652 * _tmp986 - _tmp674 * _tmp992 - _tmp678 * _tmp967 + _tmp871 * _tmp992 +
                 _tmp872 * _tmp992);

  // Output terms (1)
  Eigen::Matrix<Scalar, 4, 3> _res;

  _res(0, 0) = _tmp104 * _tmp108 - _tmp136 * (_tmp104 + _tmp135 * (_tmp122 + _tmp128));
  _res(1, 0) =
      _tmp453 * _tmp496 +
      _tmp486 *
          (-_tmp506 * (-_tmp453 * _tmp508 +
                       _tmp492 * (-_tmp453 * _tmp510 - _tmp504 * _tmp509 - _tmp575 * _tmp577)) -
           _tmp575 * _tmp579) -
      _tmp505 * (_tmp396 * _tmp498 + _tmp504);
  _res(2, 0) =
      _tmp582 * (-_tmp620 * _tmp637 -
                 _tmp635 * (-_tmp615 * _tmp633 + _tmp631 * (-_tmp582 * _tmp620 - _tmp615 * _tmp630 -
                                                            _tmp625 * _tmp628))) +
      _tmp615 * _tmp641 - _tmp640 * (_tmp625 + _tmp639 * (_tmp122 + _tmp334));
  _res(3, 0) =
      _tmp647 * _tmp664 +
      _tmp659 * (-_tmp682 * _tmp683 -
                 _tmp684 * (-_tmp647 * _tmp685 + _tmp661 * (-_tmp647 * _tmp687 - _tmp659 * _tmp682 -
                                                            _tmp669 * _tmp686))) -
      _tmp670 * (_tmp666 * (_tmp113 + _tmp342) + _tmp669);
  _res(0, 1) = _tmp108 * _tmp726 - _tmp136 * (_tmp135 * (_tmp692 + _tmp701) + _tmp726);
  _res(1, 1) =
      _tmp486 *
          (-_tmp506 * (_tmp492 * (-_tmp485 * _tmp859 - _tmp509 * _tmp736 - _tmp577 * _tmp858) -
                       _tmp508 * _tmp830) -
           _tmp579 * _tmp858) +
      _tmp495 * _tmp859 - _tmp505 * (_tmp498 * _tmp804 + _tmp736);
  _res(2, 1) =
      _tmp582 *
          (-_tmp635 * (_tmp631 * (-_tmp582 * _tmp866 - _tmp628 * _tmp867 - _tmp630 * _tmp862) -
                       _tmp633 * _tmp862) -
           _tmp637 * _tmp866) -
      _tmp640 * (_tmp639 * (_tmp696 + _tmp803) + _tmp867) + _tmp641 * _tmp862;
  _res(3, 1) =
      _tmp659 *
          (-_tmp684 * (_tmp661 * (-_tmp686 * _tmp870 - _tmp687 * _tmp869 - _tmp873 * _tmp874) -
                       _tmp685 * _tmp869) -
           _tmp873 * _tmp875) +
      _tmp664 * _tmp869 - _tmp670 * (_tmp666 * (_tmp692 + _tmp767) + _tmp870);
  _res(0, 2) = _tmp108 * _tmp911 - _tmp136 * (_tmp135 * (_tmp884 + _tmp887) + _tmp911);
  _res(1, 2) =
      _tmp1037 * _tmp496 +
      _tmp486 *
          (-_tmp1038 * _tmp578 -
           _tmp506 * (-_tmp1037 * _tmp508 +
                      _tmp492 * (-_tmp1037 * _tmp510 - _tmp1038 * _tmp486 - _tmp1040 * _tmp509))) -
      _tmp505 * (_tmp1018 * _tmp498 + _tmp1040);
  _res(2, 2) =
      _tmp1043 * _tmp641 +
      _tmp582 *
          (-_tmp1047 * _tmp637 -
           _tmp635 * (-_tmp1043 * _tmp633 +
                      _tmp631 * (-_tmp1041 * _tmp628 - _tmp1043 * _tmp630 - _tmp1047 * _tmp582))) -
      _tmp640 * (_tmp1041 + _tmp639 * (_tmp1017 + _tmp887));
  _res(3, 2) =
      _tmp1049 * _tmp664 +
      _tmp659 *
          (-_tmp1050 * _tmp875 -
           _tmp684 * (-_tmp1049 * _tmp685 +
                      _tmp661 * (-_tmp1048 * _tmp686 - _tmp1049 * _tmp687 - _tmp1050 * _tmp874))) -
      _tmp670 * (_tmp1048 + _tmp666 * (_tmp884 + _tmp935));

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
